'use strict';
// RÉPARTITION 12ÈME — NOVEMBRE 2025
// Pré-primaire ~5 ans — 15 matières

function m(mat, topic, approche, activites, exercices) {
  return { matiere:mat, topic, approche, activites, exercices };
}

const NOVEMBRE_12EME = [

  {
    n:1, dates:'03/11/2025 – 07/11/2025',
    theme:'Les aliments · Lignes obliques · Compter 1-12 · Formes et couleurs',
    matieres:[

      m('HYGIÈNE','Bien manger pour être en bonne santé',
        'Distinguer les aliments sains (fruits, légumes, eau) des aliments moins bons (sucreries, sodas). Découvrir la règle du repas équilibré.',
        ['Trier des images d\'aliments : "bon / moins bon pour la santé"',
         'Composer un plateau repas équilibré',
         'Goûter des fruits frais'],
        ['Cite 3 aliments bons pour la santé. → Corrigé : fruits, légumes, poisson, eau.',
         'Cite 1 aliment à ne pas manger trop souvent. → Corrigé : bonbons, sodas, frites.',
         'Combien de repas mange-t-on par jour ? → Corrigé : 3 repas (+ goûter).',
         'Que boit-on quand on a soif ? → Corrigé : de l\'eau.',
         'Pourquoi mange-t-on ? → Corrigé : pour grandir, avoir de l\'énergie et rester en bonne santé.']),

      m('I.C.','Mon quartier',
        'Observer et nommer les lieux du quartier : marché, école, dispensaire, mosquée/église, boutique. Sécurité dans le quartier.',
        ['Visite ou dessin du quartier',
         'Identifier les lieux importants sur une image',
         'Règle : ne pas parler à des inconnus'],
        ['Cite 2 endroits dans ton quartier. → Corrigé : marché, école, mosquée, boutique.',
         'Où va-t-on quand on est malade ? → Corrigé : au dispensaire / à l\'hôpital.',
         'Que dit-on à un inconnu qui t\'offre quelque chose ? → Corrigé : non merci, et j\'en parle à mes parents.',
         'Où achète-t-on de la nourriture ? → Corrigé : au marché ou à la boutique.',
         'Comment t\'appelle ton quartier ? → Corrigé : réponse personnelle.']),

      m('MORAL','Je suis courageux/courageuse',
        'Présenter le courage adapté à l\'âge : essayer même quand c\'est difficile, demander de l\'aide, se lever quand on tombe.',
        ['Histoire : "Tiana apprend à nager"',
         'Discussion : "As-tu eu peur de quelque chose ? As-tu été courageux ?"',
         'Valoriser les gestes de courage'],
        ['Qu\'est-ce que le courage ? → Corrigé : essayer même quand on a peur.',
         'Donne 1 exemple de courage. → Corrigé : apprendre quelque chose de nouveau, ne pas pleurer quand on tombe.',
         'As-tu été courageux récemment ? → Corrigé : réponse personnelle.',
         'Est-il normal d\'avoir peur ? → Corrigé : oui, tout le monde a peur parfois.',
         'Que fait-on quand on a peur ? → Corrigé : on en parle à un adulte de confiance.']),

      m('CONTE','La petite tortue (S2 — fin)',
        'Lire la fin du conte de la tortue. Raconter avec les images. Jeu de rôle.',
        ['Relire avec images',
         'Les enfants jouent la tortue et ses amis',
         'Questions de compréhension'],
        ['Comment se termine le conte ? → Corrigé : selon texte.',
         'La tortue a-t-elle trouvé sa maison ? → Corrigé : selon texte.',
         'Quelle leçon retiens-tu ? → Corrigé : persévérer, ne pas abandonner.',
         'Raconte le conte en 2 phrases. → Corrigé : résumé oral.',
         'Quel est ton personnage préféré ? → Corrigé : réponse personnelle.']),

      m('LANGAGE','Les aliments — nommer et décrire',
        'Nommer les aliments du quotidien malgache : riz, légumes, poisson, fruits, brèdes. Leurs couleurs, formes, goûts.',
        ['Montrer de vrais aliments ou images',
         'Goûter et décrire : sucré, salé, acide',
         'Discussion : "Qu\'as-tu mangé ce matin ?"'],
        ['Cite 5 aliments. → Corrigé : riz, légumes, poisson, mangue, banane.',
         'Comment est la mangue ? → Corrigé : jaune, sucrée, parfumée.',
         'Le riz est-il sucré ou salé ? → Corrigé : ni sucré ni salé (neutre / selon préparation).',
         'Que manges-tu au petit-déjeuner ? → Corrigé : réponse personnelle.',
         'Nomme 1 fruit rouge. → Corrigé : tomate (fruit), fraise, cerise, litchi.']),

      m('PRÉ-LECTURE','Graphisme — lignes obliques',
        'Tracer des lignes obliques (diagonales) vers la gauche et vers la droite. Préparer les lettres V, X, K, Z.',
        ['Tracer dans l\'air des diagonales',
         'Tracer en zigzag sur papier',
         'Tracer des croix et des X'],
        ['Trace une ligne oblique vers la droite. → Corrigé : évaluation.',
         'Trace une ligne oblique vers la gauche. → Corrigé : évaluation.',
         'Trace 5 zigzags. → Corrigé : évaluation.',
         'Quelle lettre ressemble à une oblique ? → Corrigé : V, X, Z, K, W.',
         'Trace une croix (+). → Corrigé : évaluation.']),

      m('NUMÉRATION','Compter 1 à 12',
        'Étendre le comptage à 12. Chant. Reconnaître les chiffres 10, 11, 12.',
        ['Compter jusqu\'à 12 avec les doigts et des objets',
         'Chant : "1 à 12"',
         'Ordonner les cartes chiffres 1-12'],
        ['Compte de 1 à 12. → Corrigé : performance orale.',
         'Quel nombre vient après 10 ? → Corrigé : 11.',
         'Quel nombre vient après 11 ? → Corrigé : 12.',
         'Montre 10 objets. → Corrigé : dénombrement.',
         'Combien de mois y a-t-il dans l\'année ? → Corrigé : 12.']),

      m('CALCUL','Additions jusqu\'à 5',
        'Pratiquer les additions jusqu\'à 5 avec des objets concrets. Écrire les chiffres du résultat.',
        ['Calculer avec des objets : 1+4, 2+3, 3+2',
         'Cartes de calcul avec dessins',
         'Ardoise : écrire le résultat'],
        ['2+3=___. → Corrigé : 5.',
         '1+4=___. → Corrigé : 5.',
         '3+2=___. → Corrigé : 5.',
         '4+1=___. → Corrigé : 5.',
         'Problème : 2 mangues + 2 mangues = ___. → Corrigé : 4.']),

      m('DESSIN','Les formes et les couleurs — associer',
        'Colorier chaque forme avec une couleur précise. Triangle rouge, carré bleu, cercle jaune. Renforcer formes + couleurs.',
        ['Colorier 3 formes avec 3 couleurs assignées',
         'Dessiner et colorier une maison simple',
         'Jeu de tri : trier des formes par couleur'],
        ['Colorie le triangle en rouge. → Corrigé : évaluation.',
         'Colorie le cercle en jaune. → Corrigé : évaluation.',
         'Quelle forme est bleue dans ton dessin ? → Corrigé : le carré.',
         'Dessine une maison avec des formes géométriques. → Corrigé : rectangle + triangle.',
         'Cite 3 formes géométriques. → Corrigé : cercle, carré, triangle.']),

      m('CHANT','Chanson "Les légumes du jardin"',
        'Apprendre une chanson sur les légumes. Nommer les légumes. Gestes de jardinage.',
        ['Chanter × 3 avec les gestes',
         'Nommer les légumes de la chanson',
         'Mimer le jardinage'],
        ['Chante la chanson des légumes. → Corrigé : performance orale.',
         'Cite 3 légumes de la chanson. → Corrigé : selon les paroles.',
         'De quelle couleur est une tomate ? → Corrigé : rouge.',
         'De quelle couleur est une carotte ? → Corrigé : orange.',
         'Mimer le geste d\'arracher une carotte. → Corrigé : geste.']),

      m('RÉCITATION','Comptine "Une pomme pour la maîtresse"',
        'Apprendre la comptine sur la pomme. Mémoriser. Gestes associés.',
        ['Apprendre × 3',
         'Ajouter les gestes',
         'Réciter seul'],
        ['Récite la comptine. → Corrigé : performance orale.',
         'De quel fruit parle la comptine ? → Corrigé : une pomme.',
         'De quelle couleur est cette pomme ? → Corrigé : rouge (ou verte).',
         'Qui reçoit la pomme ? → Corrigé : la maîtresse.',
         'Mime l\'action de donner une pomme. → Corrigé : geste.']),

      m('T.M.','Dessin à l\'éponge — tamponnage',
        'Créer des textures avec une éponge imbibée de peinture. Remplir des formes. Découvrir l\'impression.',
        ['Tremper l\'éponge dans la peinture',
         'Tamponner à l\'intérieur d\'une forme dessinée',
         'Découvrir l\'effet de texture'],
        ['Qu\'as-tu utilisé pour peindre ? → Corrigé : une éponge.',
         'Quelle couleur as-tu choisie ? → Corrigé : réponse personnelle.',
         'Quelle forme as-tu remplie ? → Corrigé : réponse personnelle.',
         'Comment obtient-on une texture avec une éponge ? → Corrigé : en tamponnant sans glisser.',
         'Que pourrais-tu créer d\'autre avec cette technique ? → Corrigé : réponse libre.']),

      m('A.P.S.','Équilibre — sur une jambe',
        'Tenir en équilibre sur une jambe. Compter jusqu\'à 5. Jeu de la statue.',
        ['Tenir sur la jambe droite : compter jusqu\'à 5',
         'Tenir sur la jambe gauche : compter jusqu\'à 5',
         'Jeu de la statue : s\'immobiliser sur 1 pied'],
        ['Tiens sur 1 pied pendant 5 secondes. → Corrigé : évaluation.',
         'Sur quelle jambe est-il plus facile de tenir ? → Corrigé : réponse personnelle.',
         'Qu\'est-ce que l\'équilibre ? → Corrigé : ne pas tomber en restant en place.',
         'Quel animal tient sur 1 patte ? → Corrigé : flamant rose, héron.',
         'Combien de secondes as-tu tenu ? → Corrigé : performance individuelle.']),

      m('ENVIRONNEMENT','Les animaux de la forêt',
        'Identifier des animaux sauvages locaux : lémuriens, caméléons, oiseaux malgaches. Sons et habitats.',
        ['Images d\'animaux de forêt malgache',
         'Imiter les sons et mouvements',
         'Discussion : "As-tu déjà vu un lémurien ?"'],
        ['Cite 2 animaux de la forêt malgache. → Corrigé : lémurien, caméléon, oiseau, serpent.',
         'Où vit le lémurien ? → Corrigé : dans la forêt de Madagascar.',
         'Quel son fait le lémurien ? → Corrigé : un cri aigu.',
         'De quelle couleur est un caméléon ? → Corrigé : il change de couleur selon l\'environnement.',
         'Pourquoi faut-il protéger les animaux sauvages ? → Corrigé : parce qu\'ils sont précieux et peuvent disparaître.']),

      m('ANGLAIS','Shapes — Les formes en anglais',
        'Apprendre les formes en anglais : circle, square, triangle, rectangle. Chanter "Shapes Song".',
        ['Flashcards formes',
         '"What shape is this?" — pointer et répondre',
         'Dessiner au signal "Draw a circle!"'],
        ['How do you say "cercle" ? → Corrigé : circle.',
         'How do you say "carré" ? → Corrigé : square.',
         'How many sides does a triangle have ? → Corrigé : three.',
         'Draw a circle. → Corrigé : production.',
         'What shape is the door ? → Corrigé : rectangle.']),

    ]
  },

  {
    n:2, dates:'10/11/2025 – 14/11/2025',
    theme:'Les vêtements · Boucles · Compter 1-15 · Comparaison de quantités',
    matieres:[

      m('HYGIÈNE','S\'habiller proprement',
        'Apprendre à s\'habiller seul : boutonner, lacer, enfiler. Choisir des vêtements propres. Ordre d\'habillage.',
        ['Jeu d\'habillage : boutonner une chemise-modèle',
         'Ranger ses vêtements soi-même',
         'Discussion : "Peux-tu t\'habiller seul(e) ?"'],
        ['Peux-tu boutonner une chemise ? → Corrigé : performance.',
         'Dans quel ordre met-on ses vêtements ? → Corrigé : sous-vêtements → vêtements → chaussures.',
         'Pourquoi porte-t-on des vêtements propres ? → Corrigé : pour être propre et respecté.',
         'Que met-on quand il pleut ? → Corrigé : un imperméable / un parapluie.',
         'Que met-on quand il fait froid ? → Corrigé : un pull, une veste.']),

      m('I.C.','Les jours de la semaine',
        'Apprendre les 7 jours de la semaine en malgache et en français. Reconnaître aujourd\'hui, hier, demain.',
        ['Chant des jours de la semaine',
         'Afficher le calendrier et pointer le jour actuel',
         '"Qu\'avons-nous fait hier ?"'],
        ['Cite les 7 jours de la semaine. → Corrigé : lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche.',
         'Quel jour sommes-nous aujourd\'hui ? → Corrigé : réponse selon le jour.',
         'Quel jour était-ce hier ? → Corrigé : réponse selon le jour.',
         'Quel jour sera-t-il demain ? → Corrigé : réponse selon le jour.',
         'Combien de jours y a-t-il dans une semaine ? → Corrigé : 7.']),

      m('MORAL','Je suis responsable de mes affaires',
        'Apprendre à prendre soin de son matériel : ranger son crayon, fermer son sac, ne pas perdre ses affaires.',
        ['Ranger son sac le soir selon une liste',
         'Prendre soin des livres et crayons',
         'Règle : "Je range mes affaires après usage"'],
        ['Que mets-tu dans ton sac le matin ? → Corrigé : cahier, crayon, gomme, trousse, collation.',
         'Que fais-tu si tu perds ton crayon ? → Corrigé : je cherche, je demande poliment.',
         'Pourquoi faut-il prendre soin de son matériel ? → Corrigé : pour ne pas perdre et pour que ça dure longtemps.',
         'Où ranges-tu ton sac en classe ? → Corrigé : sous ma chaise / à ma place.',
         'Quelle règle retiens-tu ? → Corrigé : "Je range mes affaires après usage."']),

      m('CONTE','Nouveau conte — Le lion et la souris (S1)',
        'Conte classique adapté. Le grand lion et la petite souris. La gentillesse récompensée.',
        ['Montrer les images',
         'Lire avec expression',
         'Questions de compréhension'],
        ['Qui sont les personnages ? → Corrigé : le lion et la souris.',
         'Lequel est grand ? Lequel est petit ? → Corrigé : lion = grand, souris = petite.',
         'Que fait le lion au début ? → Corrigé : selon texte.',
         'La souris aide-t-elle le lion ? → Corrigé : oui.',
         'Quelle leçon retiens-tu ? → Corrigé : même les petits peuvent aider les grands.']),

      m('LANGAGE','Les vêtements',
        'Nommer les vêtements : robe, pantalon, chemise, chaussures, chapeau. Les couleurs des vêtements. Ce qu\'on porte selon la météo.',
        ['Montrer des images de vêtements',
         'Jeu : "Je porte une ___"',
         'Trier : vêtements chauds vs vêtements légers'],
        ['Cite 4 vêtements. → Corrigé : robe, pantalon, chemise, chaussures.',
         'Que portes-tu quand il fait chaud ? → Corrigé : robe légère, short, sandales.',
         'De quelle couleur est ton uniforme ? → Corrigé : réponse selon l\'école.',
         'Qu\'est-ce qu\'on met sur la tête ? → Corrigé : un chapeau, un bonnet.',
         'Qu\'est-ce qu\'on met aux pieds ? → Corrigé : des chaussures, des sandales.']),

      m('PRÉ-LECTURE','Graphisme — boucles',
        'Tracer des boucles (guirlandes). Préparer l\'écriture des lettres e, l, b. Régularité et continuité du tracé.',
        ['Tracer des boucles dans l\'air',
         'Tracer des boucles sur papier : guirlandes',
        'Tracer des "m" et des "n" simplifiés'],
        ['Trace 5 boucles en guirlande. → Corrigé : évaluation.',
         'Vers quel côté vont les boucles ? → Corrigé : de gauche à droite.',
         'Quelle lettre ressemble à une boucle ? → Corrigé : e, l, b, d.',
         'Trace une guirlande de 7 boucles. → Corrigé : évaluation.',
         'Bien tenir le crayon : montre ta prise. → Corrigé : prise tripode.']),

      m('NUMÉRATION','Compter 1 à 15',
        'Étendre à 15. Chant. Reconnaître les chiffres 13, 14, 15. Associer chiffre et collection.',
        ['Compter de 1 à 15 avec des perles ou cailloux',
         'Chant "1 à 15"',
         'Ordonner les cartes chiffres 1-15'],
        ['Compte de 1 à 15. → Corrigé : performance orale.',
         'Quel nombre vient après 13 ? → Corrigé : 14.',
         'Montre 14 doigts (avec aide). → Corrigé : 10 + 4.',
         'Quel nombre est le plus grand : 9 ou 14 ? → Corrigé : 14.',
         'Combien de doigts as-tu en tout ? → Corrigé : 10.']),

      m('CALCUL','Comparaison — plus/moins/autant',
        'Comparer des collections : plus que, moins que, autant que. Utiliser des jetons.',
        ['Aligner des jetons en correspondance terme à terme',
         'Comparer 2 collections',
         'Utiliser les mots : "Il y en a plus/moins/autant"'],
        ['Y a-t-il plus de rouge ou de bleu ? (selon config) → Corrigé : évaluation.',
         'Mets autant de cailloux que de crayons. → Corrigé : correspondance.',
         '"Plus que" signifie quoi ? → Corrigé : en plus grande quantité.',
         '"Moins que" signifie quoi ? → Corrigé : en plus petite quantité.',
         'Montre la collection qui a le moins. → Corrigé : geste.']),

      m('DESSIN','Dessin d\'un personnage habillé',
        'Dessiner un bonhomme avec des vêtements. Ajouter les couleurs de chaque vêtement. Développer le sens des détails.',
        ['Dessiner un bonhomme (tête-corps-bras-jambes)',
         'Ajouter les vêtements (chemise, pantalon, chaussures)',
         'Colorier'],
        ['Combien de parties a ton bonhomme ? → Corrigé : tête, corps, bras, jambes, pieds.',
         'De quelle couleur est la chemise de ton bonhomme ? → Corrigé : réponse personnelle.',
         'As-tu dessiné des chaussures ? → Corrigé : évaluation.',
         'Ton bonhomme porte-t-il un chapeau ? → Corrigé : réponse personnelle.',
         'Que manque-t-il à ton bonhomme ? → Corrigé : réponse personnelle.']),

      m('CHANT','Chanson "Mon beau chapeau"',
        'Apprendre une chanson sur les vêtements avec des gestes. Nommer les vêtements cités.',
        ['Chanter × 3 avec les gestes de s\'habiller',
         'Mimer chaque vêtement mentionné',
         'Chanter seul'],
        ['Chante la chanson. → Corrigé : performance orale.',
         'Quel vêtement est cité en premier ? → Corrigé : selon les paroles.',
         'Mime mettre un chapeau. → Corrigé : geste.',
         'Mime lacer ses chaussures. → Corrigé : geste.',
         'Quelle couleur est le chapeau dans la chanson ? → Corrigé : selon les paroles.']),

      m('RÉCITATION','Comptine "Il pleut, il pleut, bergère"',
        'Apprendre la comptine classique. Lien avec la météo et les vêtements de pluie.',
        ['Apprendre la comptine × 3',
         'Mimer la pluie et les vêtements de pluie',
         'Réciter seul'],
        ['Récite la comptine. → Corrigé : performance orale.',
         'Que fait-il dans cette comptine ? → Corrigé : il pleut.',
         'Que met-on pour se protéger de la pluie ? → Corrigé : un imperméable, un parapluie.',
         'Mime la pluie avec tes doigts. → Corrigé : geste.',
         'Aimes-tu la pluie ? → Corrigé : réponse personnelle.']),

      m('T.M.','Peinture aux doigts — empreintes',
        'Créer des empreintes de doigts et de mains pour créer un tableau. Explorer la couleur et la forme.',
        ['Tremper les doigts dans la peinture',
         'Créer des empreintes sur papier',
         'Créer une image avec des empreintes (fleur, animal)'],
        ['Quelle empreinte as-tu créée ? → Corrigé : réponse personnelle.',
         'Combien de doigts as-tu utilisés ? → Corrigé : réponse personnelle.',
         'Quelle couleur as-tu choisie ? → Corrigé : réponse personnelle.',
         'Que ressemblent tes empreintes ? → Corrigé : un arbre, une fleur, un animal...',
         'Montre ton œuvre à un camarade. → Corrigé : présentation orale.']),

      m('A.P.S.','Rouler et se relever',
        'Apprendre à rouler sur un tapis (roulade avant simplifiée) et à se relever. Développer la coordination.',
        ['Montrer la roulade avant simplifiée',
         'Chaque enfant essaie avec aide',
         'Jeu : rouler et se relever rapidement'],
        ['Montre comment tu te roules. → Corrigé : performance.',
         'Comment te relèves-tu ? → Corrigé : en poussant sur les mains.',
         'Est-il important d\'être sur un tapis mou ? → Corrigé : oui, pour ne pas se faire mal.',
         'Quelle partie du corps touche le sol en premier ? → Corrigé : les mains et la tête arrondie.',
         'Dans quel sport roule-t-on beaucoup ? → Corrigé : judo, gym artistique.']),

      m('ENVIRONNEMENT','La pluie et l\'eau',
        'Observer la pluie. Où va l\'eau de pluie ? À quoi sert l\'eau ? Économiser l\'eau.',
        ['Observer la pluie par la fenêtre',
         'Expérience : recueillir l\'eau de pluie dans un seau',
         'Discussion : "Comment économise-t-on l\'eau ?"'],
        ['D\'où vient la pluie ? → Corrigé : des nuages.',
         'À quoi sert l\'eau de pluie ? → Corrigé : à arroser les plantes, remplir les rivières.',
         'Que faut-il faire pour économiser l\'eau ? → Corrigé : fermer le robinet, ne pas gaspiller.',
         'De quelle couleur est l\'eau propre ? → Corrigé : transparente, incolore.',
         'Est-ce qu\'on peut boire l\'eau de pluie directement ? → Corrigé : non, il faut la traiter d\'abord.']),

      m('ANGLAIS','Clothes — Les vêtements en anglais',
        'Apprendre les vêtements en anglais : shirt, pants, dress, shoes, hat. "I am wearing a..."',
        ['Flashcards vêtements',
         '"I am wearing a blue shirt." — chaque enfant décrit sa tenue',
         '"What are you wearing?" — répondre'],
        ['How do you say "chemise" ? → Corrigé : shirt.',
         'How do you say "chaussures" ? → Corrigé : shoes.',
         '"I am wearing a ___ shirt." → Corrigé : réponse personnelle.',
         'What color is your dress/shirt ? → Corrigé : réponse personnelle.',
         'What do you wear on your head ? → Corrigé : a hat.']),

    ]
  },

  {
    n:3, dates:'17/11/2025 – 21/11/2025',
    theme:'La maison · Spirales · Compter 1-18 · Addition jusqu\'à 8',
    matieres:[

      m('HYGIÈNE','Hygiène à table',
        'Règles à table : se laver les mains avant de manger, utiliser ses couverts, ne pas manger la bouche ouverte, remercier.',
        ['Jeu de rôle : simuler un repas',
         'Règles : assis, napkin sur les genoux, ne pas parler la bouche pleine',
         'Vérifier les mains avant de manger'],
        ['Que fais-tu avant de manger ? → Corrigé : je me lave les mains.',
         'Cite 2 règles à table. → Corrigé : s\'asseoir, ne pas parler la bouche pleine, utiliser ses couverts.',
         'Que dit-on après le repas ? → Corrigé : merci.',
         'Faut-il manger debout ou assis ? → Corrigé : assis.',
         'Que fais-tu si tu renverses quelque chose ? → Corrigé : s\'excuser et aider à nettoyer.']),

      m('I.C.','Les saisons à Madagascar',
        'Deux saisons : saison des pluies (chaud, humide) et saison sèche (moins chaud, sec). Identification des mois.',
        ['Afficher 2 images : saison des pluies vs saison sèche',
         'Identifier la saison actuelle (novembre = début saison des pluies)',
         'Discussion : "Quelle saison préfères-tu ?"'],
        ['Combien de saisons y a-t-il à Madagascar ? → Corrigé : 2.',
         'Comment s\'appelle la saison où il pleut beaucoup ? → Corrigé : la saison des pluies.',
         'En quelle saison faisons-nous cet exercice ? → Corrigé : saison des pluies.',
         'Que se passe-t-il en saison sèche ? → Corrigé : il y a moins de pluie et il fait plus frais.',
         'Quelle saison préfères-tu ? → Corrigé : réponse personnelle.']),

      m('MORAL','Je dis merci et s\'il te plaît',
        'Renforcer les formules de politesse : merci, s\'il te plaît, excusez-moi, pardon. Jeux de rôle.',
        ['Jeu de rôle : demander un objet poliment',
         'Comparer : "Donne-moi ça !" vs "S\'il te plaît, peux-tu me donner ça ?"',
         'Récompenser les formules de politesse dans la journée'],
        ['Que dit-on pour demander quelque chose ? → Corrigé : s\'il te plaît.',
         'Que dit-on quand on reçoit quelque chose ? → Corrigé : merci.',
         'Que dit-on quand on bouscule quelqu\'un ? → Corrigé : pardon / excusez-moi.',
         'Quelle formule est plus jolie : "Donne !" ou "S\'il te plaît" ? → Corrigé : "S\'il te plaît".',
         'Comment dit-on "merci" en malgache ? → Corrigé : misaotra.']),

      m('CONTE','Le lion et la souris (S2 — fin)',
        'Lire la fin du conte. Jouer le conte. Identifier la morale.',
        ['Lire S2 avec images',
         'Jeu de rôle : lion et souris',
         'Discussion : quelle est la leçon ?'],
        ['Comment la souris aide-t-elle le lion ? → Corrigé : selon texte.',
         'Quelle est la morale du conte ? → Corrigé : même les petits peuvent aider les grands. Soyons généreux.',
         'Raconte le conte en 2 phrases. → Corrigé : résumé oral.',
         'As-tu déjà aidé quelqu\'un qui est plus grand que toi ? → Corrigé : réponse personnelle.',
         'Le lion était-il gentil au début ? → Corrigé : selon texte.']),

      m('LANGAGE','Ma maison',
        'Nommer les pièces de la maison : salon, cuisine, chambre, salle de bain. Les meubles. Décrire sa maison.',
        ['Images de pièces — nommer',
         '"Où fais-tu la cuisine ?" — répondre',
         'Dessiner un plan simple de sa maison'],
        ['Cite 3 pièces de la maison. → Corrigé : salon, cuisine, chambre, salle de bain.',
         'Où dors-tu ? → Corrigé : dans ma chambre.',
         'Où prépare-t-on les repas ? → Corrigé : dans la cuisine.',
         'Qu\'y a-t-il dans le salon ? → Corrigé : canapé, table, télévision...',
         'Combien de chambres y a-t-il dans ta maison ? → Corrigé : réponse personnelle.']),

      m('PRÉ-LECTURE','Graphisme — spirales et escargots',
        'Tracer des spirales dans le sens des aiguilles d\'une montre et en sens inverse. Préparer les lettres rondes (o, a).',
        ['Tracer une spirale dans l\'air',
         'Tracer des escargots sur papier',
         'Tracer des o enchaînés'],
        ['Trace un escargot (spirale). → Corrigé : évaluation.',
         'Trace 5 escargots en ligne. → Corrigé : évaluation.',
         'Trace des "o" enchaînés. → Corrigé : évaluation.',
         'Quelle lettre ressemble à une spirale ? → Corrigé : o, a, e.',
         'Dans quel sens traces-tu la spirale ? → Corrigé : de l\'extérieur vers l\'intérieur ou l\'inverse.']),

      m('NUMÉRATION','Compter 1 à 18',
        'Étendre à 18. Compter par 2 (2, 4, 6...). Identifier le pair et l\'impair.',
        ['Compter de 1 à 18',
         'Compter par 2 avec les doigts des deux mains',
         'Pair vs impair : introduction simple'],
        ['Compte de 1 à 18. → Corrigé : performance orale.',
         'Quel nombre vient après 16 ? → Corrigé : 17.',
         'Compte par 2 : 2, 4, 6, ___, ___. → Corrigé : 8, 10.',
         'Quel est le plus grand : 15 ou 18 ? → Corrigé : 18.',
         'Quel nombre vient avant 18 ? → Corrigé : 17.']),

      m('CALCUL','Additions jusqu\'à 8',
        'Pratiquer les additions avec résultat jusqu\'à 8. Doigts, objets, ardoise.',
        ['Additions avec doigts : 3+5, 4+4, 6+2',
         'Cartes de calcul avec illustrations',
         'Ardoise : écrire le résultat'],
        ['3+5=___. → Corrigé : 8.',
         '4+4=___. → Corrigé : 8.',
         '6+2=___. → Corrigé : 8.',
         '5+3=___. → Corrigé : 8.',
         'Problème : 3 poissons + 4 poissons = ___. → Corrigé : 7.']),

      m('DESSIN','Ma maison — dessin',
        'Dessiner sa maison avec ses caractéristiques : murs, toit, fenêtres, porte, jardin. Colorier.',
        ['Observer des photos de maisons',
         'Dessiner sa maison étape par étape : rectangle, triangle-toit, fenêtres, porte',
         'Colorier'],
        ['Quelle forme a le toit de ta maison ? → Corrigé : triangle / trapèze.',
         'Combien de fenêtres as-tu dessinées ? → Corrigé : réponse personnelle.',
         'De quelle couleur as-tu colorié les murs ? → Corrigé : réponse personnelle.',
         'As-tu ajouté un jardin ? → Corrigé : réponse personnelle.',
         'Décris ta maison en 1 phrase. → Corrigé : réponse orale.']),

      m('CHANT','Chanson "Dans ma maison il y a..."',
        'Chanson sur les pièces de la maison. Chaque couplet ajoute une pièce. Mémoriser et mimer.',
        ['Chanter × 3 en ajoutant les pièces une par une',
         'Mimer les activités dans chaque pièce',
         'Chanter seul'],
        ['Chante la chanson. → Corrigé : performance orale.',
         'Quelle pièce est citée en premier ? → Corrigé : selon les paroles.',
         'Mime faire la cuisine. → Corrigé : geste.',
         'Mime dormir dans la chambre. → Corrigé : geste.',
         'Combien de pièces sont citées ? → Corrigé : selon les paroles.']),

      m('RÉCITATION','Comptine "Pomme de reinette"',
        'Apprendre la comptine "Pomme de reinette et pomme d\'api". Mémoriser. Gestes associés.',
        ['Apprendre × 3 avec les gestes',
         'Réciter en tapant dans les mains',
         'Réciter seul'],
        ['Récite la comptine. → Corrigé : performance orale.',
         'Quel fruit est dans la comptine ? → Corrigé : pomme.',
         'Montre où est ton "tapis tapi". → Corrigé : geste sur la tête.',
         'La comptine te plaît-elle ? → Corrigé : réponse personnelle.',
         'Connais-tu une autre comptine avec des fruits ? → Corrigé : réponse libre.']),

      m('T.M.','Construction — Maison en carton',
        'Construire une mini-maison avec une boîte de carton. Ajouter les détails : fenêtres découpées, porte, toit.',
        ['Récupérer une petite boîte',
         'Découper fenêtres et porte',
         'Décorer et colorier'],
        ['Qu\'as-tu utilisé pour construire ta maison ? → Corrigé : une boîte en carton.',
         'Combien de fenêtres as-tu découpées ? → Corrigé : réponse personnelle.',
         'As-tu ajouté un toit ? → Corrigé : réponse personnelle.',
         'Quelle couleur as-tu choisie pour ta maison ? → Corrigé : réponse personnelle.',
         'Combien de personnes peuvent habiter dans ta maison de carton ? → Corrigé : réponse imaginaire.']),

      m('A.P.S.','Course — départ arrêté',
        'Apprendre à partir d\'une position arrêtée et accélérer. Jeux de départ.',
        ['Départ assis : partir au signal "Go !"',
         'Départ debout, mains au sol',
         'Course de 10 m'],
        ['Montre la position de départ. → Corrigé : position squat ou mains au sol.',
         'Que fais-tu au signal "Go !" ? → Corrigé : je pars en courant.',
         'Comment cours-tu pour aller vite ? → Corrigé : je lève les genoux et balance les bras.',
         'Quel est le signal de départ ? → Corrigé : "Go !" / coup de sifflet.',
         'Combien as-tu mis de secondes pour faire 10 m ? → Corrigé : réponse individuelle.']),

      m('ENVIRONNEMENT','La maison et ses matériaux',
        'Observer de quoi est faite une maison : bois, béton, tôle, chaume, brique. Comparer les matériaux.',
        ['Observer les maisons autour de l\'école',
         'Identifier les matériaux : bois, béton, tôle',
         'Discussion : "De quoi est faite ta maison ?"'],
        ['Cite 3 matériaux de construction. → Corrigé : bois, béton, tôle, brique, bambou.',
         'De quoi est faite une maison traditionnelle malgache ? → Corrigé : bois et bambou avec toit de chaume ou de feuilles de raphia.',
         'Pourquoi utilise-t-on du béton ? → Corrigé : c\'est solide et durable.',
         'Ta maison est-elle en bois ou en béton ? → Corrigé : réponse personnelle.',
         'Quel matériau protège de la pluie sur le toit ? → Corrigé : la tôle, les tuiles, le chaume.']),

      m('ANGLAIS','Numbers 1-10',
        'Consolider les chiffres 1-10 en anglais. Compter des objets. Chanter "Ten Little Fingers".',
        ['Compter des objets en anglais',
         'Chanter "Ten Little Fingers"',
         '"How many ___ are there ?" — répondre'],
        ['Count from 1 to 10. → Corrigé : performance orale.',
         'How many fingers do you have on one hand ? → Corrigé : five.',
         'Show me 7 pencils. → Corrigé : dénombrement.',
         'How many eyes do you have ? → Corrigé : two.',
         'What number comes after 8 ? → Corrigé : nine.']),

    ]
  },

  {
    n:4, dates:'24/11/2025 – 28/11/2025',
    theme:'ÉVALUATION — Bilan du mois de Novembre',
    matieres:[
      m('ÉVALUATION','Fiche de révision — Novembre 2025',
        'Évaluation du mois de novembre. Activités orales, graphisme, numération, dessin.',
        ['Lundi : évaluation orale (Langage, Chant, Récitation, Anglais)',
         'Mardi : évaluation graphisme + Numération + Calcul',
         'Mercredi : évaluation Dessin + T.M.',
         'Jeudi : correction collective'],
        [
          '── LANGAGE ──',
          'Cite 4 vêtements. → Corrigé : robe, pantalon, chemise, chaussures.',
          'Cite 3 pièces de la maison. → Corrigé : salon, cuisine, chambre.',
          'Cite tes 5 sens. → Corrigé : vue, ouïe, odorat, goût, toucher.',
          '── NUMÉRATION ──',
          'Compte de 1 à 18. → Corrigé : performance orale.',
          'Quel nombre vient après 15 ? → Corrigé : 16.',
          'Quel est le plus grand : 12 ou 17 ? → Corrigé : 17.',
          '── CALCUL ──',
          '4+4=___. → Corrigé : 8.',
          '5+3=___. → Corrigé : 8.',
          '3+4=___. → Corrigé : 7.',
          '── GRAPHISME ──',
          'Trace 5 boucles. → Corrigé : évaluation.',
          'Trace 3 escargots. → Corrigé : évaluation.',
          '── DESSIN ──',
          'Dessine une maison avec toit, fenêtres et porte. → Corrigé : production.',
          '── CHANT ──',
          'Chante "Mon beau chapeau". → Corrigé : performance orale.',
          '── ANGLAIS ──',
          'Count from 1 to 10 in English. → Corrigé : performance orale.',
          'What color is this ? (montrer bleu) → Corrigé : blue.',
          '── HYGIÈNE ──',
          'Cite 2 règles à table. → Corrigé : se laver les mains, manger assis.',
        ]
      ),
    ]
  },

];

module.exports = { NOVEMBRE_12EME };
