'use strict';
// RÉPARTITION 12ÈME — JANVIER 2026
// Rentrée 3ème semaine de trimestre · Thèmes : transports, lettres rondes (O/C/G), 1-25, soustraction

function m(mat, topic, approche, activites, exercices) {
  return { matiere:mat, topic, approche, activites, exercices };
}

const JANVIER_12EME = [

  {
    n:1, dates:'05/01/2026 – 09/01/2026',
    theme:'Rentrée de janvier · Les transports · Lettres rondes en graphisme · Compter 1-22',
    matieres:[

      m('HYGIÈNE','Hygiène en voiture et transport',
        'Parler de l\'hygiène dans les transports : assis correctement, ne pas passer la tête par la fenêtre, se tenir propre. Ceinture de sécurité.',
        ['Images de voitures, taxi-brousse, pousse-pousse',
         'Discussion : "Comment viens-tu à l\'école ?"',
         'Règle : "En voiture, on reste assis calmement"'],
        ['Comment viens-tu à l\'école ? → Corrigé : réponse personnelle.',
         'Pourquoi ne faut-il pas passer la tête par la fenêtre ? → Corrigé : c\'est dangereux.',
         'À quoi sert la ceinture de sécurité ? → Corrigé : à retenir en cas de choc.',
         'Cite 1 moyen de transport à Madagascar. → Corrigé : taxi-brousse, pousse-pousse, pirogue.',
         'Comment se comporte-t-on dans un transport ? → Corrigé : on reste calme, assis, on ne crie pas.']),

      m('I.C.','Les transports à Madagascar',
        'Découvrir les différents moyens de transport : terrestres (taxi-brousse, pousse-pousse, zébu), aquatiques (pirogue), aériens (avion). Images et jeu.',
        ['Images des différents transports',
         'Trier : transport terrestre / aquatique / aérien',
         'Mimer les transports : "Fais l\'avion, le bateau..."'],
        ['Cite 1 transport terrestre. → Corrigé : taxi-brousse, vélo, pousse-pousse.',
         'Cite 1 transport aquatique. → Corrigé : pirogue, bateau.',
         'Cite 1 transport aérien. → Corrigé : avion, hélicoptère.',
         'Quel transport mène sur l\'eau ? → Corrigé : la pirogue ou le bateau.',
         'Mime l\'avion avec tes bras. → Corrigé : geste.']),

      m('MORAL','La patience',
        'Attendre son tour. Être patient à l\'école, dans la file, en classe. Exemples concrets.',
        ['Jeu de rôle : faire la queue pour distribuer du matériel',
         'Discussion : "As-tu déjà attendu longtemps ? Comment tu te sentais ?"',
         'Règle : "J\'attends mon tour sans me plaindre"'],
        ['Qu\'est-ce que la patience ? → Corrigé : savoir attendre calmement.',
         'Quand faut-il être patient ? → Corrigé : dans la file, en attendant son tour, en voyage.',
         'Est-il correct de pousser pour passer devant ? → Corrigé : non, on attend son tour.',
         'Comment te sens-tu quand tu attends longtemps ? → Corrigé : réponse personnelle.',
         'Donne 1 exemple de patience. → Corrigé : attendre son tour au jeu, attendre que l\'enseignant finisse de parler.']),

      m('CONTE','Nouveau conte — Le petit train (S1)',
        'Nouveau conte de janvier : le petit train qui veut traverser la montagne. Lire S1. Questions simples.',
        ['Présenter les images du train et de la montagne',
         'Lire avec expression : "Petit train, petit train, tu vas grimper..."',
         'Questions de compréhension'],
        ['Quel est le personnage du conte ? → Corrigé : le petit train.',
         'Que veut faire le petit train ? → Corrigé : traverser la montagne.',
         'Décris le train en 1 mot. → Corrigé : courageux, petit, rouge...',
         'As-tu déjà vu un train ? → Corrigé : réponse personnelle.',
         'Prédit : arrivera-t-il à traverser la montagne ? → Corrigé : prédiction libre.']),

      m('LANGAGE','Les moyens de transport — vocabulaire',
        'Apprendre les mots : voiture, vélo, moto, avion, bateau, taxi-brousse, pousse-pousse, pirogue. Décrire un trajet.',
        ['Images des transports : nommer chacun',
         '"Je vais à l\'école en..."',
         'Phrases : "Le bateau va sur l\'eau. L\'avion vole dans le ciel."'],
        ['Nomme ce transport. (montrer image voiture) → Corrigé : voiture / taxi.',
         'Nomme ce transport. (montrer image bateau) → Corrigé : bateau.',
         'Où va l\'avion ? → Corrigé : dans le ciel.',
         'Où va le bateau ? → Corrigé : sur l\'eau.',
         'Comment dis-tu "taxi-brousse" en malgache ? → Corrigé : taxi-brousse (même mot).']),

      m('PRÉ-LECTURE','Graphisme — lettres rondes : O et C',
        'Préparer les lettres rondes O et C. Tracer des cercles complets (O) et des arcs ouverts (C). Mouvement antihoraire.',
        ['Tracer des cercles en l\'air',
         'Cercle sur l\'ardoise (O)',
         'Arc ouvert (C) : cercle qu\'on n\'a pas fermé'],
        ['Trace 5 cercles (O). → Corrigé : évaluation.',
         'Trace 5 arcs (C). → Corrigé : évaluation.',
         'Quelle lettre a la forme d\'un cercle complet ? → Corrigé : O.',
         'Quelle lettre est un cercle ouvert ? → Corrigé : C (et G).',
         'Dans quel sens trace-t-on les lettres rondes ? → Corrigé : sens antihoraire (comme une montre à l\'envers).']),

      m('NUMÉRATION','Compter de 1 à 22',
        'Continuer la progression : 21 et 22. Reconnaître les chiffres. Dénombrer des collections.',
        ['Compter de 1 à 22 avec les élèves',
         'Afficher les chiffres 21 et 22 au tableau',
         'Dénombrer 22 objets'],
        ['Compte de 1 à 22. → Corrigé : performance orale.',
         'Quel nombre vient après 20 ? → Corrigé : 21.',
         'Quel nombre vient après 21 ? → Corrigé : 22.',
         'Montre 21 cailloux. → Corrigé : dénombrement.',
         'Ordonne : 9, 22, 15, 3. → Corrigé : 3, 9, 15, 22.']),

      m('CALCUL','Soustraction — enlever jusqu\'à 10',
        'Consolider la soustraction. Introduire des problèmes de la vie courante avec enlever, perdre, manger, donner.',
        ['Problèmes oraux avec manipulatifs',
         'Ardoise : 5 − 3 = ___',
         'Vérifier avec les doigts'],
        ['5−3=___. → Corrigé : 2.',
         '7−4=___. → Corrigé : 3.',
         '9−5=___. → Corrigé : 4.',
         'Problème : j\'ai 8 pommes, je donne 3 à mon ami. Combien reste ? → Corrigé : 5.',
         'Problème : 10 oiseaux sur l\'arbre, 6 s\'envolent. Combien reste ? → Corrigé : 4.']),

      m('DESSIN','Les transports — dessin',
        'Dessiner son transport préféré. Utiliser les formes : cercles (roues), rectangles (corps). Colorier.',
        ['Observer les formes des transports : roues = cercles, carrosserie = rectangle',
         'Dessiner le transport préféré',
         'Colorier + présenter'],
        ['Quel transport as-tu dessiné ? → Corrigé : réponse personnelle.',
         'Quelles formes as-tu utilisées ? → Corrigé : cercle, rectangle.',
         'Combien de roues as-tu dessiné ? → Corrigé : 2, 3 ou 4.',
         'Quelle couleur as-tu choisie ? → Corrigé : réponse personnelle.',
         'Où va ton transport ? → Corrigé : réponse personnelle.']),

      m('CHANT','Chanson du train — "Petit train va vite"',
        'Apprendre une chanson sur le train. Rythme rapide. Frapper le rythme avec les mains.',
        ['"Petit train, petit train, tchic-tchac-tchic ! Petit train, petit train, va au bout du chemin !"',
         'Frapper le rythme : tchic-tchac = deux frappements',
         'Chanter de plus en plus vite'],
        ['Chante "Petit train". → Corrigé : performance orale.',
         'Quel son fait le train ? → Corrigé : tchic-tchac / tchou-tchou.',
         'Mime le train avec tes bras. → Corrigé : geste de roues qui tournent.',
         'Chante la chanson très vite. → Corrigé : performance.',
         'Chante doucement, comme un train qui ralentit. → Corrigé : performance.']),

      m('RÉCITATION','Comptine "En voiture simone"',
        'Apprendre la comptine : "En voiture Simone, c\'est moi qui conduis c\'est toi qui klaxonnes !"',
        ['Apprendre ligne par ligne',
         'Mimer : conduire + klaxonner',
         'Réciter seul avec les gestes'],
        ['Récite la comptine. → Corrigé : performance orale.',
         'Que fait Simone dans la comptine ? → Corrigé : elle klaxonne.',
         'Qui conduit ? → Corrigé : "moi".',
         'Mime : conduire une voiture. → Corrigé : geste (mains sur un volant imaginaire).',
         'Mime : klaxonner. → Corrigé : geste.']),

      m('T.M.','Fabriquer un train en boîtes',
        'Assembler un train avec 3 petites boîtes (wagons). Décorer. Développer la motricité fine.',
        ['Coller 3 boîtes en ligne = wagons',
         'Ajouter des cercles de papier = roues',
         'Colorier et décorer'],
        ['Combien de wagons a ton train ? → Corrigé : 3.',
         'Comment as-tu fixé les roues ? → Corrigé : avec de la colle.',
         'De quelle couleur est ton train ? → Corrigé : réponse personnelle.',
         'Où va ton train imaginaire ? → Corrigé : réponse personnelle.',
         'Qu\'as-tu aimé dans cette activité ? → Corrigé : réponse personnelle.']),

      m('A.P.S.','Le jeu du train — courir en file indienne',
        'Se déplacer en file indienne en imitant un train. Changer de vitesse. Respect des autres.',
        ['Former une longue file : chaque élève tient les épaules de celui devant',
         'Se déplacer : d\'abord lentement, puis plus vite',
         'Tourner, slalomer, s\'arrêter'],
        ['Qu\'est-ce qu\'une file indienne ? → Corrigé : une file de personnes qui se suivent.',
         'Comment représente-t-on le train avec les élèves ? → Corrigé : on se tient les épaules en file.',
         'Quel est l\'élève de tête ? → Corrigé : la locomotive.',
         'Que fais-tu si le train ralentit ? → Corrigé : je ralentis aussi pour ne pas pousser.',
         'A-t-on bien coopéré ? → Corrigé : réponse collective.']),

      m('ENVIRONNEMENT','Les routes et la nature — pollution',
        'Les routes et voitures traversent la nature. Pollution des voitures. Protéger la nature en prenant les transports collectifs.',
        ['Observer image : route en forêt',
         'Discussion : "Les voitures font de la fumée, c\'est bien ou pas bien ?"',
         'Solution : prendre le bus plutôt que chaque voiture seule'],
        ['Les voitures polluent-elles l\'air ? → Corrigé : oui, elles font de la fumée.',
         'Qu\'est-ce que la pollution ? → Corrigé : quand on salit l\'air, l\'eau ou la nature.',
         'Comment peut-on moins polluer en se déplaçant ? → Corrigé : prendre le bus, marcher, faire du vélo.',
         'Cite 1 transport non polluant. → Corrigé : vélo, marche à pied, pirogue (vent).',
         'Pourquoi faut-il protéger la nature ? → Corrigé : parce qu\'on en a besoin pour vivre (eau, air, nourriture).']),

      m('ANGLAIS','Transport words',
        'Apprendre les mots en anglais : car, bus, bike, plane, boat. Jeu de devinettes.',
        ['"It flies in the sky." (avion) → plane',
         '"It goes on water." (bateau) → boat',
         '"Simon says : be a plane !"'],
        ['How do you say "voiture" in English ? → Corrigé : car.',
         'How do you say "avion" in English ? → Corrigé : plane.',
         '"It goes on water." What is it ? → Corrigé : boat.',
         '"It has two wheels." What is it ? → Corrigé : bike.',
         'How do you say "bus" in English ? → Corrigé : bus (même mot).']),

    ]
  },

  {
    n:2, dates:'12/01/2026 – 16/01/2026',
    theme:'Voyage · Lettre G ronde · Compter 1-25 · Additions et soustractions variées',
    matieres:[

      m('HYGIÈNE','Hygiène en voyage',
        'Quand on voyage, hygiène dans les transports publics. Se laver les mains après le voyage. Ne pas manger sans se laver les mains dans le taxi-brousse.',
        ['Scénario : voyage en taxi-brousse',
         '"Que fais-tu à l\'arrivée ?"',
         'Règle : "Je me lave les mains dès mon arrivée"'],
        ['Pourquoi se laver les mains après un voyage ? → Corrigé : on a touché beaucoup de surfaces potentiellement sales.',
         'Que fait-on si on éternue dans le transport ? → Corrigé : on couvre sa bouche.',
         'Cite 2 objets sales dans un transport public. → Corrigé : poignée, siège, vitre.',
         'Que faire pour ne pas attraper de microbes en voyage ? → Corrigé : ne pas toucher le visage, se laver les mains à l\'arrivée.',
         'Est-il hygiénique de manger dans le taxi-brousse ? → Corrigé : non, car les mains peuvent être sales.']),

      m('I.C.','Les voyages et les régions de Madagascar',
        'Qu\'il y a plusieurs régions à Madagascar. Pour voyager loin, on prend le taxi-brousse. La grande île.',
        ['Montrer une carte simple de Madagascar avec 2-3 régions',
         'Discussion : "As-tu déjà voyagé dans une autre ville ?"',
         'Entourer Antananarivo sur la carte'],
        ['Madagascar est-il grand ou petit ? → Corrigé : grand (c\'est la 4ème plus grande île du monde).',
         'Comment voyage-t-on entre les régions de Madagascar ? → Corrigé : taxi-brousse, avion, voiture.',
         'Cite 1 autre ville de Madagascar. → Corrigé : Tamatave, Majunga, Tuléar, Diego...',
         'As-tu déjà voyagé ? → Corrigé : réponse personnelle.',
         'Pourquoi les régions sont-elles différentes les unes des autres ? → Corrigé : climat différent, paysages, langues...']),

      m('MORAL','La générosité',
        'Partager ce qu\'on a. Donner sans attendre de retour. Donner à quelqu\'un qui en a besoin.',
        ['Histoire : un enfant qui partage son goûter',
         '"Est-ce que tu es généreux ?"',
         'Défi : faire 1 action généreuse aujourd\'hui'],
        ['Qu\'est-ce que la générosité ? → Corrigé : donner, partager ce qu\'on a avec les autres.',
         'Cite 1 action généreuse. → Corrigé : partager son repas, aider, prêter un crayon.',
         'Comment te sens-tu quand tu donnes quelque chose ? → Corrigé : bien, content, fier.',
         'Est-il plus beau de donner ou de recevoir ? → Corrigé : discussion ouverte (donner = souvent plus beau).',
         'Quelle action généreuse feras-tu aujourd\'hui ? → Corrigé : réponse personnelle.']),

      m('CONTE','Le petit train (S2 — montée de la montagne)',
        'Suite du conte. Le train commence à grimper. Difficulté. "Je peux ! Je peux !"',
        ['Relire S1 + lire S2',
         'Répétition : "Je peux ! Je peux !" en chœur',
         'Questions de compréhension'],
        ['Que fait le train dans cette partie ? → Corrigé : il grimpe la montagne.',
         'Qu\'est-ce que le train se dit ? → Corrigé : "Je peux ! Je peux !".',
         'Est-ce que la montée est facile ? → Corrigé : non, c\'est difficile.',
         'Que penses-tu du courage du train ? → Corrigé : réponse personnelle.',
         'As-tu déjà fait quelque chose de difficile ? → Corrigé : réponse personnelle.']),

      m('LANGAGE','Décrire un voyage — phrases',
        'Construire des phrases sur le voyage : "Je suis allé à... en... C\'était..."',
        ['"J\'habite à ___, je suis allé à ___ en ___."',
         'Images de destinations : mer, montagne, ville, village',
         'Choisir et décrire'],
        ['Décris un voyage imaginaire. → Corrigé : réponse personnelle.',
         'Qu\'as-tu vu lors d\'un voyage ? → Corrigé : réponse personnelle.',
         'Quel transport prendrais-tu pour aller à la mer ? → Corrigé : voiture, taxi-brousse, pirogue.',
         'Comment te sens-tu quand tu voyages ? → Corrigé : réponse personnelle.',
         'Construis la phrase : "Je vais à ___ en ___." → Corrigé : production personnelle.']),

      m('PRÉ-LECTURE','Graphisme — lettre G ronde et Q',
        'Tracer G : cercle + petite queue horizontale. Tracer Q : cercle + petite diagonale.',
        ['Tracer G : cercle antihoraire + barre à l\'intérieur',
         'Tracer Q : cercle + petite queue',
         'Comparer O, C, G, Q sur le tableau'],
        ['Trace 5 G. → Corrigé : évaluation.',
         'Trace 5 Q. → Corrigé : évaluation.',
         'Quelle est la différence entre C et G ? → Corrigé : G a une petite barre horizontale à l\'intérieur.',
         'Quelle est la différence entre O et Q ? → Corrigé : Q a une petite queue.',
         'Cite 4 lettres rondes que tu connais. → Corrigé : O, C, G, Q.']),

      m('NUMÉRATION','Compter jusqu\'à 25',
        'Continuer : 23, 24, 25. Vingt = 2 dizaines, vingt-cinq = 2 dizaines + 5 unités.',
        ['Compter de 1 à 25',
         'Afficher 23, 24, 25',
         'Dénombrement : 25 objets'],
        ['Compte de 20 à 25. → Corrigé : 20, 21, 22, 23, 24, 25.',
         'Quel nombre vient après 24 ? → Corrigé : 25.',
         'Quel nombre vient avant 23 ? → Corrigé : 22.',
         'Montre 25 bâtons. → Corrigé : dénombrement.',
         'Quel est le plus grand : 19 ou 25 ? → Corrigé : 25.']),

      m('CALCUL','Additions et soustractions — problèmes variés',
        'Alterner additions et soustractions. Problèmes de la vie réelle : acheter, donner, recevoir.',
        ['Problème marché : "J\'achète 3 mangues. Je paie. Il m\'en reste... sur 10."',
         'Ardoise : 3+5=___, 9−3=___',
         'Corriger avec les doigts ou les jetons'],
        ['6+3=___. → Corrigé : 9.',
         '8−5=___. → Corrigé : 3.',
         '4+4=___. → Corrigé : 8.',
         'Problème : 7 élèves dans la salle. 3 sortent. Combien reste ? → Corrigé : 4.',
         'Problème : j\'ai 2 bonbons, on m\'en donne 5. Combien en tout ? → Corrigé : 7.']),

      m('DESSIN','Dessin de voyage — paysage',
        'Dessiner un paysage vu du transport : mer, montagne, forêt, village. Lignes horizontales pour la terre, courbes pour les montagnes.',
        ['Observer images de paysages malgaches',
         'Choisir un paysage et dessiner',
         'Colorier avec des couleurs appropriées'],
        ['Quel paysage as-tu dessiné ? → Corrigé : réponse personnelle.',
         'Comment as-tu dessiné la montagne ? → Corrigé : lignes obliques/pyramide.',
         'Quelle couleur as-tu choisie pour la mer ? → Corrigé : bleu.',
         'Quelle couleur pour la forêt ? → Corrigé : vert.',
         'As-tu déjà vu ce paysage pour de vrai ? → Corrigé : réponse personnelle.']),

      m('CHANT','Chanson "Si tu as de la joie en toi"',
        'Apprendre "Si tu as de la joie en toi, tape des mains !" Mimer les actions.',
        ['"Si tu as de la joie en toi, tape des mains — CLAP CLAP"',
         '"...frappe du pied..." / "...dis hourra !"',
         'Chanter très vite, très lentement'],
        ['Chante "Si tu as de la joie...". → Corrigé : performance orale.',
         'Qu\'est-ce qu\'on fait dans le premier couplet ? → Corrigé : taper des mains.',
         'Mime "frappe du pied". → Corrigé : geste.',
         'Comment te sens-tu quand tu chantes cette chanson ? → Corrigé : joyeux.',
         'Chante seul devant la classe. → Corrigé : performance.']),

      m('RÉCITATION','Comptine "Promenons-nous dans les bois" — révision + nouveau couplet',
        'Réviser la comptine + ajouter un nouveau couplet. Mémoriser l\'ensemble.',
        ['Réviser les 2 premiers couplets',
         'Apprendre le couplet : "Je mets mes habits... Je mets mes chaussures..."',
         'Réciter en entier'],
        ['Récite "Promenons-nous dans les bois" en entier. → Corrigé : performance orale.',
         'Qu\'est-ce que le loup fait dans la forêt ? → Corrigé : il s\'habille.',
         'Que met-il en premier ? → Corrigé : sa chemise / ses habits.',
         'Que dit-on au loup quand il est prêt ? → Corrigé : "Loup y es-tu ? M\'entends-tu ?"',
         'Que répond le loup à la fin ? → Corrigé : "Je suis là et JE VOUS MANGE !"']),

      m('T.M.','Maquette d\'un véhicule en pâte à modeler',
        'Modeler un véhicule (voiture, bateau, avion) avec de la pâte à modeler. Motricité fine.',
        ['Modeler la forme principale',
         'Ajouter les détails : roues, ailes, cabine',
         'Présenter son véhicule à la classe'],
        ['Quel véhicule as-tu fabriqué ? → Corrigé : réponse personnelle.',
         'Quelles parties as-tu modelées ? → Corrigé : réponse personnelle.',
         'De quelle couleur est ta pâte ? → Corrigé : réponse personnelle.',
         'Quel est le rôle de ton véhicule ? → Corrigé : réponse personnelle.',
         'Combien de pièces a ton véhicule ? → Corrigé : réponse personnelle.']),

      m('A.P.S.','Course d\'obstacles — le parcours du train',
        'Parcours motricité : ramper sous une table, sauter par-dessus une ligne, slalomer. Images du voyage.',
        ['Ramper sous la table = passer dans un tunnel',
         'Sauter par-dessus la ligne = traverser une rivière',
         'Slalomer = virages de montagne'],
        ['As-tu terminé le parcours ? → Corrigé : réponse.',
         'Quel obstacle était le plus difficile ? → Corrigé : réponse personnelle.',
         'Que représentait le tunnel ? → Corrigé : une table / galerie.',
         'As-tu aidé un camarade ? → Corrigé : réponse personnelle.',
         'Quel mouvement de sport as-tu préféré ? → Corrigé : réponse personnelle.']),

      m('ENVIRONNEMENT','Les paysages malgaches — mer, montagne, forêt',
        'Les 3 grands types de paysages à Madagascar : côte/mer, hauts plateaux/montagne, forêt. Chaque région a ses richesses.',
        ['Images des 3 paysages',
         'Trier : marine / montagne / forêt',
         'Discussion : "Quel paysage préfères-tu ?"'],
        ['Cite 2 paysages de Madagascar. → Corrigé : mer/côte, montagne/hauts plateaux, forêt.',
         'Quel animal vit en forêt ? → Corrigé : lémurien, caméléon, fossa.',
         'Quel animal vit dans la mer ? → Corrigé : poisson, crevette, baleine.',
         'Qu\'y a-t-il au sommet d\'une montagne ? → Corrigé : rochers, peu de végétation, parfois de la brume.',
         'Quel paysage préfères-tu ? → Corrigé : réponse personnelle.']),

      m('ANGLAIS','Colors revision + transport colours',
        'Réviser toutes les couleurs + les utiliser pour décrire les transports : "The bus is yellow. The sky is blue."',
        ['Flash cards couleurs × 8',
         '"The car is ___." (montrer une voiture rouge) → red',
         '"The sea is ___." → blue'],
        ['What color is the grass ? → Corrigé : green.',
         'What color is the sun ? → Corrigé : yellow.',
         'Say the color of my shirt. → Corrigé : réponse selon couleur de la chemise.',
         'What color is the sky ? → Corrigé : blue.',
         'The bus is ___. (couleur choisie) → Corrigé : réponse personnelle.']),

    ]
  },

  {
    n:3, dates:'19/01/2026 – 23/01/2026',
    theme:'Les animaux sauvages · Lettres bastonnées (I/L/T/H) · Compter 1-28 · Multiplication notion',
    matieres:[

      m('HYGIÈNE','Hygiène avec les animaux',
        'Se laver les mains après avoir touché un animal. Ne pas embrasser les animaux. Les microbes des animaux.',
        ['Discussion : "Tu as un animal chez toi ?"',
         'Règle : "Après avoir touché un animal, je me lave les mains"',
         'Images de bons et mauvais comportements avec les animaux'],
        ['Pourquoi se laver les mains après avoir touché un animal ? → Corrigé : les animaux peuvent porter des microbes.',
         'Est-il prudent d\'embrasser un chien sur le museau ? → Corrigé : non, c\'est peu hygiénique.',
         'Que fait-on si on a été griffé par un chat ? → Corrigé : nettoyer la plaie et montrer à un adulte.',
         'Cite 1 animal qu\'on peut toucher sans risque. → Corrigé : animal domestique vacciné.',
         'Cite 1 animal dangereux à toucher. → Corrigé : serpent, guêpe, scorpion.']),

      m('I.C.','Les animaux sauvages de Madagascar',
        'Revoir les animaux endémiques : lémuriens, fossa, aye-aye, caméléon géant, raie, baleines. Menaces : déforestation.',
        ['Images des animaux endémiques',
         'Jeu de cartes : associer animal + habitat',
         'Discussion : "Pourquoi ces animaux sont-ils en danger ?"'],
        ['Cite 3 animaux endémiques de Madagascar. → Corrigé : lémurien, caméléon, fossa, aye-aye.',
         'Qu\'est-ce qu\'un animal endémique ? → Corrigé : un animal qu\'on ne trouve que dans 1 seul pays.',
         'Quel animal endémique de Madagascar ressemble à un singe ? → Corrigé : le lémurien.',
         'Pourquoi les animaux sauvages sont-ils en danger ? → Corrigé : déforestation, chasse, pollution.',
         'Que peut-on faire pour protéger les animaux ? → Corrigé : ne pas les chasser, protéger la forêt.']),

      m('MORAL','Le respect des animaux',
        'Ne pas maltraiter les animaux. Les animaux ressentent la douleur. Respecter toute vie.',
        ['Discussion : "As-tu déjà vu quelqu\'un maltraiter un animal ?"',
         'Histoire : un enfant qui protège un oiseau blessé',
         'Règle : "Je respecte toute vie, même les insectes"'],
        ['Est-il correct de battre un animal ? → Corrigé : non, les animaux ressentent la douleur.',
         'Que fais-tu si tu vois un animal blessé ? → Corrigé : prévenir un adulte, ne pas le toucher soi-même.',
         'Pourquoi faut-il respecter les animaux ? → Corrigé : ils sont vivants, ils ressentent, ils ont un rôle dans la nature.',
         'Cite 1 façon de respecter un animal domestique. → Corrigé : le nourrir, lui donner de l\'eau, ne pas le frapper.',
         'Cite 1 façon de respecter un animal sauvage. → Corrigé : ne pas le chasser, ne pas détruire son habitat.']),

      m('CONTE','Le petit train (S3 — arrivée au sommet)',
        'Le train arrive au sommet. Victoire ! Récompense : une belle vue.',
        ['Lire S3 avec expression',
         'Célébrer avec les élèves : "On a réussi !"',
         'Discussion : "Quelle est la leçon du conte ?"'],
        ['Qu\'est-ce que le train a réussi à faire ? → Corrigé : traverser / grimper la montagne.',
         'Comment le train se sentait-il au sommet ? → Corrigé : fier, heureux.',
         'Quelle est la leçon du conte ? → Corrigé : avec de la persévérance, on peut réussir.',
         'As-tu déjà réussi quelque chose de difficile ? → Corrigé : réponse personnelle.',
         'Raconte le conte en 3 phrases. → Corrigé : résumé oral.']),

      m('LANGAGE','Les animaux sauvages — vocabulaire',
        'Nommer, décrire les animaux sauvages. "Le lémurien vit dans la forêt. Il a de grandes oreilles."',
        ['Images d\'animaux : nommer et décrire',
         '"Il vit dans la forêt / à la mer / dans la savane"',
         'Devinettes : "Je suis petit, j\'ai une longue queue, je grimpe aux arbres. Qui suis-je ?"'],
        ['Décris le lémurien. → Corrigé : petit primate, grandes oreilles, longue queue, vit en forêt.',
         'Où vit le caméléon ? → Corrigé : dans les arbres, en forêt.',
         'Que mange un aye-aye ? → Corrigé : des insectes et des larves dans les arbres.',
         'Quel animal change de couleur ? → Corrigé : le caméléon.',
         'Quelle devinette peux-tu inventer ? → Corrigé : production personnelle.']),

      m('PRÉ-LECTURE','Graphisme — lettres bastonnées : I, L, T, H',
        'Préparer les lettres avec des traits verticaux et horizontaux. I = 1 trait vertical, L = trait vertical + horizontal bas, T = vertical + horizontal haut, H = 2 verticaux + horizontal milieu.',
        ['Tracer dans l\'air : I',
         'Tracer sur l\'ardoise : L, T, H',
         'Identifier les lettres dans les prénoms des élèves'],
        ['Trace 5 lettres I. → Corrigé : évaluation.',
         'Trace 5 lettres L. → Corrigé : évaluation.',
         'Trace 5 lettres T. → Corrigé : évaluation.',
         'Quelle lettre ressemble à une fourche ? → Corrigé : T.',
         'Quelle lettre ressemble à une échelle ? → Corrigé : H.']),

      m('NUMÉRATION','Compter jusqu\'à 28',
        'Continuer : 26, 27, 28. Décomposer en dizaines et unités. 28 = 2 dizaines + 8 unités.',
        ['Compter de 20 à 28',
         'Tableau dizaines/unités : 28 = 2D + 8U',
         'Dénombrement : 28 graines'],
        ['Compte de 20 à 28. → Corrigé : 20, 21, 22, 23, 24, 25, 26, 27, 28.',
         'Quel nombre vient après 27 ? → Corrigé : 28.',
         'Décompose 28 en dizaines et unités. → Corrigé : 2 dizaines + 8 unités.',
         'Ordonne : 28, 15, 7, 23. → Corrigé : 7, 15, 23, 28.',
         'Quel est le plus petit : 22 ou 28 ? → Corrigé : 22.']),

      m('CALCUL','Notion de multiplication — groupes égaux',
        'Introduire la notion de multiplication comme des groupes égaux. 3 × 2 = 2 + 2 + 2 = 6. Avec objets.',
        ['3 groupes de 2 jetons : "3 fois 2 jetons, combien en tout ?"',
         '2 × 4 = ? (avec doigts)',
         'Problème : 4 élèves ont chacun 2 crayons. Combien de crayons en tout ?'],
        ['2+2+2 = ___. C\'est 3 groupes de 2 = ___. → Corrigé : 6.',
         '3+3 = ___. C\'est 2 groupes de 3 = ___. → Corrigé : 6.',
         '4 élèves ont 2 crayons chacun. Combien de crayons en tout ? → Corrigé : 8.',
         '2 paires de chaussures = ___ chaussures. → Corrigé : 4.',
         '3 voitures avec 4 roues chacune = ___ roues. → Corrigé : 12.']),

      m('DESSIN','Dessin d\'un animal sauvage',
        'Dessiner son animal sauvage préféré. Utiliser les formes de base. Colorier avec les bonnes couleurs.',
        ['Choisir un animal malgache',
         'Dessiner avec des formes simples : ovales, cercles, triangles',
         'Colorier correctement + nommer'],
        ['Quel animal as-tu dessiné ? → Corrigé : réponse personnelle.',
         'Quelles formes as-tu utilisées ? → Corrigé : cercle (tête), ovale (corps)...',
         'Comment est coloré ton animal ? → Corrigé : réponse personnelle.',
         'Où vit ton animal ? → Corrigé : forêt, mer, savane...',
         'Es-tu content de ton dessin ? → Corrigé : réponse personnelle.']),

      m('CHANT','Chanson des animaux — "Dans la forêt lointaine"',
        'Apprendre "Dans la forêt lointaine, on entend le coucou / du haut de son grand chêne."',
        ['Apprendre le refrain',
         'Mimer chaque animal mentionné',
         'Chanter + mimer ensemble'],
        ['Chante "Dans la forêt lointaine". → Corrigé : performance orale.',
         'Quel animal chante dans la forêt ? → Corrigé : le coucou.',
         'Où est perché le coucou ? → Corrigé : sur son grand chêne.',
         'Mime le coucou. → Corrigé : battement d\'ailes.',
         'Quel oiseau vit dans la forêt malgache ? → Corrigé : coua, fody, martin-pêcheur...']),

      m('RÉCITATION','Comptine — "Ani, le lémurien"',
        'Comptine créée : "Ani, le lémurien, saute d\'arbre en arbre, avec ses grands yeux ronds, il voit tout dans la nuit noire."',
        ['Apprendre ligne par ligne',
         'Mimer le lémurien qui saute',
         'Réciter seul avec les gestes'],
        ['Récite la comptine. → Corrigé : performance orale.',
         'Qui est Ani ? → Corrigé : un lémurien.',
         'Que fait Ani ? → Corrigé : il saute d\'arbre en arbre.',
         'Comment sont les yeux du lémurien ? → Corrigé : grands et ronds.',
         'Mime un lémurien qui saute. → Corrigé : geste de bond.']),

      m('T.M.','Masque d\'animal',
        'Fabriquer un masque simple d\'animal. Découper les yeux, coller, décorer.',
        ['Découper le contour du masque',
         'Faire les trous pour les yeux',
         'Décorer : oreilles, moustaches, couleurs'],
        ['Quel animal est ton masque ? → Corrigé : réponse personnelle.',
         'Comment as-tu fait les oreilles ? → Corrigé : découpées et collées.',
         'Quel outil as-tu utilisé ? → Corrigé : ciseaux, colle.',
         'Est-ce difficile de découper ? → Corrigé : réponse personnelle.',
         'Mime l\'animal de ton masque. → Corrigé : performance.']),

      m('A.P.S.','Jeu des animaux — imitation motrice',
        'Imiter les déplacements des animaux : sauter comme un grenouille, ramper comme un serpent, marcher comme un éléphant.',
        ['Grenouille : sauter des deux pieds',
         'Serpent : ramper sur le ventre',
         'Éléphant : marcher lourd + trompe'],
        ['Montre comment saute une grenouille. → Corrigé : deux pieds ensemble.',
         'Montre comment rampe un serpent. → Corrigé : sur le ventre.',
         'Montre comment marche un éléphant. → Corrigé : lourd, bras pendants.',
         'Quel mouvement est le plus difficile ? → Corrigé : réponse personnelle.',
         'Quel animal es-tu le plus fort à imiter ? → Corrigé : réponse personnelle.']),

      m('ENVIRONNEMENT','Les forêts de Madagascar — richesse et menace',
        'Madagascar = l\'une des plus grandes biodiversités du monde. La forêt est menacée par le tavy et la déforestation. Ce qu\'on peut faire.',
        ['Images : forêt intacte vs zone brûlée',
         'Discussion : "Pourquoi brûle-t-on les forêts ?"',
         'Solution : planter des arbres, recycler'],
        ['Qu\'est-ce que la biodiversité ? → Corrigé : la variété des plantes et des animaux dans un endroit.',
         'Qu\'est-ce que le tavy ? → Corrigé : brûler la forêt pour faire des champs.',
         'Pourquoi le tavy est-il mauvais ? → Corrigé : il détruit les habitats des animaux et érode le sol.',
         'Cite 1 solution pour protéger la forêt. → Corrigé : planter des arbres, utiliser les ressources avec modération.',
         'Pourquoi Madagascar est-elle si spéciale ? → Corrigé : parce qu\'elle a des animaux qu\'on ne trouve nulle part ailleurs.']),

      m('ANGLAIS','Animals — wild and domestic',
        'Apprendre les animaux sauvages en anglais : lion, monkey, elephant, snake, bird, fish. + animaux domestiques déjà appris.',
        ['Flash cards animaux',
         '"What animal is this ?" (image lémurien) → "It\'s a lemur."',
         '"Simon says : be a monkey !"'],
        ['How do you say "lémurien" in English ? → Corrigé : lemur.',
         'How do you say "oiseau" ? → Corrigé : bird.',
         'What sound does a monkey make ? → Corrigé : ooh-ooh-aah-aah !',
         'How do you say "serpent" ? → Corrigé : snake.',
         '"Simon says : be a snake !" → Corrigé : geste.']),

    ]
  },

  {
    n:4, dates:'26/01/2026 – 30/01/2026',
    theme:'ÉVALUATION — Bilan janvier 12ème',
    matieres:[
      m('ÉVALUATION','Évaluation de janvier — 12ème',
        'Évaluation de fin de mois de janvier pour la 12ème pré-primaire. Exercices oraux, graphisme, numération jusqu\'à 25.',
        ['Lundi 26/01 : épreuve langage + numération',
         'Mardi 27/01 : épreuve graphisme + dessin',
         'Mercredi 28/01 : épreuve oral (chant, comptine, hygiène)',
         'Jeudi-vendredi : correction + activités libres'],
        [
          '══ LANGAGE (oral) ══',
          'Cite 4 moyens de transport. → Corrigé : voiture, bateau, avion, vélo.',
          'Cite 3 animaux sauvages de Madagascar. → Corrigé : lémurien, caméléon, fossa.',
          'Fais une phrase avec "Le train...". → Corrigé : production orale.',
          '',
          '══ NUMÉRATION ══',
          'Compte de 1 à 25. → Corrigé : performance orale.',
          'Quel nombre vient après 22 ? → Corrigé : 23.',
          'Quel est le plus grand : 18 ou 25 ? → Corrigé : 25.',
          'Montre 20 avec des bâtons. → Corrigé : dénombrement.',
          '',
          '══ CALCUL ══',
          '5+4=___. → Corrigé : 9.',
          '8−3=___. → Corrigé : 5.',
          '3 groupes de 2 = ___. → Corrigé : 6.',
          'Problème : 6 enfants, 2 partent. Combien reste ? → Corrigé : 4.',
          '',
          '══ GRAPHISME ══',
          'Trace 3 lettres O. → Corrigé : évaluation.',
          'Trace 3 lettres C et 3 lettres G. → Corrigé : évaluation.',
          'Trace 3 lettres I et 3 lettres L. → Corrigé : évaluation.',
          '',
          '══ DESSIN ══',
          'Dessine un animal sauvage de Madagascar. → Corrigé : production.',
          'Colorie un transport. → Corrigé : production.',
          '',
          '══ ORAL ══',
          'Chante "Petit train". → Corrigé : performance orale.',
          'Récite "En voiture Simone". → Corrigé : performance orale.',
          'Montre les gestes du lavage de mains. → Corrigé : performance.',
          'How do you say "lémurien" in English ? → Corrigé : lemur.',
        ]
      ),
    ]
  },

];

module.exports = { JANVIER_12EME };
