'use strict';
// RÉPARTITION 12ÈME — AVRIL 2026
// 3ème trimestre commence · S4 = Évaluation de fin de mois

function m(mat, topic, approche, activites, exercices) {
  return { matiere:mat, topic, approche, activites, exercices };
}

const AVRIL_12EME = [

  {
    n:1, dates:'06/04/2026 – 10/04/2026',
    theme:'Retour de vacances · Les couleurs et formes revisitées · Lettres E/F · Compter 1-50 · Division notion',
    matieres:[

      m('HYGIÈNE','Hygiène après les vacances',
        'Reprendre les bonnes habitudes après les vacances : régularité du sommeil, propreté, routine du matin. Retour à l\'école = retour aux règles.',
        ['Discussion : "Qu\'as-tu fait pendant les vacances ?"',
         'Rappel de la routine du matin : lever, toilette, petit déjeuner, école',
         'Règle : "À la rentrée, je reprends mes bonnes habitudes"'],
        ['Cite 3 bonnes habitudes à reprendre après les vacances. → Corrigé : dormir tôt, se laver, manger équilibré.',
         'À quelle heure doit-on se lever pour aller à l\'école ? → Corrigé : réponse selon l\'école.',
         'Que mange-t-on le matin ? → Corrigé : petit déjeuner (riz, pain, fruits).',
         'Combien d\'heures doit dormir un enfant de 5 ans ? → Corrigé : 10-12 heures.',
         'Qu\'est-ce que la routine ? → Corrigé : faire les mêmes choses dans le même ordre chaque jour.']),

      m('I.C.','Pâques et les fêtes de printemps',
        'Pâques est une fête célébrée en mars/avril. Traditions : œufs de Pâques, famille. Fête religieuse chrétienne. Respect des différentes religions à Madagascar.',
        ['Images d\'œufs de Pâques, fêtes familiales',
         'Discussion : "As-tu fêté Pâques ? Comment ?"',
         'Rappel : pas tout le monde fête Pâques (respect)'],
        ['Qu\'est-ce que Pâques ? → Corrigé : une fête chrétienne célébrée au printemps.',
         'Quel objet est le symbole de Pâques ? → Corrigé : l\'œuf.',
         'Comment fête-t-on Pâques à Madagascar ? → Corrigé : messe, repas en famille, chasse aux œufs (pour certains).',
         'Tout le monde fête-t-il Pâques ? → Corrigé : non, seulement les chrétiens.',
         'Pourquoi respecte-t-on les différentes religions ? → Corrigé : parce que chacun a le droit de croire ce qu\'il veut.']),

      m('MORAL','La persévérance',
        'Ne pas abandonner quand c\'est difficile. Essayer encore. Repenser à la fable du petit train. Valoriser les efforts.',
        ['Rappel du conte du petit train : "Je peux ! Je peux !"',
         'Discussion : "As-tu déjà abandonné quelque chose ? Regrettes-tu ?"',
         'Règle : "J\'essaie encore même si c\'est difficile"'],
        ['Qu\'est-ce que la persévérance ? → Corrigé : continuer même quand c\'est difficile.',
         'Cite 1 exemple de persévérance. → Corrigé : continuer à apprendre à lire même si c\'est difficile, continuer à s\'entraîner pour courir plus vite.',
         'Que fais-tu quand tu n\'arrives pas à faire un exercice ? → Corrigé : je demande de l\'aide, j\'essaie autrement, je recommence.',
         'Quelle valeur le petit train nous a-t-il montrée ? → Corrigé : la persévérance.',
         'À quoi sert de persévérer ? → Corrigé : à finalement réussir ce qu\'on voulait faire.']),

      m('CONTE','Nouveau conte — La petite abeille (S1)',
        '3ème trimestre, nouveau conte : la petite abeille qui apprend à faire du miel. S1 : découverte de la ruche.',
        ['Présenter les images : abeille, fleur, ruche, miel',
         'Lire S1 avec expressions variées',
         'Questions de compréhension'],
        ['Qui est le personnage du conte ? → Corrigé : une petite abeille.',
         'Où vit l\'abeille ? → Corrigé : dans une ruche.',
         'Que produit l\'abeille ? → Corrigé : du miel.',
         'As-tu déjà goûté du miel ? → Corrigé : réponse personnelle.',
         'Prédis la suite. → Corrigé : prédiction libre.']),

      m('LANGAGE','Les saisons et la nature en avril',
        'En avril à Madagascar, c\'est la fin de la saison des pluies. Observer les changements. Vocabulaire : saison sèche, saison des pluies, transition.',
        ['Observer dehors : y a-t-il encore de la pluie ?',
         '"Qu\'est-ce qui change dans la nature en ce moment ?"',
         'Comparer : octobre (début des pluies) / avril (fin des pluies)'],
        ['Quelle saison commence à s\'installer en avril ? → Corrigé : la saison sèche (hiiver austral).',
         'Comment est la végétation en avril ? → Corrigé : encore verte mais commence à sécher.',
         'Quel temps fait-il moins souvent en avril ? → Corrigé : la pluie.',
         'Que font les agriculteurs à la fin des pluies ? → Corrigé : ils récoltent, ils préparent les champs.',
         'Cite 1 changement que tu observes dans la nature en ce moment. → Corrigé : réponse personnelle.']),

      m('PRÉ-LECTURE','Graphisme — lettres E et F',
        'Tracer E : 1 trait vertical + 3 traits horizontaux. Tracer F : 1 trait vertical + 2 traits horizontaux (haut et milieu).',
        ['Tracer E dans l\'air : "Je descends, puis 3 barres à droite"',
         'Tracer F dans l\'air : "Même chose mais sans la barre du bas"',
         'Comparer E et F sur le tableau'],
        ['Trace 5 lettres E. → Corrigé : évaluation.',
         'Trace 5 lettres F. → Corrigé : évaluation.',
         'Quelle différence entre E et F ? → Corrigé : E a 3 barres horizontales, F en a 2 (sans la barre du bas).',
         'Combien de barres horizontales a E ? → Corrigé : 3.',
         'Combien de barres horizontales a F ? → Corrigé : 2.']),

      m('NUMÉRATION','Compter jusqu\'à 50',
        'Grand pas : compter jusqu\'à 50. 50 = 5 dizaines. Compter par 10 : 10, 20, 30, 40, 50.',
        ['Compter de 40 à 50',
         'Compter par dizaines : 10, 20, 30, 40, 50',
         '50 = 5 paquets de 10'],
        ['Compte de 40 à 50. → Corrigé : 40, 41, 42, ..., 50.',
         'Compte par 10 jusqu\'à 50. → Corrigé : 10, 20, 30, 40, 50.',
         '50 = ___ dizaines. → Corrigé : 5.',
         'Quel nombre vient avant 50 ? → Corrigé : 49.',
         'Ordonne : 50, 23, 41, 8. → Corrigé : 8, 23, 41, 50.']),

      m('CALCUL','Division notion — partager équitablement',
        'Introduire la division comme partage équitable. 12 ÷ 4 = 3. "Si on partage 12 bonbons entre 4 amis, chacun a combien ?"',
        ['12 jetons partagés en 4 groupes égaux',
         '"Combien dans chaque groupe ?"',
         'Problème : 8 enfants partagent 16 bonbons. Chacun a ___'],
        ['Partage 10 bâtons en 2 groupes égaux. Chaque groupe a ___. → Corrigé : 5.',
         'Partage 12 en 3. Chaque groupe a ___. → Corrigé : 4.',
         'Partage 8 en 4. → Corrigé : 2.',
         'Problème : 15 billes partagées entre 3 enfants = ___ chacun. → Corrigé : 5.',
         'Problème : 20 gâteaux pour 4 tables = ___ par table. → Corrigé : 5.']),

      m('DESSIN','Œuf de Pâques décoré',
        'Dessiner et décorer un grand œuf de Pâques avec des motifs géométriques : cercles, lignes, triangles, zigzags.',
        ['Tracer l\'ovale (œuf)',
         'Remplir avec des motifs variés',
         'Colorier avec des couleurs vives'],
        ['Quels motifs as-tu utilisés ? → Corrigé : cercles, zigzags, points, rayures.',
         'Combien de couleurs as-tu utilisées ? → Corrigé : réponse personnelle.',
         'Quel motif préfères-tu ? → Corrigé : réponse personnelle.',
         'Comment s\'appelle la forme de l\'œuf ? → Corrigé : ovale / ellipse.',
         'À qui offres-tu ton œuf de Pâques ? → Corrigé : réponse personnelle.']),

      m('CHANT','Chanson des abeilles — "Bourdonnant, bourdonnant"',
        '"Bourdonnant, bourdonnant, la petite abeille / vole de fleur en fleur pour faire son miel !"',
        ['Apprendre les paroles',
         'Mimer l\'abeille qui vole',
         'Chanter avec un bourdonnement sur "bourdonnant"'],
        ['Chante "Bourdonnant, bourdonnant". → Corrigé : performance.',
         'Qu\'est-ce que "bourdonner" ? → Corrigé : faire le son "bzzz" des abeilles.',
         'Que fait la petite abeille dans la chanson ? → Corrigé : elle vole de fleur en fleur.',
         'Pour quoi fait-elle cela ? → Corrigé : pour faire du miel.',
         'Mime l\'abeille qui vole. → Corrigé : geste de bras / voler.']),

      m('RÉCITATION','Comptine — "L\'abeille et le bourdon"',
        '"L\'abeille dit au bourdon : / partage avec moi ce miel doré ! / Le bourdon répond : bien sûr / il y en a pour tous les deux !"',
        ['Apprendre par cœur en 2 jours',
         'Jouer la scène : abeille + bourdon',
         'Réciter avec les gestes'],
        ['Récite "L\'abeille et le bourdon". → Corrigé : performance.',
         'Que demande l\'abeille ? → Corrigé : partager le miel.',
         'Que répond le bourdon ? → Corrigé : oui, il accepte de partager.',
         'Quelle valeur voit-on dans cette comptine ? → Corrigé : le partage.',
         'Mime l\'abeille qui demande. → Corrigé : geste de demande.']),

      m('T.M.','Ruche en papier alvéolé',
        'Fabriquer une ruche avec des hexagones en papier collés les uns aux autres. Observer la structure hexagonale.',
        ['Découper des hexagones dans du papier jaune/orange',
         'Coller en alvéoles = structure de ruche',
         'Ajouter des petites abeilles dessinées'],
        ['Combien d\'alvéoles as-tu faites ? → Corrigé : réponse.',
         'Quelle forme a chaque alvéole ? → Corrigé : hexagone.',
         'Pourquoi les abeilles font-elles des hexagones ? → Corrigé : c\'est la forme la plus solide et économique.',
         'Qu\'as-tu mis dans les alvéoles ? → Corrigé : réponse personnelle.',
         'Es-tu content de ta ruche ? → Corrigé : réponse personnelle.']),

      m('A.P.S.','Course d\'orientation simple — trouver les fleurs',
        'Jeu de chasse au trésor simple : trouver des "fleurs" cachées dans la cour. Courir, observer, réfléchir.',
        ['Cacher 10 fleurs en papier dans la cour',
         'Chaque élève cherche et ramasse',
         'Compter ses fleurs'],
        ['Combien de fleurs as-tu trouvées ? → Corrigé : réponse.',
         'Comment as-tu cherché ? → Corrigé : réponse personnelle.',
         'As-tu aidé un camarade à chercher ? → Corrigé : réponse.',
         'Quel endroit as-tu exploré ? → Corrigé : réponse personnelle.',
         'Qu\'as-tu appris sur l\'orientation ? → Corrigé : regarder dans différentes directions, ne pas chercher toujours au même endroit.']),

      m('ENVIRONNEMENT','Les abeilles et leur rôle dans la nature',
        'Les abeilles pollinisent les fleurs. Sans abeilles, pas de fruits. Protéger les abeilles = protéger la nourriture.',
        ['Images : abeille sur une fleur → pollinisation → fruit',
         'Discussion : "D\'où vient le miel ?"',
         'Pourquoi ne pas tuer les abeilles'],
        ['Que font les abeilles avec les fleurs ? → Corrigé : elles récoltent le pollen et le nectar (pollinisation).',
         'Qu\'est-ce que la pollinisation ? → Corrigé : transporter le pollen d\'une fleur à une autre pour qu\'elle fasse des fruits.',
         'Que produit l\'abeille ? → Corrigé : du miel et de la cire.',
         'Pourquoi ne faut-il pas tuer les abeilles ? → Corrigé : elles sont essentielles à la pollinisation et donc à notre nourriture.',
         'Cite 1 fruit qui pousse grâce aux abeilles. → Corrigé : mangue, litchi, tomate, pastèque...']),

      m('ANGLAIS','Numbers 1-50 + shapes',
        'Consolider les chiffres en anglais jusqu\'à 20 + apprendre les formes : circle, square, triangle, rectangle.',
        ['Compter de 1 à 20 en anglais',
         'Flash cards des formes',
         '"What shape is this ?" (montrer un cercle) → circle'],
        ['Count from 1 to 20 in English. → Corrigé : performance.',
         'How do you say "cercle" ? → Corrigé : circle.',
         'How do you say "carré" ? → Corrigé : square.',
         'How do you say "triangle" ? → Corrigé : triangle.',
         'Point to something that is a rectangle in the classroom. → Corrigé : door, window, blackboard...']),

    ]
  },

  {
    n:2, dates:'13/04/2026 – 17/04/2026',
    theme:'Les plantes · Lettres N/M · Compter 1-50 consolider · Additions jusqu\'à 20',
    matieres:[

      m('HYGIÈNE','Les aliments sains — manger des fruits et légumes',
        'Rappel nutrition : les fruits et légumes = vitamines. Consommer local : mangue, banane, papaïe, voanjobory. "5 fruits et légumes par jour."',
        ['Images de fruits et légumes malgaches',
         'Goûter : morceau de fruit ou légume',
         'Discussion : "Quel est ton fruit préféré ?"'],
        ['Cite 3 fruits malgaches. → Corrigé : mangue, banane, litchi, papaïe, jaquier.',
         'Cite 3 légumes malgaches. → Corrigé : brèdes, haricots, voanjobory, manioc.',
         'Pourquoi manger des fruits et légumes ? → Corrigé : pour les vitamines, minéraux, fibres qui maintiennent la santé.',
         'Combien de portions de fruits/légumes recommande-t-on par jour ? → Corrigé : 5.',
         'Quel est ton fruit préféré et pourquoi ? → Corrigé : réponse personnelle.']),

      m('I.C.','Les plantes alimentaires à Madagascar',
        'Les cultures vivrières à Madagascar : riz, manioc, haricots, patates douces, maïs, voanjobory. Importance pour l\'alimentation locale.',
        ['Images des cultures',
         'Associer plante + aliment qu\'elle donne (manioc → tubercule, riz → grain)',
         'Discussion : "Quelle plante mange-t-on le plus à Madagascar ?"'],
        ['Quelle est la plante la plus cultivée à Madagascar ? → Corrigé : le riz.',
         'Qu\'est-ce que le manioc ? → Corrigé : un tubercule comestible, riche en amidon.',
         'Cite 2 cultures vivrières de Madagascar. → Corrigé : riz, manioc, haricots, maïs.',
         'Qu\'est-ce que le voanjobory ? → Corrigé : une légumineuse (haricot de bambou) typique de Madagascar.',
         'Pourquoi cultiver ses propres aliments est important ? → Corrigé : autonomie alimentaire, fraîcheur, économies.']),

      m('MORAL','La responsabilité',
        'Être responsable : faire ce qu\'on doit faire, tenir ses promesses, assumer ses erreurs. Être responsable de ses affaires à l\'école.',
        ['Discussion : "Qui est responsable de quoi à l\'école ?"',
         'Jeu de rôle : oublier son crayon vs. l\'apporter',
         'Règle : "Je suis responsable de mes affaires"'],
        ['Qu\'est-ce que la responsabilité ? → Corrigé : faire ce qu\'on doit faire, tenir sa parole.',
         'Cite 1 responsabilité que tu as à l\'école. → Corrigé : apporter son matériel, faire attention, ne pas gêner.',
         'Cite 1 responsabilité que tu as à la maison. → Corrigé : ranger ses affaires, aider, écouter les parents.',
         'Que fais-tu si tu as oublié ton cahier ? → Corrigé : je le dis à l\'enseignant et je m\'en souviens pour la prochaine fois.',
         'Peut-on faire confiance à quelqu\'un qui n\'est pas responsable ? → Corrigé : difficilement.']),

      m('CONTE','La petite abeille (S2 — faire le miel)',
        'La petite abeille apprend à faire le miel en suivant les instructions de l\'abeille reine.',
        ['Lire S2 avec expressions',
         'Discussion : que fait-on étape par étape pour faire le miel ?',
         'Mimer les étapes : voler → fleur → rapporter le nectar → entrepôt'],
        ['Que fait l\'abeille dans cette partie du conte ? → Corrigé : elle apprend à faire le miel.',
         'Qui lui apprend ? → Corrigé : l\'abeille reine / les abeilles plus âgées.',
         'Quelles sont les étapes du miel ? → Corrigé : voler, aller à la fleur, aspirer le nectar, revenir, déposer dans l\'alvéole.',
         'Qui fait le plus de travail dans une ruche ? → Corrigé : les abeilles ouvrières.',
         'Que préfères-tu dans ce conte jusqu\'à maintenant ? → Corrigé : réponse personnelle.']),

      m('LANGAGE','Les plantes — vocabulaire',
        'Apprendre : graine, germination, pousse, feuille, tige, fleur, fruit, racine. La vie d\'une plante.',
        ['Images : cycle de la plante (graine → arbre)',
         'Placer les étiquettes sur le schéma',
         '"La graine germe, puis une tige apparaît, puis des feuilles..."'],
        ['Qu\'est-ce qu\'une graine ? → Corrigé : ce qu\'on plante pour faire pousser une plante.',
         'Qu\'est-ce que germer ? → Corrigé : commencer à pousser (la graine s\'ouvre et sort une petite racine et une petite tige).',
         'Cite 3 parties d\'une plante. → Corrigé : racine, tige, feuille, fleur, fruit.',
         'Quelle partie de la plante est sous terre ? → Corrigé : la racine.',
         'Qu\'est-ce qu\'un fruit ? → Corrigé : la partie qui contient les graines et qu\'on mange souvent.']),

      m('PRÉ-LECTURE','Graphisme — lettres N et M',
        'Tracer N : 2 traits verticaux + 1 diagonale. Tracer M : 2 traits verticaux + 2 diagonales (pointe centrale).',
        ['N dans l\'air : "Je monte, je descends en diagonale, je remonte"',
         'M dans l\'air : "Je monte, je descends, je remonte, je redescends, je remonte"',
         'Comparer N et M sur le tableau'],
        ['Trace 5 lettres N. → Corrigé : évaluation.',
         'Trace 5 lettres M. → Corrigé : évaluation.',
         'Quelle est la différence entre N et M ? → Corrigé : M a 2 pointes (ou crans), N en a 1.',
         'Combien de traits a M ? → Corrigé : 4 (2 verticaux + 2 diagonales).',
         'Quel prénom commence par M ? → Corrigé : Marie, Marc, Mamitiana... (réponse personnelle).']),

      m('NUMÉRATION','Consolider 1-50 + compter par 2 et par 5',
        'Compter par 2 : 2, 4, 6, 8... Compter par 5 : 5, 10, 15, 20...',
        ['Compter par 2 jusqu\'à 20',
         'Compter par 5 jusqu\'à 50',
         'Jeu : frapper dans les mains à chaque multiple de 5'],
        ['Compte par 2 jusqu\'à 20. → Corrigé : 2, 4, 6, 8, 10, 12, 14, 16, 18, 20.',
         'Compte par 5 jusqu\'à 50. → Corrigé : 5, 10, 15, 20, 25, 30, 35, 40, 45, 50.',
         'Quel nombre vient après 45 en comptant par 5 ? → Corrigé : 50.',
         'Quel nombre vient après 14 en comptant par 2 ? → Corrigé : 16.',
         '5 × 6 = ___ (en comptant par 5). → Corrigé : 30.']),

      m('CALCUL','Additions jusqu\'à 20',
        'Additions avec résultat jusqu\'à 20. Utiliser les doigts, les bâtons, le tableau des dizaines.',
        ['Ardoise : 7+8=___, 9+9=___',
         'Vérifier avec les doigts et bâtons',
         'Problème : "Mamie a 12 mangues. Elle en reçoit 8 de plus. Combien en tout ?"'],
        ['8+8=___. → Corrigé : 16.',
         '9+7=___. → Corrigé : 16.',
         '6+9=___. → Corrigé : 15.',
         'Problème : 12+8=___. → Corrigé : 20.',
         'Problème : Mamie avait 9 poules. On lui en donne 7 de plus. Combien en tout ? → Corrigé : 16.']),

      m('DESSIN','Dessiner une plante avec ses parties',
        'Dessiner une plante entière : racines (sous terre), tige, feuilles, fleur. Légender.',
        ['Tracer la ligne du sol (horizontale)',
         'Dessiner au-dessus : tige + feuilles + fleur',
         'Dessiner en-dessous : racines',
         'Légender chaque partie'],
        ['Quelles parties as-tu dessinées ? → Corrigé : racine, tige, feuille, fleur.',
         'Où sont les racines ? → Corrigé : sous la ligne du sol.',
         'Quelle couleur as-tu choisie pour la fleur ? → Corrigé : réponse personnelle.',
         'As-tu légendu toutes les parties ? → Corrigé : réponse.',
         'À quoi servent les racines ? → Corrigé : elles ancrent la plante et absorbent l\'eau et les minéraux du sol.']),

      m('CHANT','Chanson "Semeur, tu jettes tes graines"',
        '"Semeur, tu jettes tes graines / dans la terre et dans l\'eau / et les petits boutons qui germent / deviendront de beaux arbres bientôt !"',
        ['Apprendre les paroles',
         'Mimer : lancer les graines, l\'arbre qui pousse',
         'Chanter avec les gestes'],
        ['Chante "Semeur". → Corrigé : performance.',
         'Que fait le semeur ? → Corrigé : il jette des graines dans la terre.',
         'Que deviennent les graines ? → Corrigé : de beaux arbres.',
         'Mime un arbre qui pousse. → Corrigé : geste (partir accroupi et se lever lentement).',
         'Mime semer des graines. → Corrigé : geste de lancer.']),

      m('RÉCITATION','Comptine — "Petite graine"',
        '"Petite graine dans la terre noire / dors, dors, dors / la pluie vient te réveiller / et tu sors, tu sors, tu sors !"',
        ['Apprendre les paroles en 2 jours',
         'Mimer la graine qui dort puis qui sort de terre',
         'Accélérer le rythme'],
        ['Récite "Petite graine". → Corrigé : performance.',
         'Où dort la graine ? → Corrigé : dans la terre noire.',
         'Qu\'est-ce qui réveille la graine ? → Corrigé : la pluie.',
         'Que fait la graine quand elle se réveille ? → Corrigé : elle sort de terre (elle germe).',
         'Mime la graine qui dort. → Corrigé : s\'accroupir et fermer les yeux.']),

      m('T.M.','Jardinage — planter une graine',
        'Planter une graine (haricot, cresson, tournesol) dans un pot ou une bouteille coupée. Observer la germination.',
        ['Mettre de la terre dans le pot',
         'Faire un trou, mettre la graine, recouvrir légèrement',
         'Arroser et placer à la lumière'],
        ['Qu\'as-tu planté ? → Corrigé : réponse selon l\'activité.',
         'De quoi la graine a-t-elle besoin pour pousser ? → Corrigé : eau, lumière, terre, chaleur.',
         'Combien de jours avant de voir pousser ? → Corrigé : 3-7 jours selon la plante.',
         'Combien d\'eau as-tu mis ? → Corrigé : un peu, la terre doit être humide sans être détrempée.',
         'As-tu hâte de voir ta plante pousser ? → Corrigé : réponse personnelle.']),

      m('A.P.S.','Jeu de la nature — arbre, arbre, ruche',
        'Variante du jeu "loup" : l\'enseignant dit "arbre !" → les élèves imitent un arbre (debout, bras levés) ; "ruche !" → ils se regroupent en 3 ; "graine !" → ils s\'accroupissent.',
        ['Apprendre les 3 positions',
         'L\'enseignant crie les mots au hasard',
         'Le dernier éliminé gagne'],
        ['Que fais-tu quand on dit "arbre" ? → Corrigé : je me lève et lève les bras.',
         'Que fais-tu quand on dit "graine" ? → Corrigé : je m\'accroupis.',
         'Que fais-tu quand on dit "ruche" ? → Corrigé : je rejoins 2 camarades.',
         'Quel est le but du jeu ? → Corrigé : être le plus réactif.',
         'As-tu aimé ce jeu ? → Corrigé : réponse personnelle.']),

      m('ENVIRONNEMENT','La forêt tropicale — diversité et protection',
        'Madagascar a des forêts tropicales uniques. Ces forêts ont de nombreuses plantes médicinales et alimentaires. Protéger les forêts = préserver les ressources.',
        ['Images de la forêt tropicale malgache',
         'Nommer quelques plantes : ravinala, ficus, baobab',
         'Discussion : "Que perdrait-on si toutes les forêts disparaissaient ?"'],
        ['Qu\'est-ce qu\'une forêt tropicale ? → Corrigé : une forêt dense avec beaucoup de pluie et de végétation.',
         'Cite 2 plantes typiques de Madagascar. → Corrigé : ravinala, baobab, ficus, ylang-ylang.',
         'Qu\'est-ce que le ravinala ? → Corrigé : l\'arbre du voyageur, symbole de Madagascar.',
         'Pourquoi faut-il protéger les forêts ? → Corrigé : elles abritent des milliers d\'espèces animales et végétales uniques, régulent le climat, fournissent de l\'eau.',
         'Que se passerait-il si on coupait toutes les forêts ? → Corrigé : disparition des espèces, sécheresse, érosion des sols.']),

      m('ANGLAIS','Plants and nature vocabulary',
        'Apprendre : flower, tree, leaf, root, seed, fruit, rain, sun. Chanter "Mary had a little lamb" (sheep = animal de la nature).',
        ['Flash cards nature : tree, flower, leaf, seed',
         '"What is this ?" (montrer une feuille) → leaf',
         'Chanter "Mary had a little lamb"'],
        ['How do you say "arbre" ? → Corrigé : tree.',
         'How do you say "fleur" ? → Corrigé : flower.',
         'How do you say "feuille" ? → Corrigé : leaf.',
         'How do you say "graine" ? → Corrigé : seed.',
         'How do you say "fruit" ? → Corrigé : fruit (même mot).']),

    ]
  },

  {
    n:3, dates:'20/04/2026 – 24/04/2026',
    theme:'Les couleurs et la lumière · Lettres A/X/Z · Soustractions jusqu\'à 20 · La mesure (grand/petit/long)',
    matieres:[

      m('HYGIÈNE','Protéger ses yeux du soleil',
        'Le soleil peut abîmer les yeux. Ne pas regarder le soleil. Porter un chapeau. Se protéger la peau du soleil (crème ou vêtements).',
        ['Discussion : "As-tu déjà eu les yeux qui piquent au soleil ?"',
         'Règle : "Je ne regarde jamais le soleil directement"',
         'Observer : ombre / lumière directe'],
        ['Pourquoi ne faut-il pas regarder le soleil ? → Corrigé : ça abîme les yeux, peut rendre aveugle.',
         'Comment protège-t-on ses yeux du soleil ? → Corrigé : chapeau, lunettes de soleil, se mettre à l\'ombre.',
         'Que se passe-t-il si on est trop exposé au soleil ? → Corrigé : coups de soleil, déshydratation, malaise.',
         'Quelle heure du jour est la plus dangereuse pour le soleil ? → Corrigé : entre 10h et 15h.',
         'Que boit-on sous le soleil ? → Corrigé : de l\'eau.']),

      m('I.C.','La lumière et les couleurs de Madagascar',
        'La lumière du soleil contient toutes les couleurs. L\'arc-en-ciel à Madagascar pendant la saison des pluies. Les couleurs du drapeau malgache.',
        ['Observer l\'arc-en-ciel (image)',
         'Les 7 couleurs : rouge, orange, jaune, vert, bleu, indigo, violet',
         'Le drapeau malgache : rouge, blanc, vert — signification'],
        ['Combien de couleurs y a-t-il dans l\'arc-en-ciel ? → Corrigé : 7.',
         'Cite les 3 premières couleurs de l\'arc-en-ciel. → Corrigé : rouge, orange, jaune.',
         'Quelles sont les couleurs du drapeau malgache ? → Corrigé : rouge, blanc, vert.',
         'Que symbolise le rouge du drapeau ? → Corrigé : la souveraineté.',
         'Quand voit-on souvent un arc-en-ciel ? → Corrigé : après la pluie, quand le soleil brille.']),

      m('MORAL','La tolérance',
        'Les gens sont différents : couleur de peau, ethnie, religion, façon de s\'habiller. Ces différences sont belles. On se respecte malgré les différences.',
        ['Images d\'enfants du monde entier',
         'Discussion : "En quoi sommes-nous tous pareils ? En quoi différents ?"',
         'Règle : "Je respecte tout le monde, même si il est différent de moi"'],
        ['Qu\'est-ce que la tolérance ? → Corrigé : accepter et respecter les différences des autres.',
         'Cite 2 différences entre les personnes. → Corrigé : couleur de peau, langue, religion, façon de s\'habiller.',
         'Que font en commun tous les êtres humains ? → Corrigé : ils ressentent, aiment, ont besoin de nourriture et d\'eau.',
         'Est-il bien de se moquer de quelqu\'un parce qu\'il est différent ? → Corrigé : non, c\'est cruel et irrespectueux.',
         'Cite 1 façon de montrer de la tolérance. → Corrigé : sourire, accueillir, jouer avec tout le monde.']),

      m('CONTE','La petite abeille (S3 — distribuer le miel)',
        'La petite abeille distribue le miel à toute la ruche. Partage et joie collective.',
        ['Lire S3',
         'Discussion : "La petite abeille a-t-elle bien agi ?"',
         'Morale : travailler ensemble et partager le fruit du travail'],
        ['Que fait l\'abeille dans cette partie ? → Corrigé : elle distribue le miel.',
         'À qui distribue-t-elle le miel ? → Corrigé : à toute la ruche.',
         'Est-ce que cela lui fait plaisir ? → Corrigé : oui.',
         'Quelle valeur voit-on ici ? → Corrigé : le partage, la solidarité, la générosité.',
         'Raconte le conte en entier en 4 phrases. → Corrigé : résumé oral.']),

      m('LANGAGE','Les couleurs — révision et approfondissement',
        'Réviser les 7 couleurs de l\'arc-en-ciel. Connaître aussi : marron, gris, noir, blanc. Décrire des objets par leur couleur.',
        ['L\'arc-en-ciel en papier : coller dans le bon ordre',
         '"Ma robe est ___, mes chaussures sont ___"',
         'Devinettes de couleurs : "Je suis la couleur du ciel. Qui suis-je ?"'],
        ['Cite les 7 couleurs de l\'arc-en-ciel en ordre. → Corrigé : rouge, orange, jaune, vert, bleu, indigo, violet.',
         'De quelle couleur est le ciel ? → Corrigé : bleu.',
         'De quelle couleur est la nuit ? → Corrigé : noir.',
         'Mélange rouge et bleu : tu obtiens ___. → Corrigé : violet.',
         'Mélange jaune et bleu : tu obtiens ___. → Corrigé : vert.']),

      m('PRÉ-LECTURE','Graphisme — lettres A, X, Z',
        'Tracer A : 2 obliques + barre horizontale milieu. Tracer X : 2 diagonales croisées. Tracer Z : horizontal haut + diagonale + horizontal bas.',
        ['A dans l\'air : "Je monte en diagonale gauche, je descends en diagonale droite, je barre au milieu"',
         'X : "Je descends à droite, je descends à gauche — ils se croisent"',
         'Z : "Je tire à droite, je tire en bas à gauche, je tire à droite"'],
        ['Trace 5 lettres A. → Corrigé : évaluation.',
         'Trace 5 lettres X. → Corrigé : évaluation.',
         'Trace 5 lettres Z. → Corrigé : évaluation.',
         'Quelle lettre ressemble à 2 croix de Saint-André ? → Corrigé : X.',
         'Quelle lettre ressemble à l\'éclair ? → Corrigé : Z.']),

      m('NUMÉRATION','Consolider 1-50 — révision + reconnaître des collections',
        'Reconnaître instantanément les quantités 1-10 (subitizing). Ordonner les nombres 1-50.',
        ['Flash cards de points : reconnaître sans compter',
         'Ordonner une série mélangée de 10 nombres',
         'Jeu : "Qui a le plus grand nombre ?"'],
        ['Reconnais la collection de 7 points sans compter. → Corrigé : subitizing.',
         'Ordonne : 45, 12, 38, 7, 50. → Corrigé : 7, 12, 38, 45, 50.',
         'Quel nombre est à mi-chemin entre 40 et 50 ? → Corrigé : 45.',
         'Compte par 2 de 2 à 20. → Corrigé : 2, 4, 6, 8, 10, 12, 14, 16, 18, 20.',
         'Compte par 5 de 5 à 50. → Corrigé : 5, 10, 15, 20, 25, 30, 35, 40, 45, 50.']),

      m('CALCUL','Soustractions jusqu\'à 20 + vérification',
        'Soustraire jusqu\'à 20. Vérifier avec l\'addition inverse.',
        ['20−8=___, vérifier : 12+8=20 ✓',
         'Ardoise : 5 soustractions',
         'Problème du marché : "Il reste combien de mangues ?"'],
        ['18−9=___. → Corrigé : 9.',
         '20−7=___. → Corrigé : 13.',
         '15−8=___. → Corrigé : 7.',
         'Vérifie : 11+___ =20. → Corrigé : 9.',
         'Problème : 20 mangues au marché. On en vend 14. Combien reste ? → Corrigé : 6.']),

      m('DESSIN','L\'arc-en-ciel — peinture aux doigts ou crayons',
        'Peindre ou dessiner un arc-en-ciel avec les 7 couleurs dans l\'ordre. Exercice de motricité et de mémorisation des couleurs.',
        ['Rappeler l\'ordre des couleurs',
         'Tracer les arcs du grand au petit',
         'Colorier dans l\'ordre : rouge en bas, violet en haut (ou inversement)'],
        ['As-tu mis les 7 couleurs ? → Corrigé : réponse.',
         'Cite les couleurs de ton arc-en-ciel en ordre. → Corrigé : rouge, orange, jaune, vert, bleu, indigo, violet.',
         'Quelle couleur as-tu préférée à peindre ? → Corrigé : réponse personnelle.',
         'Un arc-en-ciel a-t-il toujours la même forme ? → Corrigé : oui, en arc (demi-cercle).',
         'Es-tu content de ton arc-en-ciel ? → Corrigé : réponse personnelle.']),

      m('CHANT','Chanson "L\'arc-en-ciel"',
        '"Rouge, orange et jaune / vert, bleu et violet / tous les jours après la pluie / l\'arc-en-ciel est là !"',
        ['Apprendre les couleurs dans la chanson',
         'Pointer chaque couleur dans le dessin',
         'Chanter + pointer'],
        ['Chante "L\'arc-en-ciel". → Corrigé : performance.',
         'Cite les couleurs dans la chanson en ordre. → Corrigé : rouge, orange, jaune, vert, bleu, violet.',
         'Quand apparaît l\'arc-en-ciel ? → Corrigé : après la pluie.',
         'As-tu déjà vu un arc-en-ciel ? → Corrigé : réponse personnelle.',
         'Chante seul devant la classe. → Corrigé : performance.']),

      m('RÉCITATION','Comptine "Un, deux, trois nous irons aux bois"',
        '"Un, deux, trois, nous irons aux bois / Quatre, cinq, six cueillir des cerises / Sept, huit, neuf dans mon panier neuf / Dix, onze, douze elles seront toutes rouges !"',
        ['Apprendre en associant chiffres + mots',
         'Mimer : aller aux bois, cueillir des cerises, remplir le panier',
         'Réciter très vite'],
        ['Récite "Un, deux, trois nous irons aux bois". → Corrigé : performance.',
         'Que cueille-t-on dans cette comptine ? → Corrigé : des cerises.',
         'Jusqu\'à quel chiffre va la comptine ? → Corrigé : douze.',
         'De quelle couleur seront les cerises à la fin ? → Corrigé : rouges.',
         'Mime cueillir des cerises. → Corrigé : geste de cueillette.']),

      m('T.M.','Mobile de l\'arc-en-ciel',
        'Fabriquer un mobile avec 7 bandes de couleur (dans l\'ordre de l\'arc-en-ciel) suspendues à un bâton.',
        ['Découper 7 bandes de papier de couleur',
         'Les attacher dans l\'ordre à un bâton ou branche',
         'Accrocher le mobile'],
        ['Combien de bandes as-tu faites ? → Corrigé : 7.',
         'Cite les 7 couleurs en ordre. → Corrigé : rouge, orange, jaune, vert, bleu, indigo, violet.',
         'Comment as-tu attaché les bandes ? → Corrigé : avec du fil, de la ficelle.',
         'Où vas-tu accrocher ton mobile ? → Corrigé : réponse personnelle.',
         'Es-tu content de ton mobile ? → Corrigé : réponse personnelle.']),

      m('A.P.S.','Danse de l\'arc-en-ciel — ruban coloré',
        'Danser avec des rubans colorés. Faire des mouvements d\'arc-en-ciel dans l\'air. Coordination, rythme, espace.',
        ['Chaque élève a un ruban d\'une couleur',
         'Danser sur une musique joyeuse',
         'Faire des arcs dans l\'air avec le ruban'],
        ['De quelle couleur est ton ruban ? → Corrigé : réponse personnelle.',
         'Quel mouvement peux-tu faire avec un ruban ? → Corrigé : arc, cercle, vague, zigzag.',
         'Comment fais-tu un arc dans l\'air ? → Corrigé : en faisant passer le bras de droite à gauche en hauteur.',
         'Comment te sens-tu quand tu danses ? → Corrigé : réponse personnelle.',
         'Aimes-tu danser avec des accessoires ? → Corrigé : réponse personnelle.']),

      m('ENVIRONNEMENT','La lumière du soleil — énergie solaire',
        'Le soleil fournit de l\'énergie : chaleur, lumière, croissance des plantes. Énergie solaire = énergie propre. Panneaux solaires.',
        ['Images : panneau solaire, maison solaire',
         'Discussion : "À quoi utilise-t-on le soleil à Madagascar ?"',
         'Avantage : énergie gratuite, propre, renouvelable'],
        ['Que nous donne le soleil ? → Corrigé : lumière, chaleur, énergie.',
         'Qu\'est-ce qu\'un panneau solaire ? → Corrigé : un appareil qui convertit la lumière du soleil en électricité.',
         'Pourquoi l\'énergie solaire est-elle "propre" ? → Corrigé : elle ne produit pas de pollution ni de déchets.',
         'Cite 1 appareil qui fonctionne à l\'énergie solaire. → Corrigé : lampe solaire, chargeur solaire, pompe solaire.',
         'Que font les plantes avec la lumière du soleil ? → Corrigé : elles font la photosynthèse (fabriquer leur nourriture).']),

      m('ANGLAIS','Colors and rainbow',
        'Nommer les 7 couleurs en anglais. Chanter "I can sing a rainbow".',
        ['"I can sing a rainbow, sing a rainbow, sing a rainbow too ! Red and yellow and pink and green / purple and orange and blue..."',
         'Montrer chaque couleur',
         'Flash cards couleurs × 7'],
        ['How do you say "rouge" ? → Corrigé : red.',
         'How do you say "vert" ? → Corrigé : green.',
         'How do you say "orange" ? → Corrigé : orange (même mot).',
         'How do you say "violet" ? → Corrigé : purple.',
         'Sing "I can sing a rainbow". → Corrigé : performance.']),

    ]
  },

  {
    n:4, dates:'27/04/2026 – 01/05/2026',
    theme:'ÉVALUATION — Bilan avril 12ème (Vendredi 01/05 = Fête du Travail)',
    matieres:[
      m('ÉVALUATION','Évaluation de fin de mois — avril 12ème',
        'Évaluation de fin de mois d\'avril. Graphisme, numération 1-50, calcul, oral. Vendredi 01/05 = Fête du Travail (jour férié).',
        ['Lundi 27/04 : épreuve langage + numération',
         'Mardi 28/04 : épreuve graphisme + dessin',
         'Mercredi 29/04 : épreuve calcul',
         'Jeudi 30/04 : épreuve orale (chant, comptine, hygiène, anglais)',
         'Vendredi 01/05 : Fête du Travail — JOUR FÉRIÉ'],
        [
          '══ LANGAGE ══',
          'Cite les 7 couleurs de l\'arc-en-ciel. → Corrigé : rouge, orange, jaune, vert, bleu, indigo, violet.',
          'Cite 3 parties d\'une plante. → Corrigé : racine, tige, feuille.',
          'Fais une phrase avec "abeille". → Corrigé : production.',
          'Cite 3 aliments malgaches. → Corrigé : riz, manioc, haricots, mangue.',
          '',
          '══ NUMÉRATION ══',
          'Compte de 1 à 50. → Corrigé : performance orale.',
          'Compte par 5 jusqu\'à 50. → Corrigé : 5, 10, 15, ..., 50.',
          'Décompose 47 : ___ D + ___ U. → Corrigé : 4D + 7U.',
          'Ordonne : 50, 27, 3, 41. → Corrigé : 3, 27, 41, 50.',
          '',
          '══ CALCUL ══',
          '9+8=___. → Corrigé : 17.',
          '20−12=___. → Corrigé : 8.',
          'La moitié de 16 = ___. → Corrigé : 8.',
          'Partage 15 en 3 groupes égaux. → Corrigé : 5.',
          '',
          '══ GRAPHISME ══',
          'Trace E, F, N, M, A, X, Z. → Corrigé : évaluation.',
          'Dessine un arc-en-ciel. → Corrigé : production.',
          '',
          '══ ORAL ══',
          'Chante "Bourdonnant, bourdonnant". → Corrigé : performance.',
          'Récite "L\'abeille et le bourdon". → Corrigé : performance.',
          'How do you say "flower" ? Montre une fleur. → Corrigé : geste.',
          'Count from 1 to 20 in English. → Corrigé : performance.',
        ]
      ),
    ]
  },

];

module.exports = { AVRIL_12EME };
