'use strict';
// RÉPARTITION 12ÈME — OCTOBRE 2025
// Source: RÉPARTITION CLASSE DE 12ème.xlsx
// 12ème = Pré-primaire, ~5 ans (Grande Section Maternelle)
// 15 matières par semaine — activités concrètes et ludiques

function m(mat, topic, approche, activites, exercices) {
  return { matiere:mat, topic, approche, activites, exercices };
}

const OCTOBRE_12EME = [

  {
    n:1, dates:'06/10/2025 – 10/10/2025',
    theme:'Moi et mon corps · Les formes · Compter 1 à 5 · Couleurs primaires',
    matieres:[

      m('HYGIÈNE','Se laver les mains',
        'Apprendre les gestes de base : se laver les mains avec du savon avant de manger et après les toilettes. Montrer les étapes en chantant "On se lave les mains".',
        ['Montrer les 4 étapes : mouiller → savonner → frotter → rincer',
         'Pratiquer avec un lavabo ou un seau',
         'Chanter la chanson des mains propres'],
        ['Montre-moi comment tu te laves les mains. → Corrigé : geste évalué.',
         'Quand se lave-t-on les mains ? → Corrigé : avant de manger et après les toilettes.',
         'Avec quoi se lave-t-on les mains ? → Corrigé : avec du savon et de l\'eau.',
         'Combien d\'étapes pour bien se laver les mains ? → Corrigé : 4 étapes.',
         'Pourquoi se lave-t-on les mains ? → Corrigé : pour enlever les microbes et ne pas tomber malade.']),

      m('I.C.','Je m\'appelle...',
        'Chaque enfant apprend à dire son prénom, son nom et son âge. Reconnaître sa photo et sa place dans le groupe. Notion de groupe classe.',
        ['Tour de classe : chaque enfant dit "Je m\'appelle... J\'ai... ans"',
         'Jeu : "Qui est-ce ?" — pointer la photo d\'un camarade',
         'Dessiner son propre visage'],
        ['Dis ton prénom. → Corrigé : performance orale.',
         'Quel âge as-tu ? → Corrigé : performance orale.',
         'Combien d\'élèves y a-t-il dans la classe ? → Corrigé : compter ensemble.',
         'Comment s\'appelle ton enseignant(e) ? → Corrigé : performance orale.',
         'Trouve la photo de ton camarade ___ dans la classe. → Corrigé : geste évalué.']),

      m('MORAL','Je suis gentil(le)',
        'Introduire la notion de gentillesse : saluer, dire bonjour, sourire. Jeu de rôle : dire bonjour le matin, remercier après une aide.',
        ['Jeu de rôle : "Bonjour !" — saluer chaque camarade',
         'Histoire courte sur un enfant poli',
         'Récompenser les gestes de politesse'],
        ['Comment dit-on bonjour en malgache ? → Corrigé : salama.',
         'Que dis-tu quand quelqu\'un t\'aide ? → Corrigé : merci.',
         'Comment montre-t-on qu\'on est gentil(le) ? → Corrigé : sourire, dire bonjour, aider.',
         'Est-ce gentil de prendre les affaires des autres ? → Corrigé : non.',
         'Que fais-tu quand un camarade pleure ? → Corrigé : réponse libre (le consoler, appeler l\'enseignant).']),

      m('CONTE','Le petit poussin — Découverte (S1)',
        'Présenter le conte du petit poussin qui découvre le monde. Écouter avec attention. Identifier les personnages et les animaux.',
        ['Montrer les images du conte une par une',
         'Lire le conte avec expression et mimiques',
         'Questions simples : Qui vois-tu ? De quelle couleur est-il ?'],
        ['Qui est le personnage principal ? → Corrigé : le petit poussin.',
         'De quelle couleur est le poussin ? → Corrigé : jaune.',
         'Quel son fait le poussin ? → Corrigé : "piii-piii".',
         'Cite 1 autre animal dans le conte. → Corrigé : selon les images.',
         'As-tu aimé ce conte ? → Corrigé : réponse personnelle.']),

      m('LANGAGE','Mon corps — parties du corps',
        'Apprendre les parties du corps : tête, yeux, nez, bouche, oreilles, bras, mains, jambes, pieds. Chanter "Tête, épaules, genoux et pieds".',
        ['Chanter "Tête, épaules, genoux et pieds" en touchant',
         'Jeu : "Montre-moi ton nez !" — pointer la partie nommée',
         'Dessiner un bonhomme simple'],
        ['Montre ta tête. → Corrigé : geste.',
         'Combien as-tu d\'yeux ? → Corrigé : 2.',
         'Combien as-tu de mains ? → Corrigé : 2.',
         'Où est ton nez ? → Corrigé : geste.',
         'Cite 3 parties du corps. → Corrigé : tête, bras, jambes (3 parmi).']),

      m('PRÉ-LECTURE','Graphisme — lignes horizontales',
        'Tracer des lignes horizontales de gauche à droite. Développer la tenue du crayon et le sens d\'écriture. Niveau : pré-écriture.',
        ['Montrer la direction : de gauche à droite',
         'Tracer des lignes dans l\'air avec le doigt',
         'Tracer sur papier rayé : 3 lignes horizontales'],
        ['Dans quel sens trace-t-on ? → Corrigé : de gauche à droite.',
         'Trace 3 lignes horizontales. → Corrigé : évaluation du tracé.',
         'Une ligne horizontale va dans quel sens ? → Corrigé : à plat, comme l\'horizon.',
         'Montre le sens de gauche à droite avec ton doigt. → Corrigé : geste évalué.',
         'Bien tenir le crayon : montre ta prise. → Corrigé : prise tripode évaluée.']),

      m('NUMÉRATION','Compter 1 à 5',
        'Apprendre à compter de 1 à 5 avec les doigts, des objets concrets. Correspondance terme à terme : 1 objet = 1 nombre. Chant de comptage.',
        ['Compter avec les doigts : 1, 2, 3, 4, 5',
         'Compter des objets concrets : crayons, cailloux, briques',
         'Chant "1, 2, 3, nous irons au bois"'],
        ['Compte tes doigts. → Corrigé : 1, 2, 3, 4, 5.',
         'Montre 3 doigts. → Corrigé : geste.',
         'Combien de crayons ? (montrer 4) → Corrigé : 4.',
         'Quel nombre vient après 3 ? → Corrigé : 4.',
         'Montre 5 avec tes doigts. → Corrigé : geste.']),

      m('CALCUL','Reconnaître les quantités 1-3',
        'Associer une quantité à son chiffre (1, 2, 3). Cartes de quantité. Dénombrement par comptage tactile.',
        ['Cartes quantité : montrer la carte 2 → "deux"',
         'Jeu de memory : associer carte chiffre et carte points',
         'Dénombrer des collections : 1, 2 ou 3 objets'],
        ['Montre la carte qui montre 2. → Corrigé : geste.',
         'Combien de pommes ? (image avec 3) → Corrigé : 3.',
         'Quel chiffre est sur cette carte ? (carte 1) → Corrigé : 1.',
         'Montre 2 cailloux. → Corrigé : geste.',
         'Est-ce que 3 c\'est plus que 1 ? → Corrigé : oui.']),

      m('DESSIN','Les couleurs primaires — rouge, bleu, jaune',
        'Découvrir les 3 couleurs primaires. Reconnaître et nommer. Colorier des formes simples en rouge, bleu ou jaune.',
        ['Montrer les 3 couleurs : rouge, bleu, jaune',
         'Trouver ces couleurs dans la classe',
         'Colorier un soleil (jaune), un ciel (bleu), une pomme (rouge)'],
        ['Montre le rouge. → Corrigé : geste.',
         'De quelle couleur est le ciel ? → Corrigé : bleu.',
         'De quelle couleur est le soleil ? → Corrigé : jaune.',
         'Colorie la pomme en rouge. → Corrigé : évaluation.',
         'Cite les 3 couleurs primaires. → Corrigé : rouge, bleu, jaune.']),

      m('CHANT','Chanson de bienvenue — "Bonjour les amis"',
        'Apprendre la chanson de bienvenue de la classe. Mémoriser les paroles et les gestes. Chanter chaque matin pour commencer la journée.',
        ['Chanter la chanson × 3 avec les gestes',
         'Les enfants imitent les gestes de l\'enseignant',
         'Chanter seul ou en petit groupe'],
        ['Chante "Bonjour les amis". → Corrigé : performance orale.',
         'Quand chante-t-on cette chanson ? → Corrigé : le matin pour commencer.',
         'Que dit-on dans le refrain ? → Corrigé : selon les paroles.',
         'Montre les gestes de la chanson. → Corrigé : performance.',
         'Aimes-tu cette chanson ? → Corrigé : réponse personnelle.']),

      m('RÉCITATION','La comptine des doigts',
        'Apprendre une comptine sur les doigts. Développer la mémoire et la diction. Nommer chaque doigt.',
        ['Réciter la comptine en montrant chaque doigt',
         'Répétition chorale × 3',
         'Chaque enfant la dit seul'],
        ['Récite la comptine. → Corrigé : performance orale.',
         'Combien de doigts as-tu sur une main ? → Corrigé : 5.',
         'Combien de doigts as-tu en tout ? → Corrigé : 10.',
         'Comment s\'appelle le plus grand doigt ? → Corrigé : le majeur.',
         'Comment s\'appelle le plus petit ? → Corrigé : l\'auriculaire (ou le petit doigt).']),

      m('T.M.','Découpage — lignes droites',
        'Apprendre à tenir les ciseaux correctement. Découper en suivant une ligne droite. Coller sur une feuille.',
        ['Montrer la prise des ciseaux : pouce dans le petit trou, 2 doigts dans le grand',
         'Exercice : découper des bandes préparées (5 cm de large)',
         'Coller les bandes en rangées sur une feuille'],
        ['Montre comment tu tiens les ciseaux. → Corrigé : évaluation de la prise.',
         'Découpe cette bande. → Corrigé : évaluation de la découpe.',
         'Colle ta bande sur la feuille. → Corrigé : évaluation.',
         'Les ciseaux sont-ils dangereux ? → Corrigé : oui, on ne court pas avec.',
         'Qu\'as-tu créé avec tes bandes découpées ? → Corrigé : réponse personnelle.']),

      m('A.P.S.','Marcher et courir en groupe',
        'Apprendre à se déplacer en groupe : marcher en file, en cercle, en ligne. Courir librement dans l\'espace. Respecter les limites du terrain.',
        ['Marcher en file indienne',
         'Courir librement au signal',
         'Jeu "La queue du loup" : attraper le mouchoir'],
        ['Peux-tu marcher en file sans te bousculer ? → Corrigé : évaluation.',
         'Que fais-tu au signal "stop" ? → Corrigé : je m\'arrête.',
         'Courir c\'est bien, mais que ne faut-il pas faire ? → Corrigé : bousculer les autres, sortir du terrain.',
         'Combien d\'enfants y a-t-il dans la file ? → Corrigé : compter ensemble.',
         'Qu\'as-tu aimé dans ce jeu ? → Corrigé : réponse personnelle.']),

      m('ENVIRONNEMENT','Le temps qu\'il fait',
        'Observer et décrire le temps : soleil, pluie, nuages, vent. Créer un tableau météo de la classe. Vocabulaire de base.',
        ['Observer le ciel ce matin',
         'Compléter le tableau météo avec un symbole',
         'Discussion : "Quel temps fait-il ?"'],
        ['Quel temps fait-il aujourd\'hui ? → Corrigé : description du temps.',
         'Dessine un soleil. → Corrigé : production.',
         'De quelle couleur est un nuage ? → Corrigé : gris ou blanc.',
         'Quand pleut-il ? → Corrigé : quand les nuages sont gris et lourds.',
         'Est-ce qu\'il fait chaud ou froid aujourd\'hui ? → Corrigé : réponse selon le temps.']),

      m('ANGLAIS','Hello! — Greetings',
        'Apprendre à dire bonjour en anglais : Hello! Hi! Good morning! My name is... Jeu d\'identité en anglais.',
        ['Répéter "Hello! My name is ___" × 5',
         'Tour de classe : chaque enfant dit son prénom en anglais',
         'Chanter "Hello, hello, what is your name?"'],
        ['Dis bonjour en anglais. → Corrigé : Hello !',
         'Comment dit-on "bonjour" le matin ? → Corrigé : Good morning!',
         '"My name is ___." → Corrigé : performance orale.',
         'Réponds à "Hello!" → Corrigé : Hello!',
         'Comment dit-on "au revoir" ? → Corrigé : Goodbye!']),

    ]
  },

  {
    n:2, dates:'13/10/2025 – 17/10/2025',
    theme:'Mon visage · Lignes verticales · Compter 1-7 · Vert et orange',
    matieres:[

      m('HYGIÈNE','Se brosser les dents',
        'Apprendre les gestes du brossage des dents : 2 fois par jour, 2 minutes, dans tous les sens. Montrer avec une grande brosse modèle.',
        ['Montrer les gestes sur un modèle (grande bouche et grande brosse)',
         'Chanter "On se brosse les dents" pour timer 2 minutes',
         'Vérifier sa brosse à dents : est-elle abîmée ?'],
        ['Combien de fois par jour se brosse-t-on les dents ? → Corrigé : 2 fois.',
         'Avec quoi se brosse-t-on les dents ? → Corrigé : une brosse et du dentifrice.',
         'Pendant combien de minutes ? → Corrigé : 2 minutes.',
         'Montre comment tu te brosses les dents. → Corrigé : geste évalué.',
         'Pourquoi se brosse-t-on les dents ? → Corrigé : pour éviter les caries et avoir les dents propres.']),

      m('I.C.','Ma famille',
        'Présenter les membres de la famille : maman, papa, frère, sœur, grand-mère, grand-père. Dessiner sa famille.',
        ['Tour de classe : "J\'ai un frère / une sœur..."',
         'Dessiner sa famille',
         'Nommer les membres de la famille montrés sur des images'],
        ['Qui est ta maman ? → Corrigé : réponse personnelle.',
         'As-tu un frère ou une sœur ? → Corrigé : réponse personnelle.',
         'Combien de personnes y a-t-il dans ta famille ? → Corrigé : réponse personnelle.',
         'Comment appelle-t-on la mère de ta maman ? → Corrigé : grand-mère.',
         'Dessine ta famille. → Corrigé : production.']),

      m('MORAL','Je partage',
        'Apprendre à partager : un jouet, un crayon, une collation. Jeu de rôle. Valoriser le partage comme geste de gentillesse.',
        ['Jeu de rôle : 1 jouet pour 2 enfants — comment partager ?',
         'Histoire : "Kalo partage ses biscuits"',
         'Récompenser les gestes de partage observés'],
        ['Qu\'est-ce que partager ? → Corrigé : donner une partie de ce qu\'on a à quelqu\'un.',
         'Est-il bien de partager ? → Corrigé : oui.',
         'Avec qui as-tu partagé quelque chose aujourd\'hui ? → Corrigé : réponse personnelle.',
         'Si tu as 2 bonbons et qu\'un ami n\'en a pas, que fais-tu ? → Corrigé : je lui en donne 1.',
         'Comment te sens-tu quand tu partages ? → Corrigé : content(e).']),

      m('CONTE','Le petit poussin (S2)',
        'Relire le conte du petit poussin. Raconter avec les images. Les enfants répètent les répliques.',
        ['Relire le conte avec les images',
         'Les enfants répètent ce que dit le poussin',
         'Jeu de rôle : jouer le conte'],
        ['Que fait le petit poussin dans le conte ? → Corrigé : selon le conte.',
         'Quel son fait le poussin ? → Corrigé : "piii-piii".',
         'Est-ce que le poussin est courageux ? → Corrigé : oui.',
         'Raconte ce que tu te rappelles du conte. → Corrigé : résumé oral simple.',
         'Quel est ton personnage préféré ? → Corrigé : réponse personnelle.']),

      m('LANGAGE','Mon visage',
        'Décrire les parties du visage : yeux, nez, bouche, oreilles, cheveux. Jeu de devinettes. Dessiner son portrait.',
        ['Miroir : chaque enfant observe son visage',
         'Jeu : "J\'ai deux ___" — nommer les parties',
         'Dessiner son autoportrait'],
        ['Combien as-tu d\'yeux ? → Corrigé : 2.',
         'Combien as-tu d\'oreilles ? → Corrigé : 2.',
         'Combien as-tu de bouche ? → Corrigé : 1.',
         'À quoi servent les yeux ? → Corrigé : à voir.',
         'À quoi sert le nez ? → Corrigé : à respirer et à sentir.']),

      m('PRÉ-LECTURE','Graphisme — lignes verticales',
        'Tracer des lignes verticales de haut en bas. Exercice de graphisme pré-écriture. Sens du tracé.',
        ['Montrer : du haut vers le bas',
         'Tracer dans l\'air avec le doigt',
         'Tracer sur papier : 3 lignes verticales'],
        ['Dans quel sens trace-t-on une ligne verticale ? → Corrigé : du haut vers le bas.',
         'Trace 3 lignes verticales. → Corrigé : évaluation.',
         'Une ligne verticale est-elle comme l\'horizon ? → Corrigé : non, elle est droite vers le bas.',
         'Trace une ligne horizontale, puis une verticale. → Corrigé : évaluation.',
         'Quelle lettre ressemble à une ligne verticale ? → Corrigé : l, i, t.']),

      m('NUMÉRATION','Compter 1 à 7',
        'Étendre le comptage à 7. Compter avec les doigts. Reconnaître les chiffres 1 à 7.',
        ['Compter avec les doigts : ajouter 6 et 7',
         'Chant de comptage 1-7',
         'Ordonner des cartes chiffres 1-7'],
        ['Compte de 1 à 7. → Corrigé : performance orale.',
         'Quel nombre vient après 5 ? → Corrigé : 6.',
         'Quel nombre vient après 6 ? → Corrigé : 7.',
         'Montre 6 doigts. → Corrigé : geste.',
         'Quel nombre est le plus grand : 3 ou 7 ? → Corrigé : 7.']),

      m('CALCUL','C\'est pareil / c\'est différent — comparaison',
        'Comparer des collections : autant, plus, moins. Utiliser des objets concrets. Pas encore d\'écriture de chiffres.',
        ['Aligner 3 rouges et 3 bleues : "Autant de chaque"',
         'Aligner 2 rouges et 4 bleues : "Il y a plus de bleues"',
         'Les enfants comparent des collections'],
        ['Quelle collection a plus d\'objets ? → Corrigé : évaluation selon la configuration.',
         'Y a-t-il autant de _____ et de _____ ? → Corrigé : évaluation.',
         'Montre la collection qui a le moins. → Corrigé : geste.',
         'Met autant de cailloux que de crayons. → Corrigé : geste de mise en correspondance.',
         'Plus / moins / autant : que signifie "autant" ? → Corrigé : la même quantité.']),

      m('DESSIN','Les couleurs — vert et orange',
        'Découvrir les couleurs secondaires vert et orange (mélange de couleurs primaires). Colorier des formes.',
        ['Montrer : jaune + bleu = vert (mélange)',
         'Montrer : rouge + jaune = orange',
         'Colorier des pommes en vert, des oranges en orange'],
        ['De quelle couleur est une herbe ? → Corrigé : verte.',
         'De quelle couleur est une orange ? → Corrigé : orange.',
         'Quelles couleurs mélange-t-on pour faire du vert ? → Corrigé : jaune + bleu.',
         'Colorie l\'herbe en vert. → Corrigé : évaluation.',
         'Cite 5 couleurs que tu connais. → Corrigé : rouge, bleu, jaune, vert, orange.']),

      m('CHANT','Chant des couleurs',
        'Apprendre une chanson sur les couleurs. Chaque couleur est associée à un objet et un geste.',
        ['Chanter la chanson × 3 avec les gestes',
         'Pointer des objets de la couleur chantée',
         'Chanter seul'],
        ['Chante la chanson des couleurs. → Corrigé : performance orale.',
         'Quelle couleur est chantée en premier ? → Corrigé : selon les paroles.',
         'Montre quelque chose de rouge dans la classe. → Corrigé : geste.',
         'Montre quelque chose de bleu. → Corrigé : geste.',
         'Combien de couleurs sont dans cette chanson ? → Corrigé : selon les paroles.']),

      m('RÉCITATION','Comptine "1, 2, 3, soleil"',
        'Apprendre la comptine "1, 2, 3, soleil" avec les gestes de la statue. Mémoriser le texte.',
        ['Apprendre la comptine × 3',
         'Jouer au jeu "1, 2, 3 soleil !" avec l\'immobilisation',
         'Réciter seul'],
        ['Récite "1, 2, 3 soleil". → Corrigé : performance orale.',
         'Que fais-tu quand on dit "soleil" ? → Corrigé : je m\'arrête comme une statue.',
         'Combien compte-t-on avant "soleil" ? → Corrigé : 3.',
         'Ce jeu t\'a-t-il plu ? → Corrigé : réponse personnelle.',
         'Quel autre jeu de comptine connais-tu ? → Corrigé : réponse libre.']),

      m('T.M.','Collage — formes simples',
        'Coller des formes géométriques pré-découpées (ronds, carrés) pour créer une image. Développer la motricité fine et la créativité.',
        ['Distribuer des formes pré-découpées : ronds, carrés, triangles',
         'Les enfants créent une image en collant (maison, visage, fleur)',
         'Nommer les formes collées'],
        ['Quelle forme as-tu utilisée pour la tête ? → Corrigé : un rond.',
         'Quelle forme as-tu utilisée pour le corps ? → Corrigé : un carré ou rectangle.',
         'Nomme les formes sur ton collage. → Corrigé : rond, carré, triangle.',
         'Combien de formes as-tu collées ? → Corrigé : compter ensemble.',
         'Qu\'as-tu créé ? → Corrigé : réponse personnelle.']),

      m('A.P.S.','Sauter à pieds joints',
        'Apprendre à sauter à pieds joints : atterrir sur les deux pieds en fléchissant les genoux. Jeux de sauts.',
        ['Montrer la technique : genoux pliés à l\'atterrissage',
         'Sauter par-dessus une ligne tracée au sol',
         'Jeu : "La grenouille" — sauter comme une grenouille'],
        ['Montre un saut à pieds joints. → Corrigé : performance.',
         'Comment atterrit-on correctement ? → Corrigé : sur les deux pieds, genoux pliés.',
         'Combien de sauts peux-tu faire d\'affilée ? → Corrigé : compter.',
         'Quel animal saute beaucoup ? → Corrigé : grenouille, kangourou, lapin.',
         'Qu\'est-ce qui t\'aide à sauter plus haut ? → Corrigé : plier les genoux et balancer les bras.']),

      m('ENVIRONNEMENT','Les animaux familiers',
        'Identifier des animaux familiers : chien, chat, lapin, oiseau, poisson. Leurs sons. Leurs habitats.',
        ['Montrer des images d\'animaux familiers',
         'Imiter les sons de chaque animal',
         'Discussion : "As-tu un animal à la maison ?"'],
        ['Quel son fait le chien ? → Corrigé : ouaf-ouaf.',
         'Quel son fait le chat ? → Corrigé : miaou.',
         'Cite 3 animaux familiers. → Corrigé : chien, chat, lapin, oiseau, poisson.',
         'Quel animal est doux et a des poils ? → Corrigé : chien, chat, lapin.',
         'As-tu un animal chez toi ? Lequel ? → Corrigé : réponse personnelle.']),

      m('ANGLAIS','Numbers 1-5',
        'Apprendre les chiffres de 1 à 5 en anglais. Chanter "1, 2, 3, 4, 5 — Once I caught a fish alive".',
        ['Répéter "one, two, three, four, five" avec les doigts',
         'Chanter la chanson des chiffres',
         'Jeu : l\'enseignant dit un chiffre, les élèves montrent les doigts'],
        ['How do you say "1" in English ? → Corrigé : one.',
         'Count from 1 to 5. → Corrigé : one, two, three, four, five.',
         'Show me 3 fingers. → Corrigé : geste.',
         'What number is this ? (montrer 4 doigts) → Corrigé : four.',
         'Which is more: 2 or 5 ? → Corrigé : five.']),

    ]
  },

  {
    n:3, dates:'20/10/2025 – 24/10/2025',
    theme:'Mes sens · Lignes courbes · Compter 1-10 · Formes géométriques',
    matieres:[

      m('HYGIÈNE','Ma toilette du matin',
        'Etablir la routine du matin : se laver le visage, se brosser les dents, se peigner, s\'habiller proprement. Ordre des gestes.',
        ['Reconstituer l\'ordre des gestes du matin avec des images séquentielles',
         'Mimer chaque geste dans l\'ordre',
         'Discussion : "Que fais-tu le matin avant l\'école ?"'],
        ['Cite 3 gestes de la toilette du matin. → Corrigé : se laver le visage, se brosser les dents, se peigner.',
         'Dans quel ordre te prépares-tu le matin ? → Corrigé : réponse personnelle.',
         'Pourquoi est-il important de faire sa toilette le matin ? → Corrigé : pour être propre, sentir bon, se respecter et respecter les autres.',
         'Tes dents sont-elles propres ce matin ? → Corrigé : réponse personnelle.',
         'Combien de gestes fais-tu chaque matin ? → Corrigé : réponse personnelle.']),

      m('I.C.','Mon école',
        'Découvrir l\'école : la salle de classe, la cour, les toilettes, le bureau du directeur. Les règles de l\'école.',
        ['Visite de l\'école : identifier chaque espace',
         'Règles : ne pas courir dans les couloirs, respecter le matériel',
         'Dessiner l\'école'],
        ['Cite 2 endroits dans ton école. → Corrigé : salle de classe, cour, toilettes, bureau du directeur.',
         'Que ne faut-il pas faire dans les couloirs ? → Corrigé : courir.',
         'À qui appartient le matériel scolaire ? → Corrigé : à l\'école, à tout le monde.',
         'Combien de salles y a-t-il dans ton école ? → Corrigé : compter ensemble.',
         'Qui dirige l\'école ? → Corrigé : le directeur / la directrice.']),

      m('MORAL','J\'écoute',
        'Apprendre à écouter sans interrompre. Jeu du téléphone arabe. Différence entre entendre et écouter.',
        ['Jeu du téléphone arabe',
         'Écouter une histoire et répondre à 3 questions',
         'Règle : "Je lève la main pour parler"'],
        ['Qu\'est-ce qu\'écouter ? → Corrigé : prêter attention à ce que quelqu\'un dit.',
         'Faut-il interrompre quelqu\'un qui parle ? → Corrigé : non, on attend son tour.',
         'Que fais-tu pour montrer que tu écoutes ? → Corrigé : je regarde la personne, je ne fais pas de bruit.',
         'Qu\'est-ce que le téléphone arabe t\'a appris ? → Corrigé : l\'importance d\'écouter attentivement.',
         'Quelle règle doit-on respecter en classe ? → Corrigé : lever la main pour parler.']),

      m('CONTE','Nouveau conte — La petite tortue (S1)',
        'Nouveau conte sur une petite tortue qui cherche sa maison. Écouter. Identifier les personnages.',
        ['Présenter le conte avec des images',
         'Lire avec expression',
         'Questions de compréhension simples'],
        ['Qui est le personnage principal ? → Corrigé : la petite tortue.',
         'Que cherche la tortue ? → Corrigé : sa maison.',
         'La tortue est-elle rapide ou lente ? → Corrigé : lente.',
         'Où vit la tortue ? → Corrigé : dans sa carapace / au bord de l\'eau.',
         'Prédis la fin : la tortue retrouve-t-elle sa maison ? → Corrigé : prédiction libre.']),

      m('LANGAGE','Mes 5 sens',
        'Découvrir les 5 sens : vue (yeux), ouïe (oreilles), odorat (nez), goût (bouche), toucher (mains). Activités sensorielles.',
        ['Boîte mystère : toucher et deviner',
         'Sentir 3 objets aux yeux fermés',
         'Goûter sucré/salé/acide'],
        ['Avec quoi vois-tu ? → Corrigé : avec mes yeux.',
         'Avec quoi entends-tu ? → Corrigé : avec mes oreilles.',
         'Avec quoi touches-tu ? → Corrigé : avec mes mains.',
         'Avec quoi goûtes-tu ? → Corrigé : avec ma bouche / ma langue.',
         'Cite tes 5 sens. → Corrigé : vue, ouïe, odorat, goût, toucher.']),

      m('PRÉ-LECTURE','Graphisme — lignes courbes',
        'Tracer des lignes courbes, des vagues, des arcs. Préparer l\'écriture des lettres rondes (c, o, a).',
        ['Tracer des vagues dans l\'air',
         'Tracer des vagues sur papier : de gauche à droite',
         'Tracer des escargots (spirales)'],
        ['Trace 3 vagues. → Corrigé : évaluation.',
         'Trace un arc de cercle. → Corrigé : évaluation.',
         'Trace une spirale. → Corrigé : évaluation.',
         'Quelle lettre ressemble à une courbe ? → Corrigé : c, o, a, u.',
         'Trace une ligne courbe de gauche à droite. → Corrigé : évaluation.']),

      m('NUMÉRATION','Compter 1 à 10',
        'Étendre le comptage à 10. Reconnaître les chiffres de 1 à 10. Dénombrer des collections jusqu\'à 10.',
        ['Compter avec les deux mains : 1 à 10',
         'Ordonner les cartes chiffres 1 à 10',
         'Dénombrer des collections de 1 à 10'],
        ['Compte de 1 à 10. → Corrigé : performance orale.',
         'Quel nombre vient après 8 ? → Corrigé : 9.',
         'Quel nombre vient après 9 ? → Corrigé : 10.',
         'Montre 8 doigts. → Corrigé : geste.',
         'Quel est le plus grand nombre que tu connais ? → Corrigé : 10.']),

      m('CALCUL','Addition très simple — 1+1, 1+2',
        'Introduire l\'addition avec des objets concrets. 1 pomme + 1 pomme = 2 pommes. Pas d\'écriture formelle encore.',
        ['Manipuler des objets : "J\'en ai 1, j\'en mets 1 de plus, combien en tout ?"',
         'Cartes images : 1 chat + 1 chat = 2 chats',
         'Jeu de doigts : 1+1, 1+2, 2+2'],
        ['1 pomme + 1 pomme = combien ? → Corrigé : 2.',
         '2 crayons + 1 crayon = combien ? → Corrigé : 3.',
         '1+2 = ___. → Corrigé : 3.',
         '2+2 = ___. → Corrigé : 4.',
         'Si j\'ai 3 billes et j\'en reçois 1, combien en ai-je ? → Corrigé : 4.']),

      m('DESSIN','Les formes géométriques — cercle, carré, triangle',
        'Reconnaître et dessiner les 3 formes de base. Les retrouver dans l\'environnement.',
        ['Montrer les 3 formes : cercle, carré, triangle',
         'Trouver ces formes dans la classe',
         'Dessiner chaque forme'],
        ['Dessine un cercle. → Corrigé : production.',
         'Dessine un carré. → Corrigé : production.',
         'Dessine un triangle. → Corrigé : production.',
         'Quelle forme ressemble à un ballon ? → Corrigé : le cercle.',
         'Combien de côtés a un triangle ? → Corrigé : 3.']),

      m('CHANT','Chanson "Tête, épaules, genoux et pieds"',
        'Apprendre la chanson avec les parties du corps. Accélérer progressivement. Mémoriser les paroles et les gestes.',
        ['Chanter lentement en touchant les parties',
         'Accélérer progressivement',
         'Chanson en compétition de vitesse'],
        ['Chante "Tête, épaules, genoux et pieds". → Corrigé : performance orale.',
         'Montre tes épaules. → Corrigé : geste.',
         'Montre tes genoux. → Corrigé : geste.',
         'Quelle partie du corps est au-dessus des épaules ? → Corrigé : la tête.',
         'Quelle partie est en dessous des genoux ? → Corrigé : les pieds.']),

      m('RÉCITATION','Comptine "Promenons-nous dans les bois"',
        'Apprendre la comptine "Promenons-nous dans les bois". Jeu de rôle : le loup. Mémoriser le texte.',
        ['Apprendre la comptine en jouant le loup',
         'Les enfants fuient quand le loup dit "Je sors !"',
         'Chaque enfant dit la comptine'],
        ['Récite la comptine. → Corrigé : performance orale.',
         'Qui est le méchant dans cette comptine ? → Corrigé : le loup.',
         'Que crie-t-on quand le loup sort ? → Corrigé : on fuit en criant.',
         'Où se promène-t-on ? → Corrigé : dans les bois.',
         'Qu\'est-ce que le loup met pour se préparer ? → Corrigé : sa chemise, son pantalon...']),

      m('T.M.','Modelage — boules et boudins',
        'Modeler de la pâte à modeler pour faire des boules et des boudins. Assembler pour faire un personnage simple.',
        ['Rouler une boule (tête)',
         'Rouler un boudin (corps)',
         'Assembler : tête + corps = bonhomme'],
        ['Comment fais-tu une boule ? → Corrigé : je roule la pâte entre mes deux paumes.',
         'Comment fais-tu un boudin ? → Corrigé : je roule la pâte sur la table.',
         'Qu\'as-tu créé avec tes boules et boudins ? → Corrigé : réponse personnelle.',
         'De quelle couleur est ta pâte ? → Corrigé : réponse personnelle.',
         'Combien de boules as-tu fait ? → Corrigé : compter.']),

      m('A.P.S.','Lancer une balle',
        'Apprendre à lancer une petite balle vers une cible. Lancer à deux mains, puis à une main. Jeu de lancer.',
        ['Lancer une balle à 2 mains vers un seau',
         'Lancer à 1 main vers une cible tracée',
         'Compter les réussites'],
        ['Montre comment tu lances la balle. → Corrigé : performance.',
         'Lancer vers la cible. → Corrigé : évaluation.',
         'Combien de fois as-tu atteint la cible ? → Corrigé : compter.',
         'Est-il plus facile de lancer à 2 mains ou 1 main ? → Corrigé : réponse personnelle.',
         'Dans quel sport lance-t-on beaucoup ? → Corrigé : baseball, handball, basketball...']),

      m('ENVIRONNEMENT','Les plantes autour de nous',
        'Observer des plantes : fleur, arbre, herbe. Les parties d\'une plante : racine, tige, feuille, fleur. Soin des plantes.',
        ['Observer des plantes dans la cour',
         'Identifier : racine, tige, feuille, fleur sur un dessin',
         'Arroser une plante de la classe'],
        ['Cite 3 parties d\'une plante. → Corrigé : racine, tige, feuille, fleur, fruit.',
         'À quoi servent les racines ? → Corrigé : à absorber l\'eau et à tenir la plante dans le sol.',
         'Pourquoi arrose-t-on les plantes ? → Corrigé : parce qu\'elles ont besoin d\'eau pour vivre.',
         'Cite 2 plantes que tu connais. → Corrigé : rose, manguier, hibiscus, bananier...',
         'De quelle couleur sont les feuilles ? → Corrigé : vertes.']),

      m('ANGLAIS','Colors — Les couleurs en anglais',
        'Apprendre les couleurs en anglais : red, blue, yellow, green, orange. Jeu "What color is it?"',
        ['Flashcards couleurs',
         '"What color is it?" — pointer et répondre',
         'Colorier selon les instructions en anglais'],
        ['How do you say "rouge" ? → Corrigé : red.',
         'How do you say "bleu" ? → Corrigé : blue.',
         '"Color the apple RED." → Corrigé : colorier en rouge.',
         'What color is the grass ? → Corrigé : green.',
         'What color is the sun ? → Corrigé : yellow.']),

    ]
  },

  {
    n:4, dates:'27/10/2025 – 31/10/2025',
    theme:'ÉVALUATION — Bilan du mois d\'Octobre',
    matieres:[

      m('ÉVALUATION','Fiche de révision — Octobre 2025',
        'Évaluation des apprentissages du mois d\'octobre. Activités orales, de graphisme et de coloriages évalués.',
        ['Lundi : Évaluation orale (Langage, Chant, Récitation)',
         'Mardi : Évaluation graphisme + Numération',
         'Mercredi : Évaluation Dessin + Collage',
         'Jeudi : Correction collective + Activités libres'],
        [
          '── LANGAGE ──',
          'Cite 5 parties du corps. → Corrigé : tête, yeux, nez, bouche, oreilles.',
          'Cite tes 5 sens. → Corrigé : vue, ouïe, odorat, goût, toucher.',
          '── NUMÉRATION ──',
          'Compte de 1 à 10. → Corrigé : performance orale.',
          'Montre 7 doigts. → Corrigé : geste.',
          'Quel nombre vient après 8 ? → Corrigé : 9.',
          '── CALCUL ──',
          '1+2=___. → Corrigé : 3.',
          '2+3=___. → Corrigé : 5.',
          '── GRAPHISME ──',
          'Trace 3 lignes horizontales. → Corrigé : évaluation.',
          'Trace 3 lignes verticales. → Corrigé : évaluation.',
          'Trace 3 vagues. → Corrigé : évaluation.',
          '── DESSIN ──',
          'Colorie le soleil en jaune et l\'herbe en vert. → Corrigé : évaluation.',
          'Dessine un cercle, un carré, un triangle. → Corrigé : évaluation.',
          '── CHANT ──',
          'Chante "Tête, épaules, genoux et pieds". → Corrigé : performance orale.',
          '── RÉCITATION ──',
          'Récite "Promenons-nous dans les bois". → Corrigé : performance orale.',
          '── ANGLAIS ──',
          'Count from 1 to 5 in English. → Corrigé : one, two, three, four, five.',
          'What color is the sky ? → Corrigé : blue.',
          '── HYGIÈNE ──',
          'Montre les gestes du lavage des mains. → Corrigé : évaluation gestuelle.',
        ]
      ),

    ]
  },

];

module.exports = { OCTOBRE_12EME };
