'use strict';

// Programme Garderie — année scolaire 2025-2026
// Matières : LANGAGE · MORALE · GRAPHISME · PRE-LECTURE · PRE-CALCUL · PRE-MATHS · ...

const m = (matiere, topic, approche, transmission, exercices) =>
  ({ matiere, topic, approche, transmission, exercices });

const PERIODES_GARDERIE = [
  { num: 1, libelle: '1ère Période', debut: '01/09/2025', semaines: [
// ── S1 : Prise de contact — toutes les matières ───────────────────────────────
{
  n: 1, dateDebut: "2025/09/01",
  theme: "Prise de contact — La rentrée",
  sous: "Prise de contact et test de pré-requis dans toutes les matières",
  matieres: [
    m("LANGAGE","Prise de contact / Test de pré-requis",
      "La première séance de Langage est consacrée à la prise de contact et au test de pré-requis. Pour des enfants de 3-4 ans entrant en Garderie, l'enseignant(e) crée une atmosphère chaleureuse et sécurisante. On observe les capacités langagières initiales de façon informelle, à travers le jeu et la conversation naturelle.",
      ["Regrouper les enfants en cercle sur le tapis. L'enseignant(e) se présente doucement : 'Bonjour, je m'appelle Maîtresse [Nom]. Et toi, comment tu t'appelles ?' — tour de cercle, chaque enfant dit son prénom ou montre s'il n'ose pas encore parler.",
       "Jeu du 'Coucou' : l'enseignant(e) cache son visage derrière ses mains puis révèle 'Coucou !' — les enfants imitent ce geste pour briser la glace et créer un premier lien affectif.",
       "Montrer 4-5 images simples (maison, chien, soleil, pomme, bébé) et demander : 'Qui sait ce que c'est ?' — observer les réponses sans corriger, juste évaluer le vocabulaire spontané.",
       "Clôture rituelle : l'enseignant(e) chante 'Au revoir, à demain !' sur un air simple et invite les enfants à agiter la main — créer le tout premier rituel de classe."],
      ["Tour de prénom : chaque enfant dit son prénom, un adulte l'écrit sur une étiquette à coller sur les vêtements.",
       "Pointer une image parmi 2 selon la consigne : 'Montre-moi le chien' — évaluation silencieuse de la compréhension orale simple.",
       "Associer un son à un animal : l'enseignant(e) fait le bruit (meuh, wouf, miaou) et l'enfant montre l'image correspondante."]),
    m("MORALE","Prise de contact / Test de pré-requis",
      "Première observation des comportements moraux et sociaux spontanés. Pour des enfants de 3-4 ans, on n'enseigne pas encore de règle formelle — on observe comment ils interagissent, s'ils disent bonjour, s'ils partagent naturellement. C'est la base pour adapter l'enseignement moral de l'année.",
      ["Accueillir chaque enfant à la porte en disant 'Bonjour !' et en se baissant à leur niveau — observer qui répond spontanément, qui reste silencieux.",
       "Temps de jeu libre avec des jouets partagés (2-3 jouets pour 5 enfants) — observer comment ils gèrent le partage : se disputent-ils ? Prennent-ils chacun leur tour ?",
       "Présenter une marionnette : 'Elle s'appelle Mimi. Elle dit bonjour comment ?' — les enfants réagissent et observent la marionnette dire bonjour.",
       "Question ouverte et simple : 'Est-ce qu'on peut prendre les affaires des autres sans demander ?' — écouter les réponses spontanées, même non verbales."],
      ["Observer : l'enfant dit-il bonjour et au revoir spontanément sans y être invité ? — noter le niveau de départ.",
       "Jeu du partage : donner un seul jouet à 2 enfants — observer s'ils partagent ou se disputent — évaluation comportementale informelle.",
       "Pointer l'image du bon comportement parmi 2 images simples (enfant qui partage / enfant qui tire les jouets)."]),
    m("GRAPHISME","Prise de contact / Test de pré-requis",
      "Observer comment les enfants de 3-4 ans tiennent un crayon et tracent. Pour beaucoup, c'est la première fois qu'ils touchent un crayon. L'objectif est uniquement d'observer le niveau de départ du geste graphique, sans stress ni jugement.",
      ["Distribuer une grande feuille blanche (A3 si possible) et des crayons de couleur épais à chaque enfant.",
       "Consigne totalement libre : 'Fais ce que tu veux sur la feuille, tu peux tout faire !' — observer la prise du crayon (poing fermé ? tripode naissant ?), le geste (aléatoire ? dirigé ?), la pression.",
       "L'enseignant(e) trace un grand cercle et une ligne horizontale au tableau : 'Qui peut faire pareil sur sa feuille ?' — sans obligation, juste observer qui peut reproduire un geste guidé.",
       "Collecter les feuilles avec le prénom de l'enfant — elles servent de référence de départ pour mesurer la progression au fil des mois."],
      ["Observer la prise du crayon (poing fermé, 2 doigts, tripode ?) — noter le niveau de départ sans intervenir encore.",
       "Tracer une ligne spontanément sur la feuille — observer si possible ou non à cet âge.",
       "Tracer un cercle spontanément — observer si forme intentionnelle ou aléatoire."]),
    m("PRE-LECTURE","Prise de contact / Test de pré-requis",
      "Observer si l'enfant reconnaît des images simples, peut pointer des objets sur demande, tient un livre dans le bon sens. À 3-4 ans, c'est le socle avant la pré-lecture : l'association image-objet-mot.",
      ["Montrer 5 flashcards d'objets courants (pomme, voiture, maison, chien, soleil) une par une — demander : 'Qui sait ce que c'est ?' — observer le vocabulaire spontané.",
       "Pointer chaque image en disant son nom clairement — les enfants répètent en chœur — évaluation de la capacité à imiter.",
       "Jeu du 'cache-cache d'images' : mettre une flashcard sous un tissu, en faire sortir un coin — qui reconnaît l'image avant de la voir entièrement ?",
       "Observer comment un enfant tient un livre illustré : le met-il dans le bon sens ? Tourne-t-il les pages une par une ?"],
      ["Pointer la bonne image parmi 2 flashcards selon la consigne : 'Montre-moi le chien' — évaluation de la compréhension orale simple.",
       "Nommer une image quand l'enseignant(e) la montre — évaluation du vocabulaire oral.",
       "Tenir un livre illustré et regarder les images dans l'ordre en tournant les pages doucement."]),
    m("PRE-CALCUL","Prise de contact / Test de pré-requis",
      "Observer si l'enfant peut réciter les premiers nombres, reconnaître une quantité de 1 à 3. À 3-4 ans, beaucoup ne savent pas encore compter au-delà de 2 — c'est une observation neutre qui aide à adapter l'enseignement.",
      ["Montrer 1 doigt, puis 2, puis 3 en disant : 'Un, deux, trois' — demander : 'Combien y en a-t-il ?' — observer les réponses.",
       "Poser 2 cailloux sur la table : 'Combien il y en a ?' — observer si l'enfant compte ou devine par intuition.",
       "Chanson des doigts : 'Un, deux, trois — je lève mes doigts !' sur un air simple avec gestes — observer la participation.",
       "Montrer un verre plein et un verre vide : 'Lequel est plein ? Lequel est vide ?' — pré-test de la notion plein/vide."],
      ["Montrer le bon nombre de doigts (1, 2 ou 3) quand l'enseignant(e) demande — évaluation de la connaissance des nombres.",
       "Prendre 2 jetons dans un tas sur demande — évaluation de la cardinalité.",
       "Pointer le groupe 'qui a plus d'objets' parmi 2 groupes (3 vs 1 objet)."]),
    m("PRE-MATHS","Prise de contact / Test de pré-requis",
      "Observer quelles notions pré-mathématiques l'enfant possède déjà : grand/petit, beaucoup/peu, même/différent. Ces notions se testent par manipulation d'objets concrets, sans écrit.",
      ["Montrer un grand cahier et un petit cahier côte à côte : 'Lequel est grand ? Lequel est petit ?' — observer et noter les réponses.",
       "Poser beaucoup de cailloux d'un côté et peu de l'autre : 'Où il y en a beaucoup ? Où il y en a peu ?' — observation de la compréhension quantitative.",
       "Montrer 2 cercles de même couleur et 1 carré de couleur différente : 'Lequel est différent des autres ?' — test de discrimination visuelle.",
       "Donner un mélange de 4 boutons rouges et 4 bleus — observer si l'enfant trie spontanément ou non."],
      ["Pointer le 'grand' objet parmi 2 objets de tailles différentes — évaluation de la notion grand/petit.",
       "Pointer le groupe 'beaucoup' entre 2 groupes (5 objets vs 1 objet) — évaluation de la notion quantitative.",
       "Trier 4 objets de 2 couleurs en 2 groupes — observation libre de la capacité de classement."]),
    m("ENVIRONNEMENT","Prise de contact / Test de pré-requis",
      "Observer la curiosité de l'enfant pour son environnement immédiat : la classe, l'école. Observer s'il reconnaît et nomme des objets courants de la vie quotidienne.",
      ["Visite guidée de la classe : montrer chaque coin (coin tapis, coin jeux, tableau, fenêtre) — observer les réactions et les questions des enfants.",
       "Pointer des objets dans la classe un par un : 'Qui sait comment s'appelle cet objet ?' — observer le vocabulaire environnemental spontané.",
       "Emmener les enfants brièvement dans le couloir ou la cour : 'Qu'est-ce que vous voyez ?' — laisser répondre librement.",
       "Retour en classe : 'Qu'est-ce que vous avez vu dehors ?' — évaluation de la mémorisation immédiate."],
      ["Nommer 3 objets montrés dans la classe (crayon, cahier, table) — évaluation du vocabulaire.",
       "Pointer la fenêtre, la porte, le tableau quand demandé — évaluation de la compréhension des consignes simples.",
       "Décrire 1 chose vue dans la cour ou le couloir — évaluation de la mémoire immédiate."]),
    m("LES COULEURS","Prise de contact / Test de pré-requis",
      "Observer quelles couleurs l'enfant reconnaît et peut nommer. À 3-4 ans, certains connaissent rouge et bleu, d'autres ne connaissent aucune couleur nommée. Cette observation guide l'ordre d'enseignement des couleurs.",
      ["Montrer 4 feutres de couleurs claires (rouge, bleu, jaune, vert) — demander pour chacun : 'Cette couleur, qui la connaît ? Comment elle s'appelle ?' — observer sans juger.",
       "Jeu de pointage dans la classe : 'Montre-moi quelque chose de rouge dans la salle.' — observer qui peut identifier la couleur rouge.",
       "Chaque enfant choisit son feutre préféré et colorie librement 2 minutes — observer les préférences de couleur.",
       "Demander le nom de la couleur choisie : 'C'est quelle couleur ?' — évaluer le vocabulaire des couleurs."],
      ["Pointer l'objet de la bonne couleur parmi 3 objets selon la consigne — évaluation de la discrimination visuelle des couleurs.",
       "Nommer la couleur d'un objet bien connu (la pomme, le ciel) — évaluation du vocabulaire couleurs.",
       "Trier 4 crayons en 2 couleurs (2 rouges et 2 bleus) en 2 groupes — évaluation du tri par couleur."]),
    m("DESSIN DIRIGÉ","Prise de contact / Test de pré-requis",
      "Observer le niveau de dessin spontané de l'enfant à 3-4 ans. À cet âge, le 'dessin' va du gribouillage aléatoire à des tentatives de formes intentionnelles. L'observation du geste graphique libre permet de situer chaque enfant.",
      ["Distribuer une feuille blanche et des crayons de couleur. Consigne très libre : 'Dessine quelque chose que tu aimes ou quelque chose que tu veux.'",
       "Observer sans intervenir : l'enfant tient-il le crayon ? Fait-il des gribouillages ? Tente-t-il des formes rondes ou allongées ?",
       "L'enseignant(e) dessine un bonhomme bâton très simple au tableau (tête-ronde + corps-ligne + 2 bras + 2 jambes) : 'Qui peut faire un bonhomme comme ça ?' — sans obligation.",
       "Afficher tous les dessins avec le prénom sans commentaire de valeur — valoriser la participation."],
      ["Dessiner librement et nommer ce qu'on a dessiné à l'enseignant(e).",
       "Tracer un cercle (tête du bonhomme) sur la feuille — observation du geste circulaire.",
       "Colorier un grand cercle pré-tracé par l'adulte avec la couleur choisie par l'enfant."]),
    m("ART PLASTIQUE","Prise de contact / Test de pré-requis",
      "Premier contact avec la pâte à modeler. Observer comment l'enfant manipule un matériau malléable : est-il à l'aise ? A-t-il déjà utilisé de la pâte ? Y a-t-il des enfants qui évitent de toucher (sensibilités tactiles) ?",
      ["Distribuer une boule de pâte à modeler à chaque enfant. Consigne totalement libre : 'Tu peux faire ce que tu veux avec ça, touche, explore !'",
       "Observer sans juger : l'enfant aplatit-il ? Roule-t-il ? Fait-il des formes intentionnelles ? Refuse-t-il de toucher ?",
       "Demander après 3-4 minutes : 'Qu'est-ce que tu as fait ?' — valoriser TOUTES les réponses quelle qu'elles soient.",
       "Tour de présentation : chaque enfant montre sa création et dit 1 mot pour la décrire si possible."],
      ["Explorer librement la pâte à modeler pendant 5 minutes — observation du rapport au matériau.",
       "Faire une boule en roulant entre les paumes et la montrer à l'enseignant(e).",
       "Nommer ou mimer ce qu'on a créé avec la pâte."]),
    m("EXERCICE SENSORIEL","Prise de contact / Test de pré-requis",
      "Observer les réactions sensorielles de l'enfant : aime-t-il toucher des matières variées ? Est-il sensible aux sons, aux textures ? Certains enfants ont des hypersensibilités qui doivent être identifiées dès la rentrée pour adapter l'enseignement.",
      ["Atelier textures : proposer 4 objets à toucher (coton très doux, papier de verre rugueux, plastique lisse, éponge mouillée) — pour chacun : 'Touche et dis ce que tu ressens.'",
       "Atelier sons : frapper sur différents matériaux (bois, métal, verre) — 'Qu'est-ce que tu entends ? C'est pareil ou différent ?'",
       "Atelier vue : observer des images de couleurs vives et des photos en noir et blanc — 'Quelle image tu préfères ?'",
       "Observer et noter : y a-t-il des enfants qui refusent de toucher certaines textures ? Des enfants qui bouchent leurs oreilles ? Ces informations guident l'adaptation pédagogique."],
      ["Classer 4 objets tactiles en 'doux' et 'pas doux' — évaluation de la discrimination tactile.",
       "Reconnaître le son grave vs le son aigu entre 2 instruments (tambour grave / clochette aiguë).",
       "Pointer l'image qu'on préfère parmi 2 images et expliquer en 1 mot."]),
    m("ANGLAIS","Prise de contact / Test de pré-requis",
      "Premier contact avec la langue anglaise pour les enfants de Garderie. Observer si certains ont déjà entendu de l'anglais à la maison, à la télévision. Créer une première impression positive et ludique de cette langue.",
      ["Entrée en classe avec une marionnette anglophone : 'Hello ! My name is Teddy ! What is your name ?' — observer les réactions : qui comprend ? qui sourit ? qui répond spontanément ?",
       "Enseigner 'Hello' et 'Goodbye' avec des gestes très clairs (saluer de la main pour Hello, agiter au revoir pour Goodbye) — répéter 3 fois lentement en chœur.",
       "Observer : y a-t-il des enfants qui connaissent déjà ces mots ? Des enfants qui répètent spontanément ?",
       "Chanson de salutation très simple : 'Hello, hello, hello friends — goodbye, goodbye, goodbye friends' sur un air inventé — observer la participation."],
      ["Répondre 'Hello' quand la marionnette dit 'Hello' — réponse physique et orale.",
       "Agiter la main et dire 'Goodbye' à la fin de la séance quand l'enseignant(e) dit 'Goodbye'.",
       "Chanter le refrain de la chanson de salutation en imitant l'enseignant(e)."]),
    m("TRAVAIL MANUEL","Prise de contact / Test de pré-requis",
      "Observer les capacités de motricité fine manuelle : l'enfant peut-il déchirer du papier avec ses deux mains ? Froisser ? Utiliser une baguette de colle ? Ces observations identifient les enfants qui n'ont jamais fait d'activité manuelle.",
      ["Déchirer du papier journal libre : 'Déchire le papier comme tu veux, en petits bouts ou en bandes.' — observer la coordination des deux mains (main qui tient, main qui tire).",
       "Froisser une feuille en boule avec les deux paumes — observer la pression et la coordination.",
       "Proposer une baguette de colle : 'Colle ta boule de papier sur une grande feuille.' — observer si l'enfant sait utiliser la colle.",
       "Montrer et féliciter la production de chaque enfant — créer un sentiment de fierté dans la réalisation."],
      ["Déchirer 3 bandes de papier journal en utilisant les deux mains — évaluation de la coordination bimanuelle.",
       "Froisser une feuille A4 en boule — évaluation de la motricité fine.",
       "Coller la boule froissée sur une grande feuille avec de la colle — évaluation de l'usage d'un outil."]),
    m("ESPACE PHYSIQUE","Prise de contact / Test de pré-requis",
      "Observer les capacités motrices globales des enfants de 3-4 ans : marchent-ils avec équilibre ? Peuvent-ils s'arrêter sur signal ? Sautent-ils ? Ces observations guident l'enseignement de l'espace physique pour l'année.",
      ["Marcher librement dans l'espace disponible : 'Marche dans la salle, va où tu veux.' — observer l'équilibre, les trajectoires, si l'enfant bouscule les autres.",
       "Sur signal (clap des mains) : s'arrêter IMMÉDIATEMENT. Recommencer. Répéter 4-5 fois — observer la réactivité au signal et le contrôle corporel.",
       "Sauter sur place : 'Qui peut sauter ? Montrez-moi !' — observer si l'enfant peut quitter le sol avec les deux pieds.",
       "Courir lentement en cercle en suivant l'enseignant(e) — observer la capacité à suivre une trajectoire."],
      ["S'arrêter immédiatement sur signal sonore (clap ou sifflet) — évaluation de la réactivité motrice.",
       "Sauter 3 fois sur place sans tomber — évaluation de l'équilibre dynamique.",
       "Marcher en file indienne derrière l'enseignant(e) sans sortir de la file — évaluation de la coordination spatiale."]),
    m("CHANT","Prise de contact / Test de pré-requis",
      "Observer les réactions des enfants à la musique : chantent-ils spontanément ? Imitent-ils les gestes ? Aiment-ils les comptines ? La voix à 3-4 ans est fragile et en développement — l'objectif est l'observation et le plaisir, pas la justesse.",
      ["Chanter 'Bonjour les enfants' sur un air simple en faisant des gestes expressifs — observer qui chante avec vous, qui regarde, qui détourne le regard.",
       "Frapper le rythme sur les genoux (pata-pata) pendant le chant — observer qui imite, qui n'imite pas.",
       "Chanter une comptine très connue ('Promenons-nous dans les bois' ou comptine locale) — observer lesquels la reconnaissent et fredonnent spontanément.",
       "Question finale : 'Qui aime chanter ? Levez la main !' — créer une culture positive autour du chant."],
      ["Chanter avec l'enseignant(e) pendant la chanson de bienvenue — évaluation de la participation musicale.",
       "Frapper le rythme sur les genoux pendant le chant — évaluation du sens du rythme naissant.",
       "Faire les gestes associés aux mots de la chanson — évaluation de la coordination parole-geste."]),
    m("RÉCITATION","Prise de contact / Test de pré-requis",
      "Observer si l'enfant peut répéter une courte phrase de mémoire après l'avoir entendue 1-2 fois. À 3-4 ans, la mémorisation verbale est en cours de développement et varie beaucoup d'un enfant à l'autre. C'est une observation sans pression.",
      ["Dire une phrase très courte : 'Je vais à l'école.' — l'enfant répète immédiatement. Observer si la phrase est bien reproduite ou approximative.",
       "Dire 2 mots liés à la rentrée à retenir : 'Crayon, cahier.' — après 30 secondes d'autre activité, demander : 'Qui se souvient des 2 mots ?'",
       "Comptine de 2 lignes seulement : 'Bonjour Maîtresse / Bonjour l'école.' — répéter collectivement 2 fois, puis chaque enfant à son tour si volontaire.",
       "Observer sans forcer : l'enfant peut-il répéter une phrase de 4-5 mots ? Seulement 1-2 mots ? Comment est la mémorisation à court terme ?"],
      ["Répéter la phrase-modèle de 4-5 mots après l'enseignant(e) — évaluation de la mémoire immédiate.",
       "Se souvenir de 2 mots après 1 minute de distraction — évaluation de la rétention à court terme.",
       "Réciter les 2 lignes de la comptine en groupe ou en solo volontaire."]),
  ],
},

// ── S2 : Exploration — Découverte de la classe ────────────────────────────────
{
  n: 2, dateDebut: "2025/09/08",
  theme: "Exploration — Découverte de la classe",
  sous: "Gribouillage libre, jeux sensoriels, découverte de l'espace, chant de bienvenue",
  matieres: [
    m("GRAPHISME","Gribouillage",
      "Le gribouillage est la toute première étape du graphisme pour les enfants de 3-4 ans. Pas de contrainte, pas de modèle — l'enfant explore librement le geste de tracer. L'enseignant(e) valorise TOUS les tracés sans jugement esthétique. L'objectif est de développer la motricité fine, le plaisir de tracer et la maîtrise progressive du crayon.",
      ["Montrer comment tenir le crayon entre 3 doigts (pouce-index-majeur) — faire mimer sans crayon d'abord comme une 'pince à linge'. Puis saisir le crayon doucement.",
       "Démonstration de gribouillage libre par l'enseignant(e) sur une grande feuille au tableau : 'Je vais dans tous les sens, je fais des boucles, je couvre toute la feuille — vous pouvez faire pareil !'",
       "Distribuer des grandes feuilles (A3) et des feutres épais. Laisser les enfants gribouiller librement 8-10 minutes. L'enseignant(e) circule et commente positivement.",
       "Variante sensorielle : tracer dans un bac de sel ou de sable fin avec l'index — libère la pression et active les sens tactiles.",
       "Partage final : afficher quelques productions et demander à l'auteur : 'Qu'est-ce que tu as fait ?' — valoriser la créativité."],
      ["Gribouillage libre sur grande feuille avec feutre épais — remplir toute la surface sans contrainte.",
       "Tracer dans un bac de sable avec l'index : d'abord des zigzags, puis des cercles — exploration sensorielle du geste.",
       "Faire des vagues sur la feuille avec de la craie grasse — geste de gauche à droite préparant au sens de l'écriture.",
       "Tracer un chemin avec le doigt entre deux points sur une fiche plastifiée — début de contrôle du geste."]),
    m("EXERCICE SENSORIEL","Jeux",
      "La semaine d'exploration sensorielle par les jeux libres est fondamentale pour les tout-petits de 3-4 ans. Par le jeu, l'enfant explore son environnement, développe ses 5 sens et construit ses premières représentations du monde. L'enseignant(e) prépare des ateliers sensoriels et observe sans trop diriger.",
      ["Présenter les ateliers sensoriels installés dans la salle : bac de sable, atelier sons, boîte des textures, images couleurs. Expliquer brièvement chaque atelier.",
       "Distribuer les enfants par petits groupes (3-4 par atelier). Rotation toutes les 6-7 minutes au signal de l'enseignant(e).",
       "L'enseignant(e) circule entre les ateliers et pose des questions douces : 'Qu'est-ce que tu ressens là ? C'est doux ou dur ? Tu aimes ?'",
       "Ateliers : (1) Bac de sable — construire, tracer, remplir des contenants. (2) Boîte des sons — deviner le son de clochette, tambour, sonnaille. (3) Boîte des textures — toucher et deviner. (4) Images couleurs — choisir la préférée.",
       "Regroupement final : chacun dit son atelier préféré avec un mot ou un geste — première expression de préférence."],
      ["Dans le bac de sable : remplir un petit bol avec une cuillère, le vider — exploration du plein/vide.",
       "Boîte tactile : mettre la main et deviner parmi 3 objets cachés (coton, caillou, éponge) — discrimination tactile.",
       "Instruments : reproduire un rythme simple (tap-tap-tap) frappé par l'enseignant(e) — discrimination auditive.",
       "Choisir sa couleur préférée parmi 4 cartes couleur et expliquer pourquoi avec 1 mot."]),
    m("ESPACE PHYSIQUE","Découverte de l'espace classe",
      "La première vraie séance d'espace physique consiste à apprendre les règles de mouvement dans la classe et la cour. Les enfants de 3-4 ans explorent l'espace en apprenant à naviguer sans se bousculer et à s'arrêter sur signal.",
      ["Expliquer les règles de sécurité avec des mots très simples : 'On ne bouscule pas, on ne court pas dans la classe, on écoute le signal.'",
       "Marche libre dans l'espace en musique douce : quand la musique s'arrête, on s'arrête complètement — répéter 5-6 fois.",
       "Jeu du 'mur de briques' : les enfants se mettent le dos au mur. Sur signal 'GO !' ils avancent vers le centre. Sur 'STOP !' ils s'immobilisent instantanément.",
       "Exploration en rampant : se déplacer à 4 pattes comme un animal — développement moteur global.",
       "Retour au calme : s'asseoir en cercle sur le tapis, respirations profondes ensemble."],
      ["S'arrêter instantanément quand la musique s'arrête — 5 répétitions chronométrées.",
       "Marcher d'un bout à l'autre de la salle sans toucher personne.",
       "Ramper jusqu'à l'enseignant(e) et revenir à sa place."]),
    m("CHANT","Bonjour",
      "La chanson 'Bonjour' est le tout premier rituel de classe à Garderie. À 3-4 ans, les chansons rituelles créent la sécurité, structurent la journée et développent le langage musical. On chante chaque matin avec des gestes simples — le corps entier participe.",
      ["L'enseignant(e) chante 'Bonjour' une première fois en entier avec des gestes expressifs (sourire, bras ouverts, salut de la main). Les enfants écoutent et observent.",
       "Apprendre ligne par ligne en répétition immédiate : l'enseignant(e) chante une ligne courte, les enfants répètent immédiatement — 3 fois par ligne.",
       "Ajouter les gestes un par un : 'Bonjour' = faire bonjour de la main. 'Comment ça va ?' = hausser les épaules avec le sourire. 'Très bien !' = lever le pouce.",
       "Chanter en entier avec les gestes — d'abord avec l'enseignant(e), puis les enfants essaient seuls.",
       "Installer le rituel : CHAQUE MATIN, dès l'arrivée, on chante 'Bonjour' tous ensemble. C'est le signal que la journée commence."],
      ["Chanter la chanson 'Bonjour' en chœur avec les gestes appris.",
       "Frapper le rythme de la chanson sur les genoux pendant que l'enseignant(e) chante — synchronisation.",
       "Chanter en petits groupes de 3-4 enfants devant les autres.",
       "Chanter en solo si un enfant le souhaite (jamais forcé, toujours valorisé)."]),
  ],
},

// ── S3 : La classe et moi ─────────────────────────────────────────────────────
{
  n: 3, dateDebut: "2025/09/15",
  theme: "La classe et moi",
  sous: "Présentation, politesse, fournitures scolaires, gribouillage, plein/vide, quantité, ROUGE, bonhomme bâton, modelage, la vue, Greetings, coloriage libre, assis-debout, Bonjour, Mes fournitures",
  matieres: [
    m("LANGAGE","Présentation nom Maîtresse, Élèves",
      "La présentation de soi est une compétence sociale fondamentale. Pour des enfants de 3-4 ans, se présenter et reconnaître les prénoms de ses camarades développe la confiance, l'aisance à l'oral et le premier sentiment d'appartenance au groupe. L'enseignant(e) crée des rituels simples, répétitifs et ludiques.",
      ["Rituel en cercle sur le tapis : l'enseignant(e) tient une balle douce et dit : 'Je m'appelle Maîtresse [Nom].' Elle passe la balle à un enfant qui dit son prénom. La balle fait le tour du cercle.",
       "Jeu 'Où est [prénom] ?' : l'enseignant(e) dit 'Où est Rivo ?' — Rivo lève la main et tout le monde l'applaudit. Répéter pour chaque enfant.",
       "Afficher les étiquettes-prénoms au tableau avec une photo si disponible. L'enseignant(e) pointe et lit chaque prénom à voix haute — les enfants répètent en chœur.",
       "Chaque enfant cherche sa propre étiquette dans un tas mélangé — reconnaissance du prénom écrit (première discrimination graphique).",
       "Chanson finale : 'Bonjour [prénom], comment ça va ?' sur l'air de 'Frère Jacques' — l'enseignant(e) chante pour chaque enfant."],
      ["Passer la balle en nommant le destinataire : 'Je passe la balle à [prénom] !' — travail d'écoute et de mémorisation des prénoms.",
       "Mimer son prénom en frappant les syllabes dans les mains : 'Ri-vo' = 2 claps. L'enseignant(e) fait d'abord, les enfants imitent.",
       "Pointer sur le panneau de prénoms : 'Qui vient mettre le doigt sur le prénom de Soa ?' — 3-4 enfants volontaires.",
       "Dessin de son visage sur une feuille avec le prénom écrit par l'adulte — premier portrait affiché dans la classe."]),
    m("MORALE","Politesse en classe",
      "La politesse s'apprend par l'exemple et la répétition. À 3-4 ans, les enfants sont en pleine construction des codes sociaux. L'enseignant(e) joue un rôle de modèle permanent : elle dit toujours 'bonjour', 'merci', 's'il vous plaît'. Les règles sont présentées sous forme d'images simples et joyeuses.",
      ["Séance d'accroche : la marionnette arrive très poliment, salue chaque enfant par son prénom, dit merci quand on lui donne quelque chose. Les enfants observent et réagissent.",
       "Comparer 2 situations illustrées : un enfant qui arrache un jouet VS un enfant qui dit 's'il te plaît, puis-je l'avoir ?' — 'Laquelle préfères-tu ?'",
       "Afficher 4 images de politesse : BONJOUR / MERCI / S'IL TE PLAÎT / AU REVOIR. L'enseignant(e) présente chacune avec un exemple joué.",
       "Entraînement rituel : chaque enfant dit 'bonjour Maîtresse' en entrant dans la classe le matin — l'enseignant(e) répond toujours chaleureusement.",
       "Histoire très courte (3 min) : un bébé lapin apprend à dire merci et découvre que tout le monde l'aime plus."],
      ["Jeu de rôle avec la marionnette : 'La marionnette te donne un jouet. Qu'est-ce que tu dis ?' — l'enfant répond 'merci'.",
       "Choisir la bonne image : parmi 2 images (enfant poli / enfant impoli), pointer celle qui montre le bon comportement.",
       "Tour de table : chaque enfant dit 'bonjour [prénom du voisin] !' et le voisin répond 'bonjour'.",
       "Colorier l'affiche de politesse : colorier les images qui montrent un enfant poli (renforcement positif)."]),
    m("GRAPHISME","Gribouillage",
      "Le gribouillage continue d'être travaillé dans cette deuxième semaine de contenu réel. On explore de nouvelles textures et de nouveaux outils pour varier les sensations et enrichir le geste. Les enfants commencent à avoir davantage de contrôle.",
      ["Rappel rapide de la semaine précédente : 'Vous vous souvenez du gribouillage ? Aujourd'hui on recommence avec de nouveaux outils.'",
       "Gribouillage à la craie grasse sur du papier noir — contraste visuel fort, très stimulant.",
       "Gribouillage avec des feutres fins sur papier blanc — travail de précision du geste.",
       "Tracer dans un bac de farine ou de semoule avec l'index — exploration sensorielle du geste.",
       "Comparaison des productions : 'Regardez ! Chaque gribouillage est différent — c'est pour ça que c'est beau !'"],
      ["Gribouillage libre sur papier noir avec craie blanche — remplir toute la surface.",
       "Tracer des zigzags (haut-bas-haut-bas) sur une feuille de grande taille.",
       "Tracer des spirales au feutre épais — geste continu en spirale sortant du centre.",
       "Tracer dans la semoule avec l'index : d'abord une ligne, puis un cercle."]),
    m("PRE-LECTURE","Présentation: les fournitures scolaires",
      "La pré-lecture commence par la familiarisation avec les objets du quotidien scolaire. Avant de lire des mots, l'enfant apprend à reconnaître des objets réels, à associer image et objet, et à les nommer. Les fournitures scolaires sont l'environnement immédiat — ancrage idéal.",
      ["Sortir les fournitures du sac de l'enseignant(e) une par une : crayon, cahier, gomme, règle, ciseaux, trousse. Pour chacune : 'Qu'est-ce que c'est ? À quoi ça sert ?' — récolter les réponses avant de nommer officiellement.",
       "Afficher les flashcards correspondantes. Pointer et lire le nom à voix haute clairement. Les enfants répètent 3 fois en chœur.",
       "Jeu du sac-surprise : mettre une fourniture dans un sac tissu. Un enfant met la main sans voir et touche. Il décrit et essaie de deviner. La classe valide.",
       "Jeu de la devinette : 'C'est petit, ça efface les erreurs, c'est quoi ?' — les enfants lèvent la main pour répondre.",
       "Afficher le tableau des fournitures dans un coin permanent de la classe."],
      ["Relier la fourniture réelle à sa flashcard image (mise en correspondance 1 à 1).",
       "Pointer la bonne fourniture selon la description orale : 'Montre-moi ce avec quoi on écrit.'",
       "Ranger 4 fournitures nommées dans la trousse dans le bon ordre.",
       "Mimer l'utilisation d'une fourniture — les camarades devinent laquelle."]),
    m("PRE-CALCUL","Plein ≠ vide",
      "'Plein' et 'vide' sont des concepts fondamentaux qui s'apprennent par la manipulation directe. À 3-4 ans, l'enfant a besoin de toucher, de remplir et de vider pour construire ces notions. On utilise des contenants concrets et des matières naturelles (eau, sable, riz).",
      ["Montrer une bouteille vide et une bouteille pleine. Demander : 'Laquelle est pleine ? Comment tu le sais ?' — les enfants répondent et touchent les bouteilles pour sentir le poids.",
       "Démonstration : verser lentement du riz d'une bouteille vide dans une pleine. Commenter : 'Avant c'était vide. Maintenant c'est plein.' Renverser et recommencer.",
       "Jeu par ateliers (3-4 enfants) : remplir des contenants avec du sable ou du riz, puis les vider. L'enseignant(e) commente : 'Tu remplis ! Maintenant c'est plein ! Tu vides... c'est vide !'",
       "Chanson avec gestes : 'Mon bol est plein (mains courbées dessus) — mon bol est vide (mains ouvertes) — je verse — et ça recommence !'",
       "Généralisation : trouver dans la classe des choses pleines et des choses vides (corbeille pleine, sac vide)."],
      ["Pointer le contenant plein parmi 3 présentés (1 plein, 2 vides) — discrimination par observation.",
       "Remplir un bol de riz avec une cuillère jusqu'à ce qu'il soit plein — activité de motricité fine.",
       "Vider un contenant en versant doucement dans un autre — contrôle moteur fin.",
       "Sur une fiche illustrée : entourer les images de contenants pleins en rouge, les vides en bleu."]),
    m("PRE-MATHS","La quantité",
      "La quantité est un concept pré-numérique essentiel. Avant de compter avec des nombres, l'enfant doit comprendre qu'un groupe d'objets a une quantité. On travaille sur de petites collections (1 à 5 objets) en comparant 'il y en a plus / moins / pareil'. Tout se passe par manipulation sensorielle.",
      ["Présenter deux assiettes : une avec 1 jeton, une avec 5 jetons. 'Laquelle a plus ?' Les enfants pointent. 'Comment tu le sais ?' — faire verbaliser en termes simples.",
       "Jeu de la comparaison : l'enseignant(e) montre 2 groupes d'objets, les enfants disent 'plus' ou 'moins' en levant la main.",
       "Constituer une collection sur commande : 'Mets 2 cailloux sur ton tapis.' — les enfants prennent et posent. L'enseignant(e) vérifie.",
       "Chanson de comptage avec gestes : 'Un, deux, trois — on tape ses mains' avec les doigts levés progressivement.",
       "Jeu du 'distributeur' : un enfant distribue 1 objet à chaque camarade — vérification collective que chacun en a autant."],
      ["Pointer la carte qui montre 'beaucoup' parmi 3 cartes illustrées (1, 3, et 5 objets).",
       "Mettre autant de jetons que de points sur la carte-modèle (correspondance terme à terme) pour des quantités de 1 à 3.",
       "Trier des collections : 'mets dans l'assiette rouge ceux qui ont beaucoup' — tri par quantité.",
       "Sur fiche : entourer le groupe qui a plus d'objets entre 2 groupes dessinés."]),
    m("ENVIRONNEMENT","Les fournitures scolaires",
      "Découvrir l'environnement scolaire commence par les objets les plus proches : les fournitures de la classe. L'objectif est que l'enfant puisse nommer, reconnaître et utiliser correctement chaque fourniture. C'est aussi une initiation aux règles d'utilisation et de rangement.",
      ["Sortir les fournitures une par une du sac. Pour chacune : 'Comment s'appelle cet objet ? À quoi ça sert ?' — valoriser toutes les réponses.",
       "Démonstration de l'utilisation correcte : tenir le crayon, ouvrir et fermer la trousse, tourner les pages du cahier.",
       "Jeu du 'bon rangement' : l'enseignant(e) montre une fourniture et les enfants indiquent où la ranger (trousse, sac, bureau).",
       "Afficher les flashcards des fournitures dans un coin de la classe. Lire les noms ensemble en chœur.",
       "Chanson des fournitures : 'Dans ma trousse il y a, un crayon et un cahier, une gomme et une règle, pour bien travailler !' avec gestes."],
      ["Nommer chaque fourniture quand l'enseignant(e) la pointe — évaluation du vocabulaire appris.",
       "Retrouver dans sa propre trousse la fourniture nommée — application concrète.",
       "Sur fiche : relier la fourniture à son utilité (crayon → écrire, gomme → effacer).",
       "Ranger sa trousse correctement à la fin de la séance — évaluation pratique."]),
    m("LES COULEURS","ROUGE",
      "Le rouge est la première couleur officiellement apprise car c'est une couleur forte, visuellement marquante et facilement identifiable pour les jeunes enfants. L'apprentissage des couleurs à 3-4 ans se fait par association, répétition et jeux de tri dans de multiples contextes.",
      ["Montrer une grande carte rouge. 'Cette couleur, qui la connaît ? Elle s'appelle ROUGE.' Faire répéter 3 fois en chœur avec enthousiasme et gestes.",
       "Chasse au rouge dans la classe : 'Cherchez un objet rouge autour de vous et levez-le !' — les enfants cherchent et montrent. Valider chaque trouvaille.",
       "Chanson : 'Le rouge, le rouge, tout ce qui est rouge — les tomates, les roses, le feu des pompiers !' avec gestes associés.",
       "Jeu de tri : trier des objets colorés et mettre les rouges dans une boîte rouge.",
       "Montrer des images rapides : 'Est-ce rouge ou pas rouge ?' — les enfants répondent avec le pouce vers le haut ou le bas."],
      ["Colorier des objets en rouge sur une fiche (pomme, ballon, cœur, fraise).",
       "Trier une collection d'objets : mettre les rouges dans la boîte rouge, les autres dans la boîte bleue.",
       "Tamponner en rouge (éponge trempée) sur la silhouette d'une pomme.",
       "Jeu de pointage : pointer tous les objets rouges sur une image de classe ou de marché."]),
    m("DESSIN DIRIGÉ","Mon bonhomme bâton",
      "Le bonhomme bâton est le premier dessin dirigé pour les enfants de 3-4 ans. Il s'agit de la représentation la plus universelle et intuitive du corps humain. L'enseignant(e) décompose le bonhomme en formes simples et guide les enfants étape par étape avec enthousiasme.",
      ["Dessiner un grand bonhomme bâton au tableau en nommant chaque partie : 'D'abord un grand rond pour la tête (tracer). Puis une ligne vers le bas pour le corps (tracer). Puis deux bras (tracer). Puis deux jambes (tracer). Voilà un bonhomme !'",
       "Faire tracer chaque partie dans l'air avec le bras avant de passer sur la feuille : 'Dans l'air, on fait un grand rond... maintenant sur la feuille !'",
       "Distribuer les feuilles. Les enfants tracent étape par étape en suivant l'enseignant(e) qui guide au tableau.",
       "Ajouter des détails simples : 'Qui veut ajouter des yeux ? Un sourire ?' — les enfants personnalisent librement.",
       "Exposition des bonhommes : afficher et féliciter chaque production."],
      ["Tracer un grand rond (tête) à main levée sur la feuille.",
       "Ajouter une ligne verticale sous le rond (corps du bonhomme).",
       "Ajouter 2 lignes pour les bras et 2 lignes pour les jambes.",
       "Colorier le bonhomme terminé avec les couleurs choisies."]),
    m("ART PLASTIQUE","Modelage",
      "Le modelage est l'une des activités les plus riches pour les jeunes enfants : il développe la motricité fine des deux mains, la sensorialité (texture, température, pression), la créativité et la concentration. À 3-4 ans, il n'y a pas d'erreur en modelage — tout ce que l'enfant crée est valable et valorisé.",
      ["Donner à chaque enfant une boule de pâte à modeler. Laisser 2 minutes d'exploration libre : 'Touche, sens, regarde — qu'est-ce que tu ressens ?'",
       "Enseigner les 3 gestes de base par démonstration : (1) BOULER — rouler entre les paumes en cercles. (2) APLATIR — presser avec la paume ouverte. (3) SERPENT — rouler sur la table en aller-retour.",
       "Les enfants pratiquent chaque geste sous guidance. L'enseignant(e) circule et guide les mains si nécessaire.",
       "Création libre : 'Maintenant fais quelque chose que tu aimes.' Pas de modèle imposé — valoriser toutes les formes.",
       "Partage des créations : chaque enfant montre et dit : 'J'ai fait un ___.'"],
      ["Faire 3 boulettes de même taille en roulant entre les paumes.",
       "Aplatir une boulette pour faire une 'crêpe' — reconnaître qu'elle est maintenant plate.",
       "Faire un serpent long et l'enrouler en escargot.",
       "Création libre : faire l'objet de son choix et le présenter à un camarade."]),
    m("EXERCICE SENSORIEL","La vue",
      "La vue est le sens dominant chez l'enfant de 3-4 ans. Développer la conscience visuelle (qu'est-ce qu'on voit ? comment on voit ? à quoi sert la vue ?) développe l'attention visuelle, la discrimination et la curiosité. Les activités combinent observation attentive et jeux de conscience corporelle.",
      ["Regroupement : 'Fermez les yeux.' Attendre 5 secondes. 'Ouvrez. Qu'avez-vous vu quand vous aviez les yeux fermés ? Rien ? Pourquoi ?' — introduire la vue comme sens.",
       "Miroir : les enfants se regardent. 'Qu'est-ce que vous voyez ? Où se trouvent vos yeux ? Votre nez ?' — pointer les organes visibles.",
       "Jeu du bandeau : un enfant a les yeux bandés. Un objet est placé devant lui. Il touche sans voir. 'Maintenant regarde !' — révéler et comparer sensation vs vision.",
       "Observation fine d'une image colorée : 'Cherchez quelque chose de rouge... quelque chose de petit... un animal...' — développement de l'attention visuelle.",
       "Discussion courte : 'À quoi sert la vue dans notre vie ?' — traverser la rue, reconnaître maman, voir la couleur."],
      ["Trouver 3 objets rouges dans la salle en regardant attentivement autour de soi.",
       "Fermer les yeux pendant que l'enseignant(e) cache un objet visible — retrouver où il est caché.",
       "Observer une image détaillée et pointer 5 éléments nommés par l'enseignant(e).",
       "Dessiner ses deux yeux sur une fiche et les colorier de la couleur qu'on choisit."]),
    m("ANGLAIS","Greetings",
      "L'anglais en Garderie commence par les salutations, formules les plus motivantes et les plus utilisées. À 3-4 ans, l'apprentissage d'une langue se fait par écoute répétée, chansons et jeux. L'objectif est que 'Hello' et 'Goodbye' deviennent des réflexes dans la routine de classe.",
      ["La marionnette Mr. Teddy arrive et dit : 'Hello children! My name is Teddy!' avec enthousiasme. Réaction des enfants : qui peut dire bonjour à Teddy ? On répond 'Hello Teddy!'",
       "Enseigner 'Hello / Hi' : l'enseignant(e) dit 'Hello !' en agitant la main. Tous répètent 5 fois. Puis un enfant dit Hello à son voisin qui répond Hello.",
       "Chanson : 'Hello, hello, hello — how are you? I'm fine, I'm fine, I hope that you are too!' avec gestes et sourires obligatoires.",
       "Enseigner Goodbye : 'Now Teddy is leaving — we say Goodbye !' Chaque enfant agite la main et dit 'Goodbye Teddy !'",
       "Rituel de fin de séance : toute la classe dit 'Goodbye ! See you tomorrow !' — ancrer le rituel dans la routine quotidienne."],
      ["Tour de cercle : chaque enfant dit 'Hello, my name is ___' à son voisin.",
       "Jeu de rapidité : l'enseignant(e) dit 'Hello' et les enfants doivent répondre 'Hello !' le plus vite possible.",
       "Chanter la chanson de salutation en duo avec un camarade.",
       "Répondre à 'How are you ?' par 'I'm fine' avec le pouce levé."]),
    m("TRAVAIL MANUEL","Coloriage libre",
      "Le coloriage libre à 3-4 ans est une exploration de la couleur et du geste graphique. 'Libre' signifie que l'enfant choisit ses couleurs et son style. L'enseignant(e) ne s'attend pas à ce que l'enfant reste dans les lignes — c'est une compétence qui vient progressivement.",
      ["Présenter la feuille de coloriage (grandes formes simples) ou une feuille blanche. 'Aujourd'hui tu colories comme tu veux — tu choisis les couleurs que tu aimes.'",
       "Montrer comment tenir le crayon : 'Pince à linge — pouce, index, majeur. Le crayon s'appuie sur le majeur.' Faire essayer sans feuille d'abord.",
       "Montrer le geste de coloriage : aller-retour réguliers, ne pas appuyer trop fort, commencer par une forme.",
       "Les enfants colorient librement 10-15 minutes. L'enseignant(e) circule et commente positivement : 'Quelle belle couleur ! J'aime ce que tu fais !'",
       "Exposition des colorages : afficher et demander à l'auteur sa couleur préférée."],
      ["Colorier une grande pomme avec 2 couleurs au minimum.",
       "Colorier un dessin simple en choisissant au moins 3 couleurs différentes.",
       "Inventer des couleurs originales : 'Et si le soleil était violet ?' — encourager la créativité.",
       "Créer un fond de couleur sur feuille blanche : remplir toute la surface."]),
    m("ESPACE PHYSIQUE","Mouvements: Assis - Debout",
      "Comprendre et maîtriser les positions 'assis' et 'debout' est une compétence posturale fondamentale. Cela développe le vocabulaire corporel et la capacité à suivre des consignes motrices simples. On travaille par jeux répétitifs très courts avec de la musique.",
      ["Regrouper en cercle avec de l'espace. 'Aujourd'hui on apprend à se lever et s'asseoir vite ! Regardez : assis... debout... assis... debout.' Démonstration lente puis rapide.",
       "Jeu collectif : 'Quand je dis DEBOUT vous vous levez, quand je dis ASSIS vous vous asseyez. Prêts ?' — commencer lentement, accélérer progressivement.",
       "Jeu de surprise : alterner les commandes de manière inattendue pour garder l'attention. Rajouter des pauses ('freeze !').",
       "Jeu musical : pendant la musique on se déplace debout, quand elle s'arrête on s'assoit. Quand elle reprend on se lève.",
       "Variante fun : 'Assis si tu aimes le riz ! Debout si tu aimes le chocolat !' — rendre le jeu personnel."],
      ["Jeu 'Jacques a dit' avec ASSIS et DEBOUT — obéir seulement si Jacques a dit.",
       "Se lever et s'asseoir 5 fois le plus vite possible — défis de rapidité.",
       "Jeu de la chaise musicale : se déplacer debout autour des chaises, s'asseoir quand la musique s'arrête.",
       "Chant-mouvement : 'Debout les enfants !' — se lever. 'Maintenant on s'assoit !' — s'asseoir."]),
    m("CHANT","Bonjour",
      "La chanson 'Bonjour' s'ancre maintenant comme rituel quotidien. Chaque matin, cette chanson structure l'entrée en classe et crée un sentiment de sécurité et d'appartenance. Les enfants commencent à mémoriser les paroles et les gestes.",
      ["Rituel d'entrée : dès que les enfants arrivent, l'enseignant(e) commence la chanson 'Bonjour'. Les enfants qui connaissent rejoignent, les autres observent et imitent.",
       "Révision : chanter en entier avec les gestes. Corriger gentiment si des mots ou gestes manquent.",
       "Varier la dynamique : chanter très doucement (voix de bébé), puis normalement, puis fort — développement du contrôle vocal.",
       "Chanter en petit groupe de 2-3 devant les autres."],
      ["Chanter la chanson de mémoire avec les gestes — évaluation de la mémorisation.",
       "Frapper le rythme sur les genoux pendant que les camarades chantent.",
       "Chanter en petits groupes de 2-3 devant la classe."]),
    m("RÉCITATION","Mes fournitures",
      "La première vraie récitation pour les enfants de Garderie. La comptine 'Mes fournitures' relie l'Environnement et la Pré-lecture aux fournitures scolaires. À 3-4 ans, la mémorisation passe par la répétition, le rythme et les gestes — jamais par la contrainte.",
      ["L'enseignant(e) récite la comptine 'Mes fournitures' une première fois avec gestes et musicalité : 'Mon crayon dessine / Mon cahier s'écrit / Ma gomme efface / Et moi j'apprends ici !'",
       "Apprendre ligne par ligne : l'enseignant(e) dit une ligne lentement — les enfants répètent immédiatement. Répéter 3 fois chaque ligne.",
       "Ajouter les gestes : 'Mon crayon dessine' = mimer d'écrire. 'Mon cahier s'écrit' = mimer de tourner une page. 'Ma gomme efface' = mimer de frotter. 'Et moi j'apprends ici' = montrer la classe.",
       "Réciter en entier avec les gestes — d'abord avec l'enseignant(e), puis les enfants seuls.",
       "Récitation par petits groupes ou individuellement si volontaire — jamais forcé."],
      ["Réciter la comptine 'Mes fournitures' en chœur avec les gestes appris.",
       "Réciter une ligne en solo en pointant la bonne fourniture sur le panneau de la classe.",
       "Frapper le rythme de la comptine sur les genoux pendant que l'enseignant(e) la récite.",
       "Associer chaque ligne de la comptine à la fourniture correspondante."]),
  ],
},

// ── S4 : La classe et moi — Consolidation ─────────────────────────────────────
{
  n: 4, dateDebut: "2025/09/22",
  theme: "La classe et moi — Consolidation",
  sous: "Consolidation: présentation, politesse, fournitures, gribouillage, plein/vide, quantité, ROUGE, bonhomme bâton, modelage, la vue, Greetings, coloriage, assis-debout, Bonjour, Mes fournitures",
  matieres: [
    m("LANGAGE","Présentation nom Maîtresse, Élèves",
      "Semaine de consolidation de la présentation. Les enfants qui n'osaient pas encore parler la semaine dernière sont encouragés. Les jeux se répètent avec des variations légères pour ancrer les prénoms dans la mémoire.",
      ["Rappel en cercle : 'Qui se souvient du prénom de son voisin ?' — test de mémorisation des prénoms.",
       "Jeu de la balle : passer la balle en nommant le destinataire et un mot sur lui ('Je passe à Rivo qui aime les voitures !').",
       "Afficher à nouveau les étiquettes-prénoms — chaque enfant trouve la sienne plus rapidement qu'avant.",
       "Chanson des prénoms : 'Bonjour [prénom], comment ça va ?' pour chaque enfant — avec participation active de la classe.",
       "Jeu final : 'Qui peut me présenter son voisin ?' — premier exercice de parler d'un autre."],
      ["Nommer 5 camarades de la classe de mémoire.",
       "Se présenter en 2 phrases : 'Je m'appelle ___ et j'ai ___ ans.'",
       "Pointer le prénom d'un camarade nommé par l'enseignant(e) sur le panneau."]),
    m("MORALE","Politesse en classe",
      "Consolidation de la politesse. Les formules doivent maintenant être spontanées dans les interactions quotidiennes. L'enseignant(e) observe qui les utilise naturellement et renforce les autres avec douceur.",
      ["Rappel des 4 formules : BONJOUR / MERCI / S'IL TE PLAÎT / AU REVOIR — pointer les affiches.",
       "Jeu des situations : l'enseignant(e) joue une scène et s'arrête : 'Qu'est-ce que le personnage devrait dire ?' — les enfants complètent.",
       "Observation positive : féliciter publiquement les enfants qui utilisent la politesse spontanément pendant la journée.",
       "Bilan collectif : 'Qu'est-ce que vous avez retenu sur la politesse ?' — 2-3 enfants répondent."],
      ["Jeu de rôle par binômes : scènes de politesse quotidiennes (donner/recevoir, demander permission).",
       "Observer et pointer dans un livre illustré les comportements polis vs impolis.",
       "Dessiner une scène de politesse et raconter ce qu'on a dessiné."]),
    m("GRAPHISME","Gribouillage",
      "Troisième séance de gribouillage. On observe une progression dans la tenue du crayon et dans le contrôle du geste. Certains enfants commencent à faire des formes intentionnelles — les valoriser.",
      ["Rappel : 'Vous vous souvenez du gribouillage ? Regardez comment vous avez progressé !' Montrer les premières productions.",
       "Nouvelle surface : gribouillage sur du carton ondulé ou une feuille texturée — sensation différente.",
       "Défi du gribouillage guidé : 'Essayons de faire tous des ronds !' puis 'Maintenant des zigzags !'",
       "Mélanger les techniques : feutre + craie grasse sur la même feuille."],
      ["Gribouillage dirigé : tracer uniquement des ronds sur toute la feuille.",
       "Tracer des zigzags et des spirales en alternance.",
       "Comparaison avec le premier gribouillage : 'Tu vois comme tu as progressé ?'"]),
    m("PRE-LECTURE","Présentation: les fournitures scolaires",
      "Consolidation de la connaissance des fournitures scolaires. Les enfants doivent maintenant les reconnaître, les nommer et savoir les utiliser sans aide.",
      ["Jeu rapide de révision : sortir les fournitures du sac — chaque enfant nomme celle qui apparaît.",
       "Jeu de la devinette : 'Je suis long, jaune, et je laisse une trace sur le papier. Qui suis-je ?' — les enfants lèvent la main.",
       "Jeu de tri : mélanger 8 images de fournitures et d'objets hors école — trier les fournitures scolaires.",
       "Dictée d'images : l'enseignant(e) dit un nom, l'enfant cherche et pointe l'image correspondante."],
      ["Nommer spontanément 5 fournitures pointées rapidement.",
       "Trier les flashcards : fournitures scolaires vs objets de maison.",
       "Mimer l'utilisation de 3 fournitures nommées par l'enseignant(e)."]),
    m("PRE-CALCUL","Plein ≠ vide",
      "Consolidation de la notion plein/vide avec de nouveaux contenants et matériaux. Les enfants doivent maintenant utiliser les mots 'plein' et 'vide' correctement dans des contextes variés.",
      ["Rappel rapide : montrer 1 verre plein et 1 verre vide — 'Qui rappelle la différence ?'",
       "Nouveaux matériaux : remplir et vider avec des billes, de l'eau (si possible), des graines.",
       "Jeu de comparaison : 'Lequel est plus plein ? Lequel est plus vide ?' entre 2 contenants partiellement remplis.",
       "Dessiner un verre plein et un verre vide — premier ancrage graphique du concept."],
      ["Remplir 3 contenants différents de tailles différentes — observer et décrire.",
       "Pointer spontanément le 'plein' et le 'vide' dans 5 situations présentées rapidement.",
       "Sur fiche : colorier les contenants pleins en vert et les vides en rouge."]),
    m("PRE-MATHS","La quantité",
      "Consolidation de la notion de quantité. Les enfants travaillent maintenant sur des collections plus grandes (jusqu'à 5) et utilisent les mots 'plus', 'moins', 'autant' avec plus de spontanéité.",
      ["Révision rapide : montrer 2 groupes d'objets — 'Plus ou moins ?' — réponse rapide en chœur.",
       "Nouveaux objets de manipulation : cubes, boutons de couleurs, petites pierres.",
       "Jeu de constitution : 'Mets autant de jetons que moi' — l'enseignant(e) en pose 3, les enfants en mettent 3.",
       "Chanson des quantités avec les doigts."],
      ["Constituer une collection de 4 objets sur demande.",
       "Comparer 2 groupes et dire lequel a 'plus' et lequel a 'moins'.",
       "Pointer sur fiche le groupe avec 'autant' que le groupe-modèle."]),
    m("ENVIRONNEMENT","Les fournitures scolaires",
      "Consolidation de la connaissance des fournitures scolaires dans leur contexte d'utilisation. Les enfants doivent maintenant nommer, utiliser correctement et ranger leurs affaires.",
      ["Révision en jeu : sortir une fourniture, la passer à un enfant qui la nomme et mime son utilisation.",
       "Jeu de rangement : mélanger 8 fournitures et demander aux enfants de tout ranger correctement.",
       "Jeu des catégories : 'Quelles fournitures sont dans la trousse ? Dans le sac ? Sur le bureau ?'",
       "Chanson des fournitures : chanter et pointer les vraies fournitures au fur et à mesure."],
      ["Nommer et utiliser correctement toutes les fournitures de sa trousse.",
       "Ranger sa trousse et son sac correctement en 2 minutes.",
       "Dessiner 3 fournitures de son choix et les nommer."]),
    m("LES COULEURS","ROUGE",
      "Consolidation de la couleur rouge. Les enfants doivent maintenant reconnaître, nommer et utiliser la couleur rouge avec certitude dans tous les contextes.",
      ["Révision flash : montrer des objets rapidement — 'C'est rouge ou pas rouge ?' — réponse immédiate.",
       "Tour de classe : chaque enfant pointe un objet rouge différent dans la salle.",
       "Jeu artistique : peindre avec de la gouache rouge ou tamponner avec une éponge rouge.",
       "Jeu de mémoire rouge : placer 5 objets rouges sur la table, couvrir, retirer un — qui a disparu ?"],
      ["Nommer spontanément 5 objets rouges de la classe.",
       "Peindre / tamponner en rouge une grande surface.",
       "Reconnaître le rouge parmi 6 couleurs présentées rapidement."]),
    m("DESSIN DIRIGÉ","Mon bonhomme bâton",
      "Consolidation du bonhomme bâton. Les enfants reprennent le même bonhomme avec plus d'aisance et commencent à ajouter des détails spontanément.",
      ["Rappel de la semaine précédente : montrer les bonhommes dessinés et observer la progression.",
       "Dessiner à nouveau au tableau étape par étape — les enfants suivent plus facilement cette fois.",
       "Encourager les détails : 'Qui veut ajouter des oreilles ? Des cheveux ? Des chaussures ?' — pas d'obligation.",
       "Nouveau défi : dessiner un bonhomme ET sa maison à côté."],
      ["Dessiner un bonhomme bâton complet de mémoire (tête + corps + bras + jambes).",
       "Ajouter au moins 2 détails au bonhomme (yeux, bouche, oreilles...).",
       "Colorier le bonhomme terminé avec au moins 3 couleurs."]),
    m("ART PLASTIQUE","Modelage",
      "Consolidation du modelage. Les enfants maîtrisent maintenant les 3 gestes de base et peuvent créer des formes plus intentionnelles. La séance devient plus créative.",
      ["Rappel des 3 gestes : bouler, aplatir, serpent — démonstration rapide.",
       "Défi du jour : créer un objet en utilisant au moins 2 des 3 gestes (exemple : un escargot = serpent + boule).",
       "Exposition mini des créations de la semaine précédente — observer les progrès.",
       "Création à thème : faire quelque chose lié à la classe (un crayon, un cahier, un bonhomme)."],
      ["Créer un objet en utilisant les 3 techniques : bouler, aplatir, rouler en serpent.",
       "Présenter sa création et l'expliquer en 1 phrase.",
       "Reconnaître les 3 techniques dans les créations de ses camarades."]),
    m("EXERCICE SENSORIEL","La vue",
      "Consolidation du sens de la vue. Exercices plus complexes d'observation fine et de discrimination visuelle. Les enfants développent leur attention aux détails.",
      ["Rappel : 'Quel sens avons-nous appris ? Montrez-moi où sont vos yeux.'",
       "Jeu des différences simplifié : comparer 2 images presque identiques — trouver 3 différences.",
       "Observation de la nature : regarder par la fenêtre — 'Combien d'arbres ? Quelle couleur est le ciel ?'",
       "Jeu de Kim visuel : mettre 5 objets, les couvrir, en retirer 1 — qui manque ?"],
      ["Trouver 3 différences entre 2 images similaires.",
       "Mémoriser 5 objets et nommer celui qui a disparu.",
       "Observer une image 10 secondes et répondre à 3 questions sur ce qu'on a vu."]),
    m("ANGLAIS","Greetings",
      "Consolidation des salutations en anglais. Les enfants intègrent 'Hello/Hi' et 'Goodbye' dans leur routine naturelle de classe. On ajoute 'How are you?' et la réponse.",
      ["Révision des acquis : la marionnette dit 'Hello' — est-ce que tout le monde répond spontanément ?",
       "Ajouter 'How are you?' — l'enseignant(e) demande à la marionnette, la marionnette répond 'I'm fine, thank you !'",
       "Exercice : tour de cercle 'Hello [prénom], how are you ?' — l'enfant répond 'I'm fine !' ou 'I'm good !'",
       "Rituel de fin : la marionnette dit 'Goodbye !' — la classe répond 'Goodbye Teddy !'"],
      ["Saluer spontanément en anglais à l'entrée et la sortie de la séance.",
       "Répondre à 'How are you ?' avec 'I'm fine !' ou 'I'm good !'",
       "Chanter la chanson de salutation de mémoire avec les gestes."]),
    m("TRAVAIL MANUEL","Coloriage libre",
      "Consolidation du coloriage. Les enfants tiennent le crayon plus facilement et choisissent leurs couleurs avec intention. Les contours sont encore approximatifs — c'est normal à cet âge.",
      ["Révision de la tenue du crayon : montrer à nouveau, corriger gentiment.",
       "Coloriage d'une image un peu plus détaillée qu'avant (2-3 zones de couleur distinctes).",
       "Défi du jour : choisir des couleurs en lien avec la réalité (pomme rouge, ciel bleu) — mais laisser libre.",
       "Comparer avec le premier coloriage : 'Regarde comme tu t'es amélioré(e) !'"],
      ["Colorier sans sortir des contours d'une grande forme simple (cercle ou carré) — défi de précision.",
       "Choisir 4 couleurs différentes pour colorier 4 zones distinctes.",
       "Colorier une image entière de façon autonome et la signer de son prénom (l'adulte écrit le prénom si besoin)."]),
    m("ESPACE PHYSIQUE","Mouvements: Assis - Debout",
      "Consolidation assis/debout. Les enfants réagissent maintenant plus vite et commencent à anticiper les consignes. On ajoute d'autres positions : accroupi.",
      ["Révision : 'ASSIS !' / 'DEBOUT !' — réponse instantanée, sans délai.",
       "Ajouter une 3e position : 'ACCROUPI !' — démonstration et pratique.",
       "Jeu de la statue : tenir une position donnée 5 secondes sans bouger.",
       "Enchaîner 3 positions : 'DEBOUT → ASSIS → ACCROUPI → DEBOUT !' — séquence motrice."],
      ["Réaliser la séquence DEBOUT-ASSIS-ACCROUPI sur signal sans erreur.",
       "Tenir une position immobile 5 secondes (statue).",
       "Jeu en binôme : un dit, l'autre fait — alterner les rôles."]),
    m("CHANT","Bonjour",
      "La chanson 'Bonjour' est maintenant mémorisée pour la plupart des enfants. La séance se concentre sur l'expression, la dynamique et le plaisir de chanter ensemble.",
      ["Chanter 'Bonjour' de mémoire en entier dès le début de la séance — sans aide de l'enseignant(e).",
       "Variations musicales : 'chanter très doucement (voix de chat)... maintenant fort (voix de lion) !'",
       "Chanter en 2 groupes qui alternent les lignes.",
       "Performance finale : chanter pour une autre classe ou pour les parents."],
      ["Chanter 'Bonjour' de mémoire avec les gestes complets.",
       "Chanter en solo avec gestes devant le groupe (volontaires uniquement).",
       "Chanter en 2 groupes en alternant les lignes."]),
    m("RÉCITATION","Mes fournitures",
      "Consolidation de la comptine 'Mes fournitures'. Les enfants qui ne la connaissaient pas encore la semaine dernière la mémorisent maintenant. Les plus avancés peuvent la réciter seuls.",
      ["Réciter la comptine 'Mes fournitures' en chœur au début — tous ensemble.",
       "Récitation par petits groupes de 3-4 enfants — identifier les progrès.",
       "Récitation individuelle volontaire : féliciter chaque enfant qui ose.",
       "Faire pointer les vraies fournitures pendant la récitation : au mot 'crayon', pointer le crayon, etc.",
       "Créer une variation : 'Ma règle mesure / Mon sac est lourd / Ma trousse est fermée / Et moi j'apprends toujours !'"],
      ["Réciter la comptine complète de mémoire avec les gestes — évaluation finale.",
       "Réciter en solo si volontaire.",
       "Pointer la fourniture correspondante à chaque ligne."]),
  ],
},

  ]},
];

module.exports = { PERIODES_GARDERIE };
