'use strict';
// RÉPARTITION 12ÈME — DÉCEMBRE 2025
// S3 = révision générale · S4 = examens fin 1ère période

function m(mat, topic, approche, activites, exercices) {
  return { matiere:mat, topic, approche, activites, exercices };
}

const DECEMBRE_12EME = [

  {
    n:1, dates:'01/12/2025 – 05/12/2025',
    theme:'Noël et fêtes · Ponts et créneaux · Compter 1-20 · Soustraction simple',
    matieres:[

      m('HYGIÈNE','La propreté des vêtements',
        'Apprendre à garder ses vêtements propres. Reconnaître un vêtement sale. Pourquoi laver ses vêtements ?',
        ['Montrer images : vêtement propre vs sale',
         'Discussion : "Qui lave les vêtements chez toi ?"',
         'Règle : "Je ne m\'essuie pas les mains sur mes vêtements"'],
        ['Comment reconnaît-on un vêtement sale ? → Corrigé : taches, odeur, poussière.',
         'Pourquoi lave-t-on les vêtements ? → Corrigé : pour enlever les microbes et rester propre.',
         'Que fait-on avec un vêtement mouillé ? → Corrigé : on le fait sécher.',
         'Qui lave les vêtements dans ta famille ? → Corrigé : réponse personnelle.',
         'Cite 2 choses qui peuvent salir un vêtement. → Corrigé : nourriture, boue, peinture.']),

      m('I.C.','Les fêtes de fin d\'année',
        'Présenter Noël et le Nouvel An comme fêtes célébrées en décembre. Traditions malgaches en fin d\'année (31 décembre). Respecter les différences de religion.',
        ['Discussion : "Comment fête-t-on en décembre chez toi ?"',
         'Dessiner une fête de famille',
         'Respect : tout le monde ne fête pas de la même façon'],
        ['Quel mois est décembre ? → Corrigé : le 12ème mois.',
         'Cite 1 fête célébrée en décembre. → Corrigé : Noël, Aïd (selon religion), Nouvel An.',
         'Avec qui fêtes-tu en décembre ? → Corrigé : réponse personnelle.',
         'Tous les enfants fêtent-ils Noël ? → Corrigé : non, cela dépend de la religion.',
         'Qu\'est-ce qu\'une fête de famille ? → Corrigé : un moment de joie partagé avec ses proches.']),

      m('MORAL','Je suis reconnaissant(e)',
        'Apprendre la gratitude : être content de ce qu\'on a, remercier pour les cadeaux grands et petits.',
        ['Discussion : "Pour quoi es-tu reconnaissant aujourd\'hui ?"',
         'Exercice : lister 3 choses pour lesquelles on est reconnaissant',
         'Histoire : un enfant qui apprécie un petit cadeau'],
        ['Qu\'est-ce que la gratitude ? → Corrigé : être content et remercier pour ce qu\'on reçoit.',
         'Cite 3 choses pour lesquelles tu es reconnaissant. → Corrigé : réponse personnelle.',
         'Comment montres-tu ta gratitude ? → Corrigé : en disant merci, en souriant, en faisant un câlin.',
         'Est-il correct de se plaindre toujours ? → Corrigé : non, il vaut mieux être reconnaissant.',
         'Pour quoi es-tu reconnaissant aujourd\'hui ? → Corrigé : réponse personnelle.']),

      m('CONTE','Nouveau conte — Le petit sapin (S1)',
        'Conte de Noël adapté : le petit sapin qui veut des décorations. Lire S1. Questions simples.',
        ['Présenter le conte avec des images hivernales/festives',
         'Lire avec expression',
         'Questions de compréhension'],
        ['Qui est le personnage de ce conte ? → Corrigé : le petit sapin.',
         'Que veut le petit sapin ? → Corrigé : être décoré / avoir des lumières.',
         'De quelle couleur est un sapin ? → Corrigé : vert.',
         'As-tu déjà vu un sapin décoré ? → Corrigé : réponse personnelle.',
         'Prédis la fin. → Corrigé : prédiction libre.']),

      m('LANGAGE','Les fêtes — vocabulaire festif',
        'Vocabulaire de fête : cadeau, décorations, joie, famille, partage. Décrire une fête.',
        ['Images de fêtes de famille',
         '"À ma fête, j\'ai reçu..."',
         'Discussion : "Qu\'est-ce qui te rend le plus joyeux en décembre ?"'],
        ['Cite 3 mots liés aux fêtes. → Corrigé : cadeau, joie, famille, décorations, repas.',
         'Qu\'as-tu fait à ta dernière fête ? → Corrigé : réponse personnelle.',
         'Qu\'est-ce qu\'un cadeau ? → Corrigé : quelque chose qu\'on offre par amour ou gentillesse.',
         'Quel est ton aliment préféré lors d\'une fête ? → Corrigé : réponse personnelle.',
         'Comment se comporte-t-on à une fête de famille ? → Corrigé : avec joie, politesse, respect.']),

      m('PRÉ-LECTURE','Graphisme — ponts et créneaux',
        'Tracer des ponts (arcs vers le haut) et des créneaux (arcs vers le bas). Préparer les lettres m, n, u, h.',
        ['Ponts : tracer dans l\'air — image du pont',
         'Créneaux : tracer dans l\'air — image des remparts',
         'Tracer en alternance ponts et créneaux'],
        ['Trace 5 ponts. → Corrigé : évaluation.',
         'Trace 5 créneaux. → Corrigé : évaluation.',
         'Quelle lettre ressemble à des ponts ? → Corrigé : m, n.',
         'Quelle lettre ressemble à un créneau ? → Corrigé : u.',
         'Alterne 3 ponts et 3 créneaux. → Corrigé : évaluation.']),

      m('NUMÉRATION','Compter 1 à 20',
        'Arriver à 20. 20 = 2 dizaines. Reconnaître les chiffres 19 et 20.',
        ['Compter de 1 à 20 avec des doigts + pieds (métaphore)',
         'Arriver à 20 : "C\'est 2 fois 10 !"',
         'Chant : "1 à 20"'],
        ['Compte de 1 à 20. → Corrigé : performance orale.',
         'Quel nombre vient après 19 ? → Corrigé : 20.',
         'Combien de dizaines y a-t-il dans 20 ? → Corrigé : 2.',
         'Quel nombre est le plus grand : 19 ou 15 ? → Corrigé : 19.',
         'Montre 20 objets. → Corrigé : dénombrement.']),

      m('CALCUL','Soustraction simple — enlever',
        'Introduire la soustraction : enlever. 5 − 2 = 3. Avec des objets concrets. Pas encore d\'écriture formelle.',
        ['Situation : "J\'ai 5 bonbons, j\'en mange 2. Combien reste ?"',
         'Manipuler des jetons : enlever des jetons',
         'Ardoise : écrire le résultat'],
        ['5−2=___. → Corrigé : 3.',
         '4−1=___. → Corrigé : 3.',
         '6−3=___. → Corrigé : 3.',
         '8−4=___. → Corrigé : 4.',
         'Problème : j\'ai 7 pommes, j\'en mange 3. Combien reste ? → Corrigé : 4.']),

      m('DESSIN','Décoration de Noël — dessin festif',
        'Dessiner une boule de Noël ou un sapin. Utiliser des couleurs vives. Ajouter des décorations.',
        ['Observer des images de décorations festives',
         'Dessiner une boule décorée ou un sapin',
         'Colorier avec des couleurs vives'],
        ['Qu\'as-tu dessiné ? → Corrigé : réponse personnelle.',
         'Quelles couleurs as-tu choisies ? → Corrigé : rouge, vert, doré...',
         'Combien de décorations as-tu ajoutées ? → Corrigé : réponse personnelle.',
         'Un sapin de Noël est-il petit ou grand ? → Corrigé : les deux (réel = grand, maison = moyen).',
         'Qu\'as-tu préféré : colorier ou dessiner ? → Corrigé : réponse personnelle.']),

      m('CHANT','Chanson "Vive le vent"',
        'Apprendre "Vive le vent" (refrain). Chanter avec les gestes de l\'hiver. Lien avec décembre et les fêtes.',
        ['Chanter "Vive le vent, vive le vent, vive le vent d\'hiver !"',
         'Mimer le vent avec les bras',
         'Chanter seul'],
        ['Chante le refrain. → Corrigé : performance orale.',
         'Quel temps fait-il dans cette chanson ? → Corrigé : du vent, de l\'hiver.',
         'Mime le vent. → Corrigé : geste.',
         'Est-ce qu\'il y a de la neige à Madagascar ? → Corrigé : non, Madagascar est un pays tropical.',
         'Quelle chanson aimes-tu à Noël ? → Corrigé : réponse personnelle.']),

      m('RÉCITATION','Comptine "Mon beau sapin"',
        'Apprendre la comptine "Mon beau sapin, roi des forêts". Mémoriser les 2 premiers vers.',
        ['Apprendre 2 vers × 3',
         'Mimer le sapin avec les bras en forme de triangle',
         'Réciter seul'],
        ['Récite les 2 premiers vers. → Corrigé : performance orale.',
         'De quel arbre s\'agit-il ? → Corrigé : du sapin.',
         'Comment est le sapin ? → Corrigé : beau, vert, décoré.',
         'Mime un sapin avec tes bras. → Corrigé : bras formant un triangle.',
         'Quelle forêt mentionne la comptine ? → Corrigé : "roi des forêts".']),

      m('T.M.','Fabrication de guirlande en papier',
        'Créer une guirlande en découpant et collant des anneaux de papier coloré. Développer la motricité fine.',
        ['Découper des bandelettes de papier coloré',
         'Former des anneaux en collant les extrémités',
         'Emboîter les anneaux pour former une guirlande'],
        ['Combien d\'anneaux as-tu créés ? → Corrigé : compter.',
         'Comment as-tu assemblé les anneaux ? → Corrigé : en passant chaque anneau dans le précédent et en collant.',
         'À quoi sert une guirlande ? → Corrigé : à décorer.',
         'Cite 3 couleurs de ta guirlande. → Corrigé : réponse personnelle.',
         'Où accrocheras-tu ta guirlande ? → Corrigé : réponse personnelle.']),

      m('A.P.S.','Danser — mouvement libre',
        'Expression corporelle libre sur une musique festive. Bouger en rythme. Coordonner les mouvements.',
        ['Mettre une musique festive',
         'Danser librement',
         'Imiter les mouvements de l\'enseignant'],
        ['Aimes-tu danser ? → Corrigé : réponse personnelle.',
         'Montre ton pas de danse préféré. → Corrigé : performance.',
         'La danse est-elle une activité sportive ? → Corrigé : oui, elle développe la coordination et l\'endurance.',
         'Que ressens-tu quand tu danses ? → Corrigé : réponse personnelle.',
         'Cite 1 danse traditionnelle malgache. → Corrigé : afindrafindrao, tsapika...']),

      m('ENVIRONNEMENT','Décembre à Madagascar — temps et nature',
        'Observer la nature en décembre (début de saison des pluies). Plantes qui poussent. Insectes. Végétation verte.',
        ['Observer la végétation : plus verte que pendant la saison sèche',
         'Discussion : "Qu\'as-tu remarqué dans la nature ce mois ?"',
         'Dessiner ce qu\'on voit dehors en décembre'],
        ['Quel mois sommes-nous ? → Corrigé : décembre.',
         'Quel temps fait-il souvent en décembre à Madagascar ? → Corrigé : chaud et pluvieux.',
         'Que voit-on dans la nature en décembre ? → Corrigé : beaucoup de vert, fleurs, insectes.',
         'Pourquoi les plantes sont-elles plus vertes pendant la saison des pluies ? → Corrigé : parce qu\'elles reçoivent beaucoup d\'eau.',
         'Cite 1 insecte qu\'on voit souvent en décembre. → Corrigé : moustique, papillon, scarabée.']),

      m('ANGLAIS','Greetings and farewells — Révision + "Merry Christmas"',
        'Réviser les salutations. Apprendre "Merry Christmas!" et "Happy New Year!". Chanson de Noël simple.',
        ['Révision : Hello, Goodbye, Good morning',
         'Apprendre : "Merry Christmas!" / "Happy New Year!"',
         'Chanter "Jingle Bells" (refrain seulement)'],
        ['How do you say "Joyeux Noël" ? → Corrigé : Merry Christmas!',
         'How do you say "Bonne Année" ? → Corrigé : Happy New Year!',
         'Sing "Jingle Bells" refrain. → Corrigé : performance orale.',
         'How do you say "bonjour" in English ? → Corrigé : Hello / Good morning.',
         'What do you say to someone leaving ? → Corrigé : Goodbye! See you!']),

    ]
  },

  {
    n:2, dates:'08/12/2025 – 12/12/2025',
    theme:'L\'hiver / saisons · Révision graphisme · Compter 1-20 (consolider) · Problèmes simples',
    matieres:[

      m('HYGIÈNE','Hygiène en période de fêtes',
        'Fêtes = beaucoup de manger, de monde, de fatigue. Hygiène alimentaire pendant les fêtes. Se laver les mains entre les plats. Ne pas trop manger de sucre.',
        ['Discussion : "Qu\'aimes-tu manger lors des fêtes ?"',
         'Identifier les aliments à limiter : sodas, bonbons',
         'Règle : "Je mange avec modération même lors des fêtes"'],
        ['Pourquoi se laver les mains avant chaque repas de fête ? → Corrigé : parce qu\'on touche beaucoup d\'objets et de personnes.',
         'Que risque-t-on à manger trop de sucreries ? → Corrigé : mal au ventre, caries, surpoids.',
         'Que boit-on de préférence à table lors d\'une fête ? → Corrigé : eau, jus de fruits naturel.',
         'Quelle règle retiens-tu ? → Corrigé : manger équilibré même lors des fêtes.',
         'Cites 2 bonnes habitudes pour rester en bonne santé pendant les fêtes. → Corrigé : boire de l\'eau, dormir suffisamment, manger des légumes.']),

      m('I.C.','Bilan de l\'année — ce que j\'ai appris',
        'Récapitulatif de tout ce qu\'on a appris depuis octobre en IC. Quiz ludique.',
        ['Quiz en images : reconnaître les personnages, lieux, règles apprises',
         'Chaque élève dit 1 chose qu\'il a apprise',
         'Discussion : "Qu\'est-ce qui t\'a le plus surpris ?"'],
        ['Cite 2 choses que tu as apprises en IC ce trimestre. → Corrigé : réponse personnelle.',
         'Combien de jours y a-t-il dans une semaine ? → Corrigé : 7.',
         'Cite les membres de ta famille. → Corrigé : réponse personnelle.',
         'Qu\'est-ce qu\'un quartier ? → Corrigé : un groupe de maisons proches de l\'école.',
         'Qu\'est-ce que la tolérance ? → Corrigé : respecter les différences des autres.']),

      m('MORAL','Bilan moral — mes bonnes actions',
        'Faire le bilan des valeurs apprises : gentillesse, partage, courage, responsabilité, politesse, gratitude. Créer un tableau de mes bonnes actions.',
        ['Chaque élève cite 1 bonne action faite ce mois',
         'Tableau collectif des bonnes actions',
         'Promesse : "Ce que je vais faire de bien en janvier"'],
        ['Cite 3 valeurs apprises ce trimestre. → Corrigé : gentillesse, partage, courage, responsabilité, politesse, gratitude.',
         'Quelle bonne action as-tu faite cette semaine ? → Corrigé : réponse personnelle.',
         'Quelle valeur est la plus importante pour toi ? → Corrigé : réponse personnelle.',
         'Que promets-tu de faire en janvier ? → Corrigé : réponse personnelle.',
         'Comment dit-on "merci" en malgache ? → Corrigé : misaotra.']),

      m('CONTE','Le petit sapin (S2 — fin)',
        'Lire la fin du conte. Jouer la scène. Quelle leçon ?',
        ['Relire S1 + lire S2',
         'Jeu de rôle : être le sapin qui se décore',
         'Discussion : quelle leçon ?'],
        ['Comment se termine le conte ? → Corrigé : selon texte.',
         'Le petit sapin est-il content à la fin ? → Corrigé : selon texte.',
         'Quelle leçon retiens-tu ? → Corrigé : être patient, la beauté vient avec du temps et de l\'effort.',
         'Raconte le conte en 2 phrases. → Corrigé : résumé oral.',
         'Dessine le petit sapin décoré. → Corrigé : production.']),

      m('LANGAGE','Révision — tout le vocabulaire du trimestre',
        'Révision de tout le vocabulaire : corps, famille, école, aliments, vêtements, maison, fêtes.',
        ['Quiz ludique en images : nommer les éléments',
         'Jeu de devinettes : "J\'ai 4 pattes et je miaule. Qui suis-je ?"',
         'Discussion : "Quel est ton mot préféré appris ce trimestre ?"'],
        ['Cite 3 parties du corps. → Corrigé : tête, bras, jambe.',
         'Cite 3 pièces de la maison. → Corrigé : salon, chambre, cuisine.',
         'Cite 3 vêtements. → Corrigé : robe, pantalon, chaussures.',
         'Cite 3 aliments. → Corrigé : riz, légumes, poisson.',
         'Quel est ton mot favori de ce trimestre ? → Corrigé : réponse personnelle.']),

      m('PRÉ-LECTURE','Révision de tous les tracés',
        'Révision de tous les graphismes du trimestre : horizontales, verticales, obliques, courbes, boucles, spirales, ponts, créneaux.',
        ['Fiche de révision graphisme : un tracé de chaque type',
         'L\'élève choisit son tracé préféré à faire × 5',
         'Bilan : quel tracé est le plus difficile ?'],
        ['Trace 1 ligne horizontale, 1 verticale, 1 oblique. → Corrigé : évaluation.',
         'Trace 3 boucles. → Corrigé : évaluation.',
         'Trace 1 spirale. → Corrigé : évaluation.',
         'Trace 3 ponts. → Corrigé : évaluation.',
         'Quel tracé trouves-tu le plus difficile ? → Corrigé : réponse personnelle.']),

      m('NUMÉRATION','Révision — compter jusqu\'à 20',
        'Révision et consolidation : compter, reconnaître, comparer, ordonner les nombres 1-20.',
        ['Compter à rebours : 10, 9, 8... 1',
         'Ordonner des cartes chiffres mélangées 1-20',
         'Dictée de 5 nombres'],
        ['Compte à rebours de 10 à 1. → Corrigé : 10, 9, 8, 7, 6, 5, 4, 3, 2, 1.',
         'Quel nombre vient après 14 ? → Corrigé : 15.',
         'Quel nombre vient avant 20 ? → Corrigé : 19.',
         'Ordonne : 17, 4, 12, 8, 20. → Corrigé : 4, 8, 12, 17, 20.',
         'Quel est le plus grand nombre que tu connais ? → Corrigé : 20.']),

      m('CALCUL','Additions et soustractions jusqu\'à 10',
        'Pratiquer les deux opérations jusqu\'à 10. Exercices variés. Vérification.',
        ['Quiz ardoise : 5 additions + 5 soustractions',
         'Problèmes oraux : "J\'ai 6 bonbons, j\'en mange 2. J\'en reçois 4. Combien en tout ?"',
         'Corriger ensemble'],
        ['3+7=___. → Corrigé : 10.',
         '9−4=___. → Corrigé : 5.',
         '6+4=___. → Corrigé : 10.',
         '10−6=___. → Corrigé : 4.',
         'Problème : 5 oiseaux + 3 oiseaux − 2 oiseaux = ___. → Corrigé : 6.']),

      m('DESSIN','Mon dessin de fête — libre',
        'Dessin libre sur le thème des fêtes de fin d\'année. Chaque enfant choisit son sujet.',
        ['Choisir librement : fête, famille, repas, décoration',
         'Dessiner et colorier',
         'Présenter son dessin'],
        ['Qu\'as-tu dessiné ? → Corrigé : réponse personnelle.',
         'Pourquoi as-tu choisi ce thème ? → Corrigé : réponse personnelle.',
         'Quelles couleurs as-tu utilisées ? → Corrigé : réponse personnelle.',
         'Es-tu content(e) de ton dessin ? → Corrigé : réponse personnelle.',
         'Montre ton dessin à un camarade et explique-le. → Corrigé : présentation orale.']),

      m('CHANT','Révision — Chants du trimestre',
        'Réviser tous les chants appris depuis octobre : "Bonjour les amis", "Tête épaules", "Couleurs", "Légumes", "Beau chapeau", "Vive le vent".',
        ['Chanter chaque refrain',
         'Vote : "Quelle est ta chanson préférée ?"',
         'Chanter la chanson préférée 2 fois'],
        ['Cite 3 chansons apprises ce trimestre. → Corrigé : selon la liste.',
         'Quelle chanson as-tu préférée ? → Corrigé : réponse personnelle.',
         'Chante le refrain de "Vive le vent". → Corrigé : performance orale.',
         'Chante "Tête, épaules, genoux et pieds" très vite. → Corrigé : performance.',
         'Quel geste accompagne la chanson des couleurs ? → Corrigé : pointer des objets colorés.']),

      m('RÉCITATION','Révision — Comptines du trimestre',
        'Réviser toutes les comptines : "Doigts", "1,2,3 soleil", "Promenons-nous dans les bois", "Pomme de reinette", "Il pleut bergère", "Mon beau sapin".',
        ['Réciter chaque comptine',
         'Vote : "Quelle est ta préférée ?"',
         'Réciter la préférée avec expression'],
        ['Cite 3 comptines apprises. → Corrigé : selon la liste.',
         'Récite "Promenons-nous dans les bois". → Corrigé : performance orale.',
         'Récite "Pomme de reinette". → Corrigé : performance orale.',
         'Récite "Mon beau sapin". → Corrigé : performance orale.',
         'Quelle comptine retiens-tu le mieux ? → Corrigé : réponse personnelle.']),

      m('T.M.','Carte de vœux — Joyeuses fêtes',
        'Fabriquer une carte de vœux pour la famille. Dessiner, décorer, écrire (ou dicter) un message.',
        ['Plier le carton en 2',
         'Dessiner à l\'intérieur : sapin, famille, soleil',
         'Dicter ou copier le message : "Joyeuses fêtes !"'],
        ['À qui as-tu offert ta carte ? → Corrigé : réponse personnelle.',
         'Quel message as-tu écrit ? → Corrigé : "Joyeuses fêtes !" ou autre.',
         'Qu\'as-tu dessiné sur ta carte ? → Corrigé : réponse personnelle.',
         'Quelle couleur as-tu choisie pour ta carte ? → Corrigé : réponse personnelle.',
         'Ta carte a-t-elle plu ? → Corrigé : réponse personnelle.']),

      m('A.P.S.','Jeux de groupe — fête sportive',
        'Jeux collectifs festifs : loup, chat perché, drapeau. Esprit d\'équipe et plaisir du mouvement.',
        ['Jouer au loup (le loup attrape les autres)',
         'Chat perché : être "perché" pour être en sécurité',
         'Jeu du drapeau : récupérer le drapeau adverse'],
        ['Quel jeu as-tu préféré ? → Corrigé : réponse personnelle.',
         'Comment gagne-t-on au jeu du loup ? → Corrigé : tous les joueurs sont attrapés / le loup attrape tout le monde.',
         'Qu\'est-ce que "chat perché" ? → Corrigé : un jeu où on est en sécurité en montant sur quelque chose.',
         'Pourquoi les jeux collectifs sont-ils importants ? → Corrigé : pour apprendre à jouer ensemble, respecter les règles, s\'amuser.',
         'As-tu bien coopéré avec tes camarades ? → Corrigé : réponse personnelle.']),

      m('ENVIRONNEMENT','Bilan nature du trimestre',
        'Révision de tout ce qu\'on a observé dans la nature depuis octobre : météo, animaux, plantes, eau, saisons.',
        ['Quiz nature en images',
         'Chaque élève cite 1 chose de la nature observée',
         'Dessiner sa chose préférée dans la nature'],
        ['Cite 2 animaux familiers. → Corrigé : chien, chat.',
         'Cite 2 animaux de la forêt malgache. → Corrigé : lémurien, caméléon.',
         'Cite 3 parties d\'une plante. → Corrigé : racine, tige, feuille.',
         'Quelle saison fait-il en décembre à Madagascar ? → Corrigé : saison des pluies.',
         'Qu\'est-ce que tu as préféré observer dans la nature ? → Corrigé : réponse personnelle.']),

      m('ANGLAIS','Révision générale — English recap',
        'Révision de tout l\'anglais du trimestre : salutations, couleurs, formes, chiffres, corps, vêtements, maison.',
        ['Quiz rapide en images : 20 mots à nommer en anglais',
         '"Simon says..." en anglais',
         'Chanter "Head, Shoulders, Knees and Toes"'],
        ['Say "hello", "goodbye", "thank you". → Corrigé : performance orale.',
         'Count from 1 to 10. → Corrigé : performance orale.',
         'What color is this ? (montrer vert) → Corrigé : green.',
         'Simon says : touch your nose ! → Corrigé : geste.',
         'How do you say "Joyeuses fêtes" ? → Corrigé : Merry Christmas / Happy Holidays!']),

    ]
  },

  {
    n:3, dates:'15/12/2025 – 19/12/2025',
    theme:'RÉVISION GÉNÉRALE — 1er trimestre',
    matieres:[
      m('RÉVISION','Révision générale — 1er trimestre 12ème',
        'Révision intensive de tous les apprentissages depuis octobre pour préparer les examens de la semaine suivante.',
        ['Lundi : révision Hygiène + Environnement + Moral + IC',
         'Mardi : révision Langage + Graphisme + Numération + Calcul',
         'Mercredi : révision Chant + Récitation + Dessin + T.M.',
         'Jeudi-vendredi : jeux de révision + activités libres'],
        [
          '── LANGAGE ──',
          'Cite 5 parties du corps. → Corrigé : tête, yeux, bras, jambes, pieds.',
          'Cite 5 aliments. → Corrigé : riz, légumes, poisson, mangue, banane.',
          '── NUMÉRATION ──',
          'Compte de 1 à 20. → Corrigé : performance orale.',
          'Quel nombre vient après 17 ? → Corrigé : 18.',
          'Ordonne : 5, 12, 3, 18, 7. → Corrigé : 3, 5, 7, 12, 18.',
          '── CALCUL ──',
          '4+6=___. → Corrigé : 10.',
          '8−3=___. → Corrigé : 5.',
          '7+2=___. → Corrigé : 9.',
          '── GRAPHISME ──',
          'Trace : horizontale, verticale, oblique, boucle, spirale. → Corrigé : évaluation.',
          '── DESSIN ──',
          'Dessine un bonhomme habillé. → Corrigé : production.',
          '── HYGIÈNE ──',
          'Montre les gestes du lavage des mains. → Corrigé : geste évalué.',
          '── ANGLAIS ──',
          'Count from 1 to 10. → Corrigé : performance orale.',
          'Cite 3 couleurs en anglais. → Corrigé : red, blue, green.',
        ]
      ),
    ]
  },

  {
    n:4, dates:'22/12/2025 – 26/12/2025',
    theme:'EXAMENS FIN DE 1ÈRE PÉRIODE + Vacances de Noël',
    matieres:[
      m('EXAMENS','Examens officiels — Fin de 1ère période + Vacances',
        'Examens de fin de 1ère période pour la 12ème. Épreuves adaptées à l\'âge (5 ans) : activités orales, graphisme, dessin, numération. Vendredi 26 décembre : vacances de Noël.',
        ['Lundi 22/12 : Épreuve de Langage + Numération (oral)',
         'Mardi 23/12 : Épreuve de Graphisme + Dessin + Calcul',
         'Mercredi 24/12 : Épreuve de Chant + Récitation + Hygiène (oral)',
         'Jeudi 25/12 : Noël — activités libres ou jour férié',
         'Vendredi 26/12 : Résultats + début vacances'],
        [
          '══ ÉPREUVE DE LANGAGE (oral) ══',
          'Cite 5 parties du corps. → Corrigé : tête, yeux, nez, bras, jambe.',
          'Cite tes 5 sens. → Corrigé : vue, ouïe, odorat, goût, toucher.',
          'Cite 3 membres de ta famille. → Corrigé : maman, papa, frère, sœur, grand-mère.',
          'Cite 4 vêtements. → Corrigé : robe, pantalon, chemise, chaussures.',
          'Cite 3 pièces de la maison. → Corrigé : salon, cuisine, chambre.',
          '',
          '══ ÉPREUVE DE NUMÉRATION ══',
          'Compte de 1 à 20. → Corrigé : performance orale.',
          'Montre 13 avec des objets. → Corrigé : dénombrement.',
          'Quel nombre vient après 16 ? → Corrigé : 17.',
          'Quel est le plus grand : 11 ou 18 ? → Corrigé : 18.',
          '',
          '══ ÉPREUVE DE CALCUL ══',
          '3+4=___. → Corrigé : 7.',
          '6+4=___. → Corrigé : 10.',
          '8−3=___. → Corrigé : 5.',
          '9−4=___. → Corrigé : 5.',
          '',
          '══ ÉPREUVE DE GRAPHISME ══',
          'Trace : 3 lignes horizontales. → Corrigé : évaluation.',
          'Trace : 3 boucles. → Corrigé : évaluation.',
          'Trace : 2 spirales. → Corrigé : évaluation.',
          'Trace : 3 ponts. → Corrigé : évaluation.',
          '',
          '══ ÉPREUVE DE DESSIN ══',
          'Dessine ta maison. → Corrigé : production évaluée.',
          'Colorie le sapin en vert et la boule en rouge. → Corrigé : évaluation.',
          '',
          '══ ÉPREUVES ORALES ══',
          'Chante "Tête, épaules, genoux et pieds". → Corrigé : performance.',
          'Récite "Promenons-nous dans les bois". → Corrigé : performance.',
          'Montre les gestes du lavage des mains. → Corrigé : performance.',
          'Count from 1 to 5 in English. → Corrigé : one, two, three, four, five.',
        ]
      ),
    ]
  },

];

module.exports = { DECEMBRE_12EME };
