'use strict';
// RÉPARTITION 12ÈME — MARS 2026
// S1 = enseignement normal · S2 = révision générale · S3 = EXAMENS FIN 2ÈME PÉRIODE · S4 = Vacances de Pâques

function m(mat, topic, approche, activites, exercices) {
  return { matiere:mat, topic, approche, activites, exercices };
}

const MARS_12EME = [

  {
    n:1, dates:'02/03/2026 – 06/03/2026',
    theme:'Le corps humain · Lettres à queue (Q/Y/g) · Compter 1-40 · Groupes et multiplication',
    matieres:[

      m('HYGIÈNE','Prendre soin de son corps',
        'Le corps humain a des besoins : manger, boire, dormir, se laver, faire de l\'exercice. Prendre soin de chaque partie du corps.',
        ['Discussion : "Comment prends-tu soin de ton corps ?"',
         'Tableau : corps / besoin / soin correspondant',
         'Règle : "Mon corps est précieux, j\'en prends soin"'],
        ['Cite 3 besoins du corps humain. → Corrigé : manger, boire, dormir, se laver, faire de l\'exercice.',
         'Que se passe-t-il si on ne dort pas assez ? → Corrigé : on est fatigué, on fait des erreurs, on est irritable.',
         'Que se passe-t-il si on ne mange pas ? → Corrigé : on a faim, on s\'affaiblit, on tombe malade.',
         'Combien d\'heures doit dormir un enfant de 5 ans ? → Corrigé : environ 10-12 heures.',
         'Cite 1 soin à faire chaque matin. → Corrigé : se laver le visage, se brosser les dents, se peigner.']),

      m('I.C.','Les parties du corps et leurs fonctions',
        'Les principaux organes et leur fonction simplifiée : cœur (pompe le sang), poumons (respirer), estomac (digérer), cerveau (penser), yeux (voir), oreilles (entendre).',
        ['Images du corps avec les organes',
         '"À quoi sert le cœur ?" Discussion',
         'Mimer chaque fonction : respirer, digérer, réfléchir'],
        ['À quoi sert le cœur ? → Corrigé : à pomper le sang dans tout le corps.',
         'À quoi servent les poumons ? → Corrigé : à respirer, à absorber l\'oxygène.',
         'À quoi sert l\'estomac ? → Corrigé : à digérer les aliments.',
         'Quel organe permet de penser ? → Corrigé : le cerveau.',
         'Cite 2 sens et les organes correspondants. → Corrigé : vue/yeux, ouïe/oreilles, goût/langue...']),

      m('MORAL','Prendre soin de soi et des autres',
        'Santé et bien-être : se soigner soi-même ET aider les autres quand ils ne vont pas bien. Solidarité.',
        ['Discussion : "Que fais-tu quand un camarade est blessé ?"',
         'Jeu de rôle : aider un ami qui a mal',
         'Règle : "Je prends soin de moi et j\'aide mes amis"'],
        ['Que fais-tu si un ami pleure à l\'école ? → Corrigé : je m\'approche, je lui demande ce qui ne va pas, je préviens l\'enseignant.',
         'Que fais-tu si tu as mal ? → Corrigé : je le dis à un adulte.',
         'Prendre soin de soi, c\'est quoi ? → Corrigé : bien manger, dormir, se laver, faire de l\'exercice, ne pas faire de bêtises.',
         'Peut-on aider quelqu\'un à aller mieux avec des mots ? → Corrigé : oui, les encouragements et la gentillesse aident beaucoup.',
         'Cite 1 façon d\'aider un camarade qui est triste. → Corrigé : l\'écouter, lui sourire, jouer avec lui.']),

      m('CONTE','Nouveau conte — Le corps qui parle (S1)',
        'Conte sur un enfant qui écoute son corps : il a mal au ventre quand il est stressé, faim quand il n\'a pas mangé. Son corps lui parle.',
        ['Présenter les images',
         'Lire S1',
         'Discussion : "Ton corps te parle-t-il aussi ?"'],
        ['Qui est le personnage du conte ? → Corrigé : un enfant.',
         'Comment son corps lui parle-t-il ? → Corrigé : par la faim, la douleur, la fatigue.',
         'Qu\'est-ce que cela signifie quand ton ventre gargouille ? → Corrigé : tu as faim.',
         'Qu\'est-ce que cela signifie quand tu as les paupières lourdes ? → Corrigé : tu as sommeil.',
         'Cite 1 autre signal de ton corps. → Corrigé : maux de tête = fatigue ou fièvre, frissons = froid ou maladie.']),

      m('LANGAGE','Les parties du corps — vocabulaire complet',
        'Révision et approfondissement du vocabulaire du corps : tête, cou, épaules, bras, coude, poignet, main, doigts, ventre, dos, jambe, genou, cheville, pied, orteils.',
        ['Pointer sur soi : "Montre ton coude / ton poignet / ta cheville"',
         '"Tête, épaules, genoux, pieds" + "coude, genou, cheville"',
         'Devinettes : "C\'est entre le bras et la main. C\'est le ___."'],
        ['Montre ton coude. → Corrigé : geste.',
         'Montre ton poignet. → Corrigé : geste.',
         'Qu\'y a-t-il entre la jambe et le pied ? → Corrigé : la cheville.',
         'Combien de doigts as-tu sur les deux mains ? → Corrigé : 10.',
         'Cite 3 parties de la tête. → Corrigé : oreilles, yeux, nez, bouche, front, joues.']),

      m('PRÉ-LECTURE','Graphisme — lettres à queue basse : g, q, y',
        'Tracer g, q, y en minuscule (cursive préparatoire) : ces lettres descendent sous la ligne de base.',
        ['g = rond + queue vers le bas à droite',
         'q = rond + queue vers le bas à droite (miroir de g)',
         'y = deux jambages + queue vers le bas'],
        ['Trace 5 lettres g. → Corrigé : évaluation.',
         'Trace 5 lettres q. → Corrigé : évaluation.',
         'Trace 5 lettres y. → Corrigé : évaluation.',
         'Quelle est la différence entre g et q ? → Corrigé : la queue de g part vers la gauche, celle de q vers la droite.',
         'Cite 3 lettres qui descendent sous la ligne. → Corrigé : g, q, y (aussi j, p).']),

      m('NUMÉRATION','Compter jusqu\'à 40',
        'Continuer la progression jusqu\'à 40. 40 = 4 dizaines. Tableau des dizaines.',
        ['Compter de 33 à 40',
         '40 = 4 paquets de 10',
         'Dénombrement : 40 bâtons en 4 groupes de 10'],
        ['Compte de 30 à 40. → Corrigé : 30, 31, 32, ..., 40.',
         'Quel nombre vient après 39 ? → Corrigé : 40.',
         '40 = ___ dizaines. → Corrigé : 4 dizaines.',
         'Décompose 37 : ___ dizaines + ___ unités. → Corrigé : 3 dizaines + 7 unités.',
         'Quel est le plus grand : 40 ou 35 ? → Corrigé : 40.']),

      m('CALCUL','Groupes et multiplication — consolider',
        'Consolider la notion de groupes égaux. 4 × 3 = 3 + 3 + 3 + 3 = 12. Avec manipulatifs.',
        ['4 groupes de 3 avec des cailloux',
         'Ardoise : 2 × 5 = ?',
         'Problème : 3 sacs de 4 pommes = combien ?'],
        ['2×5=___. → Corrigé : 10.',
         '4×3=___. → Corrigé : 12.',
         '3×4=___. → Corrigé : 12 (même résultat).',
         'Problème : 3 sacs de 4 pommes = ___. → Corrigé : 12 pommes.',
         'Problème : 5 élèves ont chacun 2 crayons = ___. → Corrigé : 10 crayons.']),

      m('DESSIN','Dessin du corps humain',
        'Dessiner un bonhomme complet avec toutes les parties du corps. Nommer les parties.',
        ['Dessiner : tête, cou, corps, bras, mains, jambes, pieds',
         'Légender : flèches vers chaque partie',
         'Colorier'],
        ['Combien de parties as-tu dessinées ? → Corrigé : réponse personnelle.',
         'As-tu dessiné les oreilles ? → Corrigé : réponse.',
         'As-tu dessiné les doigts ? → Corrigé : réponse.',
         'Quelle partie était la plus difficile à dessiner ? → Corrigé : réponse personnelle.',
         'Es-tu content de ton bonhomme ? → Corrigé : réponse personnelle.']),

      m('CHANT','Chanson "Mon corps a un cœur"',
        '"Mon corps a un cœur / mon cœur bat pour toi / mes poumons respirent / mes yeux te voient" — Inventer des gestes.',
        ['Apprendre les paroles',
         'Mimer chaque organe : mettre la main sur le cœur, respirer fort, pointer les yeux',
         'Chanter avec émotion'],
        ['Chante "Mon corps a un cœur". → Corrigé : performance.',
         'Mime le cœur qui bat. → Corrigé : main sur la poitrine.',
         'Mime les poumons qui respirent. → Corrigé : geste d\'inspiration.',
         'Mime les yeux qui voient. → Corrigé : pointer les yeux puis regarder au loin.',
         'Quelle partie du corps préfères-tu dans cette chanson ? → Corrigé : réponse personnelle.']),

      m('RÉCITATION','Comptine — "Je suis un géant"',
        '"Je suis un géant (je me lève) / je suis une souris (je m\'accroupis) / je suis un oiseau (je bats des bras) / et je m\'envole ainsi !"',
        ['Apprendre les paroles + gestes',
         'Accélérer le rythme',
         'Réciter très vite'],
        ['Récite "Je suis un géant". → Corrigé : performance.',
         'Que fait le géant ? → Corrigé : il se lève, il est grand.',
         'Que fait la souris ? → Corrigé : elle s\'accroupit, elle est petite.',
         'Que fait l\'oiseau ? → Corrigé : il bat des bras et s\'envole.',
         'Mime les 4 animaux/personnages. → Corrigé : gestes.']),

      m('T.M.','Tableau du corps humain — découpage collage',
        'Découper des silhouettes de corps dans des magazines et les coller sur un grand papier. Légender.',
        ['Chercher des images de corps en mouvement dans des magazines',
         'Découper et coller',
         'Ajouter les étiquettes-mots'],
        ['Combien de silhouettes as-tu collées ? → Corrigé : réponse.',
         'Quelles parties as-tu étiquetées ? → Corrigé : réponse personnelle.',
         'Quel mouvement font les corps que tu as découpés ? → Corrigé : réponse personnelle.',
         'As-tu bien découpé ? → Corrigé : réponse.',
         'Es-tu content de ton tableau ? → Corrigé : réponse personnelle.']),

      m('A.P.S.','Yoga pour enfants — postures animales',
        'Yoga adapté aux 5 ans : posture du chien, de la grenouille, du cobra, de l\'arbre. Concentration et équilibre.',
        ['Posture du chien : 4 pattes',
         'Posture de la grenouille : accroupi',
         'Posture du cobra : allongé, relever la tête',
         'Posture de l\'arbre : sur 1 pied, bras levés'],
        ['Montre la posture du chien. → Corrigé : à 4 pattes.',
         'Montre la posture de l\'arbre. → Corrigé : sur 1 pied, bras levés.',
         'Quelle posture est la plus difficile ? → Corrigé : réponse personnelle.',
         'As-tu tenu la posture de l\'arbre 5 secondes ? → Corrigé : réponse.',
         'Comment te sens-tu après le yoga ? → Corrigé : calme, détendu.']),

      m('ENVIRONNEMENT','Le corps et l\'environnement — air pur / pollution',
        'Nos poumons ont besoin d\'air pur. La pollution de l\'air nuit à la santé. Les arbres purifient l\'air.',
        ['Respirer dehors vs. près d\'une voiture (image)',
         'Discussion : "L\'air est-il propre où tu habites ?"',
         'Solution : planter des arbres, ne pas brûler les déchets'],
        ['Que respirent nos poumons ? → Corrigé : de l\'air (oxygène).',
         'Qu\'est-ce que l\'air pollué ? → Corrigé : de l\'air avec de la fumée, des produits chimiques, des microbes.',
         'Comment les arbres nous aident-ils ? → Corrigé : ils produisent de l\'oxygène et absorbent le CO2.',
         'Cite 1 source de pollution de l\'air. → Corrigé : voitures, feux de déchets, usines.',
         'Que peux-tu faire pour avoir de l\'air pur ? → Corrigé : planter des arbres, aérer sa maison, ne pas brûler les ordures.']),

      m('ANGLAIS','Body parts — Le corps en anglais',
        'Apprendre les parties du corps en anglais : head, shoulders, arms, hands, legs, feet, eyes, nose, mouth, ears.',
        ['"Head, shoulders, knees and toes" + "eyes and ears and mouth and nose"',
         '"Simon says: touch your nose !"',
         'Quiz rapide : 10 parties du corps'],
        ['How do you say "tête" ? → Corrigé : head.',
         'How do you say "mains" ? → Corrigé : hands.',
         'How do you say "pieds" ? → Corrigé : feet.',
         'Touch your nose ! → Corrigé : geste.',
         'Touch your ears ! → Corrigé : geste.']),

    ]
  },

  {
    n:2, dates:'09/03/2026 – 13/03/2026',
    theme:'RÉVISION GÉNÉRALE — 2ème trimestre (toutes matières)',
    matieres:[
      m('RÉVISION','Révision générale 2ème trimestre — 12ème',
        'Révision intensive de tous les apprentissages du 2ème trimestre pour préparer les examens.',
        ['Lundi : révision Hygiène, IC, Moral, Conte',
         'Mardi : révision Langage, Graphisme, Numération',
         'Mercredi : révision Calcul, Dessin, Environnement',
         'Jeudi : révision Chant, Récitation, T.M., A.P.S.',
         'Vendredi : mini-évaluation blanche orale'],
        [
          '── LANGAGE ──',
          'Cite 5 mots sur le corps. → Corrigé : tête, bras, jambe, cœur, yeux.',
          'Cite 5 mots sur les transports. → Corrigé : voiture, bateau, avion, vélo, taxi-brousse.',
          'Cite 5 mots sur l\'eau. → Corrigé : pluie, mer, rivière, puits, robinet.',
          '── NUMÉRATION ──',
          'Compte de 1 à 40. → Corrigé : performance orale.',
          'Décompose 36 : ___ dizaines + ___ unités. → Corrigé : 3D + 6U.',
          'Ordonne : 40, 18, 7, 33. → Corrigé : 7, 18, 33, 40.',
          '── CALCUL ──',
          '8+9=___. → Corrigé : 17.',
          '16−7=___. → Corrigé : 9.',
          'La moitié de 18 = ___. → Corrigé : 9.',
          '4×3=___. → Corrigé : 12.',
          '── GRAPHISME ──',
          'Trace O, C, G, Q. → Corrigé : évaluation.',
          'Trace I, L, T, H. → Corrigé : évaluation.',
          'Trace J, U, V, B, P, D, g, q, y. → Corrigé : évaluation.',
          '── CHANT ──',
          'Chante "Il pleut, il pleut, bergère". → Corrigé : performance.',
          'Chante "Mon corps a un cœur". → Corrigé : performance.',
          '── RÉCITATION ──',
          'Récite "En voiture Simone". → Corrigé : performance.',
          'Récite "Je suis un géant". → Corrigé : performance.',
          '── ANGLAIS ──',
          'Count from 1 to 20. → Corrigé : performance.',
          'Say 3 body parts in English. → Corrigé : head, arms, legs.',
        ]
      ),
    ]
  },

  {
    n:3, dates:'16/03/2026 – 20/03/2026',
    theme:'EXAMENS FIN DE 2ÈME PÉRIODE — 12ème',
    matieres:[
      m('EXAMENS','Examens officiels — Fin de 2ème période 12ème',
        'Épreuves de fin du 2ème trimestre pour la 12ème pré-primaire. Format oral et graphisme adapté aux 5 ans.',
        ['Lundi 16/03 : Épreuve de Langage + Numération (oral)',
         'Mardi 17/03 : Épreuve de Graphisme + Dessin',
         'Mercredi 18/03 : Épreuve de Calcul',
         'Jeudi 19/03 : Épreuves orales (Chant + Récitation + Hygiène)',
         'Vendredi 20/03 : Correction + remise des appréciations'],
        [
          '══ ÉPREUVE LANGAGE (oral) ══',
          'Cite 5 parties du corps. → Corrigé : tête, bras, jambe, pied, main.',
          'Cite 5 mots sur les transports. → Corrigé : voiture, bateau, avion, vélo, taxi-brousse.',
          'Cite 5 mots sur l\'eau. → Corrigé : pluie, mer, rivière, puits, nuage.',
          'Fais une phrase avec "famille". → Corrigé : production.',
          'Fais une phrase avec "transport". → Corrigé : production.',
          '',
          '══ ÉPREUVE NUMÉRATION ══',
          'Compte de 1 à 40. → Corrigé : performance orale.',
          'Quel nombre vient après 38 ? → Corrigé : 39.',
          'Quel est le plus grand : 40 ou 35 ? → Corrigé : 40.',
          'Décompose 34 : ___ D + ___ U. → Corrigé : 3D + 4U.',
          'Montre 27 avec des objets. → Corrigé : dénombrement.',
          '',
          '══ ÉPREUVE CALCUL ══',
          '9+7=___. → Corrigé : 16.',
          '15−8=___. → Corrigé : 7.',
          'La moitié de 12 = ___. → Corrigé : 6.',
          '3 groupes de 5 = ___. → Corrigé : 15.',
          'Problème : 20 élèves. La moitié part en récré. Combien reste ? → Corrigé : 10.',
          '',
          '══ ÉPREUVE GRAPHISME ══',
          'Trace : 2 O, 2 C, 2 G, 2 Q. → Corrigé : évaluation.',
          'Trace : 2 I, 2 L, 2 T, 2 H. → Corrigé : évaluation.',
          'Trace : 2 J, 2 U, 2 V. → Corrigé : évaluation.',
          'Trace : 2 B, 2 P, 2 D. → Corrigé : évaluation.',
          'Dessine ta maison. → Corrigé : production évaluée.',
          '',
          '══ ÉPREUVES ORALES ══',
          'Chante "Il pleut, il pleut, bergère". → Corrigé : performance.',
          'Récite "Je suis un géant". → Corrigé : performance.',
          'Montre les 6 étapes du lavage des mains. → Corrigé : performance.',
          'How do you say "head" ? Montre. → Corrigé : geste.',
          'Count from 1 to 10 in English. → Corrigé : performance.',
        ]
      ),
    ]
  },

  {
    n:4, dates:'23/03/2026 – 27/03/2026',
    theme:'Vacances de Pâques — Correction + activités libres',
    matieres:[
      m('VACANCES','Correction des examens + Vacances de Pâques — 12ème',
        'Semaine de Pâques. Correction collective des examens. Remise des appréciations. Activités libres et festives.',
        ['Lundi 23/03 : Correction collective + retour sur les erreurs',
         'Mardi 24/03 : Remise des appréciations aux parents',
         'Mercredi 25/03 : Jeux libres + dessin de Pâques',
         'Jeudi 26/03 : Chants + contes libres',
         'Vendredi 27/03 : Départ en vacances de Pâques'],
        [
          'Correction des exercices de numération : ce qu\'on a bien réussi.',
          'Correction des exercices de calcul : les additions et soustractions.',
          'Correction du graphisme : quelles lettres améliorer.',
          'Activité Pâques : décorer un œuf de Pâques en papier.',
          'Chanter "Petit train" + "Il pleut" une dernière fois avant les vacances.',
          'Promesse pour le 3ème trimestre : "Je vais travailler encore mieux !"',
          'Message aux parents : bilan du 2ème trimestre.',
          'Dessin libre : "Ce que je vais faire pendant les vacances".',
          'Jeu libre : jeu de la mare (grenouilles), jeu du train.',
          'Au revoir : "Bonnes vacances de Pâques !"',
        ]
      ),
    ]
  },

];

module.exports = { MARS_12EME };
