'use strict';
// RÉPARTITION 12ÈME — MAI 2026
// S2 = Fête des Mères (préparation) · S4 = Fête des Mères (dimanche 31/05) + Évaluation

function m(mat, topic, approche, activites, exercices) {
  return { matiere:mat, topic, approche, activites, exercices };
}

const MAI_12EME = [

  {
    n:1, dates:'04/05/2026 – 08/05/2026',
    theme:'Le marché · Lettres R/S · Compter 1-60 · La monnaie Ariary (notion simple)',
    matieres:[

      m('HYGIÈNE','Hygiène au marché',
        'Le marché peut être source de microbes : surfaces sales, aliments exposés à la poussière. Se laver les mains après le marché. Bien laver les fruits et légumes achetés.',
        ['Discussion : "Es-tu déjà allé au marché ?"',
         'Images : marché propre vs marché sale',
         'Règle : "Je lave les fruits et légumes avant de les manger"'],
        ['Pourquoi laver les fruits achetés au marché ? → Corrigé : ils ont été touchés par de nombreuses personnes et peuvent avoir des pesticides ou de la poussière.',
         'Que fait-on de ses mains après avoir été au marché ? → Corrigé : on se lave les mains avec du savon.',
         'Peut-on manger un fruit sans le laver ? → Corrigé : non, il faut toujours le laver.',
         'Comment laver correctement un légume ? → Corrigé : le passer sous l\'eau courante en le frottant.',
         'Cite 2 aliments qu\'on peut acheter au marché. → Corrigé : riz, légumes, poisson, viande, fruits.']),

      m('I.C.','Le marché malgache — vie économique',
        'Le marché est le lieu où on achète et vend des produits. Au marché de Madagascar : riz, légumes, poissons, vêtements, épices. Le "tsena" ou "bazary".',
        ['Images du marché malgache : Analakely, Zoma',
         'Discussion : "Qu\'est-ce qu\'on vend au marché ?"',
         'Jeu de rôle : marchande et client'],
        ['Comment appelle-t-on le marché en malgache ? → Corrigé : tsena ou bazary.',
         'Que peut-on acheter au marché ? → Corrigé : riz, légumes, fruits, poisson, épices, vêtements.',
         'Qui vend au marché ? → Corrigé : des marchands, des agriculteurs, des artisans.',
         'Pourquoi le marché est-il important pour le village ? → Corrigé : c\'est là qu\'on achète la nourriture et qu\'on vend ses produits.',
         'As-tu déjà aidé à faire les courses au marché ? → Corrigé : réponse personnelle.']),

      m('MORAL','L\'honnêteté dans les échanges',
        'Au marché, il faut être honnête : ne pas tricher sur le prix, rendre la monnaie exacte, ne pas voler. Être un bon commerçant et un bon client.',
        ['Jeu de rôle : marchand honnête vs malhonnête',
         'Discussion : "Que fais-tu si un marchand te rend trop de monnaie ?"',
         'Règle : "Je suis honnête dans mes échanges"'],
        ['Que fait un marchand honnête ? → Corrigé : il donne le vrai prix, ne trompe pas sur la quantité, rend la bonne monnaie.',
         'Que fais-tu si un marchand te rend trop de monnaie ? → Corrigé : je lui rends ce qui est en trop.',
         'Est-il bien de voler au marché ? → Corrigé : non, c\'est du vol et c\'est mal.',
         'Pourquoi l\'honnêteté est-elle importante dans le commerce ? → Corrigé : parce qu\'on ne peut faire des affaires qu\'avec des personnes en qui on a confiance.',
         'Cite 1 exemple d\'honnêteté au marché. → Corrigé : rendre la monnaie exacte, dire la vraie qualité du produit.']),

      m('CONTE','Nouveau conte — La marchande de mangues (S1)',
        'Dernier conte de l\'année : une petite fille vend des mangues au marché avec sa maman. S1 : arriver au marché.',
        ['Présenter les images : mangues, marché, petite fille',
         'Lire S1 avec expression',
         'Questions de compréhension'],
        ['Qui est le personnage du conte ? → Corrigé : une petite fille / marchande de mangues.',
         'Que vend-elle ? → Corrigé : des mangues.',
         'Avec qui est-elle ? → Corrigé : sa maman.',
         'As-tu déjà vendu ou acheté des mangues ? → Corrigé : réponse personnelle.',
         'Comment décris-tu le marché dans le conte ? → Corrigé : réponse personnelle.']),

      m('LANGAGE','Au marché — vocabulaire commercial',
        'Apprendre le vocabulaire du marché : acheter, vendre, payer, prix, monnaie, client, marchand, kilo, litre. Construire des phrases.',
        ['"Combien coûte cette mangue ?"',
         '"Je voudrais 3 mangues, s\'il vous plaît."',
         'Jeu de rôle : achat et vente'],
        ['Qui achète ? → Corrigé : le client.',
         'Qui vend ? → Corrigé : le marchand.',
         'Que dit-on pour acheter quelque chose ? → Corrigé : "Combien ça coûte ?" / "Je voudrais..."',
         'Que dit-on après avoir acheté ? → Corrigé : "Merci !"',
         'Fais une phrase avec "marché". → Corrigé : production.']),

      m('PRÉ-LECTURE','Graphisme — lettres R et S',
        'Tracer R : trait vertical + demi-cercle haut + jambe diagonale. Tracer S : deux demi-cercles opposés (serpent).',
        ['R dans l\'air : "Je monte, je fais un demi-cercle, je fais une jambe"',
         'S dans l\'air : "Je fais une courbe vers la gauche en haut, une courbe vers la droite en bas"',
         'Comparer R et B (même structure mais différents)'],
        ['Trace 5 lettres R. → Corrigé : évaluation.',
         'Trace 5 lettres S. → Corrigé : évaluation.',
         'Quelle différence entre R et P ? → Corrigé : R a une jambe en diagonale, P n\'en a pas.',
         'Quelle lettre ressemble à un serpent ? → Corrigé : S.',
         'Dans quel sens commence la lettre S ? → Corrigé : vers la gauche en partant du haut.']),

      m('NUMÉRATION','Compter jusqu\'à 60',
        'Continuer la progression : jusqu\'à 60. 60 = 6 dizaines. Compter par 10 jusqu\'à 60.',
        ['Compter de 50 à 60',
         'Compter par 10 : 10, 20, 30, 40, 50, 60',
         '60 = 6 paquets de 10'],
        ['Compte de 50 à 60. → Corrigé : 50, 51, 52, ..., 60.',
         'Compte par 10 jusqu\'à 60. → Corrigé : 10, 20, 30, 40, 50, 60.',
         '60 = ___ dizaines. → Corrigé : 6.',
         'Quel nombre vient avant 60 ? → Corrigé : 59.',
         'Décompose 57 : ___ D + ___ U. → Corrigé : 5D + 7U.']),

      m('CALCUL','La monnaie — notion simple (Ariary)',
        'Introduction à la monnaie : l\'Ariary est la monnaie de Madagascar. Reconnaître les pièces (100Ar, 50Ar, 20Ar, 10Ar). Addition pour trouver le total.',
        ['Montrer des images de pièces d\'Ariary',
         'Problème : "J\'ai 100 Ar, je dépense 50 Ar. Combien reste ?"',
         'Jeu de marché avec de la fausse monnaie'],
        ['Quelle est la monnaie de Madagascar ? → Corrigé : l\'Ariary.',
         'J\'ai 50 Ar + 50 Ar = ___ Ar. → Corrigé : 100 Ar.',
         'J\'ai 100 Ar, je dépense 60 Ar. Combien reste ? → Corrigé : 40 Ar.',
         'Une mangue coûte 20 Ar. J\'en achète 3. Total ? → Corrigé : 60 Ar.',
         'J\'ai 100 Ar et j\'achète une orange à 30 Ar. Ma monnaie = ___ Ar. → Corrigé : 70 Ar.']),

      m('DESSIN','Dessin du marché',
        'Dessiner une scène de marché : étals avec des fruits, des légumes, un marchand, un client.',
        ['Observer images de marché',
         'Dessiner les étals (rectangles) avec des produits (cercles = fruits)',
         'Ajouter des personnages'],
        ['Qu\'as-tu représenté dans ton dessin ? → Corrigé : réponse personnelle.',
         'Combien de personnages as-tu dessinés ? → Corrigé : réponse.',
         'Quels aliments voit-on sur tes étals ? → Corrigé : réponse personnelle.',
         'Quelle couleur as-tu choisie pour les fruits ? → Corrigé : réponse personnelle.',
         'As-tu montré la foule du marché ? → Corrigé : réponse personnelle.']),

      m('CHANT','Chanson "J\'irai au marché"',
        '"J\'irai au marché / acheter des fruits / des mangues et des litchis / pour toute la famille !"',
        ['Apprendre les paroles',
         'Mimer : panier au bras, choisir les fruits, payer',
         'Chanter en frappant le rythme'],
        ['Chante "J\'irai au marché". → Corrigé : performance.',
         'Que va-t-on acheter ? → Corrigé : des fruits (mangues, litchis).',
         'Pour qui achète-t-on ? → Corrigé : pour toute la famille.',
         'Mime : choisir des fruits au marché. → Corrigé : geste.',
         'Mime : payer au marchand. → Corrigé : geste.']),

      m('RÉCITATION','Comptine "Un pour toi, un pour moi"',
        '"Un pour toi, un pour moi / deux pour toi, deux pour moi / jusqu\'à dix, partageons tout / la vie est belle entre nous deux !"',
        ['Apprendre les paroles (comptine sur le partage et la numération)',
         'Mimer le partage',
         'Réciter très vite'],
        ['Récite "Un pour toi". → Corrigé : performance.',
         'Jusqu\'à quel chiffre va la comptine ? → Corrigé : dix.',
         'Quelle valeur exprime cette comptine ? → Corrigé : le partage, la générosité.',
         'Mime le partage avec un camarade. → Corrigé : geste.',
         'Chante cette comptine très vite. → Corrigé : performance.']),

      m('T.M.','Fabrication de monnaie en papier',
        'Créer de la "fausse" monnaie en papier : découper des ronds, écrire les valeurs (10, 20, 50, 100 Ar). Utiliser pour le jeu de marché.',
        ['Découper des cercles de papier',
         'Écrire (ou faire écrire) les valeurs',
         'Colorier selon la valeur'],
        ['Combien de pièces as-tu fabriquées ? → Corrigé : réponse.',
         'Quelle est la valeur la plus grande que tu as faite ? → Corrigé : 100 Ar.',
         'À quoi serviront tes pièces ? → Corrigé : au jeu de marché.',
         'Quelle forme ont les pièces de monnaie ? → Corrigé : ronde.',
         'As-tu bien écrit les chiffres ? → Corrigé : réponse.']),

      m('A.P.S.','Jeu du marché en mouvement',
        'Jeu d\'équipe : transporter les "marchandises" (balles) d\'un côté à l\'autre de la cour comme des marchands. Course.',
        ['Diviser en 2 équipes : marchands et clients',
         'Transporter les balles = marchandises',
         'Compter les balles transportées'],
        ['Combien de "marchandises" ton équipe a-t-elle transportées ? → Corrigé : réponse.',
         'Quel mouvement fait-on pour transporter ? → Corrigé : courir, porter.',
         'Ton équipe a-t-elle coopéré ? → Corrigé : réponse.',
         'Quel rôle as-tu joué ? → Corrigé : réponse.',
         'As-tu aimé ce jeu ? → Corrigé : réponse personnelle.']),

      m('ENVIRONNEMENT','Les ressources naturelles et le commerce',
        'Les produits qu\'on vend au marché viennent de la nature : riz des rizières, poisson de la mer, fruits des arbres. Respecter la nature = maintenir le commerce.',
        ['Images : du champ/mer à l\'assiette',
         'Discussion : "D\'où vient le riz qu\'on mange ?"',
         'Tracer le chemin : champ → marché → maison'],
        ['D\'où vient le riz qu\'on mange ? → Corrigé : il pousse dans les rizières (paddy).',
         'D\'où vient le poisson ? → Corrigé : de la mer, des rivières, des lacs.',
         'Quel est le chemin d\'une mangue de l\'arbre à notre table ? → Corrigé : arbre → cueillette → marché → maison.',
         'Pourquoi respecter la nature aide le commerce ? → Corrigé : si on détruit la nature, on n\'a plus de produits à vendre.',
         'Cite 2 produits naturels malgaches exportés (vendus dans d\'autres pays). → Corrigé : vanille, café, ylang-ylang, girofle.']),

      m('ANGLAIS','Shopping vocabulary',
        'Apprendre les mots du commerce en anglais : market, buy, sell, money, fruit, vegetable, how much ?',
        ['"How much is this ?" / "It is ___ Ariary."',
         'Flash cards : fruit, vegetable, market',
         'Jeu : "Buy and sell"'],
        ['How do you say "marché" ? → Corrigé : market.',
         'How do you say "acheter" ? → Corrigé : to buy.',
         'How do you say "argent" ? → Corrigé : money.',
         '"How much is this ?" means ? → Corrigé : Combien coûte ceci ?',
         'How do you say "légume" ? → Corrigé : vegetable.']),

    ]
  },

  {
    n:2, dates:'11/05/2026 – 15/05/2026',
    theme:'Fête des Mères — Préparation · Cadeau T.M. · Poème · Chant pour maman',
    matieres:[

      m('HYGIÈNE','Se préparer pour la Fête des Mères',
        'Se mettre beau pour la Fête des Mères : habits propres, coiffure soignée, mains propres. Faire honneur à sa maman.',
        ['Discussion : "Comment te prépares-tu pour une fête ?"',
         'Rappel : se laver, s\'habiller proprement, se coiffer',
         'Règle : "Pour honorer maman, je suis propre et bien présenté(e)"'],
        ['Que fais-tu pour être bien habillé pour la Fête des Mères ? → Corrigé : je porte des habits propres, je me coiffe, je me lave.',
         'Pourquoi se présenter proprement à une fête ? → Corrigé : par respect pour la personne qu\'on honore.',
         'À quelle occasion doit-on être particulièrement soigné ? → Corrigé : fêtes, cérémonies, visites importantes.',
         'Comment honores-tu ta maman ? → Corrigé : lui offrir un cadeau, lui dire merci, l\'embrasser.',
         'Qu\'est-ce que "faire honneur" à quelqu\'un ? → Corrigé : se comporter d\'une façon qui le rend fier.']),

      m('I.C.','Qu\'est-ce que la Fête des Mères ?',
        'La Fête des Mères est un moment pour remercier sa maman de tout ce qu\'elle fait. Célébrée chaque année en mai/juin selon les pays. À Madagascar, fin mai / début juin.',
        ['Discussion : "Que fait ta maman pour toi ?"',
         'Lister les choses que fait maman',
         'Discussion : "Comment peux-tu la remercier ?"'],
        ['Qu\'est-ce que la Fête des Mères ? → Corrigé : un jour spécial pour remercier sa maman.',
         'Quand fête-t-on la Fête des Mères ? → Corrigé : en mai ou juin selon les pays.',
         'Cite 3 choses que fait ta maman pour toi. → Corrigé : elle cuisine, elle aide aux devoirs, elle soigne, elle embrasse...',
         'Comment peux-tu remercier ta maman ? → Corrigé : lui offrir un cadeau, lui faire un câlin, lui dire "je t\'aime", aider à la maison.',
         'Ta maman est-elle heureuse quand tu lui offres quelque chose fait de tes mains ? → Corrigé : oui.']),

      m('MORAL','L\'amour et la gratitude envers sa maman',
        'L\'amour familial. La gratitude pour tout ce que fait maman. L\'exprimer par des mots et des gestes.',
        ['Discussion : "Qu\'est-ce que tu aimes le plus chez ta maman ?"',
         'Chaque élève dit 1 mot pour décrire sa maman',
         'Créer une "fleur des mots doux" pour maman'],
        ['Que signifie aimer quelqu\'un ? → Corrigé : vouloir son bien, penser à lui, lui faire des choses gentilles.',
         'Comment exprimes-tu ton amour à ta maman ? → Corrigé : câlins, mots doux, aide, cadeaux.',
         'Cite 3 mots pour décrire ta maman. → Corrigé : douce, courageuse, belle, forte, généreuse... réponse personnelle.',
         'Qu\'est-ce que la gratitude ? → Corrigé : être reconnaissant pour ce qu\'on reçoit.',
         'Es-tu reconnaissant(e) pour ce que fait ta maman ? → Corrigé : réponse personnelle.']),

      m('CONTE','La marchande de mangues (S2 — la vente)',
        'Suite du conte : la petite fille réussit à vendre toutes ses mangues. Elle est fière de ramener l\'argent à sa maman.',
        ['Lire S2',
         'Discussion : pourquoi la petite fille est-elle fière ?',
         'Discussion : comment aide-t-on sa maman ?'],
        ['Qu\'est-ce que la petite fille accomplit ? → Corrigé : elle vend toutes ses mangues.',
         'Comment se sent-elle ? → Corrigé : fière, heureuse.',
         'Pourquoi rapporter de l\'argent à maman lui fait-il plaisir ? → Corrigé : parce qu\'elle a contribué à aider la famille.',
         'Comment aides-tu ta maman à la maison ? → Corrigé : réponse personnelle.',
         'Quelle est la leçon de cette partie ? → Corrigé : le travail et la contribution à la famille rendent fier.']),

      m('LANGAGE','Dire je t\'aime — phrases pour maman',
        'Apprendre à exprimer ses sentiments en phrases : "Maman, tu es ma meilleure amie. Je t\'aime. Merci pour tout ce que tu fais."',
        ['"Complète : Maman, tu es ___"',
         '"Maman, j\'aime quand tu ___"',
         '"Ce que j\'aime faire avec toi, c\'est ___"'],
        ['Complète : "Maman, tu es ___." → Corrigé : production personnelle.',
         'Fais une phrase sur ta maman. → Corrigé : production.',
         'Comment dit-on "je t\'aime" en malgache ? → Corrigé : "Tiako ianao."',
         'Quel mot de remerciement connais-tu ? → Corrigé : merci, misaotra.',
         'Quelle phrase diras-tu à ta maman le jour de la fête ? → Corrigé : réponse personnelle.']),

      m('PRÉ-LECTURE','Graphisme — entraînement écriture du prénom de maman',
        'Graphisme en lien avec la Fête des Mères : écrire ou décorer les lettres du prénom de maman. Tous les graphismes du 3ème trimestre sont mobilisés.',
        ['Demander à chaque élève le prénom de sa maman',
         'Tracer les lettres du prénom (en script ou décor)',
         'Décorer chaque lettre'],
        ['Quel est le prénom de ta maman ? → Corrigé : réponse personnelle.',
         'Combien de lettres a le prénom de ta maman ? → Corrigé : réponse personnelle.',
         'Trace les lettres de son prénom. → Corrigé : évaluation.',
         'Quelle lettre était la plus difficile à tracer ? → Corrigé : réponse personnelle.',
         'As-tu bien décoré ? → Corrigé : réponse personnelle.']),

      m('NUMÉRATION','Révision 1-60 + compter par 10',
        'Consolider les acquis. Compter par 10, décomposer, ordonner. Préparer la progression vers 100.',
        ['Compter par 10 jusqu\'à 60',
         'Ordonnancer des collections de 1 à 60',
         'Préparer : "La semaine prochaine on ira jusqu\'à 70 !"'],
        ['Compte par 10 jusqu\'à 60. → Corrigé : 10, 20, 30, 40, 50, 60.',
         'Quel nombre est entre 55 et 57 ? → Corrigé : 56.',
         'Décompose 58 : ___ D + ___ U. → Corrigé : 5D + 8U.',
         'Ordonne : 60, 38, 12, 55. → Corrigé : 12, 38, 55, 60.',
         'Quel est le plus grand nombre que tu connais ? → Corrigé : 60 (ou plus selon les élèves).']),

      m('CALCUL','Révision additions, soustractions, monnaie',
        'Révision de toutes les opérations en contexte de la Fête des Mères. "Maman a reçu 3 cadeaux + 2 cadeaux = ___"',
        ['Quiz ardoise : 8 opérations',
         'Problème : "Un cadeau coûte 100 Ar + 50 Ar. Total ?"',
         'Problème monnaie : "J\'avais 200 Ar, j\'achète un cadeau à 120 Ar. Reste ?"'],
        ['7+9=___. → Corrigé : 16.',
         '20−13=___. → Corrigé : 7.',
         '100+50=___ Ar. → Corrigé : 150 Ar.',
         'Problème : 200 Ar − 120 Ar = ___ Ar. → Corrigé : 80 Ar.',
         'La moitié de 18 = ___. → Corrigé : 9.']),

      m('DESSIN','Portrait de maman',
        'Dessiner le portrait de sa maman. Tête, cheveux, yeux, sourire. Colorier avec soin. Cadeau pour la Fête des Mères.',
        ['Observer son propre visage dans un miroir',
         'Dessiner le visage de maman : ovale, yeux, nez, bouche, cheveux',
         'Colorier et signer'],
        ['Qu\'as-tu dessiné dans le portrait ? → Corrigé : tête, yeux, nez, bouche, cheveux.',
         'Quelle couleur ont les yeux de ta maman ? → Corrigé : réponse personnelle.',
         'Quelle coiffure as-tu dessinée ? → Corrigé : réponse personnelle.',
         'As-tu signé ton dessin ? → Corrigé : réponse.',
         'Es-tu content de ce cadeau ? → Corrigé : réponse personnelle.']),

      m('CHANT','Chanson "Bonne fête Maman"',
        '"Bonne fête maman, je t\'aime tellement / tu es la plus belle, la plus douce du monde / bonne fête maman, merci pour tout ce que tu fais !"',
        ['Apprendre les paroles en 2 jours',
         'Chanter avec beaucoup d\'expression et d\'amour',
         'Répéter pour la représentation du jeudi'],
        ['Chante "Bonne fête maman". → Corrigé : performance.',
         'Qui chante-t-on dans cette chanson ? → Corrigé : maman.',
         'Comment est maman dans la chanson ? → Corrigé : belle, douce.',
         'Qu\'est-ce qu\'on lui dit ? → Corrigé : bonne fête, merci, je t\'aime.',
         'Chante seul pour maman. → Corrigé : performance.']),

      m('RÉCITATION','Poème pour maman — "Ma petite maman"',
        '"Ma petite maman / tu m\'as appris à marcher / tu m\'as appris à parler / maintenant j\'apprends à écrire / et c\'est pour toi que je veux grandir !"',
        ['Apprendre par cœur sur 3 jours',
         'Réciter avec beaucoup d\'expression',
         'Répéter pour la représentation'],
        ['Récite "Ma petite maman" en entier. → Corrigé : performance.',
         'Que t\'a appris ta maman ? → Corrigé : à marcher, à parler, à vivre.',
         'Pour qui veux-tu grandir ? → Corrigé : pour ma maman.',
         'Récite le poème comme si ta maman était devant toi. → Corrigé : performance.',
         'Quel mot du poème préfères-tu ? → Corrigé : réponse personnelle.']),

      m('T.M.','Cadeau Fête des Mères — bouquet de fleurs en papier',
        'Fabriquer un bouquet de fleurs en papier de soie ou crépon. Coller sur une feuille ou assembler en vrai bouquet.',
        ['Découper des pétales de papier coloré',
         'Assembler les fleurs : pétales + cœur',
         'Former le bouquet et emballer avec un ruban'],
        ['Combien de fleurs as-tu faites ? → Corrigé : réponse.',
         'Quelles couleurs as-tu choisies ? → Corrigé : réponse personnelle.',
         'Comment as-tu assemblé les pétales ? → Corrigé : avec de la colle.',
         'Avec quoi as-tu attaché le bouquet ? → Corrigé : ficelle, ruban.',
         'Que diras-tu à ta maman quand tu lui offriras ce bouquet ? → Corrigé : "Bonne fête maman, je t\'aime !"']),

      m('A.P.S.','Répétition de la représentation pour la Fête des Mères',
        'Répétition de la chanson et du poème debout devant la classe, puis devant les autres classes. Placement, projection de la voix, sourire.',
        ['Se mettre en ligne / en arc de cercle',
         'Répéter le chant + le poème avec gestes',
         'Faire une représentation test devant une autre classe'],
        ['As-tu bien dit le poème à voix haute ? → Corrigé : réponse.',
         'As-tu chanté fort et en rythme ? → Corrigé : réponse.',
         'As-tu souri ? → Corrigé : réponse.',
         'Qu\'as-tu trouvé difficile dans la représentation ? → Corrigé : réponse personnelle.',
         'Es-tu prêt pour la vraie représentation jeudi ? → Corrigé : réponse personnelle.']),

      m('ENVIRONNEMENT','Les fleurs et leur rôle',
        'Les fleurs dans la nature : beauté, parfum, nectar pour les abeilles. Fleurs de Madagascar : hibiscus, flamboyant, frangipane, orchidées.',
        ['Images de fleurs de Madagascar',
         'Sentir des fleurs ou des plantes parfumées',
         'Discussion : "À quoi servent les fleurs dans la nature ?"'],
        ['À quoi servent les fleurs dans la nature ? → Corrigé : attirer les insectes pollinisateurs, produire des fruits.',
         'Cite 2 fleurs de Madagascar. → Corrigé : hibiscus, flamboyant, frangipane, orchidée, ylang-ylang.',
         'Quelle fleur as-tu fabriquée ? → Corrigé : réponse selon TM.',
         'Quelle est ta fleur préférée ? → Corrigé : réponse personnelle.',
         'Pourquoi offre-t-on des fleurs ? → Corrigé : pour montrer de l\'amour, de la joie, du respect.']),

      m('ANGLAIS','Happy Mother\'s Day !',
        'Apprendre à dire "Happy Mother\'s Day!" et quelques phrases : "I love you, mum. You are beautiful. Thank you!"',
        ['"Repeat after me : Happy Mother\'s Day !"',
         '"My mother is ___." (kind, beautiful, strong)',
         'Écrire (ou décorer) "I love you, Mum"'],
        ['How do you say "Bonne Fête Maman" ? → Corrigé : Happy Mother\'s Day!',
         'How do you say "je t\'aime" ? → Corrigé : I love you.',
         'How do you say "belle" ? → Corrigé : beautiful.',
         'How do you say "forte" ? → Corrigé : strong.',
         'Say 1 sentence for your mother in English. → Corrigé : réponse personnelle.']),

    ]
  },

  {
    n:3, dates:'18/05/2026 – 22/05/2026',
    theme:'La communauté · Lettres K/W · Compter 1-70 · Les mesures (long/court/grand/petit)',
    matieres:[

      m('HYGIÈNE','Hygiène dans la communauté — espaces partagés',
        'Garder propre les espaces communs : école, quartier, rue. Ne pas jeter les déchets par terre. La propreté est l\'affaire de tous.',
        ['Image : rue propre vs rue avec déchets',
         'Discussion : "Que fais-tu avec un déchet dans la rue ?"',
         'Règle : "Je mets mes déchets à la poubelle"'],
        ['Que fais-tu si tu vois un déchet par terre à l\'école ? → Corrigé : je le ramasse et le mets à la poubelle.',
         'Pourquoi garder l\'espace commun propre ? → Corrigé : parce que tout le monde l\'utilise et la propreté est importante pour la santé.',
         'Cite 2 espaces partagés. → Corrigé : l\'école, le marché, la rue, le jardin public.',
         'Que penses-tu des personnes qui jettent leurs déchets partout ? → Corrigé : c\'est irresponsable et irrespectueux.',
         'Que peux-tu faire pour garder ton quartier propre ? → Corrigé : mettre mes déchets à la poubelle, participer aux nettoyages collectifs.']),

      m('I.C.','La communauté — vivre ensemble',
        'La communauté : les gens qui vivent dans le même quartier ou village. Règles de vie commune. Aider son voisin. Le "fokonolona" à Madagascar.',
        ['Discussion : "Qui est ton voisin ?"',
         'Comprendre le fokonolona : assemblée du quartier / village',
         'Règles de la vie en communauté'],
        ['Qu\'est-ce qu\'une communauté ? → Corrigé : un groupe de personnes qui vivent dans le même endroit.',
         'Qu\'est-ce que le fokonolona ? → Corrigé : l\'assemblée des habitants d\'un village ou quartier à Madagascar.',
         'Cite 1 règle de vie en communauté. → Corrigé : ne pas faire de bruit la nuit, aider ses voisins, ne pas jeter les déchets.',
         'Comment aide-t-on ses voisins ? → Corrigé : partager la nourriture, aider les malades, garder les enfants.',
         'Pourquoi le vivre-ensemble est-il important ? → Corrigé : parce qu\'on a tous besoin des autres.']),

      m('MORAL','La coopération',
        'Travailler ensemble = faire mieux et plus vite que seul. Exemples : construire une maison, labourer un champ, préparer une fête.',
        ['Discussion : "Qu\'est-ce qu\'on réussit mieux à plusieurs ?"',
         'Jeu de coopération : tenir un cerceau ensemble',
         'Règle : "Je contribue au groupe"'],
        ['Qu\'est-ce que la coopération ? → Corrigé : travailler ensemble vers un objectif commun.',
         'Cite 1 tâche plus facile à faire à plusieurs. → Corrigé : construire, déménager, préparer la fête, labourer.',
         'Que se passe-t-il si personne ne veut coopérer ? → Corrigé : le travail n\'avance pas ou échoue.',
         'As-tu coopéré avec tes camarades cette semaine ? → Corrigé : réponse personnelle.',
         'Quel est le rôle de chacun dans un groupe ? → Corrigé : participer, faire sa part, écouter les autres.']),

      m('CONTE','La marchande de mangues (S3 — fin)',
        'La petite fille revient à la maison avec l\'argent. Elle fait un beau geste : achète un cadeau pour sa maman. Fin heureuse.',
        ['Lire S3',
         'Morale : être généreux avec ceux qu\'on aime',
         'Discussion : "Quelle est la leçon du conte ?"'],
        ['Comment finit le conte ? → Corrigé : la petite fille achète un cadeau pour sa maman.',
         'Qu\'achète-t-elle ? → Corrigé : réponse selon le texte.',
         'Comment se sent sa maman ? → Corrigé : heureuse, touchée.',
         'Quelle est la leçon du conte ? → Corrigé : être généreux avec ceux qu\'on aime.',
         'Raconte le conte complet en 4 phrases. → Corrigé : résumé oral.']),

      m('LANGAGE','La communauté — vocabulaire',
        'Apprendre : quartier, voisin, mairie, école, marché, mosque/église, fokonolona, règle, entraide. Décrire son quartier.',
        ['"Dans mon quartier, il y a ___"',
         'Images de différents bâtiments du quartier',
         'Discussion : "Qu\'est-ce que tu aimes dans ton quartier ?"'],
        ['Qu\'est-ce qu\'un quartier ? → Corrigé : une partie d\'une ville ou d\'un village.',
         'Cite 3 bâtiments qu\'on trouve dans un quartier. → Corrigé : école, marché, mairie, église, maisons.',
         'Qui est ton voisin ? → Corrigé : réponse personnelle.',
         'Fais une phrase avec "communauté". → Corrigé : production.',
         'Décris ton quartier en 2 phrases. → Corrigé : production personnelle.']),

      m('PRÉ-LECTURE','Graphisme — lettres K et W',
        'Tracer K : trait vertical + 2 obliques (haut-droite et bas-droite). Tracer W : 2 V collés ensemble (4 obliques).',
        ['K dans l\'air : "Je descends, je monte en diagonale, je descends en diagonale"',
         'W dans l\'air : "Je descends, remonte, redescends, remonte" (4 mouvements)',
         'Comparer K et X (similaires mais différents)'],
        ['Trace 5 lettres K. → Corrigé : évaluation.',
         'Trace 5 lettres W. → Corrigé : évaluation.',
         'Quelle différence entre K et X ? → Corrigé : K a un trait vertical sur la gauche, X n\'en a pas.',
         'Combien d\'obliques a W ? → Corrigé : 4.',
         'Quelle lettre ressemble à M à l\'envers ? → Corrigé : W.']),

      m('NUMÉRATION','Compter jusqu\'à 70',
        'Continuer : 60, 61, 62, ..., 70. 70 = 7 dizaines. Compter par 10 jusqu\'à 70.',
        ['Compter de 60 à 70',
         'Compter par 10 : 10, 20, ..., 70',
         '70 = 7 paquets de 10'],
        ['Compte de 60 à 70. → Corrigé : 60, 61, ..., 70.',
         'Compte par 10 jusqu\'à 70. → Corrigé : 10, 20, 30, 40, 50, 60, 70.',
         '70 = ___ dizaines. → Corrigé : 7.',
         'Quel nombre vient après 69 ? → Corrigé : 70.',
         'Décompose 67 : ___ D + ___ U. → Corrigé : 6D + 7U.']),

      m('CALCUL','Les mesures — grand/petit, long/court, lourd/léger',
        'Introduction aux mesures comparatives. Comparer deux objets : "Lequel est plus long ?" Introduire la règle.',
        ['Comparer 2 bâtons : "Lequel est le plus long ?"',
         'Comparer 2 objets : "Lequel est le plus lourd ?"',
         'Mesurer avec la règle : "Mon crayon mesure ___ cm"'],
        ['Quel est le plus long : 10 cm ou 5 cm ? → Corrigé : 10 cm.',
         'Quel est le plus lourd : une pierre ou une plume ? → Corrigé : la pierre.',
         'Mesure ton crayon. Combien de centimètres fait-il ? → Corrigé : réponse.',
         'Nomme 1 objet long dans la classe. → Corrigé : la règle, le tableau, le couloir.',
         'Nomme 1 objet court dans la classe. → Corrigé : une gomme, un bouton, un ongle.']),

      m('DESSIN','Ma rue / mon quartier',
        'Dessiner sa rue ou son quartier en vue de face : maisons, arbres, personnes, route.',
        ['Observer des images de rues malgaches',
         'Dessiner sa rue avec 3-4 maisons, des arbres, une route',
         'Ajouter des personnes'],
        ['Qu\'as-tu dessiné dans ta rue ? → Corrigé : réponse personnelle.',
         'Combien de maisons as-tu dessinées ? → Corrigé : réponse.',
         'As-tu dessiné des personnes ? → Corrigé : réponse.',
         'Quelle couleur as-tu choisie pour la route ? → Corrigé : réponse.',
         'Ressemble-t-elle à ta vraie rue ? → Corrigé : réponse personnelle.']),

      m('CHANT','Chanson "Ensemble"',
        '"Ensemble, ensemble, on est plus forts / ensemble, ensemble, on va plus loin / partager la joie et les jours / c\'est ça le sens de la vie !"',
        ['Apprendre les paroles',
         'Chanter en formant un grand cercle (symbolisant la communauté)',
         'Chanter fort pour "ensemble"'],
        ['Chante "Ensemble". → Corrigé : performance.',
         'Quel est le message de cette chanson ? → Corrigé : ensemble on est plus forts.',
         'Pourquoi a-t-on formé un cercle pour chanter ? → Corrigé : pour symboliser l\'unité et la communauté.',
         'Cite 1 chose qu\'on fait mieux ensemble. → Corrigé : réponse personnelle.',
         'Chante le refrain seul. → Corrigé : performance.']),

      m('RÉCITATION','Comptine — "Mon quartier"',
        '"Mon quartier est joli / avec ses maisons colorées / ses marchés et ses jardins / c\'est là où j\'habite et je suis bien !"',
        ['Apprendre les paroles',
         'Mimer les éléments du quartier',
         'Réciter avec fierté'],
        ['Récite "Mon quartier". → Corrigé : performance.',
         'Comment est le quartier dans la comptine ? → Corrigé : joli, coloré.',
         'Que voit-on dans ce quartier ? → Corrigé : maisons colorées, marchés, jardins.',
         'Comment te sens-tu dans ton quartier ? → Corrigé : réponse personnelle.',
         'Mime une maison colorée. → Corrigé : geste de dessiner une maison dans l\'air.']),

      m('T.M.','Maquette de mon quartier',
        'Fabriquer une maquette simple du quartier avec des boîtes (maisons), papier vert (arbres), ficelle (routes).',
        ['Boîtes de différentes tailles = maisons',
         'Rouleau de papier vert = arbres / jardins',
         'Ficelle = routes',
         'Assembler et légender'],
        ['Combien de maisons as-tu faites ? → Corrigé : réponse.',
         'As-tu une école dans ta maquette ? → Corrigé : réponse.',
         'As-tu un marché ? → Corrigé : réponse.',
         'Comment as-tu fait les routes ? → Corrigé : avec la ficelle.',
         'Es-tu content de ta maquette ? → Corrigé : réponse personnelle.']),

      m('A.P.S.','Jeu du quartier — jeu coopératif',
        'Jeu coopératif : construire une tour avec des briques sans la faire tomber. Tout le monde participe.',
        ['Chaque élève pose 1 brique à la fois',
         'La tour ne doit pas tomber',
         'Discussion : comment a-t-on réussi ?'],
        ['Combien de briques la tour avait-elle ? → Corrigé : réponse collective.',
         'La tour a-t-elle tenu ? → Corrigé : réponse.',
         'Qu\'est-ce qui s\'est passé si quelqu\'un a mal posé sa brique ? → Corrigé : la tour a failli tomber.',
         'Comment a-t-on évité que la tour tombe ? → Corrigé : en faisant attention, en aidant.',
         'Quel est le lien entre ce jeu et la communauté ? → Corrigé : ensemble, on construit quelque chose de plus solide que seul.']),

      m('ENVIRONNEMENT','Le quartier et l\'environnement',
        'L\'environnement du quartier : la propreté de la rue, les arbres dans les jardins, les ordures. Un beau quartier = nature respectée.',
        ['Images : quartier propre (arbres, propreté) vs quartier sale (déchets)',
         'Discussion : "Comment rendre son quartier plus beau et propre ?"',
         'Action : ramasser les papiers dans la cour de l\'école'],
        ['Cite 2 éléments naturels qu\'on peut avoir dans son quartier. → Corrigé : arbres, jardins, fleurs, rivière.',
         'Pourquoi les arbres dans la rue sont-ils importants ? → Corrigé : ils donnent de l\'ombre, purifient l\'air, embellissent le quartier.',
         'Que peut-on faire pour un quartier plus vert ? → Corrigé : planter des arbres et des fleurs.',
         'Que peut-on faire pour un quartier plus propre ? → Corrigé : utiliser les poubelles, organiser des nettoyages collectifs.',
         'Qu\'as-tu fait pour rendre l\'école plus propre ? → Corrigé : réponse personnelle.']),

      m('ANGLAIS','Community vocabulary',
        'Apprendre : school, market, house, street, neighbor, together. Phrases : "In my neighborhood, there is a ___."',
        ['"In my neighborhood, there is a market."',
         'Flash cards : school, market, house, street',
         '"Who is your neighbor ?"'],
        ['How do you say "école" ? → Corrigé : school.',
         'How do you say "maison" ? → Corrigé : house.',
         'How do you say "rue" ? → Corrigé : street.',
         'How do you say "ensemble" ? → Corrigé : together.',
         '"In my neighborhood there is a ___." → Corrigé : réponse personnelle.']),

    ]
  },

  {
    n:4, dates:'25/05/2026 – 29/05/2026',
    theme:'Fête des Mères (dimanche 31/05) + Évaluation de mai',
    matieres:[
      m('FÊTE DES MÈRES & ÉVALUATION','Fête des Mères + Évaluation de mai — 12ème',
        'Semaine de la Fête des Mères. Représentation + remise des cadeaux le jeudi ou vendredi. Évaluation de mai intégrée.',
        ['Lundi 25/05 : répétition générale chant + poème + cadeau',
         'Mardi 26/05 : épreuve numération 1-70 + calcul',
         'Mercredi 27/05 : épreuve graphisme + dessin',
         'Jeudi 28/05 : représentation Fête des Mères pour les mamans + remise des cadeaux',
         'Vendredi 29/05 : correction évaluations + activités libres'],
        [
          '══ RÉPÉTITION GÉNÉRALE ══',
          'Chanter "Bonne fête maman" parfaitement.',
          'Réciter "Ma petite maman" à voix haute.',
          'Remettre le bouquet de fleurs + portrait de maman.',
          '',
          '══ ÉPREUVE NUMÉRATION ══',
          'Compte de 1 à 70. → Corrigé : performance orale.',
          'Compte par 10 jusqu\'à 70. → Corrigé : 10, 20, 30, 40, 50, 60, 70.',
          'Décompose 63 : ___ D + ___ U. → Corrigé : 6D + 3U.',
          'Ordonne : 70, 45, 9, 61. → Corrigé : 9, 45, 61, 70.',
          '',
          '══ ÉPREUVE CALCUL ══',
          '8+9=___. → Corrigé : 17.',
          '20−14=___. → Corrigé : 6.',
          'La moitié de 20 = ___. → Corrigé : 10.',
          'Problème : j\'ai 100 Ar, je dépense 70 Ar. Reste ? → Corrigé : 30 Ar.',
          '',
          '══ ÉPREUVE GRAPHISME ══',
          'Trace R, S, K, W. → Corrigé : évaluation.',
          'Trace toutes les voyelles : A, E, I, O, U. → Corrigé : évaluation.',
          'Dessine ta maman. → Corrigé : production.',
          '',
          '══ ÉPREUVE ORALE ══',
          'Chante "Bonne fête maman". → Corrigé : performance.',
          'Récite "Ma petite maman". → Corrigé : performance.',
          'Cite 3 choses que fait ta maman pour toi. → Corrigé : réponse personnelle.',
          'How do you say "Happy Mother\'s Day" ? → Corrigé : Happy Mother\'s Day!',
          '',
          '══ FÊTE DES MÈRES — jeudi 28/05 ══',
          'Les mamans entrent en classe. Les enfants se lèvent.',
          'Les enfants chantent "Bonne fête maman" en chœur.',
          'Les enfants récitent "Ma petite maman" un par un ou en chœur.',
          'Remise du portrait de maman + bouquet de fleurs.',
          '"Bonne fête maman, je t\'aime !" (tous ensemble).',
        ]
      ),
    ]
  },

];

module.exports = { MAI_12EME };
