'use strict';
// RÉPARTITION 12ÈME — JUIN 2026
// Mois d\'examens · S1 = Révision générale · S2 = Épreuves écrites · S3 = Épreuves orales · S4 = Résultats + Fête Nationale 26 juin

function m(mat, topic, approche, activites, exercices) {
  return { matiere:mat, topic, approche, activites, exercices };
}

const JUIN_12EME = [

  {
    n:1, dates:'01/06/2026 – 05/06/2026',
    theme:'RÉVISION GÉNÉRALE FINALE — Toute l\'année 12ème',
    matieres:[
      m('RÉVISION','Révision générale finale — 12ème pré-primaire',
        'Révision intensive de tous les apprentissages de l\'année (octobre - mai) pour préparer les examens de fin d\'année.',
        ['Lundi : révision Hygiène + IC + Moral + Conte',
         'Mardi : révision Langage + Graphisme (toutes les lettres)',
         'Mercredi : révision Numération 1-70 + Calcul',
         'Jeudi : révision Chant + Récitation + Anglais',
         'Vendredi : révision Dessin + TM + APS + mini-examen blanc'],
        [
          '══ RÉVISION HYGIÈNE ══',
          'Cite les 6 étapes du lavage des mains. → Corrigé : mouiller, savonner, frotter, rincer, sécher.',
          'Cite 3 bonnes habitudes d\'hygiène. → Corrigé : se brosser les dents, boire de l\'eau propre, dormir suffisamment.',
          'Pourquoi l\'hygiène est-elle importante ? → Corrigé : pour rester en bonne santé.',
          '',
          '══ RÉVISION LANGAGE ══',
          'Cite 5 parties du corps. → Corrigé : tête, bras, jambe, pied, main.',
          'Cite 5 aliments. → Corrigé : riz, légumes, poisson, mangue, banane.',
          'Cite 5 animaux de Madagascar. → Corrigé : lémurien, caméléon, fossa, aye-aye, coua.',
          'Cite 5 mots sur les transports. → Corrigé : voiture, bateau, avion, vélo, taxi-brousse.',
          'Cite 5 mots sur la nature. → Corrigé : arbre, fleur, eau, forêt, graine.',
          '',
          '══ RÉVISION GRAPHISME ══',
          'Trace : O, C, G, Q, I, L, T, H, J, U, V, B, P, D, E, F, N, M, g, q, y, A, X, Z, R, S, K, W. → Corrigé : évaluation.',
          'Quel graphisme trouves-tu le plus difficile ? → Corrigé : réponse personnelle.',
          '',
          '══ RÉVISION NUMÉRATION ══',
          'Compte de 1 à 70. → Corrigé : performance orale.',
          'Compte par 10 jusqu\'à 70. → Corrigé : 10, 20, 30, 40, 50, 60, 70.',
          'Compte par 2 jusqu\'à 20. → Corrigé : 2, 4, 6, 8, 10, 12, 14, 16, 18, 20.',
          'Compte par 5 jusqu\'à 50. → Corrigé : 5, 10, 15, 20, 25, 30, 35, 40, 45, 50.',
          'Ordonne : 55, 12, 3, 68, 40. → Corrigé : 3, 12, 40, 55, 68.',
          '',
          '══ RÉVISION CALCUL ══',
          '9+8=___. → Corrigé : 17.',
          '20−13=___. → Corrigé : 7.',
          'La moitié de 18 = ___. → Corrigé : 9.',
          '4 groupes de 3 = ___. → Corrigé : 12.',
          'Partage 15 en 3. Chaque groupe = ___. → Corrigé : 5.',
          'Problème : 100 Ar − 40 Ar = ___ Ar. → Corrigé : 60 Ar.',
          '',
          '══ RÉVISION CHANT ══',
          'Chante "Tête, épaules, genoux et pieds". → Corrigé : performance.',
          'Chante "Bonne fête maman". → Corrigé : performance.',
          'Chante "Il pleut, il pleut, bergère". → Corrigé : performance.',
          '',
          '══ RÉVISION RÉCITATION ══',
          'Récite "Promenons-nous dans les bois". → Corrigé : performance.',
          'Récite "Ma petite maman". → Corrigé : performance.',
          'Récite "Je suis un géant". → Corrigé : performance.',
          '',
          '══ RÉVISION ANGLAIS ══',
          'Count from 1 to 20. → Corrigé : performance.',
          'Say 5 colors in English. → Corrigé : red, blue, green, yellow, white.',
          'How do you say "mère" ? → Corrigé : mother.',
          'How do you say "arbre" ? → Corrigé : tree.',
          'Happy Mother\'s Day ! → Corrigé : repetition.',
        ]
      ),
    ]
  },

  {
    n:2, dates:'08/06/2026 – 12/06/2026',
    theme:'EXAMENS FIN D\'ANNÉE — Épreuves écrites + orales',
    matieres:[
      m('EXAMENS','Examens fin d\'année — Épreuves écrites 12ème',
        'Épreuves écrites de fin d\'année pour la 12ème. Format adapté aux 5 ans : graphisme, numération, calcul, dessin. Épreuves orales en fin de semaine.',
        ['Lundi 08/06 : Épreuve de Numération + Graphisme',
         'Mardi 09/06 : Épreuve de Calcul + Dessin',
         'Mercredi 10/06 : Épreuve de Langage oral + Hygiène',
         'Jeudi 11/06 : Épreuve de Chant + Récitation',
         'Vendredi 12/06 : Épreuve d\'Anglais + Activités libres'],
        [
          '══ ÉPREUVE NUMÉRATION ══',
          'Compte de 1 à 70. → Corrigé : performance orale.',
          'Quel nombre vient après 65 ? → Corrigé : 66.',
          'Compte par 10 jusqu\'à 70. → Corrigé : 10, 20, 30, 40, 50, 60, 70.',
          'Décompose 64 : ___ D + ___ U. → Corrigé : 6D + 4U.',
          'Montre 35 avec des bâtons. → Corrigé : dénombrement.',
          'Ordonne : 70, 28, 51, 9. → Corrigé : 9, 28, 51, 70.',
          'Quel est le plus grand : 66 ou 69 ? → Corrigé : 69.',
          '',
          '══ ÉPREUVE GRAPHISME ══',
          'Trace : A, E, I, O, U (les voyelles). → Corrigé : évaluation.',
          'Trace : B, C, D, F, G, H, K, L, M, N, P, Q, R, S, T, V, W, X, Z. → Corrigé : évaluation.',
          'Trace : 3 boucles, 3 spirales, 3 ponts. → Corrigé : évaluation.',
          '',
          '══ ÉPREUVE CALCUL ══',
          '6+8=___. → Corrigé : 14.',
          '9+9=___. → Corrigé : 18.',
          '20−11=___. → Corrigé : 9.',
          '18−9=___. → Corrigé : 9.',
          'La moitié de 16 = ___. → Corrigé : 8.',
          '3 groupes de 5 = ___. → Corrigé : 15.',
          'Partage 20 en 4 groupes égaux. → Corrigé : 5.',
          'Problème : j\'ai 100 Ar. Un fruit coûte 30 Ar. Combien après l\'achat ? → Corrigé : 70 Ar.',
          '',
          '══ ÉPREUVE DESSIN ══',
          'Dessine un bonhomme complet avec tête, corps, bras, jambes. → Corrigé : production.',
          'Dessine ta maison. → Corrigé : production.',
          'Dessine une fleur. → Corrigé : production.',
          '',
          '══ ÉPREUVE LANGAGE (oral) ══',
          'Cite 10 parties du corps. → Corrigé : tête, cou, épaules, bras, coude, main, ventre, jambe, genou, pied.',
          'Cite 5 animaux de Madagascar. → Corrigé : lémurien, caméléon, fossa, aye-aye, coua.',
          'Cite les 7 couleurs de l\'arc-en-ciel. → Corrigé : rouge, orange, jaune, vert, bleu, indigo, violet.',
          'Cite 5 moyens de transport. → Corrigé : voiture, bateau, avion, vélo, taxi-brousse.',
          'Fais une phrase avec "eau". → Corrigé : production.',
          'Fais une phrase avec "famille". → Corrigé : production.',
          '',
          '══ ÉPREUVE HYGIÈNE (oral) ══',
          'Montre les 6 étapes du lavage des mains. → Corrigé : performance.',
          'Cite 3 bonnes habitudes d\'hygiène. → Corrigé : se laver les dents, les mains, boire de l\'eau propre.',
          'Pourquoi l\'hygiène est-elle importante ? → Corrigé : pour ne pas tomber malade.',
          '',
          '══ ÉPREUVE CHANT ══',
          'Chante "Tête, épaules, genoux et pieds" avec les gestes. → Corrigé : performance.',
          'Chante "Il pleut, il pleut, bergère". → Corrigé : performance.',
          'Chante "Bonne fête maman". → Corrigé : performance.',
          '',
          '══ ÉPREUVE RÉCITATION ══',
          'Récite "Promenons-nous dans les bois" en entier. → Corrigé : performance.',
          'Récite "Ma petite maman" en entier. → Corrigé : performance.',
          'Récite "Je suis un géant" avec les gestes. → Corrigé : performance.',
          '',
          '══ ÉPREUVE ANGLAIS ══',
          'Count from 1 to 20 in English. → Corrigé : performance.',
          'Say the 7 colors in English. → Corrigé : red, orange, yellow, green, blue, indigo, purple.',
          'Touch your head. Touch your nose. Touch your knees. → Corrigé : gestes.',
          'How do you say "maman" ? → Corrigé : mother.',
          'How do you say "eau" ? → Corrigé : water.',
          'What is 5 + 3 in English ? → Corrigé : eight.',
        ]
      ),
    ]
  },

  {
    n:3, dates:'15/06/2026 – 19/06/2026',
    theme:'Délibérations + Activités de fin d\'année',
    matieres:[
      m('BILAN','Délibérations + Activités de fin d\'année — 12ème',
        'Semaine de délibérations et d\'activités de fin d\'année. Correction des examens. Préparation de la remise des bulletins.',
        ['Lundi 15/06 : correction des examens écrits + notes',
         'Mardi 16/06 : délibération des enseignants',
         'Mercredi 17/06 : activités libres — jeux, chants, dessin libre',
         'Jeudi 18/06 : préparation des bulletins + rangement de la classe',
         'Vendredi 19/06 : répétition représentation de fin d\'année'],
        [
          'Activité libre : dessin "Ce que j\'ai appris cette année" → Corrigé : production.',
          'Activité libre : chanter toutes les chansons de l\'année.',
          'Activité libre : jeu de rôle — faire le marché, jouer au train.',
          'Activité libre : raconter son conte préféré de l\'année.',
          'Préparation : choisir 1 comptine et 1 chanson pour la représentation finale.',
          'Bilan oral : "Quelle est la chose dont tu es le plus fier cette année ?"',
          'Bilan oral : "Quel est ton meilleur souvenir de l\'année ?"',
          'Dessiner un souvenir de l\'année. → Corrigé : production.',
          'Chanter "Bonne fête maman" une dernière fois. → Corrigé : performance.',
          'Réciter "Ma petite maman" une dernière fois. → Corrigé : performance.',
        ]
      ),
    ]
  },

  {
    n:4, dates:'22/06/2026 – 26/06/2026',
    theme:'Résultats + Remise des bulletins + Fête Nationale 26 juin',
    matieres:[
      m('FIN D\'ANNÉE','Résultats + Remise des bulletins + Fête Nationale 26 juin',
        'Semaine de fin d\'année officielle. Remise des bulletins. Représentation devant les parents. Célébration de la Fête Nationale le 26 juin.',
        ['Lundi 22/06 : dernière répétition représentation finale',
         'Mardi 23/06 : Remise des bulletins aux parents + représentation finale',
         'Mercredi 24/06 : bilan de l\'année + activités libres',
         'Jeudi 25/06 : préparation du 26 juin (Fête Nationale)',
         'Vendredi 26/06 : FÊTE NATIONALE DE MADAGASCAR — Célébration à l\'école'],
        [
          '══ REPRÉSENTATION FINALE ══',
          'Chanter "Tête, épaules, genoux et pieds" avec gestes (devant les parents).',
          'Chanter "Bonne fête maman" (dédiée aux mamans présentes).',
          'Réciter "Promenons-nous dans les bois" en chœur.',
          'Réciter "Ma petite maman" chacun son tour.',
          'Présenter le dessin de l\'abeille / le mobile de l\'arc-en-ciel / la ruche.',
          'Dire "Merci" à l\'enseignant(e) en chœur.',
          '',
          '══ BILAN DE L\'ANNÉE ══',
          'Ce que j\'ai appris : compter jusqu\'à 70.',
          'Ce que j\'ai appris : 26 lettres de l\'alphabet (graphisme).',
          'Ce que j\'ai appris : les bonnes habitudes d\'hygiène.',
          'Ce que j\'ai appris : des mots en anglais.',
          'Ce que j\'ai appris : des chansons et des comptines.',
          'Ce que j\'ai appris : les animaux endémiques de Madagascar.',
          'Ce que j\'ai appris : les couleurs de l\'arc-en-ciel.',
          'Ce que j\'ai appris : les opérations (addition, soustraction, moitié, partage).',
          '',
          '══ FÊTE NATIONALE 26 JUIN ══',
          'Qu\'est-ce que le 26 juin ? → Corrigé : la Fête de l\'Indépendance de Madagascar (1960).',
          'Quelle est la couleur du drapeau malgache ? → Corrigé : rouge, blanc, vert.',
          'Chanter l\'hymne national "Ry Tanindrazanay malala ô". → Corrigé : performance.',
          'Pourquoi fête-t-on le 26 juin ? → Corrigé : parce que Madagascar a retrouvé son indépendance ce jour-là.',
          'Citer 1 chose dont tu es fier(ère) à Madagascar. → Corrigé : réponse personnelle.',
          '',
          '══ AU REVOIR & PROJETS POUR L\'ANNÉE SUIVANTE ══',
          'L\'année prochaine tu seras en 11ème ! Qu\'as-tu envie d\'apprendre ?',
          'Dessine ce que tu veux apprendre en 11ème. → Corrigé : production.',
          'Qu\'est-ce que tu aimes le plus à l\'école ? → Corrigé : réponse personnelle.',
          'Quel est ton meilleur ami à l\'école ? → Corrigé : réponse personnelle.',
          'Au revoir et bonnes vacances ! "À l\'année prochaine !"',
        ]
      ),
    ]
  },

];

module.exports = { JUIN_12EME };
