'use strict';

// Programme 12ème (Maternelle) — année scolaire 2025-2026
// Matières : LECTURE · VAKITENY · ÉCRITURE · LANGAGE · PRE-MATH · MATHS
//            MORALE · ENVIRONNEMENT · ANGLAIS · CHANT · RECITATION · EPS · DESSIN

const m = (matiere, topic, approche, transmission, exercices) =>
  ({ matiere, topic, approche, transmission, exercices });

const PERIODES_12EME = [
  { num: 1, libelle: '1ère Période', debut: '01/09/2025', semaines: [
// ── 12ème S1 : Semaine d'accueil ─────────────────────────────────────────────
{
  n: 1, dateDebut: "2025/09/01",
  theme: "12ème Maternelle — Semaine d'accueil et prise de contact",
  sous: "Accueil, découverte de la classe et de l'enseignante, activités libres",
  matieres: [
    m("LECTURE","Prise de contact — Écouter et reconnaître des sons simples",
      "Éveiller la conscience phonologique des tout-petits par l'écoute et la répétition de sons.",
      ["Accueillir chaque enfant individuellement avec un sourire","Faire le tour de la classe ensemble : les coins, le tableau, les tables","Montrer des images d'objets simples et nommer","Faire répéter les mots : mama, papa, rano, vary","Écouter des sons de la nature : oiseaux, pluie","Jeu d'imitation des sons animaux","Récapitulatif : 3 mots appris aujourd'hui"],
      ["Répète ce mot : mama → Corrigé : mama","Que vois-tu sur cette image ? → Corrigé : réponse libre selon l'image","Quel son fait le poulet ? → Corrigé : cocorico / akoko"]),
    m("VAKITENY","Prise de contact — Écouter et répéter des mots",
      "Initier l'écoute active et la répétition de mots simples en malagasy.",
      ["Chanter une comptine malagasy simple","Répéter des mots en malagasy : rano, sakafo, akoho","Pointer des images correspondantes","Faire répéter individuellement","Jeu : 'Montre-moi le...' — les enfants pointent","Comptine des animaux de la ferme","Valoriser chaque participation"],
      ["Répète : rano → Corrigé : rano","Montre-moi l'image de l'akoho (poulet) → Corrigé : pointer l'image","Que mange l'akoho ? → Corrigé : du maïs / ny katsaka"]),
    m("ÉCRITURE","Prise de contact — Tenir un crayon et tracer des lignes libres",
      "Observer la tenue du crayon et permettre aux enfants de tracer librement.",
      ["Distribuer les gros crayons de couleur","Montrer comment tenir le crayon","Tracer librement sur la feuille","Observer et corriger doucement la prise en main","Encourager chaque enfant","Ne pas forcer des formes précises","Regarder et commenter les tracés"],
      ["Montre comment tu tiens ton crayon → Corrigé : observation individuelle","Trace une ligne du haut vers le bas → Corrigé : vérifier le tracé","Quel crayon préfères-tu ? → Corrigé : réponse libre"]),
    m("LANGAGE","Se présenter : dire son prénom",
      "Apprendre à dire son prénom et à comprendre l'importance de s'identifier.",
      ["L'enseignante se présente : 'Je m'appelle Madame...'","Demander à chaque enfant : 'Comment tu t'appelles ?'","Aider les enfants timides","Jeu du ballon : celui qui l'attrape dit son prénom","Apprendre le prénom de 2 voisins","Faire l'appel : les enfants répondent 'Présent(e)'","Récapitulatif : l'enseignante répète tous les prénoms"],
      ["Comment tu t'appelles ? → Corrigé : Je m'appelle ...","Quel est le prénom de ton voisin ? → Corrigé : réponse individuelle","Réponds quand j'appelle ton prénom → Corrigé : évaluation de la réactivité"]),
    m("PRE-MATH","Test de pré-requis : notions de base (grand/petit, plein/vide)",
      "Évaluer les notions pré-mathématiques de base que les enfants ont acquises avant l'école.",
      ["Montrer deux objets de taille différente : grand/petit","Les enfants pointent le grand, puis le petit","Montrer un verre plein et un verre vide","Les enfants désignent plein et vide","Comparer 2 groupes d'objets : lequel a plus ?","Observer les réactions et les stratégies","Préparer les activités de la période"],
      ["Lequel est grand ? (montrer deux objets) → Corrigé : le plus grand objet","Lequel est vide ? (montrer deux verres) → Corrigé : verre sans eau","Y a-t-il plus de billes ici ou là ? → Corrigé : réponse selon les quantités montrées"]),
    m("MATHS","Test de pré-requis : compter les doigts de 1 à 5",
      "Évaluer la capacité à compter et à représenter les chiffres de 1 à 5.",
      ["Montrer 1 doigt et dire 'un'","Montrer 2 doigts et dire 'deux'","Continuer jusqu'à 5 doigts","Demander aux enfants de montrer le bon nombre de doigts","Compter des objets concrets sur la table","Qui sait compter au-delà de 5 ?","Préparer les groupes de niveau"],
      ["Montre 3 doigts → Corrigé : évaluation gestuelle","Compte ces crayons (en donner 4) → Corrigé : 4","Quel chiffre vient après 3 ? → Corrigé : 4"]),
    m("MORALE","Découverte des règles de la classe maternelle",
      "Présenter de façon ludique les règles essentielles de la vie en classe maternelle.",
      ["Accueillir avec un grand sourire","Présenter la règle 1 : on ne crie pas, on parle doucement","Règle 2 : on partage les jouets et les crayons","Règle 3 : on range après avoir joué","Mimer chaque règle avec les enfants","Dessiner le symbole de chaque règle","Afficher les règles avec des images"],
      ["Comment parle-t-on en classe ? → Corrigé : doucement, sans crier","Que fait-on après avoir joué ? → Corrigé : on range les jouets","Comment partage-t-on les crayons ? → Corrigé : chacun utilise à son tour"]),
    m("ENVIRONNEMENT","Découverte de l'école : la classe, la cour, les toilettes",
      "Explorer l'environnement scolaire et identifier les différents espaces.",
      ["Visite guidée de la classe avec l'enseignante","Découvrir la cour : où joue-t-on ?","Trouver les toilettes : où sont-elles ?","Identifier la cantine ou le coin repas","Nommer chaque espace en malagasy et en français","Jeu : 'Où est-on ?' — deviner l'espace","Récapitulatif : les 3 espaces importants"],
      ["Où est-ce qu'on joue ? → Corrigé : dans la cour","Où sont les toilettes ? → Corrigé : indiquer la direction","Que fait-on dans la classe ? → Corrigé : on apprend, on dessine, on chante"]),
    m("ANGLAIS","Hello — Découverte de la salutation en anglais",
      "Initier les tout-petits à la salutation en anglais de manière ludique.",
      ["Saluer les enfants en anglais : Hello !","Faire répéter : Hello !","Chanter : 'Hello, hello, how are you?'","Goodbye : dire au revoir en anglais","Jeu : l'enseignante dit Hello à chaque enfant","Répondre : Hello ! Je m'appelle...","Récapitulatif : 2 mots appris"],
      ["Répète : Hello → Corrigé : Hello","Comment dit-on 'au revoir' en anglais ? → Corrigé : Goodbye","Chante la chanson Hello → Corrigé : évaluation orale"]),
    m("CHANT","Bonjour / Good morning — Découverte de la chanson",
      "Apprendre une chanson bilingue simple de salutation pour la rentrée maternelle.",
      ["Chanter la chanson lentement une fois","Répéter 'Bonjour' et 'Good morning'","Ajouter des gestes : saluer de la main","Répéter ensemble","Chanter plus vite la deuxième fois","Jeu : se saluer en chantant par deux","Qui peut chanter seul ?"],
      ["Chante 'Bonjour' dans la chanson → Corrigé : évaluation orale","Que dit-on le matin en anglais ? → Corrigé : Good morning","Quel geste fait-on en chantant 'Bonjour' ? → Corrigé : on salue de la main"]),
    m("RECITATION","La rentrée — Écouter et répéter le poème",
      "Initier les enfants à la mémorisation par l'écoute et la répétition collective.",
      ["Réciter le poème 'La rentrée' lentement et avec expression","Demander aux enfants d'écouter en silence","Répéter la première ligne en chœur","Faire répéter un enfant seul","Reprendre la première ligne collectivement","Ajouter la deuxième ligne","Chanter / réciter avec enthousiasme"],
      ["Répète la première ligne du poème → Corrigé : évaluation orale","De quoi parle le poème ? → Corrigé : de la rentrée à l'école","Qui peut réciter une partie seul ? → Corrigé : évaluation volontaire"]),
    m("EPS","Découverte du corps : bouger librement dans la cour",
      "Permettre aux enfants d'explorer librement l'espace et de bouger leur corps.",
      ["Aller dans la cour en tenant la main d'un camarade","Courir librement en sécurité","S'arrêter sur signal (claquement de mains)","Sauter sur place","Se regrouper en cercle","Jeu du 'chat' simple : toucher sans tomber","Retour au calme : respirer lentement"],
      ["Peux-tu courir jusqu'au mur et revenir ? → Corrigé : évaluation physique","Saute 3 fois sur place → Corrigé : évaluation physique","Que fait-on quand on entend le signal ? → Corrigé : on s'arrête"]),
    m("DESSIN","Dessin libre : découverte des crayons de couleur",
      "Permettre une première exploration libre des crayons de couleur sans contrainte.",
      ["Distribuer les feuilles et les crayons de couleur","Montrer comment tenir le crayon","Dessiner ce qu'on veut librement","Encourager sans corriger le contenu","Commenter les tracés avec bienveillance","Écrire le prénom de l'enfant sur sa feuille","Afficher tous les dessins dans la classe"],
      ["Qu'est-ce que tu as dessiné ? → Corrigé : réponse libre","Combien de couleurs tu as utilisées ? → Corrigé : réponse libre","Peux-tu me montrer le crayon rouge ? → Corrigé : pointer le crayon rouge"]),
    m("TRAVAUX MANUELS","Découverte des matériaux : papier, crayons, colle",
      "Faire toucher et explorer différents matériaux pour développer la motricité fine.",
      ["Distribuer différents matériaux : papier doux, carton, tissu","Toucher et décrire : mou, dur, lisse, rugueux","Déchirer du papier librement","Froisser du papier en boule","Coller une boule de papier sur une feuille","Ranger les matériaux dans les boîtes","Récapitulatif : 3 matériaux et leur texture"],
      ["Comment est ce papier ? (doux ou dur) → Corrigé : doux","Fais une boule avec ce papier → Corrigé : évaluation gestuelle","Où colle-t-on la boule de papier ? → Corrigé : sur la feuille avec de la colle"]),
  ],
},

// ── 12ème S2 : Lettre i · Nombres 0-5 · Fournitures scolaires ────────────────
{
  n: 2, dateDebut: "2025/09/08",
  theme: "12ème Maternelle — Lettre i · Nombres 0-5 · Fournitures scolaires",
  sous: "Lettre i · Compter jusqu'à 5 · Se présenter · Politesse en classe",
  matieres: [
    m("LECTURE","La lettre i : reconnaissance visuelle et sonore",
      "Faire découvrir la lettre i aux tout-petits par des activités sensorielles et ludiques.",
      ["Montrer la lettre I en grande taille sur un carton","Prononcer le son [i] de façon exagérée","Chercher des images avec le son [i] : île, igloo, iris","Tracer la lettre i dans l'air avec le doigt","Tracer i sur le tableau avec le doigt","Retrouver la lettre i dans son prénom","Jeu : qui peut dire un mot avec [i] ?"],
      ["Quel son fait cette lettre ? (montrer i) → Corrigé : [i]","Montre-moi la lettre i dans le mot 'île' → Corrigé : pointer le i","Cite un mot avec le son [i] → Corrigé : île, iris, igloo"]),
    m("VAKITENY","Lettre i : écouter et répéter des mots contenant i",
      "Renforcer la conscience phonologique du son [i] par des jeux de répétition.",
      ["Comptine : 'I comme île, i comme igloo'","Répéter des mots en malagasy avec [i] : iny, izy, ira","Jeu : 'Claque si tu entends [i]'","Claper les mains sur le son [i] dans une suite de mots","Comptine des voyelles : A, E, I, O, U","Mimer des mots avec le son [i]","Récapitulatif : 5 mots avec [i]"],
      ["Frappe dans tes mains si tu entends [i] : maison, île, table → Corrigé : île","Lis cette syllabe : i → Corrigé : [i]","Nomme un mot malagasy avec [i] → Corrigé : izy, iny"]),
    m("ÉCRITURE","Lettre i : tracer la lettre i en maternelle",
      "Apprendre à tracer la lettre i (bâton + point) en développant la motricité fine.",
      ["Montrer le tracé de i : un bâton vertical et un point","Tracer dans l'air avec le gros doigt","Tracer sur le dos d'un camarade","Tracer sur l'ardoise avec une grosse craie","Tracer sur papier préligné avec un gros crayon","Compter le nombre de i tracés","Valoriser chaque effort"],
      ["Trace la lettre i sur ton ardoise → Corrigé : vérifier le tracé","Combien d'éléments a la lettre i ? → Corrigé : 2 (un bâton et un point)","Qui peut tracer 3 fois la lettre i ? → Corrigé : évaluation gestuelle"]),
    m("LANGAGE","Se présenter : mon nom et le nom de la maîtresse",
      "Apprendre à dire son prénom complet et à nommer sa maîtresse.",
      ["Rappel : se présenter (prénom)","Ajouter le nom de famille : 'Je m'appelle Prénom Nom'","Présenter la maîtresse : 'Ma maîtresse s'appelle Madame...'","Jeu du ballon : 'Je m'appelle... et ma maîtresse s'appelle...'","Dessiner un portrait de la maîtresse","Écrire son prénom sur son dessin","Récapitulatif : son nom et le nom de la maîtresse"],
      ["Comment tu t'appelles (prénom et nom) ? → Corrigé : réponse individuelle","Comment s'appelle ta maîtresse ? → Corrigé : Madame ...","Dessine ta maîtresse → Corrigé : évaluation libre"]),
    m("PRE-MATH","Plein et vide : comparer des contenants",
      "Comprendre les notions plein et vide par manipulation concrète de contenants.",
      ["Montrer un verre plein d'eau et un verre vide","Nommer : plein — vide","Verser l'eau d'un verre à l'autre : plein devient vide","Montrer différents contenants (bouteille, bol, assiette)","Les enfants désignent le contenant plein ou vide","Jeu : remplir les contenants avec du sable ou de l'eau","Récapitulatif : plein / vide"],
      ["Lequel est plein ? (montrer deux verres) → Corrigé : le verre avec de l'eau","Que se passe-t-il quand on verse l'eau ? → Corrigé : le premier devient vide, le deuxième est plein","Remplis ce bol avec du sable → Corrigé : évaluation gestuelle"]),
    m("MATHS","Les nombres de 0 à 5 : compter et représenter",
      "Construire la suite numérique de 0 à 5 avec des objets concrets et des doigts.",
      ["Compter de 0 à 5 avec les doigts","Montrer 0 : aucun objet sur la table","Montrer 1, 2, 3, 4, 5 avec des objets","Associer le chiffre et la quantité","Chanter la comptine des chiffres 0-5","Exercice : mettre le bon nombre d'objets","Récapitulatif : les 6 chiffres 0 à 5"],
      ["Montre 4 doigts → Corrigé : évaluation gestuelle","Combien d'objets y a-t-il ? (en poser 3) → Corrigé : 3","Quel chiffre vient après 2 ? → Corrigé : 3"]),
    m("MORALE","Politesse en classe : dire bonjour et merci",
      "Ancrer les formules de politesse de base par des jeux de rôle simples.",
      ["Montrer comment dire bonjour le matin en entrant","Dire merci quand on reçoit quelque chose","Dire s'il vous plaît pour demander","Jeu de rôle : entrer en classe et saluer la maîtresse","Jeu de rôle : recevoir un crayon et dire merci","Afficher les mots de politesse avec des images","Récapitulatif : 3 mots magiques"],
      ["Que dit-on quand on entre en classe ? → Corrigé : Bonjour Madame","Que dit-on quand on reçoit un cadeau ? → Corrigé : Merci","Comment demande-t-on quelque chose ? → Corrigé : S'il vous plaît"]),
    m("ENVIRONNEMENT","Les fournitures scolaires : crayon, cahier, sac",
      "Identifier et nommer les fournitures scolaires essentielles de la maternelle.",
      ["Sortir les objets du sac : crayon, cahier, trousse","Nommer chaque objet en français et malagasy","À quoi sert chaque objet ?","Jeu de Kim : cacher un objet et deviner lequel manque","Ranger les objets dans la trousse puis dans le sac","Colorier une image de fournitures scolaires","Récapitulatif : 5 fournitures nommées"],
      ["Comment s'appelle cet objet ? (montrer un crayon) → Corrigé : un crayon / penisily","À quoi sert un cahier ? → Corrigé : à écrire et à dessiner","Où range-t-on ses affaires ? → Corrigé : dans le sac / la trousse"]),
    m("ANGLAIS","Greeting et Introducing : Hello, What is your name?",
      "Apprendre les expressions de salutation et de présentation en anglais.",
      ["Révision : Hello, Goodbye","Nouveau : What is your name? — My name is...","Modèle en chaîne : chaque enfant se présente en anglais","How are you? — I'm fine / I'm happy","Jeu de marionnettes : la marionnette salue les enfants","Chanson : Hello song","Récapitulatif : 4 expressions en anglais"],
      ["What is your name? → Corrigé : My name is ...","How are you? → Corrigé : I'm fine, thank you","Say hello to your friend → Corrigé : Hello !"]),
    m("CHANT","Bonjour / Good morning — Mémoriser la chanson",
      "Mémoriser la chanson bilingue 'Bonjour / Good morning' avec les gestes.",
      ["Révision de la semaine passée","Chanter ensemble avec les gestes","Chanter par groupes : les filles, puis les garçons","Ajouter de l'expression : fort, doux, lent, rapide","Jeu : chanter en ronde","Évaluation : qui peut chanter seul ?","Récapitulatif : la chanson avec les gestes"],
      ["Chante 'Bonjour / Good morning' → Corrigé : évaluation orale","Quel geste fait-on pour 'Bonjour' ? → Corrigé : évaluation gestuelle","Que dit-on le matin dans la chanson ? → Corrigé : Bonjour / Good morning"]),
    m("RECITATION","La rentrée — Mémoriser le début du poème",
      "Mémoriser les 2 premières lignes du poème 'La rentrée' par répétition collective.",
      ["Rappel : écouter le poème entier","Répéter la ligne 1 en chœur (5 fois)","Répéter la ligne 2 en chœur (5 fois)","Enchaîner les 2 lignes","Réciter avec des gestes","Réciter individuellement (volontaires)","Afficher le poème illustré dans la classe"],
      ["Récite la première ligne → Corrigé : évaluation orale","Combien de lignes connais-tu maintenant ? → Corrigé : 2 lignes","Récite les 2 premières lignes → Corrigé : évaluation orale"]),
    m("EPS","Mouvements corporels : en haut / en bas",
      "Apprendre et expérimenter les notions 'en haut' et 'en bas' par des mouvements du corps.",
      ["Lever les bras en haut : 'en haut !'","Baisser les bras en bas : 'en bas !'","Sauter en levant les bras","Accroupir les bras en bas","Jeu : 'Simon dit — en haut !' ou 'en bas !'","Pointer en haut (le plafond) et en bas (le sol)","Répéter vite, puis lentement"],
      ["Lève les bras en haut → Corrigé : évaluation gestuelle","Montre-moi 'en bas' → Corrigé : baisser les bras ou se baisser","Que fait-on quand on dit 'en haut' ? → Corrigé : on lève les bras"]),
    m("DESSIN","Dessiner une fourniture scolaire",
      "Dessiner un objet scolaire simple (crayon, livre) en suivant un modèle.",
      ["Montrer l'objet réel et une image simple","Observer les formes : rectangle (livre), long triangle (crayon)","Tracer le contour de l'objet étape par étape","Ajouter les détails","Colorier avec les bonnes couleurs","Écrire le nom de l'objet avec l'aide de la maîtresse","Exposer les dessins"],
      ["Qu'as-tu dessiné ? → Corrigé : un crayon / un livre","De quelle couleur est ton crayon dessiné ? → Corrigé : réponse libre","Montre la forme de base de ton dessin → Corrigé : rectangle ou ligne longue"]),
    m("TRAVAUX MANUELS","Découpage libre avec les ciseaux",
      "Initier les enfants à l'utilisation des ciseaux en toute sécurité par du découpage libre.",
      ["Présenter les ciseaux à bouts ronds","Règle de sécurité : on ne court pas avec des ciseaux","Montrer comment tenir les ciseaux (4 doigts dans le grand trou, pouce dans le petit)","Pratiquer l'ouverture et la fermeture","Découper librement du papier journal","Ne jamais pointer les ciseaux vers quelqu'un","Ranger les ciseaux après usage"],
      ["Comment tient-on les ciseaux ? → Corrigé : 4 doigts et le pouce dans les trous","Que ne faut-il jamais faire avec des ciseaux ? → Corrigé : courir avec, les pointer vers quelqu'un","Où range-t-on les ciseaux ? → Corrigé : dans la boîte, pointe vers le bas"]),
  ],
},

// ── 12ème S3 : Lettre a · Nombres 5-10 · Quantité ────────────────────────────
{
  n: 3, dateDebut: "2025/09/15",
  theme: "12ème Maternelle — Lettre a · Nombres 5-10 · Quantité",
  sous: "Lettre a · Compter de 5 à 10 · Peu/beaucoup/rien · Discipline en classe",
  matieres: [
    m("LECTURE","La lettre a : reconnaissance visuelle et sonore",
      "Faire découvrir la lettre a par des activités sensorielles et ludiques adaptées aux tout-petits.",
      ["Montrer la lettre A en grande taille sur un carton","Prononcer le son [a] de façon exagérée : 'aaaaa'","Chercher des images avec le son [a] : arbre, âne, ampoule","Tracer la lettre a dans l'air avec le doigt","Retrouver la lettre a dans son prénom","Comptine : 'A comme arbre, a comme âne'","Jeu : qui peut dire un mot avec [a] ?"],
      ["Quel son fait la lettre a ? → Corrigé : [a]","Montre la lettre a dans le mot 'arbre' → Corrigé : pointer le a","Cite un mot avec le son [a] → Corrigé : arbre, âne, avion"]),
    m("VAKITENY","Lettre a : écouter et répéter des mots contenant a",
      "Renforcer la conscience phonologique du son [a] par des jeux de répétition.",
      ["Comptine : 'A comme ala (forêt), a comme akoho'","Répéter des mots malagasy avec [a] : ala, akoho, anana","Jeu : clapper sur le son [a]","Claper les mains sur le [a] dans : arbre, bois, âne, table","Répertorier les mots avec [a]","Mimer des mots avec le son [a]","Récapitulatif : 5 mots avec [a]"],
      ["Frappe si tu entends [a] : ala, sekoly, ana → Corrigé : ala et ana","Nomme un mot malagasy avec [a] → Corrigé : ala, akoho, anana","Répète : ala → Corrigé : ala"]),
    m("ÉCRITURE","Lettre a : tracer la lettre a en maternelle",
      "Apprendre à tracer la lettre a en suivant le modèle pas à pas.",
      ["Montrer le tracé de a : un rond et un bâton à droite","Tracer dans l'air avec le gros doigt","Tracer sur le dos d'un camarade","Tracer sur l'ardoise avec la grosse craie","Tracer sur papier préligné avec un gros crayon","Compter le nombre de a tracés","Valoriser les progrès et féliciter"],
      ["Trace la lettre a sur ton ardoise → Corrigé : vérifier le tracé","Combien d'éléments a la lettre a ? → Corrigé : un rond et un bâton","Trace 3 fois la lettre a → Corrigé : évaluation gestuelle"]),
    m("LANGAGE","Se présenter : âge, classe et lieu d'habitation",
      "Enrichir la présentation personnelle en ajoutant l'âge, la classe et le quartier.",
      ["Rappel de la semaine : prénom et nom de la maîtresse","Ajouter : 'J'ai ... ans'","Ajouter : 'J'habite à ...'","Modèle complet : 'Je m'appelle..., j'ai ... ans, j'habite à ...'","Jeu en cercle : chacun dit son modèle","Deviner qui parle selon les descriptions","Récapitulatif : les 4 informations de la présentation"],
      ["Quel âge as-tu ? → Corrigé : J'ai ... ans","Où habites-tu ? → Corrigé : J'habite à ...","Dis ta présentation complète → Corrigé : évaluation orale"]),
    m("PRE-MATH","Quantité : peu, beaucoup, rien",
      "Comprendre et utiliser le vocabulaire de la quantité relative : peu, beaucoup, rien.",
      ["Montrer une assiette vide : 'il n'y a rien'","Mettre 2 raisins : 'il y en a peu'","Remplir l'assiette : 'il y en a beaucoup'","Comparer deux groupes : peu vs beaucoup","Exercice : trier les images (peu/beaucoup/rien)","Jeu : remplir un bol avec peu ou beaucoup de sable","Récapitulatif : les 3 termes"],
      ["Montre un groupe de 'beaucoup' → Corrigé : pointer le groupe le plus grand","Y a-t-il peu ou beaucoup d'élèves dans la classe ? → Corrigé : réponse selon la classe","Remplis le bol avec peu de sable → Corrigé : évaluation gestuelle"]),
    m("MATHS","Les nombres de 5 à 10 : compter et représenter",
      "Construire la suite numérique de 5 à 10 en continuant depuis les acquis de la semaine 2.",
      ["Rappel : compter de 0 à 5","Continuer : 6, 7, 8, 9, 10","Montrer 6 à 10 objets et compter","Comptine des chiffres 0 à 10","Associer les chiffres 6-10 aux quantités","Exercice : placer le bon nombre d'objets","Récapitulatif : la suite de 0 à 10"],
      ["Compte de 5 à 10 → Corrigé : 5, 6, 7, 8, 9, 10","Combien d'objets y a-t-il ? (en poser 7) → Corrigé : 7","Quel chiffre vient après 8 ? → Corrigé : 9"]),
    m("MORALE","Discipline en classe : lever la main, écouter",
      "Consolider les règles de discipline par des pratiques répétées et des récompenses.",
      ["Rappel : les règles de politesse","Règle de discipline : lever la main avant de parler","Pratiquer : poser une question avec la main levée","Règle : écouter quand la maîtresse parle","Jeu : 'Qui écoute bien ?' — observer et récompenser","Système de points positifs pour la bonne discipline","Récapitulatif : 2 règles clés"],
      ["Que fait-on avant de parler ? → Corrigé : on lève la main","Que fait-on quand la maîtresse parle ? → Corrigé : on l'écoute en silence","Pourquoi ces règles sont-elles importantes ? → Corrigé : pour que tout le monde apprenne bien"]),
    m("ENVIRONNEMENT","Les fournitures scolaires (suite) : règle, gomme, trousse",
      "Identifier de nouvelles fournitures scolaires et comprendre leur utilité.",
      ["Rappel des fournitures de la semaine passée","Présenter de nouvelles fournitures : règle, gomme, trousse","À quoi sert une gomme ? (effacer les erreurs)","À quoi sert une règle ? (tracer des lignes droites)","Jeu de Kim : quel objet a disparu ?","Ranger chaque objet à sa place","Récapitulatif : 8 fournitures connues"],
      ["À quoi sert une gomme ? → Corrigé : à effacer les erreurs","Qu'est-ce qu'une trousse ? → Corrigé : une pochette pour ranger les crayons et stylos","Nomme 3 fournitures dans ton sac → Corrigé : réponse libre"]),
    m("ANGLAIS","School things : les objets de la classe en anglais",
      "Apprendre le vocabulaire des objets scolaires en anglais avec des flashcards.",
      ["Révision : Hello, What is your name?","Nouveaux mots : book, pencil, eraser, ruler, bag","Montrer la flashcard, dire le mot, répéter","Jeu : 'What is this?' en pointant les objets","Phrase : 'I have a book.'","Exercice : dessiner l'objet nommé en anglais","Récapitulatif : 5 objets en anglais"],
      ["How do you say 'crayon' in English? → Corrigé : pencil","What is this? (montrer une gomme) → Corrigé : eraser","Point to the book → Corrigé : évaluation gestuelle"]),
    m("CHANT","Bonjour / Good morning — Consolidation avec expression",
      "Consolider la chanson avec des variations de vitesse et d'expression.",
      ["Chanter la chanson lentement","Chanter plus vite","Chanter très doucement","Chanter très fort","Chanter en rond en se tenant par la main","Solo : un enfant chante devant les autres","Récapitulatif : la chanson maîtrisée"],
      ["Chante la chanson doucement → Corrigé : évaluation orale","Chante la chanson très fort → Corrigé : évaluation orale","Qui peut chanter seul devant la classe ? → Corrigé : évaluation volontaire"]),
    m("RECITATION","La rentrée — Mémoriser la suite du poème",
      "Mémoriser les 2 lignes suivantes du poème 'La rentrée' par répétition collective.",
      ["Rappel et révision des 2 lignes de la semaine passée","Apprendre la ligne 3 en chœur","Apprendre la ligne 4 en chœur","Enchaîner les 4 lignes","Récitation avec des gestes expressifs","Récitation individuelle pour volontaires","Réciter le poème depuis le début jusqu'à la ligne 4"],
      ["Récite les 2 premières lignes → Corrigé : évaluation orale","Ajoute la 3ème ligne → Corrigé : évaluation orale","Récite le poème jusqu'à la ligne 4 → Corrigé : évaluation orale"]),
    m("EPS","Mouvements : assis / debout",
      "Apprendre à contrôler son corps en réponse aux instructions assis/debout.",
      ["Position de départ : debout","Sur signal : s'asseoir rapidement","Sur signal : se lever rapidement","Jeu : 'Simon dit — debout !' ou 'assis !'","Varier la vitesse : lent, rapide","Jeu collectif : assis si garçon, debout si fille","Récapitulatif : les deux positions"],
      ["Lève-toi ! → Corrigé : évaluation gestuelle","Assieds-toi ! → Corrigé : évaluation gestuelle","Que fait-on quand on entend 'debout' ? → Corrigé : on se lève"]),
    m("DESSIN","Dessiner une fourniture scolaire — suite",
      "Dessiner une deuxième fourniture scolaire (cahier ou trousse) en suivant les étapes.",
      ["Choisir l'objet à dessiner : cahier ou trousse","Observer les formes : rectangle","Tracer le contour à main levée","Ajouter les détails (lignes du cahier, fermeture de la trousse)","Colorier avec soin","Écrire le nom de l'objet","Comparer les deux dessins de la semaine"],
      ["Qu'est-ce que tu dessines cette semaine ? → Corrigé : un cahier ou une trousse","Quelle forme a un cahier ? → Corrigé : un rectangle","Écris le nom de l'objet → Corrigé : aide si besoin"]),
    m("TRAVAUX MANUELS","Modelage en pâte à modeler : faire une boule",
      "Développer la motricité fine en modelant des boules et des rouleaux de pâte à modeler.",
      ["Distribuer la pâte à modeler","Montrer comment rouler une boule entre les paumes","Les enfants font une grosse boule","Faire une petite boule","Faire un rouleau en frottant","Créer un animal simple avec les formes","Ranger la pâte dans les boîtes"],
      ["Comment fait-on une boule ? → Corrigé : on roule la pâte entre les mains","Fais une boule de la taille de ta paume → Corrigé : évaluation gestuelle","Que crées-tu avec tes boules ? → Corrigé : réponse libre"]),
  ],
},

// ── 12ème S4 : Lettre o · Nombres 0-10 · Le corps humain ────────────────────
{
  n: 4, dateDebut: "2025/09/22",
  theme: "12ème Maternelle — Lettre o · Nombres 0-10 · Le corps humain",
  sous: "Lettre o · Révision complète 0-10 · Corps humain · Hygiène du corps",
  matieres: [
    m("LECTURE","La lettre o : reconnaissance visuelle et sonore",
      "Faire découvrir la lettre o et consolider les voyelles apprises (a, i, o).",
      ["Montrer la lettre O en grande taille","Prononcer le son [o] : 'oooo'","Chercher des images avec [o] : orange, oiseau, omby","Révision : a, i, o — les 3 voyelles apprises","Comptine des voyelles A-I-O","Retrouver les 3 voyelles dans des mots","Récapitulatif : 3 voyelles maîtrisées"],
      ["Quel son fait la lettre o ? → Corrigé : [o]","Cite un mot avec [o] → Corrigé : orange, oiseau, eau","Montre les 3 voyelles apprises → Corrigé : a, i, o"]),
    m("VAKITENY","Lettre o : écouter et répéter des mots contenant o",
      "Renforcer la conscience phonologique du son [o] et réviser les sons [a] et [i].",
      ["Comptine : 'O comme omby (zébu), o comme orona'","Jeu : clapper sur le [o] dans une suite de mots","Révision : clapper sur [a], [i], [o] séparément","Jeu combiné : lever la main pour [a], taper les pieds pour [o]","Chanter une comptine avec les 3 voyelles","Trouver des mots malagasy avec chaque voyelle","Récapitulatif : sons [a], [i], [o]"],
      ["Frappe si tu entends [o] : omby, sekoly, orona → Corrigé : omby et orona","Quel son entends-tu dans 'ala' ? → Corrigé : [a]","Nomme un mot malagasy avec [o] → Corrigé : omby, orona, ony"]),
    m("ÉCRITURE","Lettre o : tracer la lettre o",
      "Apprendre à tracer la lettre o (un rond fermé) et consolider les lettres a et i.",
      ["Montrer le tracé de o : un rond bien fermé","Tracer dans l'air avec le doigt","Tracer sur l'ardoise","Tracer sur papier préligné","Révision rapide : tracer a, i, o","Exercice : écrire une ligne de a, une ligne de i, une ligne de o","Comparer les 3 lettres : formes et tracés"],
      ["Trace la lettre o sur ton ardoise → Corrigé : vérifier le tracé","Quelle lettre est faite d'un rond ? → Corrigé : o","Trace les 3 voyelles dans l'ordre → Corrigé : a, i, o"]),
    m("LANGAGE","Mon nom : le dire, l'écrire et l'épeler",
      "Identifier et épeler son prénom, première étape vers l'écriture autonome.",
      ["Chaque enfant dit son prénom et le compte (nombre de lettres)","Épeler son prénom : M-A-R-I-E","Reconnaître son prénom écrit sur une étiquette","Trier les étiquettes des prénoms : trouver le sien","Décorer son étiquette de prénom","Écrire les lettres de son prénom avec aide","Afficher les prénoms décorés"],
      ["Dis et épelle ton prénom → Corrigé : évaluation individuelle","Combien de lettres a ton prénom ? → Corrigé : compter ensemble","Trouve ton étiquette-prénom → Corrigé : évaluation individuelle"]),
    m("PRE-MATH","Grandeur : grand et petit",
      "Comparer des objets selon leur taille et utiliser le vocabulaire grand/petit.",
      ["Montrer deux objets de taille très différente","Nommer : grand et petit","Comparer des enfants : le plus grand, le plus petit de la classe","Classer des objets du plus petit au plus grand","Exercice : dessiner un grand arbre et un petit arbre","Jeu : 'Montre-moi le grand...'","Récapitulatif : grand / petit / plus grand / plus petit"],
      ["Montre le plus grand objet → Corrigé : évaluation gestuelle","Dessine un grand chapeau et un petit chapeau → Corrigé : vérifier","Qui est le plus grand de la classe ? → Corrigé : réponse collective"]),
    m("MATHS","Les nombres de 0 à 10 : révision complète",
      "Consolider l'ensemble de la suite numérique 0-10 par des activités variées.",
      ["Compter de 0 à 10 et de 10 à 0 (à rebours)","Compter en sautant : 0, 2, 4, 6, 8, 10","Associer chaque chiffre à sa quantité","Jeu de loto des chiffres","Placer les chiffres dans l'ordre sur une frise","Exercice : relier le chiffre au bon nombre d'objets","Récapitulatif : la frise numérique 0-10"],
      ["Compte de 0 à 10 → Corrigé : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10","Compte à rebours de 5 à 0 → Corrigé : 5, 4, 3, 2, 1, 0","Montre 9 doigts → Corrigé : évaluation gestuelle"]),
    m("MORALE","L'hygiène du corps : se laver les mains et le visage",
      "Apprendre les gestes d'hygiène essentiels : se laver les mains et le visage.",
      ["Pourquoi se laver ? (pour éliminer les microbes)","Démonstration : se laver les mains (6 gestes)","Étape 1 : mouiller les mains","Étape 2 : savonner","Étape 3 : frotter","Étape 4 : rincer","Récapitulatif : les étapes du lavage des mains"],
      ["Pourquoi se lave-t-on les mains ? → Corrigé : pour éliminer les microbes","Combien d'étapes pour se laver les mains ? → Corrigé : 6 étapes","Quand doit-on se laver les mains ? → Corrigé : avant de manger, après les toilettes"]),
    m("ENVIRONNEMENT","Le corps humain : les parties du corps",
      "Identifier et nommer les principales parties du corps humain.",
      ["Montrer un grand dessin du corps humain","Nommer : la tête, le bras, la jambe, le pied, la main","Toucher la partie nommée sur son propre corps","Chanter 'Promenons-nous dans les bois' ou comptine du corps","Dessiner un bonhomme simple","Légender 3 parties du corps sur le dessin","Récapitulatif : 6 parties du corps nommées"],
      ["Montre ta tête → Corrigé : évaluation gestuelle","Nomme cette partie (pointer le bras) → Corrigé : le bras","Combien d'oreilles a un humain ? → Corrigé : 2"]),
    m("ANGLAIS","The body : les parties du corps en anglais",
      "Apprendre le vocabulaire du corps humain en anglais.",
      ["Rappel des objets scolaires en anglais","Nouveaux mots : head, eyes, nose, mouth, hand, arm, leg","Comptine 'Head, Shoulders, Knees and Toes'","Jeu : 'Touch your head!'","Phrase simple : 'I have two eyes.'","Dessiner et légender un bonhomme en anglais","Récapitulatif : 7 mots du corps"],
      ["Touch your nose → Corrigé : évaluation gestuelle","What are these? (pointer les yeux) → Corrigé : eyes","Sing 'Head, Shoulders, Knees and Toes' → Corrigé : évaluation orale"]),
    m("CHANT","Bonjour / Good morning — Consolidation finale",
      "Maîtriser la chanson 'Bonjour / Good morning' et la chanter avec confiance.",
      ["Chanter la chanson complète avec tous les gestes","Évaluation : petit groupe devant la classe","Chanter en canon si les enfants sont prêts","Ajouter un instrument de percussion (taper dans les mains)","Chanter dans la cour pour d'autres classes","Inventer un nouveau couplet simple","Récapitulatif : la chanson mémorisée"],
      ["Chante la chanson avec les gestes → Corrigé : évaluation orale","Quel couplet préfères-tu ? → Corrigé : réponse libre","Chante la chanson pour tes camarades → Corrigé : évaluation orale"]),
    m("RECITATION","La rentrée — Récitation complète",
      "Réciter le poème 'La rentrée' dans son intégralité avec expression.",
      ["Révision : réciter les 4 lignes connues","Apprendre la dernière partie si le poème est plus long","Récitation collective avec expression","Récitation par groupes (filles, garçons)","Récitation individuelle pour les volontaires","Évaluation finale : noter les progrès","Récapitulatif : le poème maîtrisé"],
      ["Récite le poème entier → Corrigé : évaluation orale","Récite avec de l'expression (fort/doux/lent) → Corrigé : évaluation orale","De quoi parle le poème 'La rentrée' ? → Corrigé : du retour à l'école"]),
    m("EPS","Jeux libres et organisés dans la cour",
      "Développer la motricité globale par des jeux libres et des jeux organisés simples.",
      ["Échauffement : marcher, puis courir lentement","Jeu organisé 1 : 'Les statues' — s'arrêter sur signal","Jeu organisé 2 : 'Le train' — faire une chaîne","Jeu libre : explorer la cour librement","Jeu coopératif : transporter une balle sans les mains","Retour au calme : respiration lente","Récapitulatif : les jeux préférés"],
      ["Qu'est-ce que le jeu des statues ? → Corrigé : on s'arrête et on ne bouge plus sur signal","Fais partie du train : tiens l'épaule du camarade → Corrigé : évaluation gestuelle","Quel jeu as-tu préféré ? → Corrigé : réponse libre"]),
    m("DESSIN","Coloriage : les cheveux du bonhomme",
      "Colorier les cheveux d'un bonhomme prédessiné en choisissant des couleurs et en restant dans les contours.",
      ["Distribuer une feuille avec un bonhomme prédessiné","Observer le bonhomme : tête, corps, membres","Choisir la couleur des cheveux","Colorier doucement en restant dans le contour","Choisir la couleur du visage et du corps","Colorier les vêtements","Signer et exposer le bonhomme colorié"],
      ["Quelle couleur as-tu choisie pour les cheveux ? → Corrigé : réponse libre","As-tu bien colorié sans dépasser ? → Corrigé : observation","Combien de couleurs as-tu utilisées ? → Corrigé : au moins 3"]),
    m("TRAVAUX MANUELS","Modelage en pâte à modeler : un bonhomme simple",
      "Créer un bonhomme simple en pâte à modeler en utilisant les techniques de boule et rouleau.",
      ["Rappel : faire une boule (tête) et un rouleau (corps)","Faire la tête : grosse boule","Faire le corps : gros rouleau","Assembler tête et corps","Ajouter les bras : 2 petits rouleaux","Ajouter les jambes : 2 gros rouleaux","Présenter son bonhomme"],
      ["Combien de boules faut-il pour un bonhomme ? → Corrigé : 1 pour la tête","Combien de jambes a ton bonhomme ? → Corrigé : 2","Présente ton bonhomme à la classe → Corrigé : évaluation orale"]),
  ],
},

  ]},
];

module.exports = { PERIODES_12EME };
