'use strict';

// Données thématiques par période/semaine — 10ème (CE1, 7-8 ans)
// Programme officiel RAPS 10ème Madagascar 2025-2026
//
// Alternance :
//   - MESURE  : semaines impaires  | GÉOMÉTRIE : semaines paires
//   - GÉO     : semaines impaires  | TANTARA   : semaines paires
//   (sauf révision/bilan)

const PERIODES_10EME = [
  // ═══════════════════════════════════════════════════════════════════════
  // PÉRIODE 1 — 01/09/2025  (7 semaines)
  // Thème général : La vie scolaire et l'environnement immédiat
  // ═══════════════════════════════════════════════════════════════════════
  {
    num: 1, libelle: '1ère Période', debut: '01/09/2025',
    semaines: [
      {
        n:1,
        theme: 'La rentrée — Découverte de la classe et de l\'école',
        sous:  'Se présenter, connaître ses camarades, les règles de la classe',
        mala_theme:  'Ny sekoly vaovao: ny kilasy, ny namana, ny mpampianatra',
        mala_litera: 'Fehezanteny tsotra: ny anarana sy ny fanamarihana',
        arith:    'Les nombres de 0 à 29 : lire, écrire, décomposer en dizaines et unités',
        mesure:   'La longueur : notions de plus long / plus court, comparaison directe',
        geom:     null,
        probleme: 'Problèmes de comptage et comparaison (jusqu\'à 20)',
        sci:      'Le corps humain : parties du corps, rôles des membres et des sens',
        geo:      'Mon école et mon quartier : repérer les lieux importants',
        tantara:  null,
        ffmom:    'La famille : rôles et responsabilités de chaque membre',
        hetsika:  'Fanitsiana ny fitaovam-pianarana: penisily, boky, saco — fomba fitandremana',
        arts:     'Feo mozika: do-ré-mi — écouter, reconnaître et reproduire les 3 notes',
        sary:     'Dessin de soi : autoportrait simplifié (tête, corps, mains, pieds)',
        eps:      'Jeux de découverte : courir, s\'arrêter sur signal, explorer la cour',
      },
      {
        n:2,
        theme: 'La famille et la maison',
        sous:  'Vocabulaire de la famille, description de la maison et des pièces',
        mala_theme:  'Ny fianakaviana: ny ray-amandreny, ny rahalahy, ny anabavy',
        mala_litera: 'Fehezanteny mitohy: fampiasana "sy", "ary", "fa"',
        arith:    'Les nombres de 30 à 59 : lecture, écriture, ordre croissant/décroissant',
        mesure:   null,
        geom:     'Les formes géométriques : carré, rectangle, triangle, cercle — reconnaissance',
        probleme: 'Problèmes additifs simples : réunion et ajout (résultat ≤ 30)',
        sci:      'Les cinq sens : organes, rôles, expériences simples de perception',
        geo:      null,
        tantara:  'Ma communauté : les ancêtres fondateurs du village/quartier (histoire locale)',
        ffmom:    'L\'école : règles de vie, droits et devoirs de l\'élève',
        hetsika:  'Fandrafetana sy fanitsiana ny toeram-pianarana: manadio, manohy boky',
        arts:     'Feo mozika: fa-sol-la — gamme simplifiée, répéter et distinguer les 6 premières notes',
        sary:     'Ma maison : dessin de la façade avec les fenêtres et la porte',
        eps:      'Jeux d\'équilibre et de coordination : marcher sur une ligne, sauter à cloche-pied',
      },
      {
        n:3,
        theme: 'L\'hygiène et la santé au quotidien',
        sous:  'Les gestes d\'hygiène personnelle, prévenir les maladies simples',
        mala_theme:  'Ny fahadiovan\'ny vatana: misasa, manadio nify, mitafy tsara',
        mala_litera: 'Voambolana: teny mifandray amin\'ny fahadiovan\'ny vatana',
        arith:    'Les nombres de 60 à 99 : lire, écrire, comparer, encadrer',
        mesure:   'La longueur : le mètre (m) et le centimètre (cm) — notion et instruments',
        geom:     null,
        probleme: 'Problèmes soustractifs : enlever, comparer (résultat ≤ 40)',
        sci:      'L\'hygiène corporelle : se laver les mains (séquence de 6 gestes), brosser les dents',
        geo:      'Mon village / ma ville : les services publics (école, dispensaire, marché)',
        tantara:  null,
        ffmom:    'Les règles de vie à l\'école : respect, ponctualité, entraide',
        hetsika:  'Fanasana tanana : fomba sy dingana miaraka amin\'ny savony sy rano',
        arts:     'Hira : apprendre une chanson traditionnelle courte (refrain de 4 lignes)',
        sary:     'Dessin d\'observation : un légume ou un fruit apporté en classe (forme, couleur)',
        eps:      'Course lente : endurance de base, courir 3 minutes sans s\'arrêter',
      },
      {
        n:4,
        theme: 'La nature autour de moi — Les saisons',
        sous:  'Observer la nature, identifier les saisons à Madagascar',
        mala_theme:  'Ny voajanahary: ny havoana, ny renirano, ny ala sy ny saha',
        mala_litera: 'Vakiteny fohy: mamaky fehezanteny an-tsehatra, mahatakatra votoatiny',
        arith:    'Les nombres de 100 à 199 : centaines, dizaines, unités',
        mesure:   null,
        geom:     'Droite, demi-droite, segment : tracer et reconnaître',
        probleme: 'Problèmes de réunion et d\'ajout avec des nombres ≤ 60',
        sci:      'Les saisons à Madagascar : saison des pluies / saison sèche — caractéristiques',
        geo:      null,
        tantara:  'L\'origine de Madagascar : les premiers habitants et leurs activités',
        ffmom:    'L\'environnement naturel : pourquoi protéger la nature qui nous entoure',
        hetsika:  'Fanamboarana taolam-boninkazo amin\'ny ravim-bary : kisaly tsotra',
        arts:     'Dihy: pas de base d\'une danse régionale malgache (3 mouvements)',
        sary:     'Dessin du paysage local : collines, rivière, rizières (3 plans)',
        eps:      'Saut en longueur sans élan : technique de base (appel, envol, réception)',
      },
      {
        n:5,
        theme: 'Les animaux de la ferme et de la maison',
        sous:  'Caractéristiques, utilités et soins des animaux domestiques',
        mala_theme:  'Ny biby ao an-trano sy eo amin\'ny tany: akoho, omby, alika, saka',
        mala_litera: 'Fampiasana ny matoanteny eo amin\'ny fehezanteny: asàna ny matoanteny',
        arith:    'Les nombres de 200 à 499 : décomposer, comparer, ordonner',
        mesure:   'La masse : léger / lourd, la balance — comparaison directe et indirecte',
        geom:     null,
        probleme: 'Problèmes: compter les pattes/ailes/œufs des animaux (multiplication intuitive)',
        sci:      'Les animaux domestiques : corps, mode de vie, utilités pour l\'humain',
        geo:      'Les régions agricoles de Madagascar : rizières, élevage, pêche',
        tantara:  null,
        ffmom:    'Le travail agricole : valoriser le travail des paysans et leurs savoirs',
        hetsika:  'Fiompiana akoho : construire un enclos simple, donner à manger',
        arts:     'Hira : mémoriser le refrain d\'une chanson sur les animaux de la ferme',
        sary:     'Dessin d\'un animal de la ferme : zébu ou poule (formes de base)',
        eps:      'Lancer : attraper et lancer une balle à deux mains, viser une cible',
      },
      {
        n:6,
        theme: 'Révision de la 1ère Période',
        sous:  'Bilan des apprentissages, remédiation ciblée',
        mala_theme:  'Fanavaozana P1: ny kilasy, ny fianakaviana, ny voajanahary',
        mala_litera: 'Fanavaozana voambolana sy fehezanteny P1',
        arith:    'Révision Arithmétique P1 : nombres 0-499, lecture, écriture, comparaison',
        mesure:   'Révision Mesure P1 : longueur et masse',
        geom:     'Révision Géométrie P1 : formes et lignes',
        probleme: 'Révision Problèmes P1 : addition et soustraction en contexte',
        sci:      'Révision Sciences P1 : corps humain, hygiène, saisons, animaux',
        geo:      'Révision Géographie P1',
        tantara:  'Révision Histoire P1',
        ffmom:    'Révision FFMOM P1',
        hetsika:  'Bilan Hetsika P1 : présentation des productions réalisées',
        arts:     'Bilan Arts P1 : chanter les chansons apprises',
        sary:     'Bilan Sary P1 : exposition des dessins de la période',
        eps:      'Révision EPS P1 : parcours multi-activités',
      },
      {
        n:7,
        theme: 'Bilan — 1ère Période',
        sous:  'Évaluation de fin de première période',
        mala_theme:  'Bilan P1', mala_litera: 'Bilan P1',
        arith: 'Bilan P1', mesure: 'Bilan P1', geom: 'Bilan P1', probleme: 'Bilan P1',
        sci: 'Bilan P1', geo: 'Bilan P1', tantara: 'Bilan P1', ffmom: 'Bilan P1',
        hetsika: 'Bilan P1', arts: 'Bilan P1', sary: 'Bilan P1', eps: 'Bilan P1',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PÉRIODE 2 — 27/10/2025  (7 semaines)
  // Thème général : L'alimentation, les animaux et la nature vivante
  // ═══════════════════════════════════════════════════════════════════════
  {
    num: 2, libelle: '2ème Période', debut: '27/10/2025',
    semaines: [
      {
        n:1,
        theme: 'Les aliments et une alimentation saine',
        sous:  'Groupes alimentaires, repas équilibré, aliments locaux de Madagascar',
        mala_theme:  'Ny sakafo: vary, anana, hena, voankazo — izay sakafo tsara ho an\'ny vatana',
        mala_litera: 'Voambolana: karazam-sakafo sy ny toerana ahazoana azy',
        arith:    'L\'addition sans retenue à 2 chiffres : technique et vérification',
        mesure:   'La masse : le kilogramme (kg) — peser des aliments, comparer',
        geom:     null,
        probleme: 'Problèmes : achats au marché (addition de prix simples)',
        sci:      'Les groupes alimentaires : énergie, bâtisseurs, protecteurs — exemples locaux',
        geo:      'Les zones de production alimentaire à Madagascar : riz, manioc, zébu, vanille',
        tantara:  null,
        ffmom:    'Se nourrir : droit à l\'alimentation, solidarité face à la faim',
        hetsika:  'Fikarakarana sakafo tsotra: famolavolana ron\'anana (salade de légumes)',
        arts:     'Hira: chanter une chanson sur la nourriture avec des gestes expressifs',
        sary:     'Nature morte : dessiner le contenu d\'un panier du marché (3 légumes)',
        eps:      'Natation / jeux aquatiques : flotter, souffler dans l\'eau, battements de pieds',
      },
      {
        n:2,
        theme: 'Les plantes — Observation et utilités',
        sous:  'Parties de la plante, cycle de vie, plantes utiles à Madagascar',
        mala_theme:  'Ny zavamaniry: ny fakany, ny tahony, ny raviny, ny voninkazo, ny voany',
        mala_litera: 'Fampiasana ny anarana ankalamanjana (pluriel): ny formes amin\'ny teny',
        arith:    'L\'addition avec retenue simple : unités et dizaines',
        mesure:   null,
        geom:     'Le carré et le rectangle : propriétés, tracer avec règle et équerre',
        probleme: 'Problèmes : planter des graines, calculer des rangées et colonnes',
        sci:      'La plante : racine, tige, feuille, fleur, fruit/graine — fonctions de chaque partie',
        geo:      null,
        tantara:  'Les royaumes de Madagascar : Imerina et son expansion (IVe–XIXe siècle)',
        ffmom:    'Prendre soin des plantes : responsabilité envers le vivant',
        hetsika:  'Fambolena voam-boly: fanamboarana tany kely, famafazana voan\'anana',
        arts:     'Solfège : lire et chanter les 7 notes de la gamme (do à si) sur portée simplifiée',
        sary:     'Dessin botanique : une plante complète avec racine, tige, feuilles, fleur',
        eps:      'Natation : coulée ventrale, enchaîner souffler / glisser / battre les pieds',
      },
      {
        n:3,
        theme: 'L\'eau — Ressource essentielle',
        sous:  'Les usages de l\'eau, états de l\'eau, protection des sources',
        mala_theme:  'Ny rano: izay anaovana azy, ny fomba fitandremana azy',
        mala_litera: 'Vakiteny: mamaky lahatsoratra fohy sy mahatakatra votoatiny',
        arith:    'La soustraction sans retenue à 2 chiffres : technique et vérification',
        mesure:   'La capacité : le litre (L) et le demi-litre — mesurer des liquides',
        geom:     null,
        probleme: 'Problèmes : partager de l\'eau, calculer la consommation quotidienne',
        sci:      'Les états de l\'eau : solide (glace), liquide, vapeur — expériences simples',
        geo:      'Les fleuves et lacs de Madagascar : Betsiboka, Tsiribihina, lac Alaotra',
        tantara:  null,
        ffmom:    'L\'eau : un droit fondamental — économiser et ne pas polluer les sources',
        hetsika:  'Fanamboarana filitra rano tsotra: sifotra miaraka amin\'ny sisin-driaka',
        arts:     'Hira: mémoriser une chanson sur l\'eau (paroles complètes + mélodie)',
        sary:     'Paysage aquatique : dessiner une rivière avec les rives, les arbres et le ciel',
        eps:      'Natation : crawl simplifié — coordination bras et jambes sur 5 mètres',
      },
      {
        n:4,
        theme: 'La forêt malgache — Biodiversité unique',
        sous:  'Richesse forestière de Madagascar, espèces endémiques, déforestation',
        mala_theme:  'Ny ala Malagasy: ny hazo, ny biby, ny voninkazo manokana',
        mala_litera: 'Asa an-tsoratra tsotra: soratana fehezanteny 3 momba ny lohahevitra',
        arith:    'La soustraction avec retenue simple : unités et dizaines',
        mesure:   null,
        geom:     'Le triangle : reconnaître, nommer les côtés et sommets, tracer',
        probleme: 'Problèmes : compter des arbres plantés et abattus (soustraction en contexte)',
        sci:      'La forêt : plantes et animaux endémiques (lémuriens, baobabs, caméléons)',
        geo:      null,
        tantara:  'Andrianampoinimerina et l\'unification de Madagascar (fin XVIIIe siècle)',
        ffmom:    'Protéger la forêt : comprendre pourquoi la déforestation est dangereuse',
        hetsika:  'Fanambolena hazo: mamindra zanak\'ala ho amin\'ny toerana vaovao',
        arts:     'Dihy: enchaîner 3 pas de la danse régionale apprise, avec musique',
        sary:     'Affiche de sensibilisation : "Aro ny ala!" (protège la forêt) — slogan + dessin',
        eps:      'Judo / lutte traditionnelle : position de base, chute avant, respect',
      },
      {
        n:5,
        theme: 'Le marché et les échanges dans la vie quotidienne',
        sous:  'Les transactions commerciales simples, les prix, rendre la monnaie',
        mala_theme:  'Ny tsena: ny mpivarotra, ny mividy, ny vola, ny sandan\'ny entana',
        mala_litera: 'Fanazarana hiteny: maneho sary sy milaza ny zava-nisy',
        arith:    'L\'addition et la soustraction : révision et mélange, calcul mental ×10',
        mesure:   'Révision mesures P2 : masse et capacité dans le contexte du marché',
        geom:     null,
        probleme: 'Problèmes combinés : acheter, payer, rendre la monnaie (2 opérations)',
        sci:      'La conservation des aliments : séchage, salage, fermentation — pourquoi et comment',
        geo:      'Les marchés de Madagascar : Analakely, Anosibe — rôle économique',
        tantara:  null,
        ffmom:    'L\'honnêteté dans le commerce : droits du consommateur, escroquerie',
        hetsika:  'Jeu de rôle "Tsena": tenir un stand de marché, calculer les prix et la monnaie',
        arts:     'Hira: composer une courte mélodie sur le thème du marché (4 mesures)',
        sary:     'Dessin animé du marché : personnages, étals, couleurs vives',
        eps:      'Judo : projection simple O-Soto-Gari — déséquilibre et chute contrôlée',
      },
      {
        n:6,
        theme: 'Révision de la 2ème Période',
        sous:  'Bilan des apprentissages, remédiation ciblée',
        mala_theme:  'Fanavaozana P2: ny sakafo, ny zavamaniry, ny rano, ny ala',
        mala_litera: 'Fanavaozana ny lesona P2',
        arith:    'Révision Arithmétique P2 : addition et soustraction avec retenue',
        mesure:   'Révision Mesures P2 : masse et capacité',
        geom:     'Révision Géométrie P2 : formes planes',
        probleme: 'Révision Problèmes P2 : problèmes à 2 opérations',
        sci:      'Révision Sciences P2 : plantes, eau, forêt, alimentation',
        geo:      'Révision Géographie P2',
        tantara:  'Révision Histoire P2',
        ffmom:    'Révision FFMOM P2',
        hetsika:  'Bilan Hetsika P2 : présentation des productions',
        arts:     'Bilan Arts P2 : récital des chansons apprises',
        sary:     'Bilan Sary P2 : exposition',
        eps:      'Révision EPS P2 : natation et judo',
      },
      {
        n:7,
        theme: 'Bilan — 2ème Période',
        sous:  'Évaluation de fin de deuxième période',
        mala_theme:  'Bilan P2', mala_litera: 'Bilan P2',
        arith: 'Bilan P2', mesure: 'Bilan P2', geom: 'Bilan P2', probleme: 'Bilan P2',
        sci: 'Bilan P2', geo: 'Bilan P2', tantara: 'Bilan P2', ffmom: 'Bilan P2',
        hetsika: 'Bilan P2', arts: 'Bilan P2', sary: 'Bilan P2', eps: 'Bilan P2',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PÉRIODE 3 — 05/01/2026  (7 semaines)
  // Thème général : La maison, la ville, l'espace et les transports
  // ═══════════════════════════════════════════════════════════════════════
  {
    num: 3, libelle: '3ème Période', debut: '05/01/2026',
    semaines: [
      {
        n:1,
        theme: 'Ma maison — Les pièces et les objets du quotidien',
        sous:  'Vocabulaire de la maison, responsabilités ménagères, propreté',
        mala_theme:  'Ny trano: ny efitra fisakafoana, ny trano-fandriana, ny lavakuisy',
        mala_litera: 'Ny matoanteny amin\'ny ankehitriny: manoratra fehezanteny 3',
        arith:    'La multiplication : sens (addition répétée) et premier tables (×1, ×2)',
        mesure:   'La longueur : mesurer avec une règle graduée en cm, estimer',
        geom:     null,
        probleme: 'Problèmes : disposer des meubles, calculer des surfaces de façon intuitive',
        sci:      'L\'air dans la maison : aération, ventilation, pollutions intérieures',
        geo:      'Les types d\'habitat à Madagascar : case en bois, maison en briques, appartement',
        tantara:  null,
        ffmom:    'Les tâches ménagères : partage équitable entre tous les membres de la famille',
        hetsika:  'Fanadiovana ny trano: ny fomba tsara sy ny fitaovana ampiasaina',
        arts:     'Solfège : lire une partition simplifiée de 4 mesures, nommer les notes',
        sary:     'Plan de ma maison vue du dessus : pièces légendées en couleur',
        eps:      'Gymnique : roulade avant et arrière, chandelle, position groupée',
      },
      {
        n:2,
        theme: 'La ville et ses services — Se repérer dans l\'espace',
        sous:  'Plan de ville, services publics, transport urbain',
        mala_theme:  'Ny tanàna: ny lalana, ny tobin\'ny fiara, ny banky, ny hopitaly',
        mala_litera: 'Vakiteny: lahatsoratra mifandray amin\'ny toeran\'ny tanàna',
        arith:    'La multiplication : tables ×2 et ×3 — apprendre, réciter, appliquer',
        mesure:   null,
        geom:     'Le rectangle et le carré : périmètre (notion, calculer en ajoutant les côtés)',
        probleme: 'Problèmes : calculer des distances à pied en ville (addition de longueurs)',
        sci:      'Les transports et la pollution de l\'air : voitures, bus, vélos — impacts',
        geo:      null,
        tantara:  'La colonisation française à Madagascar (1896) : cause, événements, conséquences',
        ffmom:    'La vie en ville : règles de sécurité routière pour un piéton de 8 ans',
        hetsika:  'Fanamboarana sary an\'ny tanàna: plan de la ville en carton et en couleur',
        arts:     'Hira: apprendre une chanson à 2 voix simples (canon à 2 parties)',
        sary:     'Plan de ville : dessiner une rue avec les bâtiments (école, marché, mairie)',
        eps:      'Gymnique : enchaîner roulade + chandelle + saut groupé',
      },
      {
        n:3,
        theme: 'Les transports — Voyager à Madagascar',
        sous:  'Modes de transport locaux et nationaux, sécurité routière',
        mala_theme:  'Ny fitaterana: taxi-brousse, fiara, lakana, fiaranandriaka',
        mala_litera: 'Asa an-tsoratra: manoratra lalana sy toromarika',
        arith:    'La multiplication : tables ×4 et ×5 — apprendre, réciter, appliquer',
        mesure:   'La longueur : le mètre (m), km (notion) — distances entre villes',
        geom:     null,
        probleme: 'Problèmes : durée d\'un trajet, nombre de passagers dans un taxi-brousse',
        sci:      'Les moyens de transport et l\'énergie : carburant, électricité, énergie humaine',
        geo:      'Le réseau routier de Madagascar : les routes nationales RN1, RN2, RN7',
        tantara:  null,
        ffmom:    'La sécurité routière : les panneaux de signalisation, traverser en sécurité',
        hetsika:  'Fanamboarana taozavatra fiara madinika: sarindran\'ny fiara (maquette)',
        arts:     'Dihy: apprendre une danse de transport rythmée (imiter les mouvements)',
        sary:     'Dessin d\'un taxi-brousse ou d\'une pirogue : proportions et couleurs',
        eps:      'Athlétisme : course de vitesse 20 m — départ, course, arrivée',
      },
      {
        n:4,
        theme: 'Madagascar — Géographie physique',
        sous:  'Relief, côtes, fleuves, régions de Madagascar',
        mala_theme:  'Madagascar: ny havoana, ny lemaka, ny renirano, ny morontsiraka',
        mala_litera: 'Mamaky sary sarintany: mahatakatra ny faritr\'i Madagascar',
        arith:    'La multiplication : tables ×6 et ×7 — apprendre, réciter, appliquer',
        mesure:   null,
        geom:     'Le cercle : centre, rayon, diamètre — tracer au compas',
        probleme: 'Problèmes : calculer le nombre de km entre 2 villes sur une carte à l\'échelle',
        sci:      'Le relief et le climat : pourquoi il pleut plus sur la côte est que sur l\'ouest',
        geo:      null,
        tantara:  'Les héros de l\'indépendance : Philibert Tsiranana et le 26 juin 1960',
        ffmom:    'Être fier d\'être Malgache : les symboles nationaux (drapeau, hymne, armoiries)',
        hetsika:  'Fanamboarana sarintany Madagascar amin\'ny taratasy menanika: fanoratana sy fanasiana',
        arts:     'Hira firenena: apprendre l\'hymne national "Ry Tanindrazanay malala ô"',
        sary:     'Carte de Madagascar : dessin et légende des régions principales',
        eps:      'Athlétisme : saut en longueur avec élan — 3 appels, mesurer la distance',
      },
      {
        n:5,
        theme: 'L\'école dans le monde — Apprendre ensemble',
        sous:  'Différents systèmes scolaires, importance de l\'éducation',
        mala_theme:  'Ny fianarana maneran-tany: fianarana any Finland, Japon, China, Madagasikara',
        mala_litera: 'Fanehoana hevitra: milaza izay tianao ho toavina amin\'ny sekoly',
        arith:    'La multiplication : tables ×8, ×9, ×10 — apprendre, réciter, appliquer',
        mesure:   'Le temps : lire l\'heure (heures entières et demies), calendrier scolaire',
        geom:     null,
        probleme: 'Problèmes : horaires d\'école, durée des cours, calculer le temps de travail',
        sci:      'Le cerveau et l\'apprentissage : comment apprend-on ? Le rôle du sommeil',
        geo:      'Les continents et les océans : situer Madagascar sur le planisphère',
        tantara:  null,
        ffmom:    'Le droit à l\'éducation : pourquoi tous les enfants doivent aller à l\'école',
        hetsika:  'Fanamboarana taratasy famintinana: ny lesona tiantsika indrindra ity taona ity',
        arts:     'Chant international : apprendre une chanson simple dans une autre langue',
        sary:     'Mon école idéale : dessin de rêve (architecture, jardin, équipements)',
        eps:      'Athlétisme : relais 4×20 m — passage du témoin, travail d\'équipe',
      },
      {
        n:6,
        theme: 'Révision de la 3ème Période',
        sous:  'Bilan des apprentissages, remédiation ciblée',
        mala_theme:  'Fanavaozana P3: ny trano, ny tanàna, ny fitaterana, Madagasikara',
        mala_litera: 'Fanavaozana ny lesona P3',
        arith:    'Révision Arithmétique P3 : tables de multiplication (×1 à ×10)',
        mesure:   'Révision Mesures P3 : longueur et temps',
        geom:     'Révision Géométrie P3 : périmètre, cercle',
        probleme: 'Révision Problèmes P3 : multiplication en contexte',
        sci:      'Révision Sciences P3 : air, transport, géographie physique, cerveau',
        geo:      'Révision Géographie P3',
        tantara:  'Révision Histoire P3',
        ffmom:    'Révision FFMOM P3',
        hetsika:  'Bilan Hetsika P3',
        arts:     'Bilan Arts P3 : récital',
        sary:     'Bilan Sary P3',
        eps:      'Révision EPS P3 : gymnique et athlétisme',
      },
      {
        n:7,
        theme: 'Bilan — 3ème Période',
        sous:  'Évaluation de fin de troisième période',
        mala_theme:  'Bilan P3', mala_litera: 'Bilan P3',
        arith: 'Bilan P3', mesure: 'Bilan P3', geom: 'Bilan P3', probleme: 'Bilan P3',
        sci: 'Bilan P3', geo: 'Bilan P3', tantara: 'Bilan P3', ffmom: 'Bilan P3',
        hetsika: 'Bilan P3', arts: 'Bilan P3', sary: 'Bilan P3', eps: 'Bilan P3',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PÉRIODE 4 — 23/02/2026  (6 semaines)
  // Thème général : La santé, le sport et les métiers
  // ═══════════════════════════════════════════════════════════════════════
  {
    num: 4, libelle: '4ème Période', debut: '23/02/2026',
    semaines: [
      {
        n:1,
        theme: 'La santé — Prévention et soins',
        sous:  'Les maladies courantes à Madagascar, l\'hygiène avancée, le dispensaire',
        mala_theme:  'Ny fahasalamana: aretina mahazatra (tazo, rotsa, kalo) sy fomba fisorohana',
        mala_litera: 'Fanazarana an-tsoratra: manoratra fehezanteny tsotra momba ny fahasalamana',
        arith:    'La division : notion de partage égal, partager des objets en groupes',
        mesure:   'La masse : gramme (g) et kilogramme (kg) — conversion simple (1 kg = 1000 g)',
        geom:     null,
        probleme: 'Problèmes : partager des médicaments ou des rations alimentaires équitablement',
        sci:      'Les maladies courantes : paludisme, diarrhée, rhume — causes, symptômes, prévention',
        geo:      'Les hôpitaux et centres de santé à Madagascar : accès aux soins selon les régions',
        tantara:  null,
        ffmom:    'Le droit à la santé : couverture sanitaire, vaccination, médecin de base',
        hetsika:  'Fanomboana fanafody natiora tsotra: fomba fanao Malagasy hanapahan\'aina',
        arts:     'Hira : chant de bien-être — "Fahasalamana" (composition collective)',
        sary:     'Affiche de santé : "Misasa tanana!" — étapes illustrées en 6 vignettes',
        eps:      'Basket-ball : dribbler, passer, tirer — techniques de base',
      },
      {
        n:2,
        theme: 'Le sport et les loisirs — Vivre en bonne santé',
        sous:  'Bienfaits du sport, sports traditionnels et modernes à Madagascar',
        mala_theme:  'Ny fanatanjahan-tena: kalokalo Malagasy (tolon-omby, biraoka, moraingy)',
        mala_litera: 'Mamaky lahatsoratra: mahatakatra votoatiny sy mamaly fanontaniana',
        arith:    'La division : distribuer en parties égales, écrire l\'opération ÷',
        mesure:   null,
        geom:     'Symétrie axiale : reconnaître et reproduire une figure symétrique',
        probleme: 'Problèmes : partager des joueurs en équipes, calculer des scores',
        sci:      'Le corps en mouvement : muscles, os, articulations — comment ils travaillent',
        geo:      null,
        tantara:  'Les jeux traditionnels de Madagascar : moraingy, katro, bôkô — origines',
        ffmom:    'Le fair-play : respecter les règles du jeu, perdre et gagner avec dignité',
        hetsika:  'Fanamboarana baolina voatavo (balle de feuilles de bananiers) pour jouer',
        arts:     'Musique et sport : créer un rythme de tambour pour accompagner les jeux',
        sary:     'Dessin sportif : un athlète en plein effort (mouvement, dynamisme)',
        eps:      'Basket-ball : jeu à 3 contre 3, arbitrage par les élèves, respecter les règles',
      },
      {
        n:3,
        theme: 'Les métiers — Travailler pour la communauté',
        sous:  'Métiers du quartier, outils de travail, respect du travail d\'autrui',
        mala_theme:  'Ny asa: dokotera, mpampianatra, mpiompy, mpamboly, mpivarotra',
        mala_litera: 'Voambolana momba ny asa: ny fitaovana, ny toerana, ny anjara-asan\'ny tsirairay',
        arith:    'La division et la multiplication : lien entre les deux opérations (inverse)',
        mesure:   'Le temps : durée (heures de travail), calendrier (jours ouvrables)',
        geom:     null,
        probleme: 'Problèmes de partage et de regroupement liés aux métiers (salaire, production)',
        sci:      'Les outils et les machines simples : levier, plan incliné, poulie — principe',
        geo:      'Les activités économiques par région : pêche côtière, agriculture des hautes terres',
        tantara:  null,
        ffmom:    'Le respect des métiers : tous les métiers sont importants et complémentaires',
        hetsika:  'Visite imaginaire : inviter un parent pour présenter son métier, poser des questions',
        arts:     'Hira : chant sur les métiers ("Ny asa tsirairay manan\'danja")',
        sary:     'Portrait de métier : dessiner quelqu\'un qui travaille (détails de tenue et outils)',
        eps:      'Volley-ball : service par en dessous, manchette simple — en binômes',
      },
      {
        n:4,
        theme: 'L\'environnement — Prendre soin de la planète',
        sous:  'Déchets, recyclage, énergie renouvelable à Madagascar',
        mala_theme:  'Ny tontolo iainana: fomba fitandremana ny tany, ny rano, ny rivotra',
        mala_litera: 'Asa an-tsoratra: manoratra tatitra fohy momba ny tontolo iainana',
        arith:    'Révision multiplication et division : calcul mental, exercices variés',
        mesure:   null,
        geom:     'Solides : cube, pavé droit, cylindre — reconnaître, décrire, trouver dans la vie réelle',
        probleme: 'Problèmes : trier et compter des déchets, calculer ce qui est recyclable',
        sci:      'Les déchets et le recyclage : trier les déchets, transformer, réutiliser',
        geo:      null,
        tantara:  'La déforestation à Madagascar : causes historiques et conséquences actuelles',
        ffmom:    'Être éco-citoyen : les gestes quotidiens pour protéger l\'environnement',
        hetsika:  'Fanamboarana taozavatra avy amin\'ny fako: vase, pot à crayons (recyclage)',
        arts:     'Chant engagé : créer des paroles sur la protection de l\'environnement (4 lignes)',
        sary:     'Affiche écologique : "Arovy ny tontolo iainana" — dessin + slogan coloré',
        eps:      'Volley-ball : enchaînement service + manchette, jeu en équipes de 4',
      },
      {
        n:5,
        theme: 'Révision de la 4ème Période',
        sous:  'Bilan des apprentissages, remédiation ciblée',
        mala_theme:  'Fanavaozana P4: ny fahasalamana, ny asa, ny tontolo iainana',
        mala_litera: 'Fanavaozana ny lesona P4',
        arith:    'Révision Arithmétique P4 : division et multiplication liées',
        mesure:   'Révision Mesures P4 : masse et temps',
        geom:     'Révision Géométrie P4 : solides et symétrie',
        probleme: 'Révision Problèmes P4 : opérations combinées',
        sci:      'Révision Sciences P4 : santé, corps, environnement',
        geo:      'Révision Géographie P4',
        tantara:  'Révision Histoire P4',
        ffmom:    'Révision FFMOM P4',
        hetsika:  'Bilan Hetsika P4 : exposition des productions',
        arts:     'Bilan Arts P4 : récital final',
        sary:     'Bilan Sary P4 : exposition',
        eps:      'Révision EPS P4 : basket + volley',
      },
      {
        n:6,
        theme: 'Bilan — 4ème Période',
        sous:  'Évaluation de fin de quatrième période',
        mala_theme:  'Bilan P4', mala_litera: 'Bilan P4',
        arith: 'Bilan P4', mesure: 'Bilan P4', geom: 'Bilan P4', probleme: 'Bilan P4',
        sci: 'Bilan P4', geo: 'Bilan P4', tantara: 'Bilan P4', ffmom: 'Bilan P4',
        hetsika: 'Bilan P4', arts: 'Bilan P4', sary: 'Bilan P4', eps: 'Bilan P4',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PÉRIODE 5 — 20/04/2026  (9 semaines)
  // Thème général : Révisions, consolidation, projets de fin d'année
  // ═══════════════════════════════════════════════════════════════════════
  {
    num: 5, libelle: '5ème Période', debut: '20/04/2026',
    semaines: [
      {
        n:1,
        theme: 'Les fêtes et traditions de Madagascar',
        sous:  'Famadihana, fêtes nationales, cérémonies de la vie quotidienne',
        mala_theme:  'Ny fety Malagasy: ny famadihana, ny andro firaisankina, ny ankizy',
        mala_litera: 'Fitantarana: manoratra lahatsoratra fohy momba ny fety',
        arith:    'Problèmes combinant toutes les opérations : + − × ÷ en contexte de fête',
        mesure:   'Révision complète des mesures : longueur, masse, capacité, temps',
        geom:     null,
        probleme: 'Problèmes de la vie festive : partager des gâteaux, calculer des invités',
        sci:      'La chaleur et la lumière du soleil : effets sur les êtres vivants, saisons solaires',
        geo:      'Les fêtes régionales : Donia (Nosy Be), Santabary (Alaotra), Asara be',
        tantara:  null,
        ffmom:    'Le 26 juin : l\'indépendance, l\'identité nationale, célébrer en citoyen',
        hetsika:  'Fanamboarana lafarinina ho an\'ny fety: bôcakely na mokary (recette traditionnelle)',
        arts:     'Dihy: enchaîner toutes les danses apprises depuis P1 en spectacle',
        sary:     'Illustration de fête : une scène de famadihana en couleurs vives',
        eps:      'Jeux traditionnels : moraingy (lutte douce), katro, bôkô en tournoi ludique',
      },
      {
        n:2,
        theme: 'La mer et les côtes de Madagascar',
        sous:  'Vie marine, pêche, menaces sur les océans',
        mala_theme:  'Ny ranomasina sy ny amoron\'ny ranomasina: ny biby anaty rano, ny jono',
        mala_litera: 'Fanazarana hiteny: maneho sary amin\'ny teny (décrire une image)',
        arith:    'Les fractions simples : moitié (½), quart (¼), tiers (⅓) — notion intuitive',
        mesure:   null,
        geom:     'Révision Géométrie complète : formes planes + solides',
        probleme: 'Problèmes : partager une prise de poisson en fractions (½, ¼)',
        sci:      'La vie marine : poissons, baleines, coraux — adaptation au milieu aquatique',
        geo:      null,
        tantara:  'La pêche traditionnelle : les Vezo et leur savoir-faire maritime séculaire',
        ffmom:    'Protéger les océans : pollution plastique, surpêche, aires marines protégées',
        hetsika:  'Fanamboarana landy amin\'ny tarafia: sarindran\'ny sambo (maquette de pirogue)',
        arts:     'Hira: apprendre une chanson des pêcheurs (mélodie douce en 2 couplets)',
        sary:     'Aquarelle marine : fond marin coloré avec coraux et poissons tropicaux',
        eps:      'Natation de révision : crawl complet 10 mètres, brasse simplifiée',
      },
      {
        n:3,
        theme: 'Les insectes et les petits animaux',
        sous:  'Caractéristiques, rôles dans la nature, insectes utiles et nuisibles',
        mala_theme:  'Ny biby kely: bibikely sy biby famabony — ny andraikitry ny tsirairay',
        mala_litera: 'Vakiteny sarobidy: mamaky lahatsoratra misy voambolana vaovao',
        arith:    'Les fractions : trouver la moitié et le quart d\'un nombre (÷2 et ÷4)',
        mesure:   'La longueur : révision complète — mm, cm, m — mesurer des objets réels',
        geom:     null,
        probleme: 'Problèmes : combien de pattes pour 6 insectes ? (multiplication × 6)',
        sci:      'Les insectes : abeille, fourmi, papillon, moustique — corps et rôles dans la nature',
        geo:      'La biodiversité endémique : Madagascar, île aux 5% d\'espèces mondiales uniques',
        tantara:  null,
        ffmom:    'Respecter le vivant : ne pas tuer les insectes utiles, protéger les abeilles',
        hetsika:  'Observation d\'insectes avec loupe : dessiner et décrire un insecte trouvé dehors',
        arts:     'Musique de la nature : imiter les sons des insectes avec des instruments de corps',
        sary:     'Dessin scientifique : un papillon (symétrie, couleurs, détails des ailes)',
        eps:      'Athlétisme : décathlon simplifié — course 20 m + saut + lancer de balle',
      },
      {
        n:4,
        theme: 'Le ciel, les astres et le temps qu\'il fait',
        sous:  'Le soleil, la lune, les étoiles, les phénomènes météorologiques',
        mala_theme:  'Ny lanitra: ny masoandro, ny volana, ny kintana — ny andro sy ny alina',
        mala_litera: 'Fanadihadiana: manontany sy manome valiny momba ny zavatra hita',
        arith:    'Révision : les 4 opérations mélangées (+ − × ÷) sur des nombres ≤ 500',
        mesure:   null,
        geom:     'Angles : droit, aigu, obtus — reconnaître sans rapporteur (par comparaison)',
        probleme: 'Problèmes : calculer des durées (lever/coucher du soleil, phases de lune)',
        sci:      'Le système solaire simplifié : Terre, Lune, Soleil — mouvement, jour/nuit, saisons',
        geo:      null,
        tantara:  'Les savoirs astronomiques des ancêtres malgaches : almanach, signes du zodiaque',
        ffmom:    'L\'environnement cosmique : émerveillement, respect du monde naturel',
        hetsika:  'Fanamboarana planétarium de poche: boîte en carton avec trous pour les étoiles',
        arts:     'Hira alina: chanter une berceuse malgache en montrant la lune et les étoiles',
        sary:     'Dessin du ciel de nuit : lune, étoiles, silhouette de baobab en contre-jour',
        eps:      'Judo final : tournoi classe complète — projections et immobilisations appris',
      },
      {
        n:5,
        theme: 'Révision générale I — Mathématiques',
        sous:  'Consolider toutes les notions mathématiques de l\'année',
        mala_theme:  'Fanavaozana ankapobeny I: ny matematika',
        mala_litera: 'Fanavaozana I: ny Malagasy',
        arith:    'Révision Arithmétique annuelle : tous les nombres, toutes les opérations',
        mesure:   'Révision Mesures annuelle : longueur, masse, capacité, temps',
        geom:     'Révision Géométrie annuelle : formes, périmètre, solides, angles',
        probleme: 'Révision Problèmes annuelle : sélection des types les plus difficiles',
        sci:      'Révision Sciences I : corps humain, plantes, animaux',
        geo:      'Révision Géographie I : Madagascar physique et humaine',
        tantara:  'Révision Histoire I : chronologie des événements principaux',
        ffmom:    'Révision FFMOM I : droits et devoirs en société',
        hetsika:  'Bilan Hetsika : grand projet collectif (jardin de l\'école)',
        arts:     'Révision Arts I : répétition spectacle de fin d\'année',
        sary:     'Révision Sary I : affiche collective de l\'année',
        eps:      'Révision EPS I : natation + athlétisme',
      },
      {
        n:6,
        theme: 'Révision générale II — Langues et Sciences',
        sous:  'Consolider le Malagasy, le Français et les Sciences',
        mala_theme:  'Fanavaozana ankapobeny II: ny teny Malagasy',
        mala_litera: 'Fanavaozana II: vakiteny sy fanehoana hevitra',
        arith:    'Quiz mathématique : 20 questions variées, calcul mental',
        mesure:   'Problèmes de mesure combinés : calculer périmètre + masse + temps en 1 exercice',
        geom:     'Construction géométrique libre : créer une figure composée de formes apprises',
        probleme: 'Concours de problèmes : résoudre en équipes, stratégie collective',
        sci:      'Révision Sciences II : eau, air, matière, environnement',
        geo:      'Révision Géographie II : économie, transports, villes',
        tantara:  'Révision Histoire II : colonisation, indépendance, République',
        ffmom:    'Révision FFMOM II : citoyenneté active',
        hetsika:  'Finalisation jardin de l\'école : arroser, entretenir, récolter',
        arts:     'Révision Arts II : répétition spectacle de fin d\'année (polissage)',
        sary:     'Révision Sary II : finaliser toutes les productions pour exposition',
        eps:      'Révision EPS II : basket + volley (matchs de classe)',
      },
      {
        n:7,
        theme: 'Révision générale III — Histoire et Géographie',
        sous:  'Consolider toutes les notions sociales et civiques',
        mala_theme:  'Fanavaozana ankapobeny III: fanavaozana ny lesona rehetra',
        mala_litera: 'Fanavaozana III: famokarana voasoratra',
        arith:    'Révision : jeux mathématiques (bingo des tables, quiz rapide)',
        mesure:   'Révision : mesures dans des problèmes réels (cuisine, jardin, sport)',
        geom:     'Révision : construire et reconnaître figures et solides',
        probleme: 'Problèmes extra : défis pour les élèves avancés',
        sci:      'Révision Sciences III : l\'environnement et le développement durable',
        geo:      'Révision Géographie III : carte de Madagascar complète et légendée',
        tantara:  'Révision Histoire III : frise chronologique commentée',
        ffmom:    'Révision FFMOM III : présentation d\'un projet citoyen',
        hetsika:  'Exposition finale : présenter toutes les productions de l\'année',
        arts:     'Révision Arts III : répétition finale du spectacle de fin d\'année',
        sary:     'Révision Sary III : voter pour le plus beau dessin de la classe',
        eps:      'Révision EPS III : sports collectifs libres (choix des élèves)',
      },
      {
        n:8,
        theme: 'Bilan annuel',
        sous:  'Évaluation de fin d\'année — toutes les matières',
        mala_theme:  'Bilan annuel', mala_litera: 'Bilan annuel',
        arith: 'Bilan annuel Arithmétique', mesure: 'Bilan annuel Mesure',
        geom: 'Bilan annuel Géométrie', probleme: 'Bilan annuel Problèmes',
        sci: 'Bilan annuel Sciences', geo: 'Bilan annuel Géographie',
        tantara: 'Bilan annuel Histoire', ffmom: 'Bilan annuel FFMOM',
        hetsika: 'Grand projet annuel : jardin de l\'école, présentation aux parents',
        arts: 'Grand spectacle de fin d\'année : chants, danses, musique',
        sary: 'Mon plus beau dessin de l\'année : libre choix',
        eps: 'Fête sportive de fin d\'année : relais, sauts, matchs',
      },
      {
        n:9,
        theme: 'Fête de fin d\'année',
        sous:  'Célébration, remise de prix, remerciements et perspectives',
        mala_theme:  'Fety fianarana: fankafizana sy fisaorana', mala_litera: 'Fety',
        arith: 'Jeux mathématiques : escape game des chiffres', mesure: 'Bilan',
        geom: 'Bilan', probleme: 'Défis mathématiques amusants',
        sci: 'Expériences scientifiques ludiques pour les parents',
        geo: 'Présentation : Madagascar en images (expo)', tantara: 'Frise de l\'année',
        ffmom: 'Discours citoyen : ce que j\'ai appris à être un bon citoyen',
        hetsika: 'Exposition finale des productions manuelles de l\'année',
        arts: 'Grand spectacle collectif : chants, danses et musique pour les familles',
        sary: 'Remise de diplômes dessinés par les élèves',
        eps: 'Fête sportive : jeux collectifs en familles et célébration',
      },
    ],
  },
];

module.exports = { PERIODES_10EME };
