'use strict';

// Données thématiques par période/semaine — 8ème (CM1, ~10-11 ans)
// Programme officiel RAPS 8ème Madagascar 2025-2026
// Source : RÉPARTITION CLASSE DE 8ème.xlsx
//
// Matières : MALAGASY · FRANÇAIS · ARITHMÉTIQUE · GÉOMÉTRIE · MESURE
//            CONNAISSANCES USUELLES · GÉOGRAPHIE · TANTARA · FFMOM · ANGLAIS · EPS

const PERIODES_8EME = [

  // ═══════════════════════════════════════════════════════════════════════
  // PÉRIODE 1 — Septembre + début Octobre (7 semaines)
  // Thème général : Présentation d'un personnage — Numération jusqu'au milliard
  // ═══════════════════════════════════════════════════════════════════════
  {
    num: 1, libelle: '1ère Période', debut: '01/09/2025',
    semaines: [
      {
        n: 1,
        theme: "Semaine d'orientation — Prise de contact et test de pré-requis",
        sous:  "Accueil des élèves, découverte du programme et évaluation des acquis de 9ème",
        mala_theme:  "PRE-REQUIS ET ORIENTATION — Vakiteny (texte de bienvenue en classe)",
        mala_litera: "Révision des acquis de 9ème — structures de phrases simples",
        arith:   "Test de pré-requis — numération et 4 opérations sur les entiers (révision 9ème)",
        geom:    "Test de pré-requis — lignes, angles et figures planes (révision 9ème)",
        sm:      "Test de pré-requis — mesures de longueur et de masse (révision 9ème)",
        cu:      "Prise de contact — révision du corps humain : les 5 sens et leurs organes",
        fr:      "Portrait d'un personnage — La phrase : GNS et GV (Monsieur, elle copie — texte 1)",
        geo:     "La Terre notre planète — globe terrestre, planisphère, coordonnées géographiques",
        tantara: "Ny ilàna ny tantara — pourquoi étudier l'histoire · Niavian'ny Malagasy",
        ffmom:   "Fifanampian'ny mpiarabelona — solidarité et valeurs citoyennes à l'école",
        anglais: "Introducing and Greeting — se présenter et saluer en anglais",
        eps:     "Prise de contact EPS — règles de sécurité, sports au programme de 8ème",
      },
      {
        n: 2,
        theme: "Portrait d'un personnage — Les nombres jusqu'à 1 million",
        sous:  "Lecture et écriture des grands nombres — vocabulaire du portrait",
        mala_theme:  "Madio izay — Lov p.9 (vakiteny : propreté et santé, personnage modèle)",
        mala_litera: "Ny fahadiovana — fampiharana ny voambolana vaovao sy ny famintinana",
        arith:   "Les nombres de 1 à 1 million — lecture, écriture, décomposition en classes (M·C·D·U)",
        geom:    "Les lignes — droite, demi-droite, segment, courbe ; classification des angles",
        sm:      "Mesure de longueur — km, m, dm, cm, mm : conversions et exercices",
        cu:      "Les différentes parties du corps humain — squelette, organes, systèmes et fonctions",
        fr:      "Portrait d'un personnage — La phrase GNS/GV (texte : Inscription scolaire)",
        geo:     "La Terre : globe terrestre et planisphère — localisation par coordonnées géographiques",
        tantara: "Ny ilàna ny tantara — Niavian'ny Malagasy : taona sy taonjato",
        ffmom:   "Fifanampian'ny mpiarabelona — entraide entre voisins et vie communautaire",
        anglais: "School things — matériel scolaire, vocabulaire de la vie de classe",
        eps:     "Athlétisme — course de vitesse : technique de course et chronométrage sur 60 m",
      },
      {
        n: 3,
        theme: "Portrait d'un personnage suite — Numération et mesure des angles",
        sous:  "Comparaison de nombres — mesure et tracé d'angles au rapporteur",
        mala_theme:  "I Fano Lov P12 — lecture expressive et compréhension de l'histoire de Fano",
        mala_litera: "Ny fanatanjahantena — ny teny verindroa sy fanazarana hiteny",
        arith:   "Les nombres jusqu'à 1 million — comparaison (< > =), ordre, encadrement",
        geom:    "Mesure des angles au rapporteur — angle aigu (< 90°), droit (90°), obtus (> 90°)",
        sm:      "Mesure de longueur suite — exercices de conversion et résolution de problèmes",
        cu:      "L'articulation et les os — types d'articulations, fractures, premiers soins",
        fr:      "Portrait d'un personnage suite — COD et COI (texte : Monsieur, elle copie)",
        geo:     "Les grands repères du globe — pôles, équateur, tropiques, méridiens, parallèles",
        tantara: "Taona sy ny taonjato — le calendrier, les siècles, la chronologie à Madagascar",
        ffmom:   "Fahaizamiaina — droits et responsabilités des élèves à l'école",
        anglais: "School things continued — activités scolaires et routine quotidienne de classe",
        eps:     "Athlétisme — saut en longueur : technique d'élan, appel et réception",
      },
      {
        n: 4,
        theme: "Relations familiales — Les nombres jusqu'au milliard",
        sous:  "Documents officiels — grands nombres et calcul d'angles",
        mala_theme:  "Ray aman-dreny P.21 — ny fifandraisana eo amin'ny ankohonana",
        mala_litera: "Mpanolotra : hoy / hono — discours indirect et rapportés en malagasy",
        arith:   "Les nombres de 1 million à 1 milliard — lecture, écriture, décomposition",
        geom:    "Calcul d'angles — angles supplémentaires (somme = 180°), complémentaires (somme = 90°)",
        sm:      "Mesure de masse — g, dag, hg, kg, q, t : conversions et exercices pratiques",
        cu:      "L'œil et l'oreille — anatomie, fonctionnement, défauts de vision et d'audition",
        fr:      "Documents officiels — CCT et CCL (texte : J'ai une carte d'identité)",
        geo:     "Les mouvements de la Terre — rotation (jour/nuit), révolution (saisons)",
        tantara: "Ireo vanim-potoanan'ny tantaran'i Madagasikara — les grandes périodes historiques",
        ffmom:   "Fifandraisan'ny fianakaviana — rôles, liens et responsabilités dans la famille",
        anglais: "Greeting revisited — salutations formelles et informelles selon le contexte",
        eps:     "Athlétisme — saut en longueur : performance mesurée (5 essais, noter le meilleur)",
      },
      {
        n: 5,
        theme: "Relations entre amis — Grands nombres : opérations",
        sous:  "Les relations sociales — opérations sur les grands nombres",
        mala_theme:  "Mpihavana tsy mifankalala Lov 25 — deux amis qui ne s'entendent plus",
        mala_litera: "Andraikitry ny tsirairay eo amin'ny ankohonana — responsabilités familiales",
        arith:   "Les nombres de 1 million à 1 milliard — comparaison, encadrement, problèmes",
        geom:    "Calcul d'angles — exercices d'application avancés avec le rapporteur",
        sm:      "Mesure de masse suite — exercices complexes et problèmes de la vie réelle",
        cu:      "La langue et le nez — sens du goût et de l'odorat, rôles biologiques et soins",
        fr:      "La classe et ses règles — pronoms personnels (texte : En classe, il y a des règles)",
        geo:     "Rôle du soleil — lumière, chaleur, énergie solaire et photosynthèse",
        tantara: "Les Arabes à Madagascar — Arabo teto Madagasikara : commerce et Islam",
        ffmom:   "Fifandraisan'ny haben'ny ankohonana sy ny sokajim-pilàna — liens sociaux",
        anglais: "Classroom objects — désigner et demander des objets de la classe en anglais",
        eps:     "Athlétisme — course de relais 4×60 m : technique de passage du témoin",
      },
      {
        n: 6,
        theme: "Traditions malgaches — Addition et soustraction des entiers",
        sous:  "Fanarahana fomban-drazana — opérations sur les grands nombres",
        mala_theme:  "Fanarahana fomban-drazana P31 — respecter les traditions ancestrales malgaches",
        mala_litera: "Ny havana / Ny Riba — vocabulaire des relations familiales et sociales",
        arith:   "Addition et soustraction des grands nombres (avec et sans retenue) — technique posée",
        geom:    "Le carré — propriétés, construction à l'équerre, calcul de périmètre",
        sm:      "Mesure de capacité — litre, dl, cl, ml : conversions et problèmes concrets",
        cu:      "La peau — protection, thermorégulation, sens du toucher, hygiène de la peau",
        fr:      "L'école — les déterminants (texte : La leçon de musique p.38)",
        geo:     "Les océans et les continents — localisation, superficies et caractéristiques",
        tantara: "Fiainan'ny Malagasy fahagola — modes de vie des Malgaches avant la colonisation",
        ffmom:   "Ny fifanakalozan-kevitra — débat respectueux et échange d'idées citoyennes",
        anglais: "The weather — parler de la météo en anglais (sunny, rainy, cloudy, cold, hot)",
        eps:     "Jeux collectifs — règles fondamentales, fair-play et esprit d'équipe",
      },
      {
        n: 7,
        theme: "La ville et ses services — Multiplication et division des entiers",
        sous:  "Services urbains — multiplication et division posées des grands nombres",
        mala_theme:  "Mananjary Lov P35 — la vie dans une ville côtière de Madagascar",
        mala_litera: "Ny tanàna — vocabulaire de la vie urbaine et des services de la ville",
        arith:   "Multiplication et division des grands nombres — technique posée et vérification",
        geom:    "Le carré — calcul d'un côté à partir du périmètre ou de l'aire",
        sm:      "Mesure de capacité suite — correspondances et exercices de conversion complexes",
        cu:      "L'appareil digestif et les dents — anatomie, digestion, hygiène dentaire",
        fr:      "Les événements de la vie — genre et nombre des noms (texte : Projet de fête)",
        geo:     "Madagascar dans le monde — localisation, données géographiques, voisins",
        tantara: "La première rencontre avec les Européens — Nahitan'ny Eropeana an'i M/car voalohany",
        ffmom:   "Fanajana ny teny nomena — tenir sa parole, respecter ses engagements",
        anglais: "The clothes — vocabulaire des vêtements, décrire une tenue en anglais",
        eps:     "Jeux collectifs — formation tactique et stratégie d'équipe en situation de jeu",
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PÉRIODE 2 — Octobre fin + Novembre + Décembre (7 semaines)
  // Thème général : Hygiène et santé — Les nombres décimaux — Fractions
  // ═══════════════════════════════════════════════════════════════════════
  {
    num: 2, libelle: '2ème Période', debut: '27/10/2025',
    semaines: [
      {
        n: 1,
        theme: "La vie en ville — Multiplication et division des entiers (suite)",
        sous:  "Activités urbaines — opérations sur les entiers et calcul d'aire du carré",
        mala_theme:  "Trano an-tanan-dehibe — les grandes maisons et immeubles en ville",
        mala_litera: "Asa aman-draharaha — les métiers et activités de la vie urbaine",
        arith:   "Multiplication et division des entiers — problèmes complexes de la vie réelle",
        geom:    "Le carré — calcul de l'aire (S = côté × côté) et applications pratiques",
        sm:      "Mesure de surface — cm², dm², m² : notion, estimation et conversions",
        cu:      "Les aliments — groupes alimentaires, ration équilibrée, hygiène alimentaire",
        fr:      "Les moments de la vie sociale — genre et nombre des adjectifs (L'invitation)",
        geo:     "Les îles de l'océan Indien — Madagascar, Réunion, Maurice, Comores, Mayotte",
        tantara: "Ireo fanjakana nisy teto Madagasikara — les grands royaumes malgaches (aperçu)",
        ffmom:   "Tobim-pahasalamana — le centre de santé communautaire, accès aux soins",
        anglais: "The numbers — chiffres, calcul mental et mathématiques simples en anglais",
        eps:     "Athlétisme — saut en longueur : compétition amicale avec mesure des distances",
      },
      {
        n: 2,
        theme: "L'école et ses règles — Les nombres décimaux",
        sous:  "Vie scolaire — notion et écriture des nombres décimaux",
        mala_theme:  "Ny sekoly ao an-tanàna — une école en ville : organisation et règles",
        mala_litera: "Ny sekoly — vocabulaire scolaire et organisation de la vie de classe",
        arith:   "Les nombres décimaux — notion, écriture, lecture, partie entière et partie décimale",
        geom:    "Le rectangle — propriétés, construction, calcul du périmètre et demi-périmètre",
        sm:      "Mesure de surface — exercices d'estimation et calculs pratiques",
        cu:      "L'appareil respiratoire — poumons, bronches, trachée, respiration, maladies (asthme)",
        fr:      "L'invitation — pronoms relatifs : qui, que, qu', où (texte : L'invitation)",
        geo:     "La carte de Madagascar — lecture, orientation, échelle, coordonnées géographiques",
        tantara: "Ireo endrim-pifandraisana tamin'ny vahiny — contacts commerciaux et culturels",
        ffmom:   "Fanajana ny fitsipiky ny sekoly — respecter le règlement intérieur de l'école",
        anglais: "The body — les parties du corps en anglais (head, shoulders, knees and toes...)",
        eps:     "Football — règles de base, positions des joueurs, échauffement spécifique",
      },
      {
        n: 3,
        theme: "Patriotisme et identité — Addition et soustraction des décimaux",
        sous:  "Amour de la patrie — opérations sur les nombres décimaux",
        mala_theme:  "Taratasin'i Fano — lettre personnelle : format, contenu et analyse stylistique",
        mala_litera: "Ny fitiavan-tanindrazana — vocabulaire civique et patriotique en malagasy",
        arith:   "Addition et soustraction des nombres décimaux (avec et sans retenue) — technique",
        geom:    "Le rectangle — calcul d'une dimension à partir du périmètre connu",
        sm:      "Mesure agraire — l'are (a) et l'hectare (ha) : notion et conversions",
        cu:      "L'appareil reproducteur — bases de la reproduction humaine (adapté à l'âge)",
        fr:      "Hygiène et santé — adjectifs possessifs (texte : Visite médicale au dispensaire)",
        geo:     "Le relief de Madagascar — hautes terres centrales, côtes, plaines, massifs",
        tantara: "Fanjakana Betsileo — le royaume Betsileo : organisation politique et culturelle",
        ffmom:   "Fitsipika mifehy ny fifamoivoizana — règles de circulation et sécurité routière",
        anglais: "The colour — les couleurs en anglais : nommer, décrire, comparer des objets colorés",
        eps:     "Football — techniques de base : contrôle de balle, passe précise, tir au but",
      },
      {
        n: 4,
        theme: "Madagascar notre patrie — Multiplication et division des décimaux",
        sous:  "Unité nationale — opérations avancées sur les décimaux",
        mala_theme:  "Madagasikara tanindrazanay — notre pays, son histoire et son identité culturelle",
        mala_litera: "Firaisam-pirenena — unité nationale, diversité culturelle et cohésion sociale",
        arith:   "Multiplication et division des nombres décimaux — règle de déplacement de virgule",
        geom:    "Le rectangle — calcul de l'aire (S = longueur × largeur) et applications",
        sm:      "Correspondance entre mesures de surface et mesures agraires (m² ↔ a ↔ ha)",
        cu:      "L'appareil urinaire — les reins, la filtration du sang, l'urine, hygiène rénale",
        fr:      "Hygiène et santé suite — adjectifs démonstratifs (texte : Hygiène et santé)",
        geo:     "Les cours d'eau de Madagascar — fleuves principaux, rivières et lacs",
        tantara: "Fanjakana Sakalava — le royaume Sakalava : structure, territoire et culture",
        ffmom:   "Fanajana fananam-pirenena — patrimoine national malgache, identité et culture",
        anglais: "The fruits — les fruits tropicaux, leur importance à Madagascar et en Afrique",
        eps:     "Football — jeu en équipe : stratégie collective, rôles des postes, match amical",
      },
      {
        n: 5,
        theme: "Agriculture malgache — Opérations décimales avancées",
        sous:  "Riziculture et élevage — calculs décimaux complexes et triangle",
        mala_theme:  "Fambolena vary any Alaotra — la culture du riz au lac Alaotra (texte documentaire)",
        mala_litera: "Ny voly vary — techniques et vocabulaire de la riziculture malgache",
        arith:   "Multiplication et division des décimaux — problèmes complexes de la vie quotidienne",
        geom:    "Le triangle — propriétés (somme angles = 180°), calcul de l'aire (B × H ÷ 2)",
        sm:      "Correspondance mesures de surface et agraires — exercices approfondis",
        cu:      "L'appareil circulatoire et le sang — cœur, artères, veines, pouls, hypertension",
        fr:      "Maladie et prévention — le présentatif 'il y a' (texte : L'interview d'un infirmier)",
        geo:     "Le climat de Madagascar — les 4 grandes zones climatiques et leurs caractéristiques",
        tantara: "Fanjakana Betsimisaraka — le royaume Betsimisaraka : histoire et organisation",
        ffmom:   "Fahasalamana — prévention des maladies courantes, vaccination et hygiène",
        anglais: "The vegetables — les légumes tropicaux, jardinage et alimentation saine",
        eps:     "Basketball — passe, dribble, tir au panier : techniques fondamentales",
      },
      {
        n: 6,
        theme: "Le temps et les saisons — Les fractions",
        sous:  "Saisons à Madagascar — notion de fraction, comparaison et simplification",
        mala_theme:  "Ny lohataona Lov p.60 — la saison pluvieuse et ses caractéristiques à Madagascar",
        mala_litera: "Ny fitaovam-pamokarana — outils agricoles utilisés selon les saisons",
        arith:   "Les fractions — numérateur, dénominateur, fraction propre/impropre, comparaison, simplification",
        geom:    "Le trapèze — propriétés, bases parallèles, classification et calcul de l'aire",
        sm:      "Les nombres sexagésimaux — heure, minute, seconde : lecture, écriture et conversion",
        cu:      "Les parasitoses intestinales et le paludisme — agent, vecteur, symptômes, prévention",
        fr:      "Le temps et les saisons — l'interrogation 'est-ce que ?' (texte : La sécheresse dans le sud)",
        geo:     "La végétation de Madagascar — forêt tropicale, savane, mangrove, épineux du sud",
        tantara: "Fanjakana Merina — le royaume Merina : Andrianampoinimerina et l'unification de l'île",
        ffmom:   "Fampahalalam-baovao — rôle des médias, information citoyenne et sources fiables",
        anglais: "The animals — animaux sauvages et domestiques, espèces endémiques de Madagascar",
        eps:     "Basketball — jeu 3×3 : stratégie de jeu, récupération de balle et contre-attaque",
      },
      {
        n: 7,
        theme: "Révision P2 — Les fractions décimales",
        sous:  "Consolidation des acquis — fractions décimales et révision générale P2",
        mala_theme:  "Ny fahavaratra Lov P.61 — la saison des pluies, l'agriculture et les activités saisonnières",
        mala_litera: "Ny voly hazo — l'arboriculture, la gestion des vergers et ressources forestières",
        arith:   "Les fractions décimales — dixièmes, centièmes, millièmes et conversions fraction↔décimal",
        geom:    "Le parallélogramme — propriétés, côtés parallèles, diagonales et calcul de l'aire",
        sm:      "Conversion des nombres complexes — transformer des durées en heures décimales",
        cu:      "La tuberculose et la peste — agents pathogènes, transmission, prévention et traitement",
        fr:      "Le temps et les saisons — pronoms interrogatifs (texte : Le climat de Madagascar)",
        geo:     "Effectif et répartition de la population malgache — répartition géographique",
        tantara: "Ny fanjanahantany — la colonisation française de Madagascar (1895-1960)",
        ffmom:   "Fampahalalam-baovao suite — évaluer l'information, distinguer vrai et faux",
        anglais: "The family — les membres de la famille en anglais, expressions d'appartenance",
        eps:     "Révision EPS P2 — évaluation des compétences sportives de la période",
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PÉRIODE 3 — Janvier + Février (7 semaines)
  // Thème général : Le commerce et la ville — Fractions et budget familial
  // ═══════════════════════════════════════════════════════════════════════
  {
    num: 3, libelle: '3ème Période', debut: '05/01/2026',
    semaines: [
      {
        n: 1,
        theme: "Les animaux de Madagascar — Réduction au même dénominateur",
        sous:  "Faune malgache et protection — fractions à même dénominateur",
        mala_theme:  "Fararano Lov p.L22 — la saison froide et les activités animales saisonnières",
        mala_litera: "Ny karazam-biby — classification des animaux : vertébrés et invertébrés",
        arith:   "Fractions : réduction au même dénominateur (PPCM) — méthode et exercices",
        geom:    "Le losange — propriétés, diagonales perpendiculaires et calcul de l'aire",
        sm:      "Addition et soustraction des nombres complexes (heures, minutes, secondes)",
        cu:      "Dysenterie et choléra — maladies des mains sales, transmission, prévention, ORS",
        fr:      "Le cyclone — adverbes interrogatifs (texte : Devant la vitrine — commerce)",
        geo:     "La pyramide des âges — lecture et interprétation de la structure démographique",
        tantara: "Tolom-panafahana — les premières résistances à la colonisation française",
        ffmom:   "Fitsipika mifehy ny fifamoivoizana — code de la route, transport et sécurité",
        anglais: "The room — les pièces de la maison et le mobilier en anglais",
        eps:     "Judo — tenue, respect de l'adversaire, chutes ukemi, technique d'entrée de base",
      },
      {
        n: 2,
        theme: "Environnement naturel — Addition et soustraction des fractions",
        sous:  "Protection de la forêt — opérations sur les fractions",
        mala_theme:  "Fanolokolona ny fambolena p.75 — protéger l'agriculture et l'environnement naturel",
        mala_litera: "Ny doro tanety sy ny tavy — feux de brousse et déforestation : causes et effets",
        arith:   "Addition et soustraction des fractions (même dénominateur et dénominateurs différents)",
        geom:    "Le cercle — rayon, diamètre, centre, corde, arc, définitions et vocabulaire",
        sm:      "Multiplication et division des nombres complexes (heures et minutes)",
        cu:      "Le secourisme — premiers secours : position latérale, arrêt hémorragie, brûlures",
        fr:      "Commerce et publicité — pronoms possessifs (texte : Devant la vitrine suite)",
        geo:     "Croissance de la population malgache — natalité, mortalité, espérance de vie",
        tantara: "Ny fahaleovantena — l'indépendance de Madagascar : 26 juin 1960, acteurs clés",
        ffmom:   "Ny sampan-draharaham-panjakana — les institutions de l'État malgache",
        anglais: "The means of transport — les moyens de transport, itinéraires en anglais",
        eps:     "Judo — projection O-Goshi : technique, sécurité et pratique par binômes",
      },
      {
        n: 3,
        theme: "Faune sauvage — Multiplication et division des fractions",
        sous:  "Protection de la faune malgache — opérations avancées sur les fractions",
        mala_theme:  "Ny haiafo Lov p.80 — les animaux sauvages de Madagascar et leur protection",
        mala_litera: "Doro tanety sy ny tavy suite — solutions : reforestation, agroforesterie",
        arith:   "Multiplication et division des fractions — règles, simplification, applications",
        geom:    "Le cercle — calcul de la surface (S = π × r²) et du rayon ou diamètre",
        sm:      "Multiplication et division des nombres complexes suite — problèmes pratiques",
        cu:      "Le chat et le chien — animaux domestiques, soins vétérinaires, utilité à Madagascar",
        fr:      "Commerce et itinéraire en ville — pronoms démonstratifs (texte : Perdu dans la ville)",
        geo:     "L'exode rural — causes économiques, conséquences urbaines et solutions",
        tantara: "Repoblika I — la Première République (1960-1975) : Tsiranana, politiques",
        ffmom:   "Ady amin'ny endrim-panavakavahana — lutter contre toutes formes de discrimination",
        anglais: "The opposite — les contraires en anglais (fast/slow, big/small, hot/cold...)",
        eps:     "Judo — tournoi amical par équipes : arbitrage, respect, ippon et waza-ari",
      },
      {
        n: 4,
        theme: "L'élevage à Madagascar — Budget familial",
        sous:  "Élevage et pêche — gestion du budget familial et solides géométriques",
        mala_theme:  "Fiompian-dry Tremo P.90 — l'élevage de poulets : gestion quotidienne et commercialisation",
        mala_litera: "Ny fiompiana — l'élevage à Madagascar : bovins, volaille, porcins, techniques",
        arith:   "Le budget familial — recettes, dépenses, épargne, équilibre budgétaire et déficit",
        geom:    "Le cube — développé, surface latérale (SL), surface de base (SB), surface totale (ST)",
        sm:      "Mesure de volume — cm³, dm³, m³ : notion d'espace et premières conversions",
        cu:      "Le poisson — anatomie, mode de vie aquatique, pêche, conservation et valeur nutritive",
        fr:      "La ville : quartiers et itinéraires — lettres finales muettes (texte : Perdu dans la ville)",
        geo:     "Les grandes villes de Madagascar — Antananarivo, Toamasina, Mahajanga, Fianarantsoa",
        tantara: "Tetezamita I — la première transition politique (1972-1975) : Ramanantsoa",
        ffmom:   "Ady amin'ny endrim-panavakavahana — égalité des sexes et dignité humaine",
        anglais: "Date and time — dire la date, l'heure, les jours de la semaine et les mois",
        eps:     "Volleyball — manchette, service par en bas, règles de base et placement en jeu",
      },
      {
        n: 5,
        theme: "Au bord de la mer — Les échanges commerciaux",
        sous:  "Voyages et littoral — échanges commerciaux et solides géométriques",
        mala_theme:  "Fanaovam-beloma teny amoron-dranomasina p100 — adieux au bord de la mer",
        mala_litera: "Ny fifamoivoizana — les transports : avion, train, bus, taxi-brousse à Madagascar",
        arith:   "Les échanges commerciaux — prix d'achat, prix de revient, prix de vente, bénéfice, perte",
        geom:    "Le cube — calcul du volume (V = côté³) et applications pratiques de la vie quotidienne",
        sm:      "Mesure de volume suite — conversions complexes entre cm³, dm³ et m³",
        cu:      "La poule et l'œuf — élevage avicole, cycle de vie de l'œuf, incubation 21 jours",
        fr:      "Les transports en ville — voix active et passive (texte : Les retrouvailles p130)",
        geo:     "L'agriculture à Madagascar — types de cultures, riziculture, exportations (vanille, café)",
        tantara: "Repoblika II — la Deuxième République (1975-1993) : Ratsiraka, socialisme",
        ffmom:   "Ady amin'ny endrim-panavakavahana suite — solidarité et inclusion sociale",
        anglais: "Date and time suite — exercices avancés avec l'heure, les durées et le calendrier",
        eps:     "Volleyball — passe haute (manchon), service par en dessus, stratégie de match",
      },
      {
        n: 6,
        theme: "Préparer un voyage — Placement d'argent",
        sous:  "Voyage à Toamasina — intérêts simples et parallélépipède",
        mala_theme:  "Handao vetivety an'i Toamasina p104 — préparer et organiser un voyage à Toamasina",
        mala_litera: "Ny fitanterana — vocabulaire des transports et des voyages en malagasy",
        arith:   "Placement d'argent — capital initial, taux d'intérêt annuel, calcul des intérêts simples",
        geom:    "Le parallélépipède rectangle — développé, SL, SB, ST : formules et exercices",
        sm:      "Correspondance mesure de volume et capacité — 1 dm³ = 1 L, 1 cm³ = 1 mL",
        cu:      "L'abeille et le criquet — insectes utiles à Madagascar, miel, apiculture, pollinisation",
        fr:      "Les préparatifs de voyage — verbes en -GER/-CER (texte : Guide du voyageur p138)",
        geo:     "L'élevage à Madagascar — bovins zébus, ovins, porcins, volaille : zones et importance",
        tantara: "Tetezamita II — la deuxième transition politique (1991-1993) : pluralisme",
        ffmom:   "Révision générale FFMOM P3",
        anglais: "Révision générale Anglais P3",
        eps:     "Volleyball — match complet avec arbitrage élève et respect des règles officielles",
      },
      {
        n: 7,
        theme: "Révision P3 — Partages égaux et voyage",
        sous:  "Vol en avion et révision — partages équitables et mesures de volume",
        mala_theme:  "Fiaingan'ny fiaramanidina p109 — embarquer dans un avion, voyage aérien",
        mala_litera: "Ny fitanterana suite — révision vocabulaire des transports pour la P3",
        arith:   "Partages égaux — diviser équitablement une somme ou une quantité entre plusieurs",
        geom:    "Le parallélépipède rectangle — calcul du volume (V = l × L × h) et applications",
        sm:      "Révision générale des mesures P3 — longueur, masse, surface, capacité, volume",
        cu:      "La plante et la fleur — parties de la plante, photosynthèse, reproduction végétale",
        fr:      "Révision P3 Français — verbes pronominaux à l'impératif, orthographe",
        geo:     "La pêche à Madagascar — types de pêche, zones maritimes, importance économique",
        tantara: "Repoblika III — la Troisième République (1993-) : démocratie, constitution",
        ffmom:   "Révision générale FFMOM P3",
        anglais: "Révision générale Anglais P3",
        eps:     "Révision EPS P3 — évaluation des acquis sportifs de la troisième période",
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PÉRIODE 4 — Février fin + Mars (6 semaines)
  // Thème général : Le voyage — Partages et opérations complexes
  // ═══════════════════════════════════════════════════════════════════════
  {
    num: 4, libelle: '4ème Période', debut: '23/02/2026',
    semaines: [
      {
        n: 1,
        theme: "Journée des écoles — Révision et consolidation P1-P3",
        sous:  "Bilan pédagogique intermédiaire — révision de toutes les matières",
        mala_theme:  "Révision Malagasy P1-P3 — relecture des textes et révision des notions clés",
        mala_litera: "Révision générale Malagasy — tsianjery, fiteny, fitsipika",
        arith:   "Révision générale Arithmétique P1-P3 — entiers, décimaux, fractions, budget",
        geom:    "Révision générale Géométrie P1-P3 — angles, périmètres, aires, solides",
        sm:      "Révision générale Mesure P1-P3 — longueur, masse, surface, capacité, volume",
        cu:      "Révision générale Sciences P1-P3 — corps humain, animaux, plantes, maladies",
        fr:      "Révision générale Français P1-P3 — grammaire, orthographe, conjugaison",
        geo:     "Révision générale Géographie P1-P3 — Madagascar : relief, climat, population",
        tantara: "Révision générale Tantara P1-P3 — des origines aux républiques malgaches",
        ffmom:   "Révision générale FFMOM P1-P3 — droits, devoirs et valeurs citoyennes",
        anglais: "Révision générale Anglais P1-P3",
        eps:     "Révision générale EPS P1-P3 — bilan sportif semestriel",
      },
      {
        n: 2,
        theme: "Voyage et découvertes — Partages inégaux",
        sous:  "Visite et repas malgach — partager selon des proportions données",
        mala_theme:  "Famangiana sy sakafo P114 — visite chez des amis et repas traditionnels malgaches",
        mala_litera: "Filazana ho avy : te-, -ta — formes de la prédiction et de l'anticipation",
        arith:   "Partages inégaux — répartir une quantité selon des proportions données (ex : 2/5 et 3/5)",
        geom:    "Surface diminuée — calculer la surface restante après soustraction d'une surface",
        sm:      "Correspondance mesure de volume et capacité — exercices avancés combinés",
        cu:      "La graine et la germination — cycle de vie complet : de la graine au plant",
        fr:      "CC de cause — identifier et produire (texte : Mora en voyage p148)",
        geo:     "L'artisanat à Madagascar — raphia, broderie, vannerie, sculpture sur bois, lamba",
        tantara: "Tetezamita III — la troisième transition politique (2009-2013) : période de crise",
        ffmom:   "Révision et consolidation FFMOM P4",
        anglais: "Révision Anglais P4",
        eps:     "Jeux d'équipe — tournoi inter-classes : arbitrage élève et respect des règles",
      },
      {
        n: 3,
        theme: "Migrations et déménagements — Partages inégaux avancés",
        sous:  "S'installer dans une nouvelle ville — partages complexes et surfaces",
        mala_theme:  "Mifindra monina Lov p118 — quitter son village et s'installer en ville",
        mala_litera: "Mpamaritza sy mpisolo toerana — déterminants de lieu et pronoms spatiaux",
        arith:   "Partages inégaux avancés — problèmes à plusieurs étapes avec données réelles",
        geom:    "Surface augmentée — calculer la surface totale après ajout d'une surface",
        sm:      "Révision des mesures P4 — exercices combinant différents types de mesures",
        cu:      "Les états de la matière — solide, liquide, gaz, changements d'état et exemples",
        fr:      "CC de conséquence — identifier et produire (texte : Révision P4)",
        geo:     "Mines et énergies à Madagascar — chromite, graphite, ilménite, énergie solaire",
        tantara: "Repoblika IV — la Quatrième République (2013-) : institutions et gouvernance",
        ffmom:   "Ady amin'ny endrim-panavakavahana — justice sociale, équité et droits humains",
        anglais: "Révision Anglais P4",
        eps:     "Athlétisme — saut en hauteur : technique du fosbury, mesure et performance",
      },
      {
        n: 4,
        theme: "Révision générale P4 — L'intervalle",
        sous:  "Consolidation P4 — l'intervalle et le cylindre",
        mala_theme:  "Révision générale Malagasy P4",
        mala_litera: "Tsirinteny sara-droa — les proverbes malgaches à deux temps et leur signification",
        arith:   "L'intervalle — nombre de valeurs entières entre deux bornes (piquets et intervalles)",
        geom:    "Le cylindre — développé, surface latérale (SL = 2πrh), de base (SB = πr²), totale",
        sm:      "Révision générale des mesures P4 — problèmes récapitulatifs",
        cu:      "La balance et les vases communicants — principe de l'équilibre, vases communicants",
        fr:      "Verbe 'être' et 'avoir' au présent du conditionnel — formation et emplois",
        geo:     "L'industrie à Madagascar — industries agro-alimentaires, textiles, artisanales",
        tantara: "Fikambanana iraisam-pirenena — ONU, Union Africaine, SADC : rôles et enjeux",
        ffmom:   "Révision générale FFMOM P4",
        anglais: "Révision générale Anglais P4",
        eps:     "Révision EPS P4 — évaluation semestrielle : bilan sportif de la période",
      },
      {
        n: 5,
        theme: "Bilan P4 — Évaluation du 2ème trimestre",
        sous:  "Évaluation formelle de fin de deuxième trimestre (toutes matières)",
        mala_theme:  "Bilan Malagasy P4",
        mala_litera: "Bilan Malagasy P4",
        arith:   "Bilan Arithmétique P4",
        geom:    "Bilan Géométrie P4",
        sm:      "Bilan Mesure P4",
        cu:      "Bilan Connaissances Usuelles P4",
        fr:      "Bilan Français P4",
        geo:     "Bilan Géographie P4",
        tantara: "Bilan Tantara P4",
        ffmom:   "Bilan FFMOM P4",
        anglais: "Bilan Anglais P4",
        eps:     "Bilan EPS P4",
      },
      {
        n: 6,
        theme: "Récupération et consolidation P4",
        sous:  "Remédiation individuelle — renforcement des notions non maîtrisées",
        mala_theme:  "Récupération Malagasy P4 — relecture et exercices ciblés",
        mala_litera: "Récupération Malagasy P4",
        arith:   "Récupération Arithmétique P4 — exercices ciblés sur les lacunes identifiées",
        geom:    "Récupération Géométrie P4 — tracés et calculs de révision",
        sm:      "Récupération Mesure P4",
        cu:      "Récupération Connaissances Usuelles P4",
        fr:      "Récupération Français P4",
        geo:     "Récupération Géographie P4",
        tantara: "Récupération Tantara P4",
        ffmom:   "Récupération FFMOM P4",
        anglais: "Récupération Anglais P4",
        eps:     "Récupération EPS P4 — activités ludiques de consolidation sportive",
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PÉRIODE 5 — Avril + Mai + Juin (9 semaines)
  // Thème général : Révisions générales et bilan annuel
  // ═══════════════════════════════════════════════════════════════════════
  {
    num: 5, libelle: '5ème Période', debut: '20/04/2026',
    semaines: [
      {
        n: 1,
        theme: "Révision — Le métal, l'aimant et la boussole",
        sous:  "Révision générale des matières — sciences physiques : magnétisme",
        mala_theme:  "Révision Malagasy P5 S1 — relecture des textes clés de l'année",
        mala_litera: "Fandrasana teny — collecte et révision du vocabulaire annuel en malagasy",
        arith:   "L'intervalle suite — exercices d'application et problèmes de révision",
        geom:    "Révision Géométrie P5 S1 — figures planes, solides et calculs",
        sm:      "Révision Mesures P5 S1",
        cu:      "Le métal et l'aimant — propriétés magnétiques, pôles, boussole et orientation",
        fr:      "Révision Français P5 S1 — CC de but, conditionnel et subjonctif",
        geo:     "L'industrie à Madagascar suite — zones industrielles, enjeux économiques",
        tantara: "Ireo daty iraisam-pirenena — les dates clés mondiales : ONU, décolonisation",
        ffmom:   "Révision générale FFMOM P5 S1",
        anglais: "Révision générale Anglais P5 S1",
        eps:     "Révision EPS P5 S1 — évaluation des compétences athlétiques et collectives",
      },
      {
        n: 2,
        theme: "L'air, le sol et l'environnement",
        sous:  "Révision générale — sciences de l'environnement et développement durable",
        mala_theme:  "Révision Malagasy P5 S2",
        mala_litera: "Révision Malagasy P5 S2",
        arith:   "Révision Arithmétique P5 S2",
        geom:    "Révision Géométrie P5 S2",
        sm:      "Révision Mesures P5 S2",
        cu:      "L'air et le sol — composition, pollution atmosphérique, érosion, développement durable",
        fr:      "Révision Français P5 S2",
        geo:     "Révision Géographie P5 S2 — Madagascar dans son contexte régional et mondial",
        tantara: "Révision Tantara P5 S2",
        ffmom:   "Révision FFMOM P5 S2",
        anglais: "Révision Anglais P5 S2",
        eps:     "Révision EPS P5 S2",
      },
      {
        n: 3,
        theme: "La pile électrique — Révision générale I (Périodes 1 et 2)",
        sous:  "Circuit électrique — révision systématique des matières P1 et P2",
        mala_theme:  "Révision générale I Malagasy — textes P1 et P2",
        mala_litera: "Révision générale I Malagasy — grammaire et syntaxe P1 et P2",
        arith:   "Révision générale I — numération, opérations sur entiers et décimaux",
        geom:    "Révision générale I — lignes, angles, figures planes (carré, rectangle, triangle)",
        sm:      "Révision générale I — mesures de longueur, masse et capacité",
        cu:      "La pile électrique — circuit simple, conducteur/isolant, symboles, schéma",
        fr:      "Révision générale I Français — grammaire, conjugaison et orthographe P1-P2",
        geo:     "Révision générale I Géographie — Madagascar physique et humaine",
        tantara: "Révision générale I Tantara — des origines malgaches à la colonisation",
        ffmom:   "Révision générale I FFMOM — droits, lois et institutions",
        anglais: "Révision générale I Anglais — vocabulaire et grammaire P1-P2",
        eps:     "Révision générale I EPS — athlétisme et jeux collectifs",
      },
      {
        n: 4,
        theme: "Révision générale II — Périodes 3 et 4",
        sous:  "Révision systématique des matières P3 et P4",
        mala_theme:  "Révision générale II Malagasy — textes P3 et P4",
        mala_litera: "Révision générale II Malagasy — grammaire et syntaxe P3 et P4",
        arith:   "Révision générale II — fractions, budget familial, échanges, partages",
        geom:    "Révision générale II — figures géométriques, solides, volumes",
        sm:      "Révision générale II — mesures de surface, volume et mesures agraires",
        cu:      "Révision générale II — animaux, plantes, états de la matière et environnement",
        fr:      "Révision générale II Français — textes descriptifs, narration, argumentation",
        geo:     "Révision générale II Géographie — population, économie et activités malgaches",
        tantara: "Révision générale II Tantara — indépendance et républiques de Madagascar",
        ffmom:   "Révision générale II FFMOM — citoyenneté et vie en société",
        anglais: "Révision générale II Anglais — vocabulaire et grammaire P3-P4",
        eps:     "Révision générale II EPS — jeux collectifs et sports de combat (judo)",
      },
      {
        n: 5,
        theme: "Révision générale III — Programme complet",
        sous:  "Révision globale de toutes les matières pour la préparation aux examens",
        mala_theme:  "Révision générale III Malagasy — textes représentatifs de l'année",
        mala_litera: "Révision générale III Malagasy — synthèse grammaticale de l'année",
        arith:   "Révision générale III — problèmes récapitulatifs multi-notions",
        geom:    "Révision générale III — constructions géométriques et calculs variés",
        sm:      "Révision générale III — problèmes de mesure récapitulatifs",
        cu:      "Révision générale III — corps humain, maladies, sciences naturelles",
        fr:      "Révision générale III Français — production écrite et expression orale",
        geo:     "Révision générale III Géographie — carte commentée de Madagascar",
        tantara: "Révision générale III Tantara — frise chronologique de Madagascar",
        ffmom:   "Révision générale III FFMOM — synthèse civique de l'année",
        anglais: "Révision générale III Anglais — conversation et compréhension",
        eps:     "Révision générale III EPS — bilan sportif avec auto-évaluation",
      },
      {
        n: 6,
        theme: "Révision générale IV — Consolidation finale",
        sous:  "Approfondissement et consolidation définitive de tous les acquis de l'année",
        mala_theme:  "Révision générale IV Malagasy",
        mala_litera: "Révision générale IV Malagasy",
        arith:   "Révision générale IV — problèmes de synthèse et défis mathématiques",
        geom:    "Révision générale IV — évaluation des constructions et tracés",
        sm:      "Révision générale IV — problèmes de mesures récapitulatifs",
        cu:      "Révision générale IV — expériences simples et applications scientifiques",
        fr:      "Révision générale IV Français — expression écrite : le texte complet",
        geo:     "Révision générale IV Géographie — Madagascar dans le monde",
        tantara: "Révision générale IV Tantara — comparaison des époques",
        ffmom:   "Révision générale IV — citoyenneté active et engagement",
        anglais: "Révision générale IV Anglais — mini-exposé en anglais",
        eps:     "Révision générale IV EPS — tournoi de fin d'année",
      },
      {
        n: 7,
        theme: "Examen blanc — Révision finale complète",
        sous:  "Évaluation blanche simulant l'examen de fin d'année (toutes matières)",
        mala_theme:  "Examen blanc Malagasy",
        mala_litera: "Examen blanc Malagasy",
        arith:   "Examen blanc Arithmétique",
        geom:    "Examen blanc Géométrie",
        sm:      "Examen blanc Mesure",
        cu:      "Examen blanc Connaissances Usuelles",
        fr:      "Examen blanc Français",
        geo:     "Examen blanc Géographie",
        tantara: "Examen blanc Tantara",
        ffmom:   "Examen blanc FFMOM",
        anglais: "Examen blanc Anglais",
        eps:     "Examen blanc EPS",
      },
      {
        n: 8,
        theme: "Bilan annuel — Évaluation de fin d'année scolaire",
        sous:  "Évaluation formelle de fin d'année et remise des bulletins",
        mala_theme:  "Bilan annuel Malagasy",
        mala_litera: "Bilan annuel Malagasy",
        arith:   "Bilan annuel Arithmétique",
        geom:    "Bilan annuel Géométrie",
        sm:      "Bilan annuel Mesure",
        cu:      "Bilan annuel Connaissances Usuelles",
        fr:      "Bilan annuel Français",
        geo:     "Bilan annuel Géographie",
        tantara: "Bilan annuel Tantara",
        ffmom:   "Bilan annuel FFMOM",
        anglais: "Bilan annuel Anglais",
        eps:     "Bilan annuel EPS",
      },
      {
        n: 9,
        theme: "Fête de fin d'année — Célébration et remise de prix",
        sous:  "Célébration collective, spectacle des élèves et clôture de l'année scolaire",
        mala_theme:  "Fety fianarana — célébration de l'année scolaire 8ème",
        mala_litera: "Tononkalo sy hira — récitation et chant pour la fête de fin d'année",
        arith:   "Jeux mathématiques de fin d'année — défis et quizz",
        geom:    "Expositions de productions géométriques des élèves",
        sm:      "Activités de mesure ludiques : concours de précision",
        cu:      "Expériences scientifiques ludiques pour la fête",
        fr:      "Saynète ou dialogue en français pour la fête",
        geo:     "Présentation : Madagascar en images et en chiffres",
        tantara: "Spectacle historique : moments forts de l'histoire malgache",
        ffmom:   "Cérémonies et valeurs : discours des élèves sur la citoyenneté",
        anglais: "English song or short play for the celebration",
        eps:     "Démonstrations sportives et remise de prix EPS",
      },
    ],
  },
];

module.exports = { PERIODES_8EME };
