'use strict';

// Données thématiques par période/semaine — 11ème (CP)
// Utilisé par gen_11eme_v2.js

const PERIODES_11EME = [
  {
    num: 1, libelle: '1ère Période', debut: '09/09/2024',
    semaines: [
      { n:1, theme:'Iza moa aho? — La rentrée scolaire', sous:'Se présenter, découvrir la classe',
        lettre:'A', kajy:'Nombres de 0 à 5', fr:'Se présenter (prénom, âge, école)',
        ffmom:'Iza aho? — ny anako, ny taonako', hetsika:'Fampiasana ny fitaovam-pianarana',
        tsianjery:'Ny voalohany, faha-roa, fahatelo', arts:'Feo do-ré-mi: fihainoan\'ny tononkira',
        sary:'Sary ny tenako: hazo sary (dessin du corps)', eps:'Fitandremana ny vatana: fanazarana fitsangana' },
      { n:2, theme:'Iza moa aho? — Ma famille', sous:'La famille proche: père, mère, frères, sœurs',
        lettre:'E', kajy:'Nombres de 6 à 10', fr:'Ma famille (ray-amandreny, rahalahy, anabavy)',
        ffmom:'Ny fianakaviana: andraikitry ny tsirairay', hetsika:'Fanadiovana ny kilasy: fomba tsara',
        tsianjery:'Raiko, reniko, rahalahy', arts:'Feo fa-sol-la: mihira mirindra',
        sary:'Sary ny fianakavianako: famille en dessin', eps:'Lalao fitomboana: cours-sauts' },
      { n:3, theme:'Iza moa aho? — Mon corps', sous:'Les parties du corps: tête, bras, jambes',
        lettre:'I', kajy:'Addition jusqu\'à 5', fr:'Les parties du corps (tête, bras, jambes, mains)',
        ffmom:'Ny vatako sy ny fitandremany', hetsika:'Fanasana ny tanana tsara',
        tsianjery:'Lohako, tanako, tongotro', arts:'Hira: Ny vatako (chant sur le corps)',
        sary:'Dessin du corps complet: légendage', eps:'Lalao: mihetsika araka ny baiko' },
      { n:4, theme:'Iza moa aho? — Les couleurs et vêtements', sous:'Couleurs, vêtements de l\'école',
        lettre:'O', kajy:'Addition jusqu\'à 10', fr:'Les couleurs (rouge, bleu, vert, jaune...)',
        ffmom:'Ny akanjoko: fomba fitafiana tsara', hetsika:'Fanadiovana ny akanjoko',
        tsianjery:'Mena, manga, maintso, mavo', arts:'Tononkira sy loko: do-mi-sol',
        sary:'Lokon\'ny akanjoko: colorier un dessin', eps:'Fitaizana lava: haingana sy miadana' },
      { n:5, theme:'Iza moa aho? — Mes affaires d\'école', sous:'Fournitures scolaires: crayon, cahier...',
        lettre:'U', kajy:'Soustraction jusqu\'à 5', fr:'Mes affaires d\'école (crayon, cahier, cartable)',
        ffmom:'Ny fitaovam-pianaranako: fikarakarana azy', hetsika:'Fandrafetana toerana fianarana',
        tsianjery:'Penisily, boky, saco', arts:'Feo si-do: gamme complète',
        sary:'Dessin du cartable et affaires', eps:'Lalao kibo-bola: toucher et courir' },
      { n:6, theme:'Révision P1 — Les voyelles', sous:'Révision: A E I O U + nombres 0-10',
        lettre:'Révision A-E-I-O-U', kajy:'Révision P1 (nombres et opérations 0-10)', fr:'Révision P1',
        ffmom:'Fanavaozana P1: ny fianakaviana sy ny sekoly', hetsika:'Famaranana asa P1',
        tsianjery:'Fanavaozana kabary fohy', arts:'Fanavaozana hira P1',
        sary:'Sary fanavaozana P1', eps:'Lalao fanavaozana P1' },
      { n:7, theme:'Bilan P1', sous:'Évaluation de la première période',
        lettre:'Bilan', kajy:'Bilan P1', fr:'Bilan P1',
        ffmom:'Bilan FFMOM P1', hetsika:'Bilan Hetsika P1',
        tsianjery:'Bilan Tsianjery P1', arts:'Bilan Arts P1',
        sary:'Bilan Sary P1', eps:'Bilan EPS P1' },
    ]
  },
  {
    num: 2, libelle: '2ème Période', debut: '04/11/2024',
    semaines: [
      { n:1, theme:'Kojakojaina ny tenako — Le corps et l\'hygiène', sous:'Hygiène du corps, se laver',
        lettre:'B-D', kajy:'Soustraction jusqu\'à 10', fr:'Les parties du corps et l\'hygiène',
        ffmom:'Ny fahadiovan\'ny tenako: dingana isan\'andro', hetsika:'Fanasana tanana: savony sy rano',
        tsianjery:'Misasa, mihinana, matory tsara', arts:'Hira: Ny fahadiovanay',
        sary:'Dessin: comment je me lave le matin', eps:'Exercice doux: s\'étirer le matin' },
      { n:2, theme:'Kojakojaina ny tenako — Se nourrir', sous:'Les aliments, les repas',
        lettre:'K-G', kajy:'Nombres jusqu\'à 20', fr:'Les aliments (sakafo, légumes, fruits)',
        ffmom:'Ny fihinana tsara: sakafo ara-pahasalamana', hetsika:'Fikarakarana sakafo tsotra',
        tsianjery:'Vary, anana, hena, voankazo', arts:'Hira sakafo: mankafy ny sakafo',
        sary:'Dessin des aliments du marché', eps:'Lalao mihetsika: mitondra harona' },
      { n:3, theme:'Kojakojaina ny tenako — La maladie', sous:'Malade, médecin, médicaments',
        lettre:'F-V', kajy:'Addition jusqu\'à 20', fr:'Je suis malade (malade, docteur, médicament)',
        ffmom:'Aretina: fomba fisoroana sy fikarakarana', hetsika:'Fanomanana ranon\'aretina tsotra',
        tsianjery:'Feno, fo, fy — fianakaviana sy fitandremana', arts:'Hira: Aza marary',
        sary:'Dessin du médecin et du patient', eps:'Fitaizana: saina sy vatan-tsaina' },
      { n:4, theme:'Kojakojaina ny tenako — Le sommeil et repos', sous:'Bien dormir, se reposer',
        lettre:'H-R', kajy:'Soustraction jusqu\'à 20', fr:'Le sommeil (dormir tôt, se reposer)',
        ffmom:'Ny fialamboly sy ny tory tsara', hetsika:'Fanomanana fandriana tsara',
        tsianjery:'Hora matory: 8 ora isan\'alina', arts:'Hira alina: tononkira malemy',
        sary:'Dessin: ma chambre à coucher', eps:'Yoga enfant: respirations et étirements' },
      { n:5, theme:'Kojakojaina ny tenako — Le sport et les jeux', sous:'Sport, jeux, exercice physique',
        lettre:'L-M', kajy:'Nombres jusqu\'à 50', fr:'Les activités sportives (courir, sauter, nager)',
        ffmom:'Ny lalao sy ny fahasalamana: fiantraikany tsara', hetsika:'Fanamboarana taratasim-panatanjahan-tena',
        tsianjery:'Mizotra, miezaka, mahaiza', arts:'Hira: Mihazakazaka sy mihetsika',
        sary:'Dessin des sports (football, natation)', eps:'Parcours sportif: courir, sauter, ramper' },
      { n:6, theme:'Révision P2', sous:'Révision consonnes B,D,K,G,F,V,H,R,L,M + opérations 0-50',
        lettre:'Révision B,D,K,G,F,V,H,R,L,M', kajy:'Révision P2', fr:'Révision P2',
        ffmom:'Fanavaozana P2: ny tenako sy ny fahasalamana', hetsika:'Bilan asa P2',
        tsianjery:'Fanavaozana fihiran\'ny P2', arts:'Fanavaozana hira P2',
        sary:'Sary fanavaozana P2', eps:'Lalao fanavaozana P2' },
      { n:7, theme:'Bilan P2', sous:'Évaluation de la deuxième période',
        lettre:'Bilan', kajy:'Bilan P2', fr:'Bilan P2',
        ffmom:'Bilan P2', hetsika:'Bilan P2', tsianjery:'Bilan P2',
        arts:'Bilan P2', sary:'Bilan P2', eps:'Bilan P2' },
    ]
  },
  {
    num: 3, libelle: '3ème Période', debut: '06/01/2025',
    semaines: [
      { n:1, theme:'Fifandraisako — L\'école et les camarades', sous:'Ma classe, mes amis, l\'enseignant',
        lettre:'N-S', kajy:'Nombres jusqu\'à 100', fr:'À l\'école (camarade, enseignant, classe)',
        ffmom:'Ny sekoly: fitsipika sy ny andraikiny', hetsika:'Fanadiovana ny toeran\'ny sekoly',
        tsianjery:'Namanako, mpampianatra, sekoly', arts:'Hira: ny sekoly malalanay',
        sary:'Dessin de ma classe vue du dessus', eps:'Lalao: volankazo, football simplifié' },
      { n:2, theme:'Fifandraisako — Les animaux domestiques', sous:'Animaux familiers: poule, chien, zébu',
        lettre:'T-Z', kajy:'Addition jusqu\'à 100', fr:'Les animaux domestiques (poulet, chien, chat, vache)',
        ffmom:'Ny biby ao an-trano: fanaraha-maso', hetsika:'Fiompiana akoho: fanomezana sakafo',
        tsianjery:'Akoho, alika, omby, saka', arts:'Hira: ny biby ao an-tokantranay',
        sary:'Dessin des animaux de la ferme', eps:'Lalao "biby": imiter les animaux' },
      { n:3, theme:'Fifandraisako — Le village', sous:'Mon quartier, le marché, la mosquée/église',
        lettre:'P-TR', kajy:'Soustraction jusqu\'à 100', fr:'Dans le village (magasin, marché, mosquée)',
        ffmom:'Ny tanana: ny mpiara-belona tsara', hetsika:'Mampiasa rano tsara ao an-tanàna',
        tsianjery:'Tanana, tsena, ekoly, fiangonana', arts:'Hira: Ny tanananay',
        sary:'Dessin du marché du village', eps:'Course en équipe: relais village' },
      { n:4, theme:'Fifandraisako — Le marché', sous:'Acheter, vendre, compter au marché',
        lettre:'D-DR', kajy:'Multiplication: table de 2', fr:'Au marché (acheter, payer, rendre la monnaie)',
        ffmom:'Ny tsena: fomba tsara fividy', hetsika:'Fivarotan-javatra tsotra: jeu de marché',
        tsianjery:'Vidy, varotra, manome vola', arts:'Hira: Ao an-tsena',
        sary:'Dessin du marché avec les prix', eps:'Lalao "tsena": porter des charges légères' },
      { n:5, theme:'Fifandraisako — La nature', sous:'Arbres, fleurs, rivière — respect de la nature',
        lettre:'Révision consonnes N,S,T,Z,P,TR,D,DR', kajy:'Tables de 2, 5 et 10', fr:'La nature (arbre, fleur, rivière, colline)',
        ffmom:'Miaro ny tontolo iainana: tsy manimba', hetsika:'Fambolena zavamaniry: voa anana',
        tsianjery:'Hazo, voninkazo, rano, rova', arts:'Hira: Ny tontolo malalako',
        sary:'Dessin du paysage de mon village', eps:'Promenade dans la nature: observation' },
      { n:6, theme:'Révision P3', sous:'Révision générale P3: consonnes + opérations',
        lettre:'Révision P3', kajy:'Révision P3', fr:'Révision P3',
        ffmom:'Fanavaozana P3', hetsika:'Bilan P3', tsianjery:'Fanavaozana P3',
        arts:'Fanavaozana hira P3', sary:'Sary fanavaozana P3', eps:'Lalao fanavaozana P3' },
      { n:7, theme:'Bilan P3', sous:'Évaluation de la troisième période',
        lettre:'Bilan', kajy:'Bilan P3', fr:'Bilan P3',
        ffmom:'Bilan P3', hetsika:'Bilan P3', tsianjery:'Bilan P3',
        arts:'Bilan P3', sary:'Bilan P3', eps:'Bilan P3' },
    ]
  },
  {
    num: 4, libelle: '4ème Période', debut: '03/03/2025',
    semaines: [
      { n:1, theme:'Manavaka ny fananako — Mes affaires et vêtements', sous:'Décrire, comparer ses objets',
        lettre:'Diphtongues AO-AI', kajy:'Mesures de longueur (m, dm, cm, mm)', fr:'Mes objets et vêtements (grand, petit, long, court)',
        ffmom:'Ny fananako: mikarakara sy mitandrina', hetsika:'Fanitsiana akanjoka: manjaitra bokotra',
        tsianjery:'Lavitr\'erana, akaiky, lehibe, kely', arts:'Hira: Ny fananako sarobidy',
        sary:'Dessin et comparaison de tailles', eps:'Sauter à la corde: mesurer ses sauts' },
      { n:2, theme:'Manavaka ny fananako — Ma maison', sous:'Les pièces, les meubles, la propreté',
        lettre:'Diphtongues OI-OU', kajy:'Mesures de masse (kg, g)', fr:'Ma maison (salon, chambre, cuisine)',
        ffmom:'Ny trano: fanadiovana ny efitra tsirairay', hetsika:'Fandefasan\'entana: peser des objets',
        tsianjery:'Efitrano, latabatra, seza, kitay', arts:'Hira: Ny tranoko malalanay',
        sary:'Plan de ma maison vue du dessus', eps:'Portage équilibré: sacs et balises' },
      { n:3, theme:'Manavaka ny fananako — Faire les courses', sous:'Au marché: lire les prix, payer',
        lettre:'Diphtongues EI-IA', kajy:'Mesures de capacité (L, dL, cL)', fr:'Faire les courses (liste, prix, total)',
        ffmom:'Mpividy tsara: mihevitra ny vidiny', hetsika:'Fikarakarana rano fahasalamana: fikajiana',
        tsianjery:'Iray litatra, antsasaky, ampahatelo', arts:'Hira: Mividy eny am-tsena',
        sary:'Dessin de la liste de courses avec prix', eps:'Parcours: transporter des bouteilles d\'eau' },
      { n:4, theme:'Manavaka ny fananako — L\'argent malgache', sous:'Les ariary: compter et rendre la monnaie',
        lettre:'Révision diphtongues AO,AI,OI,OU,EI,IA', kajy:'La monnaie malgache (ariary)', fr:'L\'argent et les achats (combien ça coûte?)',
        ffmom:'Ny vola: tsy mandany poakaty', hetsika:'Varotra eny an-tsena: jeu de rôle',
        tsianjery:'Vola iray ariary, folo, zato', arts:'Hira: Ny vola tsara ampiasaina',
        sary:'Dessin des billets et pièces malgaches', eps:'Lalao: manao ny tsena' },
      { n:5, theme:'Révision P4', sous:'Révision générale P4: diphtongues + mesures',
        lettre:'Révision P4', kajy:'Révision P4', fr:'Révision P4',
        ffmom:'Fanavaozana P4', hetsika:'Bilan P4', tsianjery:'Fanavaozana P4',
        arts:'Fanavaozana hira P4', sary:'Sary fanavaozana P4', eps:'Lalao fanavaozana P4' },
      { n:6, theme:'Bilan P4', sous:'Évaluation de la quatrième période',
        lettre:'Bilan', kajy:'Bilan P4', fr:'Bilan P4',
        ffmom:'Bilan P4', hetsika:'Bilan P4', tsianjery:'Bilan P4',
        arts:'Bilan P4', sary:'Bilan P4', eps:'Bilan P4' },
    ]
  },
  {
    num: 5, libelle: '5ème Période', debut: '20/04/2025',
    semaines: [
      { n:1, theme:'Manaja ny tontolo — La nature', sous:'Arbres, fleurs, animaux sauvages',
        lettre:'Textes courts — lecture guidée', kajy:'Introduction au partage égal', fr:'La nature: les arbres et les fleurs de Madagascar',
        ffmom:'Miaro ny ala: tsy mandoro', hetsika:'Fambolena hazo: dingana fototra',
        tsianjery:'Ala, hazo, voninkazo, voankazo', arts:'Hira: Ny voary tontolo',
        sary:'Dessin d\'un paysage naturel de Madagascar', eps:'Promenade scolaire: observer la nature' },
      { n:2, theme:'Manaja ny tontolo — Les animaux de Madagascar', sous:'Lémuriens, caméléons, fosa',
        lettre:'Compréhension de texte: lecture autonome', kajy:'Division simple par 2 et par 5', fr:'Les animaux de Madagascar (lémur, caméléon)',
        ffmom:'Ny biby misy ao Madagasikara: arovana', hetsika:'Fikajiana ny biby ao an-tanana',
        tsianjery:'Gidro, tana, fosa, voay', arts:'Hira: Ny biby malagasy',
        sary:'Dessin d\'un lémur dans la forêt', eps:'Lalao: imiter les mouvements des animaux' },
      { n:3, theme:'Manaja ny tontolo — Protéger l\'environnement', sous:'Ne pas polluer, recycler, planter',
        lettre:'Production écrite: mini-texte sur la nature', kajy:'Géométrie: carré, rectangle, cercle, triangle', fr:'Protéger l\'environnement (ne pas jeter, recycler)',
        ffmom:'Ny tontolo: andraikitray hiarovana azy', hetsika:'Fanangonana fako: fomba tsara',
        tsianjery:'Aza mandoto, amboly hazo, arovy', arts:'Hira: Manaja ny tontolo',
        sary:'Affiche: message pour protéger la forêt', eps:'Nettoyage de la cour de l\'école' },
      { n:4, theme:'Manaja ny tontolo — L\'eau', sous:'L\'eau: une ressource précieuse à protéger',
        lettre:'Révision lecture et production', kajy:'Mesures du temps: heure, jour, semaine, mois', fr:'L\'eau (sources, usages, économie d\'eau)',
        ffmom:'Ny rano: loharano sarobidy', hetsika:'Fikajiana rano: fampiasana tsara',
        tsianjery:'Rano, loharano, riaka, renirano', arts:'Hira: Ny rano maimbo',
        sary:'Dessin du cycle de l\'eau simplifié', eps:'Natation ou jeux d\'eau en plein air' },
      { n:5, theme:'Révision générale I — Périodes 1 et 2', sous:'Révision: voyelles, consonnes 1, nombres 0-50',
        lettre:'Révision générale I', kajy:'Révision générale I', fr:'Révision générale I',
        ffmom:'Fanavaozana I', hetsika:'Fanavaozana I', tsianjery:'Fanavaozana I',
        arts:'Fanavaozana I', sary:'Fanavaozana I', eps:'Lalao fanavaozana I' },
      { n:6, theme:'Révision générale II — Périodes 3 et 4', sous:'Révision: consonnes 2, mesures, tables',
        lettre:'Révision générale II', kajy:'Révision générale II', fr:'Révision générale II',
        ffmom:'Fanavaozana II', hetsika:'Fanavaozana II', tsianjery:'Fanavaozana II',
        arts:'Fanavaozana II', sary:'Fanavaozana II', eps:'Lalao fanavaozana II' },
      { n:7, theme:'Révision générale III — Toute l\'année', sous:'Révision complète: tout le programme',
        lettre:'Révision générale III', kajy:'Révision générale III', fr:'Révision générale III',
        ffmom:'Fanavaozana III', hetsika:'Fanavaozana III', tsianjery:'Fanavaozana III',
        arts:'Fanavaozana III', sary:'Fanavaozana III', eps:'Lalao fanavaozana III' },
      { n:8, theme:'Bilan annuel', sous:'Évaluation de fin d\'année',
        lettre:'Bilan annuel', kajy:'Bilan annuel', fr:'Bilan annuel',
        ffmom:'Bilan annuel', hetsika:'Bilan annuel', tsianjery:'Bilan annuel',
        arts:'Bilan annuel', sary:'Bilan annuel', eps:'Bilan annuel' },
      { n:9, theme:'Fête de fin d\'année', sous:'Célébration, remise de prix, spectacle',
        lettre:'Fête — lecture de diplôme', kajy:'Jeux mathématiques', fr:'Fête de fin d\'année',
        ffmom:'Fety fianarana: fankafizana', hetsika:'Fanomanana ny fety',
        tsianjery:'Fety, fankafizana, dera', arts:'Spectacle de fin d\'année: chant et danse',
        sary:'Mon plus beau dessin de l\'année', eps:'Journée sportive de fin d\'année' },
    ]
  },
];

module.exports = { PERIODES_11EME };
