'use strict';

// Données thématiques par période/semaine — 7ème (CM2)
// Utilisé par gen_7eme_v2.js

const PERIODES_7EME = [
  {
    num: 1, libelle: '1ère Période', debut: '09/09/2024',
    semaines: [
      { n:1, theme:'La vie à l\'école et l\'environnement immédiat — La rentrée', sous:'Découverte de la classe, des camarades, règles de vie',
        mala_theme:'Voambolana vaovao: ny sekoly — ny kilasy', mala_litera:'Voaafatra tsotra: fehezanteny mitohy',
        calc:'Nombres jusqu\'au milliard: lecture, écriture, décomposition',
        fr:'LA VILLE: vocabulaire de base (rue, école, marché, mairie)',
        tantara:'Madagascar avant la colonisation: les royaumes (aperçu)',
        geo:'La Terre et ses caractéristiques: forme, dimensions',
        cu:'Le squelette humain: définition, rôle, principaux os',
        ffmom:'Iza aho? Ny maha-olom-pirenena Malagasy: zo sy adidy',
        hetsika:'Fanamboarana tany: fanomboana sy famboazana anana',
        arts:'Ny feo mozika: do, ré, mi, fa, sol, la, si — fihainoan\'ny tononkira',
        sary:'Fitaovana sy fomba: dessin d\'observation d\'un objet',
        eps:'Natation: rotations (plan ventral, position dorsale)' },
      { n:2, theme:'La vie à l\'école — Les relations sociales', sous:'Vivre ensemble, respect mutuel, camaraderie',
        mala_theme:'Fampahalalana momba ny mpiara-monina', mala_litera:'Famenonkafatra: fampiasana famenonkafatra ao amin\'ny fehezanteny',
        calc:'Nombres jusqu\'au milliard: comparaison, ordre, encadrement',
        fr:'Mots de la ville: se repérer, donner un itinéraire',
        tantara:'L\'origine des Malgaches: théories et preuves',
        geo:'Mouvements de la Terre: rotation et révolution',
        cu:'Les muscles: types, rôle dans les mouvements',
        ffmom:'Ny sekoly: ny kilasy, ny kaomity mpianatra',
        hetsika:'Fiompiana akoho: ny trano fiompiana, ny sakafo',
        arts:'Ny dihy misy ao amin\'ny faritra: salegy (pas de base)',
        sary:'Dessin d\'observation: sary hita maso (un objet)',
        eps:'Natation: enchaînement coulée ventrale + roulade' },
      { n:3, theme:'Environnement immédiat — Mon quartier, ma maison', sous:'Description du milieu de vie, vocabulaire spatial',
        mala_theme:'Ny tontolo manodidina: trano sy fari-piadidiana', mala_litera:'Fanazarana hiteny: fehezanteny mitohy — litorary',
        calc:'Unités de longueur: km, m, dm, cm, mm — conversion',
        fr:'Carte/plan: lire et comprendre un plan de quartier',
        tantara:'Les Malgaches anciens: mode de vie, agriculture',
        geo:'Relief de Madagascar: montagnes, plaines, plateaux',
        cu:'Le système nerveux: cerveau, moelle épinière, nerfs',
        ffmom:'Ny zo sy adidiko amin\'ny sekoly',
        hetsika:'Fahandroana atody: fomba sy dingana',
        arts:'Fanoratana feo: sol, do (solfège simplifié)',
        sary:'Sary firizy: décoration géométrique (formes apprises)',
        eps:'Natation: battements alternatifs jambes + coordination bras' },
      { n:4, theme:'La ville et ses services — Institutions locales', sous:'Mairie, poste, hôpital, école — rôles et fonctions',
        mala_theme:'Ny tanàna: ireo ivon\'ny asa', mala_litera:'Fanitarana fehezanteny: famenoana anarana sy velabelarana',
        calc:'Échelle sur une carte: calculer des distances réelles',
        fr:'Correspondance: lire une carte postale et y répondre',
        tantara:'Premiers contacts avec l\'Europe (XVIe siècle)',
        geo:'Types de côtes de Madagascar: falaises, plages, mangroves',
        cu:'Les aliments: étude du lait, catégories nutritionnelles',
        ffmom:'Ny fianakaviana: andraikitry ny ray-amandreny sy ny zanaka',
        hetsika:'Fandidiana sy fanjairana tsotra: fanombohana amin\'ny tady',
        arts:'Hira: ny hirampirenena sy ny vakodraza',
        sary:'Sary mifandray amin\'ny lohahevitra: dessin sur la ville',
        eps:'Natation: mouvements simultanés + respiration' },
      { n:5, theme:'Révision P1 — La vie à l\'école et la ville', sous:'Révision de toutes les matières P1',
        mala_theme:'Fanavaozana P1: ny sekoly sy ny tanàna', mala_litera:'Fanavaozana ny lesona: famintinana P1',
        calc:'Périmètre du carré et du rectangle (formule et calcul)',
        fr:'Grammaire: COD, COI, pronoms personnels',
        tantara:'Synthèse: frise chronologique Madagascar avant 1895',
        geo:'Climat de Madagascar: les 4 grands domaines climatiques',
        cu:'Équilibre alimentaire: pyramide alimentaire',
        ffmom:'Ny vondrombahoaka: ny kaominina sy ny ben\'ny tanàna',
        hetsika:'Fanamboarana taozavatra amin\'ny volomborona',
        arts:'Révision arts P1',
        sary:'Révision sary P1',
        eps:'Natation: propulsion — combinaison bras et jambes' },
      { n:6, theme:'Révision générale P1', sous:'Révision et approfondissement',
        mala_theme:'Fanavaozana ankapobeny P1', mala_litera:'Révision générale P1',
        calc:'Révision P1 Calcul',
        fr:'Révision P1 Français',
        tantara:'Révision Tantara P1',
        geo:'Révision Géo P1',
        cu:'Révision CU P1',
        ffmom:'Mifanaja sy mifankatia ao amin\'ny sekoly',
        hetsika:'Bilan Hetsika P1',
        arts:'Bilan Arts P1',
        sary:'Bilan Sary P1',
        eps:'Révision natation P1' },
      { n:7, theme:'Bilan P1', sous:'Évaluation première période',
        mala_theme:'Bilan P1', mala_litera:'Bilan P1',
        calc:'Bilan P1', fr:'Bilan P1',
        tantara:'Bilan P1', geo:'Bilan P1', cu:'Bilan P1',
        ffmom:'Bilan FFMOM P1', hetsika:'Bilan P1',
        arts:'Bilan P1', sary:'Bilan P1', eps:'Bilan P1' },
    ]
  },
  {
    num: 2, libelle: '2ème Période', debut: '04/11/2024',
    semaines: [
      { n:1, theme:'L\'alimentation saine — Les loisirs et la vie sociale', sous:'Alimentation équilibrée, loisirs à Madagascar',
        mala_theme:'Karazam-pihariana: ny fambolena sy fiompiana', mala_litera:'Votoatin-kafatra: fahitana sy fahazoana',
        calc:'Les fractions: numérateur, dénominateur, écriture, lecture',
        fr:'LES LOISIRS: vocabulaire (sport, musique, lecture, cinéma)',
        tantara:'Le Royaume de Madagascar au XIXe siècle: territoire, rois',
        geo:'La population malagasy: effectif, croissance démographique',
        cu:'La reproduction humaine: organes reproducteurs, rôles',
        ffmom:'Ny soa ho an\'ny rehetra: fiaraha-miasa vondrombahoaka',
        hetsika:'Fiompiana akoho: fandaharam-pikarakarana isan\'andro',
        arts:'Fanoratana feo: sol, la, si, do, re, mi (solfège P2)',
        sary:'Sary firizy: motifs symétriques — décoration complexe',
        eps:'Natation: mouvements alternatifs bras (crawl simplifié)' },
      { n:2, theme:'L\'alimentation — Bien se nourrir à Madagascar', sous:'Produits locaux, nutrition, recettes',
        mala_theme:'Ny tontolo iainana: rano, rivotra, tany', mala_litera:'Famenonkafatra: fehezanteny karazana',
        calc:'Fractions: équivalentes, simplification, comparaison',
        fr:'Mots et expressions: "Je fais du...", "J\'aime..." (loisirs)',
        tantara:'Andrianampoinimerina et Radama Ier: la grande île unifiée',
        geo:'Variables démographiques: natalité, mortalité, migration',
        cu:'Le cycle menstruel: fécondation, grossesse',
        ffmom:'Ny loisirs sy ny fialamba: zo sy tombony',
        hetsika:'Famolavolana taozavatra amin\'ny tanimanga',
        arts:'Ny dihy eo amin\'ny faritra: apprendre une danse traditionnelle',
        sary:'Sary mifandray amin\'ny lohahevitra: dessin sur les loisirs',
        eps:'Natation: mouvements simultanés (brasse simplifiée)' },
      { n:3, theme:'Les loisirs et la vie sociale — Activités culturelles', sous:'Sport, musique, littérature à Madagascar',
        mala_theme:'Ny aretimifindra: fomba fisoroana sy fikarakarana', mala_litera:'Fehezanteny (types): fampahalalana sy fiokoana',
        calc:'Fractions: addition et soustraction (même dénominateur)',
        fr:'Remplir une feuille de match / bulletin d\'adhésion à un club',
        tantara:'Les contacts avec les Anglais: missionnaires, commerce',
        geo:'L\'exode rural: définition, causes, conséquences',
        cu:'MST/SIDA: définition, transmission, prévention',
        ffmom:'Ny fisorohana aretina: fitandremana ny fahasalamana',
        hetsika:'Fandidiana sy fanjairana akanjon-jaza (couture)',
        arts:'Hira: chant sur la vie sociale',
        sary:'Sary fanairana: affiche sur la santé',
        eps:'Danse: salegy — pas de base + soa miditra' },
      { n:4, theme:'Loisirs — Sports et compétitions', sous:'Sports à Madagascar, règles, fair-play',
        mala_theme:'Ny fahadiovan\'ny vatana: fihetsika isan\'andro', mala_litera:'Asa an-tsoratra: fanaovana tatitra fohy',
        calc:'Multiplication d\'une fraction par un entier: applications',
        fr:'Pronoms relatifs: qui, que, qu\', où — règle et exercices',
        tantara:'Les contacts avec les Français: tensions et traités 1883-1885',
        geo:'Les grandes villes de Madagascar: Antananarivo, Toamasina...',
        cu:'Le paludisme: parasite, vecteur, symptômes, lutte',
        ffmom:'Ny fahadiovan\'ny toerana: sekoly, tanàna, tontolo',
        hetsika:'Famafazana voan\'anana: tany, fanamboarana, famafazana',
        arts:'Hira: mémorisation chant traditionnel complet',
        sary:'Sary mandravaka lahatsoratra: illustrer un texte',
        eps:'Danse: enchaînement complet + musique' },
      { n:5, theme:'Colonisation — Introduction', sous:'Débuts de la colonisation française à Madagascar',
        mala_theme:'Ny loisirs sy ny fialamba: ny fisakafoana, fahasalamana', mala_litera:'Fanavaozana ny lesona P2',
        calc:'LES ÉCHANGES COMMERCIAUX: prix d\'achat, vente, bénéfice',
        fr:'Discours indirect: Verbes dire, écrire, répondre — 5 temps indicatif',
        tantara:'Vers la colonisation: les événements de 1895',
        geo:'Fonctions des villes: administrative, économique, socioculturelle',
        cu:'La peste et le choléra: agents, transmission, lutte',
        ffmom:'Ny zavatra tian\'ny ankizy: fitakiana sy fomba tsara',
        hetsika:'Fikarakarana ny zanak\'akoho: sakafo, rano, toerana',
        arts:'Fanoratana feo sy dihy: enchaîner musique et mouvement',
        sary:'Sary mandravaka lahatsoratra: illustration publicitaire',
        eps:'Gymnastic: mouvements des bras (latéraux, verticaux)' },
      { n:6, theme:'Révision P2', sous:'Révision générale deuxième période',
        mala_theme:'Fanavaozana P2', mala_litera:'Révision générale P2',
        calc:'Révision P2 Calcul', fr:'Révision P2 Français',
        tantara:'Révision Tantara P2', geo:'Révision Géo P2', cu:'Révision CU P2',
        ffmom:'Mpiara-belona tsara: mifampitompo', hetsika:'Bilan P2',
        arts:'Bilan Arts P2', sary:'Bilan Sary P2', eps:'Révision EPS P2' },
      { n:7, theme:'Bilan P2', sous:'Évaluation deuxième période',
        mala_theme:'Bilan P2', mala_litera:'Bilan P2',
        calc:'Bilan P2', fr:'Bilan P2',
        tantara:'Bilan P2', geo:'Bilan P2', cu:'Bilan P2',
        ffmom:'Bilan P2', hetsika:'Bilan P2',
        arts:'Bilan P2', sary:'Bilan P2', eps:'Bilan P2' },
    ]
  },
  {
    num: 3, libelle: '3ème Période', debut: '06/01/2025',
    semaines: [
      { n:1, theme:'Les métiers et activités — Institutions de la République', sous:'Branches du gouvernement, fonctions civiques',
        mala_theme:'Ny Andrimpanjakana samihafa: ireo biraom-panjakana', mala_litera:'Fitsipiky ny teny: karazana teny',
        calc:'LES FACTURES: pourcentage (notion, calcul), remise, taxe',
        fr:'LES MÉTIERS: vocabulaire (médecin, enseignant, agriculteur...)',
        tantara:'Madagascar sous la colonisation (1895-1960): les statuts',
        geo:'L\'agriculture à Madagascar: types de cultures (riz, café, vanille)',
        cu:'La poule: parties du corps, mode de vie, élevage, utilité',
        ffmom:'Ny asan\'ny olona ao amin\'ny kaominina: ny sekretera',
        hetsika:'Fanamboarana taozavatra amin\'ny volomborona: voninkazo',
        arts:'Famerena ny feo rehetra: gamme complète + lecture notes',
        sary:'Sary firizy: fanoritana sy fandokoana motif géométrique',
        eps:'Gymnastic: chandelle, appui renversé groupé, roulade avant' },
      { n:2, theme:'Les métiers — Enquête et interview', sous:'Observer, interviewer, noter, présenter un métier',
        mala_theme:'Ny fampahalalana vaovao: gazety, radio, TV, internet', mala_litera:'Voambolana: fitsipiky ny fampiasana',
        calc:'Factures: lire, compléter et vérifier une facture',
        fr:'Enquête sur un métier: observer, interviewer, présenter',
        tantara:'Conséquences économiques de la colonisation: travail forcé',
        geo:'Problèmes de l\'agriculture malgache: techniques, manque de moyens',
        cu:'L\'œuf: coupe, éclosion (21 jours), utilité',
        ffmom:'Ny fitsipika ifanombonan\'ny asa: fifanarahana sy fepetra',
        hetsika:'Fandidiana sy fanjairana akanjon-jaza (costume)',
        arts:'Dihy: apprendre nouvelle danse traditionnelle régionale',
        sary:'Sary mandravaka tononkalo: illustrer un poème',
        eps:'Gymnastic: équilibre fessier, sautillés, enchaînement' },
      { n:3, theme:'Les métiers — Production et artisanat', sous:'Artisanat malgache, ressources naturelles',
        mala_theme:'Ny fivoaran\'ny kolontaina Malagasy: fomba amam-panao', mala_litera:'Fanazarana hiteny: maneho hevitra',
        calc:'UNITÉS DE VOLUME: m³, dm³, cm³ — notion, conversion',
        fr:'Élaboration d\'une recette: fabriquer, noter les étapes',
        tantara:'Conséquences sociales: système scolaire colonial, médecine',
        geo:'L\'élevage: animaux, grandes régions, types (extensif/intensif)',
        cu:'Le poisson: corps, respiration (branchies), élevage',
        ffmom:'Ny zon\'ny mpiasa: saram-piasana, fitsaharana, fiarovana',
        hetsika:'Fambolena mangahazo: fanamboarana tany, famafazana',
        arts:'Hira vakodraza: mémoriser + gestuelle',
        sary:'Sary mifandray amin\'ny lohahevitra: dessin sur la forêt',
        eps:'Athlétisme: course de vitesse 20m et 30m' },
      { n:4, theme:'Évolution coloniale — Résistance malgache', sous:'La résistance Menalamba, mouvement nationaliste',
        mala_theme:'Ny asan\'ny tantsaha: fambolena, fiompiana, jono', mala_litera:'Asa an-tsoratra: tatitra fohy',
        calc:'LES INTERVALLES: nombre de piquets vs intervalles',
        fr:'Discours indirect: rapporter les propos d\'un artisan',
        tantara:'La résistance Menalamba (1895-1897): causes, déroulement',
        geo:'La pêche: types, grandes zones de pêche à Madagascar',
        cu:'Le chien et le chat: caractéristiques, utilité, soins',
        ffmom:'Ny maha-andry lehilahy sy vehivavy mitovy eo amin\'ny asa',
        hetsika:'Fiompiana akoho: tombam-barotra rehetra',
        arts:'Enchaînement musique + danse + chant',
        sary:'Sary fanairana: affiche sur la protection de la forêt',
        eps:'Athlétisme: saut en longueur (élan, appel, réception)' },
      { n:5, theme:'Ressources naturelles — Agriculture et sylviculture', sous:'Ressources de Madagascar, développement durable',
        mala_theme:'Ny asan\'ny mpanao tantara: fikarohana vaovao', mala_litera:'Fanavaozana ny lesona P3',
        calc:'BUDGET FAMILIAL: gain, recette, dépense, économie, dette',
        fr:'Texte argumentatif: pour ou contre un métier?',
        tantara:'La résistance politique: VVS, Ralaimongo, MDRM',
        geo:'L\'exploitation forestière: utilisation et conséquences',
        cu:'L\'abeille: parties, colonie (reine, ouvrières), apiculture',
        ffmom:'Ny fitakiana sy ny fifandraisan-kevitra tsara eo amin\'ny asa',
        hetsika:'Fanamboarana zezika (compost): dingana sy tombony',
        arts:'Révision Arts P3',
        sary:'Révision Sary P3',
        eps:'Judo: Hon-gesagatame — maintien, retournement' },
      { n:6, theme:'Révision P3', sous:'Révision générale troisième période',
        mala_theme:'Fanavaozana P3', mala_litera:'Révision générale P3',
        calc:'Révision P3 Calcul', fr:'Révision P3 Français',
        tantara:'Révision Tantara P3', geo:'Révision Géo P3', cu:'Révision CU P3',
        ffmom:'Bilan FFMOM P3', hetsika:'Bilan P3',
        arts:'Bilan Arts P3', sary:'Bilan Sary P3', eps:'Révision EPS P3' },
      { n:7, theme:'Bilan P3', sous:'Évaluation troisième période',
        mala_theme:'Bilan P3', mala_litera:'Bilan P3',
        calc:'Bilan P3', fr:'Bilan P3',
        tantara:'Bilan P3', geo:'Bilan P3', cu:'Bilan P3',
        ffmom:'Bilan P3', hetsika:'Bilan P3',
        arts:'Bilan P3', sary:'Bilan P3', eps:'Bilan P3' },
    ]
  },
  {
    num: 4, libelle: '4ème Période', debut: '03/03/2025',
    semaines: [
      { n:1, theme:'Emploi — Énergie et ressources', sous:'Les sources d\'énergie à Madagascar',
        mala_theme:'Ny fanalalahana toekarena: ny sakantsakana', mala_litera:'Maneho hevitra: fanononana sy lantom-peo',
        calc:'LES PARTAGES: partages égaux (division et vérification)',
        fr:'LE VOYAGE: vocabulaire (gare, port, aéroport, hôtel)',
        tantara:'Les formes de la colonisation: économique, social, éducatif',
        geo:'L\'énergie à Madagascar: sources (bois, pétrole, solaire, hydro)',
        cu:'Les plantes: parties, photosynthèse',
        ffmom:'Ny fanalahana ny toekarena: fiombonan\'asa sy tombony',
        hetsika:'Fandidiana sy fanjairana tantin\'ivy sy mosara',
        arts:'Famerena ny feo rehetra + hira vakodraza',
        sary:'Sary fanairana "Slogan": affiche contre la déforestation',
        eps:'Judo: Randori debout — Kumi-kata + projection' },
      { n:2, theme:'Énergie — Ressources minières et industrie', sous:'Ressources minières de Madagascar',
        mala_theme:'Ny zon\'olo mbelona: zon\'ny ankizy', mala_litera:'Fanononana: haavon\'ny feo — manontany, manambara',
        calc:'Partages proportionnels: répartir selon des critères',
        fr:'Lire un plan de ville: repérer gares, hôtels, sites touristiques',
        tantara:'La résistance: VVS (1913), Ralaimongo (1929), MDRM (1946)',
        geo:'Les ressources minières: chromite, graphite, ilménite, saphir',
        cu:'La reproduction des plantes: sexuée et végétative',
        ffmom:'Ny zon\'ny ankizy: ny signa ny faritra (UNICEF, CDE)',
        hetsika:'Fanamboarana taozavatra amin\'ny ravin\'ampanga',
        arts:'Dihy: enchaînement toutes les danses + nouvelle danse',
        sary:'Fandravahana an-tsary: illustration d\'annonce publicitaire',
        eps:'Judo: technique O-Soto-Gari — déséquilibre + projection' },
      { n:3, theme:'Protection de l\'environnement', sous:'Lutte contre la déforestation, recyclage',
        mala_theme:'Ny endrika ny fampiharan\'ny zon\'ny ankizy', mala_litera:'Voambolana: teny vaovao sy fampiasana',
        calc:'Partages inégaux: résoudre des problèmes réels',
        fr:'Le personnel de voyage: chauffeur, pilote, hôtesse',
        tantara:'Les événements de 1947: soulèvement, répression, bilan',
        geo:'L\'artisanat: types (raphia, broderie, bois), matières premières',
        cu:'Le sol: types, dégradation, protection',
        ffmom:'Ny andraikitry ny ankizy: eo an-trano, sekoly, tanàna',
        hetsika:'Fandidiana sy fanjairana akanjon-jaza menavava (terminé)',
        arts:'Hira: composer une mélodie simple sur 4 notes',
        sary:'Fanamboarana taozavatra: dessin préparatoire feuilles',
        eps:'Athlétisme: saut en hauteur ou course en relais' },
      { n:4, theme:'L\'indépendance de Madagascar', sous:'Le chemin vers l\'indépendance (1946-1960)',
        mala_theme:'Ny andraikitry ny ankizy ao an-tokantrano sy sekoly', mala_litera:'Asa an-tsoratra: fitantarana fohy (5-8 fehezanteny)',
        calc:'NOMBRES SEXAGÉSIMAUX: heure, minute, seconde',
        fr:'Compléments circonstanciels de cause et de conséquence',
        tantara:'Le chemin vers l\'indépendance: 1946-1960',
        geo:'L\'industrie: types (agroalimentaire, textile, BTP)',
        cu:'États physiques de la matière: solide, liquide, gaz',
        ffmom:'Ny fitovian\'jo: malazan\'ny lalàna Malagasy',
        hetsika:'Fambolena mangahazo: famindrana zanak\'anana (repiquage)',
        arts:'Présentation artistique: chant + danse + musique pour classe',
        sary:'Sary mifandray amin\'ny lohahevitra: voyage',
        eps:'Basket-ball: occupation du terrain, tir et récupération' },
      { n:5, theme:'Révision P4', sous:'Révision générale quatrième période',
        mala_theme:'Fanavaozana ny lesona P4 rehetra', mala_litera:'Fanavaozana P4',
        calc:'Mouvement uniforme: vitesse = distance ÷ durée',
        fr:'Verbes irréguliers au conditionnel présent',
        tantara:'Le 26 juin 1960: l\'indépendance — acteurs, célébration',
        geo:'Les transports: routes (RN), voies ferrées, ports, aéroports',
        cu:'L\'air: composition, importance, pollution',
        ffmom:'Ny adidy amin\'ny tontolo iainana: miaro ny ala, rano, tany',
        hetsika:'Fanamboarana zezika: vokatra voavozona',
        arts:'Révision Arts P4',
        sary:'Révision Sary P4',
        eps:'Attaque en surnombre (3 contre 2): tactique' },
      { n:6, theme:'Bilan P4', sous:'Évaluation quatrième période',
        mala_theme:'Bilan P4', mala_litera:'Bilan P4',
        calc:'Bilan P4', fr:'Bilan P4',
        tantara:'Bilan P4', geo:'Bilan P4', cu:'Bilan P4',
        ffmom:'Bilan FFMOM P4', hetsika:'Bilan P4',
        arts:'Bilan P4', sary:'Bilan P4', eps:'Bilan P4' },
    ]
  },
  {
    num: 5, libelle: '5ème Période', debut: '20/04/2025',
    semaines: [
      { n:1, theme:'Vie sociale — Cérémonies malgaches', sous:'Famadihana, mariage, baptême',
        mala_theme:'Ny tontolo iainana: biby arovana sy zavamaniry sarobidy', mala_litera:'Maneho hevitra: fitsikerana sy fanakarana',
        calc:'VOLUME, CAPACITÉ, MASSE: correspondances (1L=1dm³)',
        fr:'LA VIE SOCIALE: cérémonies malgaches (famadihana, mariage)',
        tantara:'Les Républiques: Repoblika I (1960-1975)',
        geo:'Le commerce intérieur: produits échangés, marchés',
        cu:'Le métal et l\'aimant: propriétés, pôles, boussole',
        ffmom:'Ny adidy amin\'ny tontolo iainana: fikajiana ny ala sy rano',
        hetsika:'Fanamboarana taozavatra amin\'ny akorandriaka (bambou)',
        arts:'Révision: toutes les danses apprises',
        sary:'Sary: dessin libre sur l\'environnement de Madagascar',
        eps:'Judo: tournoi final (Randori + projections)' },
      { n:2, theme:'Environnement et pauvreté', sous:'La pauvreté à Madagascar: manifestations, causes, solutions',
        mala_theme:'Ny fikajiana ny tontolo iainana: fiaraha-monina', mala_litera:'Fanoritsoritana: milaza sary sy toe-javatra',
        calc:'Révision générale: les 4 opérations sur entiers et décimaux',
        fr:'Proposition subordonnée: "Je pense que...", "Il faut que..."',
        tantara:'Repoblika II (1975-1993): politique, économie',
        geo:'Le commerce extérieur: exportations (vanille, café)',
        cu:'La pile électrique: circuit simple, allumer une ampoule',
        ffmom:'Ny zon\'ny olom-pirenena: fifidianana, fahafahana miteny',
        hetsika:'Mandidy sy manjaitra tantin\'ivy sy mosara (costume)',
        arts:'Révision: tous les chants appris',
        sary:'Sary fanairana: affiche protection de la nature',
        eps:'Athlétisme: décathlon simplifié (course + saut + lancer)' },
      { n:3, theme:'Commerce et échanges', sous:'Commerce intérieur et extérieur, coopératives',
        mala_theme:'Ny vahoaka sy ny mpitondra: zon\'ny olom-pirenena', mala_litera:'Fitantarana: lahatsoratra fohy 10-15 fehezanteny',
        calc:'Révision générale: fractions (+ - × ÷) et problèmes',
        fr:'LA PROTECTION ENVIRONNEMENT: vocabulaire (déforestation, recyclage)',
        tantara:'Repoblika III (1993-): constitution, droits fondamentaux',
        geo:'La pauvreté à Madagascar: manifestations, causes',
        cu:'L\'environnement: pollution (air, eau, sol)',
        ffmom:'Ny fiombonan\'asa: kaoperativa, fiaraha-monina',
        hetsika:'Fanamboarana zezika: famaranana sy fampiasana',
        arts:'Création: chant court sur l\'environnement',
        sary:'Ny fahaizana mandoko: aquarelle ou gouache',
        eps:'Basket: match complet avec arbitrage' },
      { n:4, theme:'Protection de la nature — Biodiversité', sous:'Espèces endémiques de Madagascar, préservation',
        mala_theme:'Adidy sy andraikitra amin\'ny faritra misy (kaominina)', mala_litera:'Baikoteny: manome toromarika maharitsy',
        calc:'Révision générale: mesures (longueur, masse, volume)',
        fr:'La forme passive: "La forêt est détruite par les feux"',
        tantara:'Les grands problèmes de Madagascar après l\'indépendance',
        geo:'Les inégalités régionales: zones rurales vs urbaines',
        cu:'Conséquences de la pollution et solutions: recyclage',
        ffmom:'Ny fampandrosoana maharitra: tombony ho an\'ny taranaka',
        hetsika:'Fiompiana akoho: tombam-barotra + bilan',
        arts:'Grand spectacle de fin d\'année: chants + danses',
        sary:'Fandokoana loko: la couleur dans l\'art malgache',
        eps:'Volley-ball: renvoi manchette + service par en bas' },
      { n:5, theme:'Révision générale I — Périodes 1 et 2', sous:'Révision: vie sociale, alimentation, colonisation',
        mala_theme:'Ny tetik\'asa fanatsarana ny tontolo iainana', mala_litera:'Fanavaozana ny lesona I',
        calc:'Révision générale I: opérations et mesures',
        fr:'Verbes: devoir, pouvoir, vouloir (indicatif + conditionnel)',
        tantara:'Révision générale I Tantara',
        geo:'Bilan annuel Géo: carte de Madagascar commentée',
        cu:'Révision générale I CU',
        ffmom:'Bilan FFMOM: fahaiza-momba ny zon\'ny andriamitsika',
        hetsika:'Révision Hetsika I',
        arts:'Révision Arts I',
        sary:'Révision Sary I',
        eps:'Révision EPS I: natation + gymnastic' },
      { n:6, theme:'Révision générale II — Périodes 3 et 4', sous:'Révision: métiers, résistance, environnement',
        mala_theme:'Fanavaozana ny lesona II', mala_litera:'Révision générale II',
        calc:'Révision générale II: fractions et partages',
        fr:'Révision générale II Français',
        tantara:'Révision générale II Tantara',
        geo:'Révision générale II Géo',
        cu:'Révision générale II CU',
        ffmom:'Révision générale FFMOM',
        hetsika:'Révision Hetsika II',
        arts:'Révision Arts II',
        sary:'Révision Sary II',
        eps:'Révision EPS II: judo + athlétisme' },
      { n:7, theme:'Révision générale III — Tout le programme', sous:'Révision complète annuelle',
        mala_theme:'Révision générale III', mala_litera:'Révision générale III',
        calc:'Révision générale III',
        fr:'Révision générale III Français',
        tantara:'Révision générale III',
        geo:'Révision générale III',
        cu:'Révision générale III CU',
        ffmom:'Révision générale III',
        hetsika:'Révision Hetsika III',
        arts:'Révision Arts III',
        sary:'Révision Sary III',
        eps:'Révision EPS III: sports collectifs' },
      { n:8, theme:'Bilan annuel', sous:'Évaluation de fin d\'année',
        mala_theme:'Bilan annuel', mala_litera:'Bilan annuel',
        calc:'Bilan annuel Calcul', fr:'Bilan annuel Français',
        tantara:'Bilan annuel Tantara', geo:'Bilan annuel Géo', cu:'Bilan annuel CU',
        ffmom:'Bilan annuel FFMOM', hetsika:'Grand projet: jardin de l\'école',
        arts:'Grand spectacle collectif', sary:'Mon plus beau dessin',
        eps:'Bilan annuel EPS' },
      { n:9, theme:'Fête de fin d\'année', sous:'Célébration, remise de prix, spectacle',
        mala_theme:'Fety fianarana', mala_litera:'Fety',
        calc:'Jeux mathématiques de fin d\'année', fr:'Texte libre: mes vacances',
        tantara:'Fête fin d\'année', geo:'Présentation: Madagascar en images',
        cu:'Sciences appliquées: expériences simples', ffmom:'Festy fianarana: fankafizana',
        hetsika:'Exposition finale', arts:'Fête finale',
        sary:'Dessin souvenir', eps:'Fête sportive de fin d\'année' },
    ]
  },
];

module.exports = { PERIODES_7EME };
