'use strict';
// RÉPARTITION 12ÈME — FÉVRIER 2026
// S2 = Évaluation interne + Journée des écoles (pas de cours normaux)

function m(mat, topic, approche, activites, exercices) {
  return { matiere:mat, topic, approche, activites, exercices };
}

const FEVRIER_12EME = [

  {
    n:1, dates:'02/02/2026 – 06/02/2026',
    theme:'L\'eau et l\'hygiène · Lettres en crochet (J/U/V) · Compter 1-30 · Soustraction consolidation',
    matieres:[

      m('HYGIÈNE','L\'eau propre — boire et se laver',
        'Différence entre eau potable et eau sale. Pourquoi boire de l\'eau propre. Ne jamais boire l\'eau des rivières sans la faire bouillir. Filtrage.',
        ['Images : eau claire vs eau boueuse',
         'Discussion : "D\'où vient l\'eau que tu bois ?"',
         'Règle : "Je bois de l\'eau propre ou bouillie"'],
        ['Qu\'est-ce que l\'eau potable ? → Corrigé : eau qu\'on peut boire sans danger.',
         'D\'où vient l\'eau propre ? → Corrigé : robinet, puits filtré, eau bouillie, eau en bouteille.',
         'Peut-on boire l\'eau de la rivière directement ? → Corrigé : non, il faut la faire bouillir d\'abord.',
         'Comment rendre l\'eau propre ? → Corrigé : la faire bouillir, la filtrer.',
         'Pourquoi l\'eau sale est-elle dangereuse ? → Corrigé : elle contient des microbes qui donnent des maladies.']),

      m('I.C.','L\'eau à Madagascar — rivières et mer',
        'Madagascar est entourée d\'eau (mer) et traversée par des rivières. Les usages de l\'eau : boire, cuisiner, pêcher, laver. Respecter l\'eau.',
        ['Carte : montrer les rivières et les côtes de Madagascar',
         'Discussion : "Comment utilises-tu l\'eau à la maison ?"',
         'Discussion : "Que se passe-t-il si on n\'a plus d\'eau ?"'],
        ['Par quoi Madagascar est-elle entourée ? → Corrigé : par la mer (l\'Océan Indien).',
         'Cite 2 usages de l\'eau. → Corrigé : boire, cuisiner, se laver, pêcher, irriguer.',
         'Pourquoi faut-il économiser l\'eau ? → Corrigé : parce qu\'elle est précieuse et pas toujours disponible.',
         'Que pêche-t-on dans les rivières de Madagascar ? → Corrigé : poissons, crevettes.',
         'Que se passerait-il sans eau ? → Corrigé : on ne pourrait pas vivre.']),

      m('MORAL','L\'honnêteté',
        'Dire la vérité même quand c\'est difficile. Ne pas mentir ni tricher. L\'honnêteté crée la confiance.',
        ['Histoire : un enfant qui casse quelque chose et dit la vérité',
         'Discussion : "Qu\'est-ce qui se passe quand on ment ?"',
         'Règle : "Je dis toujours la vérité"'],
        ['Qu\'est-ce que l\'honnêteté ? → Corrigé : dire la vérité, ne pas mentir, ne pas tricher.',
         'Que se passe-t-il si on ment souvent ? → Corrigé : les autres ne nous font plus confiance.',
         'Que fais-tu si tu casses quelque chose par accident ? → Corrigé : je le dis à l\'adulte responsable.',
         'Est-il parfois difficile de dire la vérité ? → Corrigé : oui, mais c\'est toujours mieux.',
         'Cite 1 exemple d\'honnêteté. → Corrigé : rendre un objet trouvé, avouer une erreur.']),

      m('CONTE','Nouveau conte — La grenouille et la pluie (S1)',
        'Nouveau conte de février : une grenouille qui appelle la pluie pour remplir la mare. S1 : présentation.',
        ['Présenter les images : grenouille, mare sèche, nuages',
         'Lire S1 avec expression',
         'Questions de compréhension'],
        ['Qui est le personnage du conte ? → Corrigé : une grenouille.',
         'Quel est le problème dans ce conte ? → Corrigé : la mare est sèche, il n\'y a plus d\'eau.',
         'Que fait la grenouille ? → Corrigé : elle appelle la pluie.',
         'As-tu déjà vu une grenouille ? → Corrigé : réponse personnelle.',
         'Que prédis-tu pour la suite ? → Corrigé : prédiction libre.']),

      m('LANGAGE','L\'eau — vocabulaire',
        'Apprendre les mots : pluie, rivière, mer, lac, cascade, robinet, puits, goutte, bouillir. Construire des phrases.',
        ['Images de sources d\'eau : nommer',
         '"La pluie tombe du ciel. La rivière coule..."',
         'Relier image et mot'],
        ['Cite 3 sources d\'eau. → Corrigé : pluie, rivière, mer, lac, puits, robinet.',
         'Qu\'est-ce qu\'une cascade ? → Corrigé : de l\'eau qui tombe d\'une hauteur.',
         'Fais une phrase avec "la pluie". → Corrigé : production.',
         'Comment s\'appelle l\'eau sous la terre ? → Corrigé : nappe phréatique / eau souterraine.',
         'Quelle source d\'eau est la plus proche de chez toi ? → Corrigé : réponse personnelle.']),

      m('PRÉ-LECTURE','Graphisme — lettres en crochet : J, U, V',
        'Tracer J = trait vertical + crochet bas. U = deux verticaux + fond arrondi. V = deux obliques qui se rejoignent.',
        ['Tracer J dans l\'air : "Je descends et je crochet !"',
         'Tracer U : "Je descends, j\'arrondis, je remonte"',
         'Tracer V : "Je descends en oblique, je remonte en oblique"'],
        ['Trace 5 lettres J. → Corrigé : évaluation.',
         'Trace 5 lettres U. → Corrigé : évaluation.',
         'Trace 5 lettres V. → Corrigé : évaluation.',
         'Quelle différence entre U et V ? → Corrigé : U est arrondi en bas, V est pointu en bas.',
         'Quelle lettre ressemble à un crochet ? → Corrigé : J.']),

      m('NUMÉRATION','Compter jusqu\'à 30',
        'Arriver à 30. 30 = 3 dizaines. Tableau des dizaines et unités.',
        ['Compter de 25 à 30',
         '30 = 3 bâtons de 10',
         'Afficher 30 au tableau avec décomposition'],
        ['Compte de 25 à 30. → Corrigé : 25, 26, 27, 28, 29, 30.',
         'Quel nombre vient après 29 ? → Corrigé : 30.',
         '30 = ___ dizaines + ___ unités. → Corrigé : 3 dizaines + 0 unités.',
         'Quel est le plus grand nombre que tu connais maintenant ? → Corrigé : 30.',
         'Ordonne : 29, 12, 30, 5. → Corrigé : 5, 12, 29, 30.']),

      m('CALCUL','Soustraction — consolider jusqu\'à 15',
        'Pratiquer la soustraction avec des nombres plus grands. 12 − 5 = 7. Vérifier avec addition.',
        ['12 − 5 = ? (avec les bâtons)',
         'Vérifier : 7 + 5 = 12 ✓',
         'Ardoise : 5 soustractions'],
        ['10−4=___. → Corrigé : 6.',
         '12−7=___. → Corrigé : 5.',
         '15−8=___. → Corrigé : 7.',
         'Problème : 13 poissons dans la mare. La grenouille en mange 4. Combien reste ? → Corrigé : 9.',
         'Vérifie : 9+4=___. → Corrigé : 13.']),

      m('DESSIN','Dessiner la pluie et l\'eau',
        'Dessiner un paysage de pluie. Traits verticaux pour la pluie. Lignes horizontales pour la mare. Couleur bleue.',
        ['Observer : comment dessine-t-on la pluie ? (traits obliques vers le bas)',
         'Dessiner : nuages + pluie + mare + grenouille',
         'Colorier en bleu'],
        ['Comment as-tu dessiné la pluie ? → Corrigé : petits traits obliques.',
         'De quelle couleur est l\'eau ? → Corrigé : bleu.',
         'Qu\'as-tu mis dans le ciel ? → Corrigé : nuages.',
         'Qu\'as-tu ajouté sur la mare ? → Corrigé : grenouille, nénuphars...',
         'Es-tu content de ton dessin ? → Corrigé : réponse personnelle.']),

      m('CHANT','Chanson "Il pleut, il pleut, bergère"',
        'Apprendre "Il pleut, il pleut, bergère, presse tes blancs moutons." Mimer la pluie avec les doigts.',
        ['Apprendre la mélodie',
         'Mimer : pluie = doigts tombent vers le bas, mouton = main en forme de nuage',
         'Chanter ensemble'],
        ['Chante "Il pleut, il pleut, bergère". → Corrigé : performance orale.',
         'Qui doit se dépêcher dans la chanson ? → Corrigé : la bergère.',
         'Que doit-elle ramener ? → Corrigé : ses moutons.',
         'Mime la pluie avec tes doigts. → Corrigé : geste.',
         'Quel temps fait-il dans cette chanson ? → Corrigé : il pleut.']),

      m('RÉCITATION','Comptine "Une grenouille qui voulait être aussi grosse qu\'un bœuf"',
        'Version courte et simplifiée de la fable. La grenouille se gonfle. Morale : contentez-vous de ce que vous êtes.',
        ['Apprendre 2 vers',
         'Mimer : se gonfler comme la grenouille',
         'Morale : être content de soi'],
        ['Récite la comptine. → Corrigé : performance orale.',
         'Que veut faire la grenouille ? → Corrigé : être aussi grosse qu\'un bœuf.',
         'Réussit-elle ? → Corrigé : non, elle éclate.',
         'Quelle est la leçon ? → Corrigé : être content de ce qu\'on est.',
         'Mime une grenouille qui se gonfle. → Corrigé : geste.']),

      m('T.M.','Fabrication de moulin à eau (eau + roue)',
        'Fabriquer une roue simple en carton qui tourne. Observer comment l\'eau peut faire tourner une roue (moulins).',
        ['Découper une roue en carton',
         'Faire des "palettes" sur les bords',
         'Verser de l\'eau et observer la rotation'],
        ['As-tu réussi à faire tourner ta roue ? → Corrigé : réponse.',
         'Qu\'est-ce qui fait tourner la roue ? → Corrigé : l\'eau / le vent.',
         'À quoi sert un moulin à eau ? → Corrigé : à moudre du grain, à produire de l\'électricité.',
         'Quel outil as-tu utilisé ? → Corrigé : ciseaux, colle.',
         'Qu\'as-tu appris de cette activité ? → Corrigé : réponse personnelle.']),

      m('A.P.S.','Jeu de l\'eau — équilibre et coordination',
        'Jeu : transporter de l\'eau dans une cuillère (ou petite tasse) d\'un point à un autre. Ne pas renverser. Concentration.',
        ['Course en relais avec une cuillère d\'eau',
         'Passer des obstacles sans renverser',
         'Variante : yeux fermés pour les plus avancés'],
        ['As-tu réussi à ne pas renverser l\'eau ? → Corrigé : réponse.',
         'Quel mouvement était le plus difficile ? → Corrigé : réponse personnelle.',
         'Comment t\'es-tu concentré ? → Corrigé : réponse personnelle.',
         'Pourquoi faut-il être concentré dans ce jeu ? → Corrigé : pour ne pas renverser l\'eau.',
         'As-tu aidé un camarade ? → Corrigé : réponse personnelle.']),

      m('ENVIRONNEMENT','L\'eau dans la nature — cycle de l\'eau (simplifié)',
        'La pluie tombe, s\'écoule en rivières, s\'évapore et forme les nuages. Cycle simple en images.',
        ['Schéma très simple : pluie → rivière → mer → nuage → pluie',
         'Discussion : "Où va l\'eau de pluie ?"',
         'Observer les flaques après la pluie'],
        ['D\'où vient la pluie ? → Corrigé : des nuages.',
         'Où va l\'eau de pluie ? → Corrigé : dans les rivières, dans le sol, dans la mer.',
         'Comment l\'eau monte-t-elle dans les nuages ? → Corrigé : elle s\'évapore (chaleur du soleil).',
         'Qu\'est-ce que le cycle de l\'eau ? → Corrigé : le chemin que fait l\'eau de la pluie jusqu\'aux nuages et qui recommence.',
         'A-t-on déjà observé une flaque disparaître ? → Corrigé : réponse personnelle (évaporation).']),

      m('ANGLAIS','Water words + weather',
        'Apprendre : rain, water, river, sea, cloud. Décrire le temps : "It is raining. The sky is grey."',
        ['"What is the weather today ?" → regarder par la fenêtre',
         'Flash cards : rain, sun, cloud, wind',
         '"Touch the rain card. Touch the sun card."'],
        ['How do you say "pluie" ? → Corrigé : rain.',
         'How do you say "mer" ? → Corrigé : sea.',
         '"It is ___." (montrer image de pluie) → Corrigé : raining.',
         'What color are clouds ? → Corrigé : white or grey.',
         'How do you say "nuage" ? → Corrigé : cloud.']),

    ]
  },

  {
    n:2, dates:'09/02/2026 – 13/02/2026',
    theme:'ÉVALUATION INTERNE + Journée des écoles — Pas de cours normaux',
    matieres:[
      m('ÉVALUATION','Évaluation interne 2ème trimestre + Journée des écoles — 12ème',
        'Semaine spéciale : évaluation interne du 2ème trimestre + Journée des écoles (Kermesse scolaire). Les élèves de 12ème participent aux activités festives (chants, danses, sketches). Pas de cours normaux.',
        ['Lundi : épreuve de numération (compter 1-30, additions/soustractions simples)',
         'Mardi : épreuve de graphisme + dessin',
         'Mercredi : épreuve orale (langage, chant, récitation)',
         'Jeudi-Vendredi : Journée des écoles — activités festives',
         'Décoration de la classe, préparation des expositions'],
        [
          '══ ÉPREUVE NUMÉRATION ══',
          'Compte de 1 à 30. → Corrigé : performance orale.',
          'Quel nombre vient après 28 ? → Corrigé : 29.',
          '5+7=___. → Corrigé : 12.',
          '10−6=___. → Corrigé : 4.',
          '3 groupes de 3 = ___. → Corrigé : 9.',
          '',
          '══ ÉPREUVE GRAPHISME ══',
          'Trace 3 O, 3 C, 3 G. → Corrigé : évaluation.',
          'Trace 3 I, 3 L, 3 T. → Corrigé : évaluation.',
          'Trace 3 J, 3 U, 3 V. → Corrigé : évaluation.',
          'Dessine ta famille. → Corrigé : production.',
          '',
          '══ ÉPREUVE ORALE ══',
          'Cite 5 mots sur l\'eau. → Corrigé : pluie, mer, rivière, puits, robinet.',
          'Récite "Il pleut, il pleut, bergère". → Corrigé : performance orale.',
          'Chante "Petit train". → Corrigé : performance orale.',
          'How do you say "rain" en malgache ? → Corrigé : ranonorana.',
          '',
          '══ JOURNÉE DES ÉCOLES ══',
          'Participation : chant collectif de la classe 12ème',
          'Participation : danse ou comptine devant les parents',
          'Visite des expositions et activités périscolaires',
          'Remise de dessins aux parents',
        ]
      ),
    ]
  },

  {
    n:3, dates:'16/02/2026 – 20/02/2026',
    theme:'La famille et le foyer · Lettres arrondies (B/P/D) · Compter 1-33 · Partage et moitié',
    matieres:[

      m('HYGIÈNE','Hygiène à la maison — rangement et propreté',
        'Maintenir sa chambre propre. Ranger ses affaires. Aider à la vaisselle. La propreté à la maison protège la santé.',
        ['Jeu de rôle : ranger la salle de classe',
         '"À la maison, qui range ?"',
         'Règle : "Je range mes affaires après chaque activité"'],
        ['Cite 2 gestes de propreté à la maison. → Corrigé : ranger ses jouets, laver la vaisselle, balayer.',
         'Pourquoi ranger sa chambre ? → Corrigé : pour être propre, ne pas perdre ses affaires, éviter les accidents.',
         'Que fais-tu après avoir mangé ? → Corrigé : je porte mon assiette à la cuisine / je l\'essuie.',
         'Qui aide à la maison dans ta famille ? → Corrigé : réponse personnelle.',
         'Quelle tâche ménagère peux-tu faire seul ? → Corrigé : ranger mes jouets, faire mon lit, balayer.']),

      m('I.C.','La famille élargie à Madagascar',
        'La famille malgache peut être grande : parents, grands-parents, oncles, tantes, cousins. Solidarité familiale. Le "fihavanana".',
        ['Dessiner l\'arbre généalogique simple',
         'Vocabulaire malgache : ray (père), reny (mère), dadabe (grand-père), nenibe (grand-mère)',
         'Discussion : "Combien êtes-vous dans ta famille ?"'],
        ['Qui est ton dadabe ? → Corrigé : mon grand-père.',
         'Qui est ta nenibe ? → Corrigé : ma grand-mère.',
         'Qu\'est-ce que le fihavanana ? → Corrigé : la solidarité et l\'entraide entre les Malgaches.',
         'Combien de personnes as-tu dans ta famille proche ? → Corrigé : réponse personnelle.',
         'Cite les membres de ta famille. → Corrigé : réponse personnelle.']),

      m('MORAL','Le respect des aînés',
        'Respecter les personnes plus âgées. Saluer les aînés correctement. Ne pas les interrompre quand ils parlent. Tradition malgache.',
        ['Jeu de rôle : saluer un grand-parent',
         '"Comment salues-tu ton dadabe ?"',
         'Règle : "Je salue les adultes en premier"'],
        ['Que fait-on quand on rencontre un adulte ? → Corrigé : on le salue en premier.',
         'Est-il poli d\'interrompre un adulte ? → Corrigé : non, on attend qu\'il finisse de parler.',
         'Comment dit-on "bonjour" avec respect en malgache ? → Corrigé : "Manao ahoana ianao ?" ou incliner la tête.',
         'Cite 1 geste de respect envers les aînés. → Corrigé : leur céder sa place, les saluer en premier, écouter.',
         'Pourquoi respecte-t-on les aînés ? → Corrigé : ils ont l\'expérience, ils nous apprennent beaucoup.']),

      m('CONTE','La grenouille et la pluie (S2 — la pluie arrive)',
        'La pluie arrive enfin. La mare se remplit. Tout le village est content.',
        ['Relire S1 + lire S2',
         'Expression des émotions : soulagement, joie',
         'Discussion : "Comment se sentent les villageois ?"'],
        ['Que se passe-t-il dans cette partie ? → Corrigé : la pluie arrive enfin.',
         'Comment se sent la grenouille ? → Corrigé : heureuse, soulagée.',
         'Pourquoi tout le monde est content ? → Corrigé : parce que l\'eau revient.',
         'Quelle valeur voit-on dans ce conte ? → Corrigé : la persévérance, l\'espoir.',
         'Raconte S1 et S2 en 2 phrases. → Corrigé : résumé oral.']),

      m('LANGAGE','La maison — vocabulaire révisé + meubles',
        'Révision et approfondissement : les pièces + les meubles. "Dans la cuisine, il y a une table, une chaise, un réfrigérateur."',
        ['Images de pièces meublées : nommer',
         '"Dans ma chambre, il y a..."',
         'Jeu : "Dans quelle pièce est le lit ?"'],
        ['Dans quelle pièce dort-on ? → Corrigé : la chambre.',
         'Cite 2 meubles de la cuisine. → Corrigé : table, chaise, réfrigérateur, évier.',
         'Cite 2 meubles du salon. → Corrigé : canapé, fauteuil, télévision, table basse.',
         '"Dans quelle pièce est la baignoire ?" → Corrigé : dans la salle de bain.',
         'Décris ta chambre en 2 phrases. → Corrigé : production personnelle.']),

      m('PRÉ-LECTURE','Graphisme — lettres à bosse : B, P, D',
        'Tracer B = trait vertical + 2 demi-cercles droits. P = trait vertical + 1 demi-cercle haut. D = trait vertical + 1 grand arc droit.',
        ['Tracer B : "Je descends, puis je fais 2 bosses à droite"',
         'Tracer P : "Je descends, 1 bosse en haut à droite"',
         'Tracer D : "Je descends, 1 grand arc à droite"'],
        ['Trace 5 lettres B. → Corrigé : évaluation.',
         'Trace 5 lettres P. → Corrigé : évaluation.',
         'Trace 5 lettres D. → Corrigé : évaluation.',
         'Quelle différence entre B et P ? → Corrigé : B a 2 bosses, P en a 1 (en haut).',
         'Quelle différence entre B et D ? → Corrigé : B a 2 petites bosses, D a 1 grande courbe.']),

      m('NUMÉRATION','Compter jusqu\'à 33',
        'Continuer la progression : 31, 32, 33. 33 = 3 dizaines + 3 unités.',
        ['Compter de 30 à 33',
         'Décomposer 33 = 3D + 3U',
         'Dénombrement : 33 graines'],
        ['Compte de 30 à 33. → Corrigé : 30, 31, 32, 33.',
         'Quel nombre vient après 32 ? → Corrigé : 33.',
         'Décompose 33 en dizaines et unités. → Corrigé : 3 dizaines + 3 unités.',
         'Quel est le plus grand : 33 ou 28 ? → Corrigé : 33.',
         'Ordonne : 33, 21, 8, 30. → Corrigé : 8, 21, 30, 33.']),

      m('CALCUL','La moitié — partager en 2 parts égales',
        'Notion de moitié : couper en 2 parts égales. La moitié de 10 = 5. Utiliser des objets concrets.',
        ['Couper une feuille en 2 : "Est-ce qu\'elles sont égales ?"',
         'Partager 8 jetons en 2 groupes égaux',
         'La moitié de 6 = ? (avec les doigts)'],
        ['La moitié de 4 = ___. → Corrigé : 2.',
         'La moitié de 8 = ___. → Corrigé : 4.',
         'La moitié de 10 = ___. → Corrigé : 5.',
         'Partage 6 bonbons entre 2 amis. Chacun a ___. → Corrigé : 3.',
         'La moitié de 12 = ___. → Corrigé : 6.']),

      m('DESSIN','Dessin de ma maison',
        'Dessiner sa maison avec les pièces. Vue de l\'extérieur : porte, fenêtres, toit. Colorier.',
        ['Observer des images de maisons malgaches (en bois, en brique)',
         'Dessiner la façade : rectangle + triangle (toit)',
         'Ajouter porte + fenêtres'],
        ['Combien de fenêtres a ta maison ? → Corrigé : réponse personnelle.',
         'Quelle forme a le toit ? → Corrigé : triangle.',
         'Quelle forme a la porte ? → Corrigé : rectangle.',
         'Quelle couleur as-tu choisie pour les murs ? → Corrigé : réponse personnelle.',
         'As-tu ajouté un jardin ? → Corrigé : réponse personnelle.']),

      m('CHANT','Chanson "Bateau sur l\'eau" (en lien avec la famille et l\'eau)',
        '"Bateau sur l\'eau, la rivière, la rivière, bateau sur l\'eau, la rivière et le ruisseau !"',
        ['Apprendre la mélodie',
         'Mimer le bateau qui se balance',
         'Chanter vite puis lentement'],
        ['Chante "Bateau sur l\'eau". → Corrigé : performance orale.',
         'Où va le bateau dans la chanson ? → Corrigé : sur la rivière et le ruisseau.',
         'Mime un bateau qui se balance. → Corrigé : geste.',
         'Quel est le rythme de cette chanson : vite ou lent ? → Corrigé : variable.',
         'Chante seul devant la classe. → Corrigé : performance.']),

      m('RÉCITATION','Comptine — "Maman chérie"',
        '"Maman chérie, je t\'aime ! Tu es douce, tu es belle, tu es ma plus grande amie !"',
        ['Apprendre ligne par ligne',
         'Réciter avec beaucoup d\'expression',
         'En préparation de la Fête des Mères (mai)'],
        ['Récite "Maman chérie". → Corrigé : performance orale.',
         'Que dit-on à maman dans cette comptine ? → Corrigé : je t\'aime, tu es douce, belle, mon amie.',
         'Pourquoi on aime sa maman ? → Corrigé : réponse personnelle.',
         'Mime un câlin pour maman. → Corrigé : geste.',
         'Quand est la fête des mères ? → Corrigé : au mois de mai.']),

      m('T.M.','Cadre photo — pour la famille',
        'Fabriquer un cadre photo en carton pour y glisser un dessin de sa famille.',
        ['Découper le cadre en carton',
         'Décorer avec des gommettes ou coloriage',
         'Glisser son dessin de famille dans le cadre'],
        ['Pour qui as-tu fait ce cadre ? → Corrigé : réponse personnelle.',
         'Comment as-tu décoré ton cadre ? → Corrigé : réponse personnelle.',
         'Quel dessin as-tu mis dedans ? → Corrigé : ma famille.',
         'Offriras-tu ce cadre à quelqu\'un ? → Corrigé : réponse personnelle.',
         'Qu\'as-tu préféré : découper ou décorer ? → Corrigé : réponse personnelle.']),

      m('A.P.S.','Jeu de la maison — parcours coopératif',
        'Construire "une maison" ensemble avec des briques en mousse ou boîtes. Coopération. Objectif commun.',
        ['Chaque élève apporte sa brique / boîte',
         'Construire ensemble la maison',
         'Discussion : qu\'est-ce qui s\'est passé quand on n\'a pas coopéré ?'],
        ['Avez-vous réussi à construire la maison ? → Corrigé : réponse collective.',
         'Que se passe-t-il si chacun fait ce qu\'il veut sans écouter ? → Corrigé : la construction ne tient pas.',
         'Comment a-t-on coopéré ? → Corrigé : réponse collective.',
         'Quel rôle as-tu joué ? → Corrigé : réponse personnelle.',
         'Pourquoi la coopération est-elle importante ? → Corrigé : parce qu\'ensemble on accomplit plus.']),

      m('ENVIRONNEMENT','Les plantes utiles à la maison',
        'Les plantes qu\'on cultive dans le jardin ou autour de la maison : basilic, citronnelle, aloe vera, ravintsara. Leurs usages.',
        ['Images de plantes domestiques et médicinales',
         'Sentir : citronnelle, basilic',
         'Discussion : "Quelles plantes as-tu chez toi ?"'],
        ['Cite 1 plante qu\'on trouve dans les jardins malgaches. → Corrigé : citronnelle, basilic, aloe vera, ravintsara.',
         'À quoi sert la citronnelle ? → Corrigé : arôme culinaire, éloigne les moustiques.',
         'À quoi sert l\'aloe vera ? → Corrigé : soins de la peau, brûlures.',
         'Quelle plante sentais-tu dans le jardin ? → Corrigé : réponse personnelle.',
         'Est-il bien d\'avoir des plantes chez soi ? → Corrigé : oui, elles purifient l\'air et embellissent la maison.']),

      m('ANGLAIS','Family words',
        'Apprendre : mother, father, sister, brother, grandmother, grandfather. Présenter sa famille en anglais.',
        ['"My name is ___, and my mother\'s name is ___."',
         'Flash cards famille',
         '"Point to the grandmother."'],
        ['How do you say "mère" in English ? → Corrigé : mother.',
         'How do you say "père" ? → Corrigé : father.',
         'How do you say "dadabe" in English ? → Corrigé : grandfather.',
         'How do you say "nenibe" ? → Corrigé : grandmother.',
         'Who is in your family ? → Corrigé : My family is... (réponse personnelle).']),

    ]
  },

  {
    n:4, dates:'23/02/2026 – 27/02/2026',
    theme:'Révision · Lettres B/P/D · Numération · Partage — préparation mars',
    matieres:[

      m('HYGIÈNE','Révision hygiène — gestes essentiels',
        'Révision de tous les gestes d\'hygiène appris depuis octobre. Quiz ludique. Récompense collective.',
        ['Quiz images : bonne ou mauvaise hygiène ?',
         'Mimer chaque geste correct',
         'Bilan : "Quel geste est le plus important ?"'],
        ['Cite les 6 étapes du lavage des mains. → Corrigé : mouiller, savonner, frotter paumes, frotter dos, frotter entre les doigts, rincer, sécher.',
         'Cite 3 bons gestes d\'hygiène. → Corrigé : se laver les mains, se brosser les dents, boire de l\'eau propre.',
         'Cite 2 mauvaises habitudes d\'hygiène. → Corrigé : ne pas se laver les mains, boire l\'eau sale...',
         'Que fais-tu le matin avant d\'aller à l\'école ? → Corrigé : me laver, m\'habiller, prendre le petit déjeuner.',
         'Pourquoi l\'hygiène est-elle importante ? → Corrigé : pour rester en bonne santé.']),

      m('I.C.','Révision IC — société et monde',
        'Révision de tout le contenu IC du trimestre : transports, eau, famille, animaux. Quiz.',
        ['Quiz en images',
         'Jeu de devinettes',
         'Chaque élève pose 1 question à un camarade'],
        ['Cite 3 moyens de transport à Madagascar. → Corrigé : taxi-brousse, pousse-pousse, pirogue, avion.',
         'Qu\'est-ce que le fihavanana ? → Corrigé : la solidarité et l\'entraide entre Malgaches.',
         'Cite 2 animaux endémiques de Madagascar. → Corrigé : lémurien, caméléon.',
         'Pourquoi faut-il économiser l\'eau ? → Corrigé : elle est précieuse et peut manquer.',
         'Cite 2 régions ou villes de Madagascar. → Corrigé : Antananarivo, Tamatave, Majunga, Tuléar.']),

      m('MORAL','Révision morale — mes valeurs',
        'Révision de toutes les valeurs apprises : patience, générosité, honnêteté, respect des aînés, respect des animaux.',
        ['Chaque élève cite sa valeur préférée',
         'Quiz : "Que fais-tu si... ?"',
         'Bilan : "Laquelle ai-je pratiquée ce mois ?"'],
        ['Cite 5 valeurs apprises ce trimestre. → Corrigé : patience, générosité, honnêteté, respect des aînés, respect des animaux.',
         'Quelle valeur trouves-tu la plus difficile à pratiquer ? → Corrigé : réponse personnelle.',
         'Quelle valeur as-tu pratiquée cette semaine ? → Corrigé : réponse personnelle.',
         'Donne 1 exemple de générosité. → Corrigé : partager son goûter.',
         'Donne 1 exemple de patience. → Corrigé : attendre son tour sans se plaindre.']),

      m('CONTE','La grenouille et la pluie — conte complet',
        'Lire le conte en entier. Récitation par les élèves. Jouer la scène finale.',
        ['Lire le conte complet S1+S2',
         'Jeu de rôle : un élève joue la grenouille',
         'Discussion finale : "Quelle est la leçon ?"'],
        ['Raconte le conte en 3 phrases. → Corrigé : résumé oral.',
         'Quel est le problème au début ? → Corrigé : la mare est sèche.',
         'Quelle est la solution ? → Corrigé : la pluie arrive.',
         'Quelle est la leçon du conte ? → Corrigé : persévérer, avoir de l\'espoir.',
         'Quel est ton personnage préféré ? → Corrigé : réponse personnelle.']),

      m('LANGAGE','Révision vocabulaire — tous les thèmes',
        'Révision de tout le vocabulaire du trimestre. Quiz en images. "Qu\'est-ce que c\'est ? Où est-ce ? Que fait-on avec ?"',
        ['Quiz rapide : 20 images à nommer',
         'Jeu : "Je décris, tu devines"',
         '"Quelle est ta phrase préférée ?"'],
        ['Cite 5 aliments. → Corrigé : riz, légumes, poisson, banane, pain.',
         'Cite 5 animaux. → Corrigé : lémurien, chien, poisson, vache, poulet.',
         'Cite 5 objets de la maison. → Corrigé : table, lit, assiette, livre, crayon.',
         'Fais une phrase avec "eau". → Corrigé : production.',
         'Fais une phrase avec "famille". → Corrigé : production.']),

      m('PRÉ-LECTURE','Révision graphisme — toutes les lettres apprises',
        'Révision de tous les graphismes : O, C, G, Q, I, L, T, H, J, U, V, B, P, D.',
        ['Fiche de révision : 1 de chaque lettre',
         'L\'élève choisit sa lettre préférée à tracer × 10',
         'Identifier les lettres dans les prénoms'],
        ['Trace O, C, G, Q. → Corrigé : évaluation.',
         'Trace I, L, T, H. → Corrigé : évaluation.',
         'Trace J, U, V. → Corrigé : évaluation.',
         'Trace B, P, D. → Corrigé : évaluation.',
         'Quelle lettre préfères-tu tracer ? → Corrigé : réponse personnelle.']),

      m('NUMÉRATION','Révision — compter jusqu\'à 33 + décomposer',
        'Révision complète : compter, reconnaître, ordonner, décomposer de 1 à 33.',
        ['Compter de 1 à 33',
         'Compter à rebours de 20 à 1',
         'Dicter 5 nombres à écrire'],
        ['Compte de 1 à 33. → Corrigé : performance orale.',
         'Compte à rebours de 10 à 1. → Corrigé : performance.',
         'Décompose 25 : ___ dizaines + ___ unités. → Corrigé : 2D + 5U.',
         'Quel nombre vient avant 33 ? → Corrigé : 32.',
         'Ordonne : 33, 15, 2, 27. → Corrigé : 2, 15, 27, 33.']),

      m('CALCUL','Révision additions, soustractions, moitié',
        'Révision de toutes les opérations du trimestre. Ardoise rapide.',
        ['Quiz ardoise : 10 opérations mélangées',
         'Problème de la semaine',
         'Corriger ensemble'],
        ['4+9=___. → Corrigé : 13.',
         '15−7=___. → Corrigé : 8.',
         'La moitié de 14 = ___. → Corrigé : 7.',
         '3 groupes de 4 = ___. → Corrigé : 12.',
         'Problème : J\'ai 20 billes. Je perds la moitié. Combien reste ? → Corrigé : 10.']),

      m('DESSIN','Dessin libre — souvenir de février',
        'Dessin libre : ce dont l\'élève se souvient le mieux de ce mois. Présenter et expliquer.',
        ['Choisir librement le sujet',
         'Dessiner et colorier',
         'Présenter : "J\'ai dessiné ___ parce que___"'],
        ['Qu\'as-tu dessiné ? → Corrigé : réponse personnelle.',
         'Pourquoi as-tu choisi ce sujet ? → Corrigé : réponse personnelle.',
         'Quelles couleurs as-tu choisies ? → Corrigé : réponse personnelle.',
         'Es-tu content de ton dessin ? → Corrigé : réponse personnelle.',
         'Qu\'as-tu préféré apprendre en février ? → Corrigé : réponse personnelle.']),

      m('CHANT','Révision — tous les chants du trimestre',
        'Chanter tous les refrains appris : "Bonjour", "Tête épaules", "Petit train", "Si tu as de la joie", "Il pleut", "Bateau sur l\'eau".',
        ['Enchaîner les refrains sans pause',
         'Vote : chanson préférée du trimestre',
         'Chanter la chanson préférée 3 fois'],
        ['Chante le refrain de "Petit train". → Corrigé : performance.',
         'Chante "Il pleut, il pleut, bergère". → Corrigé : performance.',
         'Chante "Bateau sur l\'eau". → Corrigé : performance.',
         'Quelle est ta chanson préférée du trimestre ? → Corrigé : réponse personnelle.',
         'Chante "Si tu as de la joie". → Corrigé : performance.']),

      m('RÉCITATION','Révision — toutes les comptines du trimestre',
        'Réviser toutes les comptines : "Doigts", "1,2,3 soleil", "Promenons-nous dans les bois", "Mon beau sapin", "En voiture Simone", "Ani le lémurien", "Maman chérie".',
        ['Réciter chaque comptine',
         'Vote : la plus belle comptine',
         'Réciter la préférée avec expression maximale'],
        ['Récite "En voiture Simone". → Corrigé : performance.',
         'Récite "Ani le lémurien". → Corrigé : performance.',
         'Récite "Maman chérie". → Corrigé : performance.',
         'Récite "Promenons-nous dans les bois". → Corrigé : performance.',
         'Quelle comptine tu retiens le mieux ? → Corrigé : réponse personnelle.']),

      m('T.M.','Collage libre — mon mois préféré',
        'Collage libre avec magazines, papiers colorés, représentant le souvenir préféré de ce trimestre.',
        ['Choisir son sujet (transport, animal, famille, eau)',
         'Découper et coller',
         'Présenter son collage'],
        ['Qu\'as-tu représenté ? → Corrigé : réponse personnelle.',
         'Comment as-tu découpé les formes ? → Corrigé : avec des ciseaux.',
         'Qu\'as-tu utilisé pour coller ? → Corrigé : de la colle.',
         'Quel est ton souvenir préféré du trimestre ? → Corrigé : réponse personnelle.',
         'À qui montreras-tu ton collage ? → Corrigé : réponse personnelle.']),

      m('A.P.S.','Fête sportive de fin de trimestre',
        'Mini-jeux sportifs : course, saut, lancer de balle, équilibre. Médailles pour tous.',
        ['Course de 10 mètres',
         'Saut à cloche-pied 5 fois',
         'Lancer de balle dans un panier'],
        ['As-tu couru vite ? → Corrigé : réponse personnelle.',
         'Combien de fois as-tu sauté à cloche-pied ? → Corrigé : réponse.',
         'As-tu mis la balle dans le panier ? → Corrigé : réponse.',
         'Quel jeu as-tu préféré ? → Corrigé : réponse personnelle.',
         'As-tu encouragé tes camarades ? → Corrigé : réponse personnelle.']),

      m('ENVIRONNEMENT','Bilan — ce que j\'ai appris sur la nature',
        'Révision de tout le contenu environnemental : eau, plantes, animaux, saisons, forêt, pollution.',
        ['Quiz nature en images',
         'Chaque élève cite 1 chose apprise',
         'Dessin : "Ce que je vais protéger dans la nature"'],
        ['Cite 2 animaux endémiques. → Corrigé : lémurien, caméléon.',
         'Pourquoi faut-il protéger la forêt ? → Corrigé : c\'est l\'habitat des animaux, ça régule le climat.',
         'Cite le cycle de l\'eau en 3 étapes. → Corrigé : pluie → rivière/sol → évaporation → nuage → pluie.',
         'Que peut-on faire pour protéger la nature ? → Corrigé : ne pas jeter les déchets, planter des arbres, économiser l\'eau.',
         'Qu\'as-tu préféré apprendre en environnement ce trimestre ? → Corrigé : réponse personnelle.']),

      m('ANGLAIS','English review — tout le trimestre',
        'Révision de tout l\'anglais : salutations, couleurs, formes, chiffres, corps, famille, animaux, transport, météo, eau.',
        ['Quiz rapide : 20 mots à donner en anglais',
         '"Simon says..." avec les mots appris',
         'Chanter "Head, Shoulders, Knees and Toes"'],
        ['Count from 1 to 20. → Corrigé : performance orale.',
         'Say 5 colors in English. → Corrigé : red, blue, green, yellow, white.',
         'How do you say "famille" ? → Corrigé : family.',
         'How do you say "pluie" ? → Corrigé : rain.',
         'How do you say "lémurien" ? → Corrigé : lemur.']),

    ]
  },

];

module.exports = { FEVRIER_12EME };
